DFE-Digital/itt-mentor-services

.better-html.yml, .erb-lint.yml, Gemfile, Gemfile.lock, config/initializers/better_html.rb, spec/views/erb_safety_check_spec.rb
I'm adding Better HTML to our codebase so that we have safety checks and consistent styling in place for html views.
I've more or less followed the configuration that is used for get-into-teaching-app. 
There are some limitations.
- Only safety is checked as part of running `erb-lint`.  
- Other better-html default checks are done on render (only during test and development), so you might end up with some errors like this one, even though the linter passes: 
I've added a spec as well. Happy to take one or the other out if people think this is overkill.
You can test it is working by adding some invalid html (see [better-html read me](https://github.com/Shopify/better-html#configuration)) to `application.html.erb`. If it's a javascript safety issue, the linter will fail. If it's …
=> lb/Implement better-html

.github/workflows/deploy.yml
We currently don't have CI available. This pull request goal is to add a lint step and test step to our CI via github action.
NONE
CI should run be green.
https://trello.com/c/G2AoTkQi/52-setup-github-actions-and-basic-ci
=> Add lint and test to CI

app/controllers/heartbeat_controller.rb, config/routes.rb, config/routes/placements.rb, spec/requests/heartbeat_spec.rb, spec/system/home_page_spec.rb
Add a simple healthcheck page so kubernetes can monitor the container.
New healthcheck route
Just visit `/healthcheck`
- 2 file changes are because of the linter.
https://trello.com/c/z21wL0OH/77-add-healthcheck-endpoint
=> Add healthcheck endpoint

config/initializers/better_html.rb
See slack thread
https://ukgovernmentdfe.slack.com/archives/C06962474AC/p1703087297691049?thread_ts=1703080111.267879&cid=C06962474AC
Adding an early return for BetterHtml when the environment is production.
=> Skip BetterHtml config in production

app/controllers/claims/support/application_controller.rb, app/controllers/placements/support/application_controller.rb
The top level `ApplicationController` already requires authentication.
Remove duplicate calls to `:authenticate_user!`
Check if Authentication is _still_ required.
=> Remove double authenticate_user in Support Application Controllers

app/controllers/claims/support/users_controller.rb
Only show schools with **claims** users 
To fetch just the claims users
=> Only show claims users for claims school users

.github/workflows/build_and_deploy.yml, Makefile, terraform/application/application.tf, terraform/application/config/review_app_env.yml, terraform/application/variables.tf
To reduced the code maintenance overhead, we need to refactor some environment variables
Create yml files per environment for the env variables: review_app_env.yml(in this case) and populate review_app_env.yml with values from [.env](https://github.com/DFE-Digital/itt-mentor-services/blob/main/.env.example)
Ensure single env variables are removed from variables.tf
review_app_env.yml has been created with the correct value and syntax
A mechanism to pass the env variables has been added to the application configuration
=> 876-ittms-refactor-environment-variables-configuration

app/controllers/claims/support/application_controller.rb, app/controllers/placements/support/application_controller.rb, config/locales/en.yml
Move "You cannot perform this action" from controller to Locales.
- Move "You cannot perform this action" from controller to Locales.
=> Move you cannot perform this action text to locales

db/seeds.rb
Fixes the seeds following changes made to the database schema in #157.
Cherry-picked from @CatalinVoineag's PR #140 (thanks for fixing this Catalin!)
=> Fix seeds after renaming claims and placements on school

.github/workflows/build_and_deploy.yml, terraform/application/config/qa.tfvars.json, terraform/application/database.tf
Create QA environment, so we can have proper testing before promoting to production
- Create QA environment
- Continuous deployment after merge and tests
The url before were generated from setting the ci to run on a feature branch:
https://track-and-pay-qa.test.teacherservices.cloud/schools/000c2383-692f-4225-b8d8-bc20d3f12f9a
https://manage-school-placements-qa.test.teacherservices.cloud/personas
[](https://trello.com/c/9RGafMrv/826-ittms-create-qa-environment)
=> 826 create qa environment

.github/workflows/build_and_deploy.yml
We (_I_ 😅) want to condense the deployment message.
Update PR comment format into a table.
See the deployment message below.
=> Update the format of the deployment comment into a table

.github/actions/deploy-environment/action.yml, .github/workflows/build_and_deploy.yml, .github/workflows/delete_review_app.yml, Makefile, terraform/application/.terraform.lock.hcl, terraform/application/terraform.tf
Trello card
https://trello.com/c/3m8PNLG6/937-enable-azure-rbac-deployment-on-all-services
Context
Enable azure rbac on deployment (for when it is enabled in the cluster)
Changes proposed in this pull request
Update Makefile, terraform and workflows to use rbac if configured for the cluster
Guidance to review
make env terraform-plan
=> Added RBAC to project

.github/workflows/build_and_deploy.yml
Fix build: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/7725855516/job/21061601423
Fix seed step after RBAC change
Code review: Same as the other workflow steps with make
https://trello.com/c/3m8PNLG6
=> [937] Add missing PR_NUMBER

README.md, docs/connect-to-azure.md
I've updated the documentation following a walk-through with the developers on the team. Missed steps have been added and hints added where helpful.
I've also updated the README to include the new `asdf` plugins that this project uses.
This is in a separate PR because #190 was accidentally merged in early.
https://github.com/DFE-Digital/itt-mentor-services/blob/update-azure-documentation/docs/connect-to-azure.md
=> Update documentation for connecting to Azure

Makefile
Enable precise Azure finance reporting for this service
Update the Product tag. It has been applied manually already to the review and QA environments.
Check Product tag on resource groups:
- https://portal.azure.com/#@platform.education.gov.uk/resource/subscriptions/20da9d12-7ee1-42bb-b969-3fe9112964a7/resourceGroups/s189t01-ittms-rv-rg/overview
- https://portal.azure.com/#@platform.education.gov.uk/resource/subscriptions/20da9d12-7ee1-42bb-b969-3fe9112964a7/resourceGroups/s189t01-ittms-qa-rg/overview
https://trello.com/c/LYorZnzO
=> [829] Update Product tag

spec/system/placements/support/support_users/support_user_adds_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_views_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_views_support_users_spec.rb
Currently Rspec is broken due to a merge of 2 PRs at similar times.
Broken tests now use DfE Sign in Method instead of Persona
run `bundle exec rspec`
=> Fix broken rspec since test login change to DfE

README.md
I've updated the README file to include the new dependencies introduced by #219.
I've also tried restructuring the file slightly to make it read more clearly and simpler to follow.
=> Add new dependencies to README

app/mailers/test_mailer.rb, app/views/test_mailer/dummy_email.text.erb
To improve our test coverage, we want to remove any unused files and classes.
- Remove `TestMailer`
- Remove `app/views/notify_mailer/send_school_invite_email.text.erb`
SimpleCov should not fail.
=> Drop TestMailer and unused mailer view

.rubocop.yml, spec/tasks/gias_update_spec.rb
Rubocop rules
Enable the stubbed mock rule and fix on violation
Test pass, linter passes
=> Enable stubbed mock rule

.rubocop.yml, spec/system/claims/invite_a_user_to_a_school_spec.rb, spec/system/claims/support/schools/invite_a_user_to_a_school_spec.rb, spec/system/claims/view_a_users_details_spec.rb, spec/system/claims/view_organisations_spec.rb, spec/system/claims/view_schools_as_support_user_spec.rb, spec/system/claims/view_users_of_a_school_spec.rb, spec/system/placements/view_organisations_spec.rb
Enable RSpec/InstanceVariable rubocop rule
rubocop
specs
tests pass?
=> Enable RSpec/InstanceVariable rubocop rule

spec/support/dfe_sign_in_user_helper.rb, spec/system/claims/sign_in_as_a_claims_user_spec.rb, spec/system/claims/sign_out_as_claims_user_spec.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb, spec/system/placements/sign_out_as_a_placements_user_spec.rb
We want to increase our testing code covrage. This PR adds specs to sign out path and when the omniauth payload from dfe sign in is empty.
Specs
Do tests pass?
=> Test Sign out and dfe sign in bad response

spec/system/claims/sign_in_as_a_claims_user_spec.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb
Test normal user trying to access support page
Claims and placements Sign in specs 
Review
Do tests pass?
=> Test normal user trying to access support page

app/controllers/claims/support/schools_controller.rb, app/controllers/placements/support/providers_controller.rb, app/controllers/placements/support/schools_controller.rb, app/forms/provider_onboarding_form.rb, app/forms/school_onboarding_form.rb, spec/forms/provider_onboarding_form_spec.rb, spec/forms/school_onboarding_form_spec.rb
Refactor SchoolOnboardingForm and ProviderOnboardingForm to align with documents https://github.com/DFE-Digital/itt-mentor-services/blob/main/docs/conventions/form_objects.md
Changes to code to align with documentation https://github.com/DFE-Digital/itt-mentor-services/blob/main/docs/conventions/form_objects.md and to inherit from ApplicationForm
https://trello.com/c/Oi0FciHC/199-align-schoolonboardingform-and-provideronboardingform-with-documentation
=> Refactor organisation onboarding forms to align with docs

app/controllers/claims/schools/users_controller.rb, app/controllers/claims/support/schools/users_controller.rb, app/controllers/placements/organisations/users_controller.rb, app/controllers/placements/support/organisations/users_controller.rb, app/forms/user_invite_form.rb, spec/forms/user_invite_form_spec.rb
Refactor UserInviteForm to align with documents https://github.com/DFE-Digital/itt-mentor-services/blob/main/docs/conventions/form_objects.md
Changes to code to align with documentation https://github.com/DFE-Digital/itt-mentor-services/blob/main/docs/conventions/form_objects.md and to inherit from ApplicationForm
https://trello.com/c/SOVhz3cx/198-align-userinviteform-with-documentation
=> Align UserInviteForm with Docs

adr/00005-user-authorisation-using-pundit.md
We want a scalable pattern of working with user permissions.
Add the ADR to adopt Pundit for User permissions.
View the rendered ADR: https://github.com/DFE-Digital/itt-mentor-services/blob/adr/user-authorisation/adr/00005-user-authorisation-using-pundit.md
=> Add User Authorisation ADR

app/controllers/claims/schools/mentors_controller.rb, app/views/claims/schools/_primary_navigation.html.erb, app/views/claims/schools/mentors/index.html.erb, app/views/claims/support/claims/index.html.erb, config/locales/en.yml, config/locales/en/claims/schools/mentors.yml, config/locales/en/claims/schools/primary_navigation.yml, config/locales/en/claims/support/claims.yml, config/locales/en/claims/support/schools/mentors.yml, config/routes/claims.rb, db/seeds.rb, spec/system/claims/schools/mentors/view_mentors_spec.rb, spec/system/claims/support/schools/mentors/view_mentors_spec.rb
This PR adds the index page for mentors for normal and support users. In the claims doamin
- Mentors index page for normal user
- Mentors index page for support users
- Fix seed file
Visit `claims.localhost:3000/schools/:school_id/mentors`
Visit `claims.localhost:3000/support/schools/:school_id/mentors` as support user
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/0ff6b44f-2057-4e9e-9472-6dc0a3a7783e
=> Add claims mentors index for support and normal users

docs/data-model.md
As we've made some updates with the introduction of the `MentorMembership` model, we should update the documentation here.
Update the documentation to reflect the `MentorMembership` model addition.
- View the [rendered version](https://github.com/DFE-Digital/itt-mentor-services/blob/dd/update-data-model-from-mentor-memberships/docs/data-model.md) ✨
=> Update Data Model documentation with MentorMembership updates

terraform/application/application.tf
Now that we've got GoodJob configured (see #297), I am tweaking the Terraform configuration so that a GoodJob worker process runs in Azure to process background jobs.
Special thanks to @saliceti for [helping me][1] with this. 🙌
[1]: https://ukgovernmentdfe.slack.com/archives/C06962474AC/p1708445829067419
https://trello.com/c/9uy2ArZJ/217-set-up-active-job
=> Run GoodJob workers in Azure

docs/active-job.md
Following the introduction of GoodJob in #297, I've added documentation with some useful details for developers.
I've added documentation which covers:
- Our choice of job runner (GoodJob)
- How to access the admin dashboard
- How scheduled tasks are configured
[See the rendered document here](https://github.com/DFE-Digital/itt-mentor-services/blob/document-good-job/docs/active-job.md) ✨
The final checklist item in this card: https://trello.com/c/9uy2ArZJ/217-set-up-active-job
=> Add documentation for Active Job

app/controllers/placements/schools/placements_controller.rb, app/models/mentor.rb, app/models/placement.rb, app/models/subject.rb, app/views/placements/schools/placements/remove.html.erb, app/views/placements/schools/placements/show.html.erb, config/locales/en/placements/schools/placements.yml, config/routes/placements.rb, spec/models/mentor_spec.rb, spec/models/placement_spec.rb, spec/models/subject_spec.rb, spec/system/placements/schools/placements/remove_a_placement_spec.rb
School Users need to ability to remove placements.
Add Views/Controller methods/Routes/etc. to allow Schools Users the ability to remove placements.
_Review should be based on the [prototype](https://school-placements-beta-dev-73591d8bbe5f.herokuapp.com/)_
_Screenshots of Prototype (29/02/2024)_
_Note: Adding a placement is not part of this PR and therefore buttons and functionality are missing_
- (Assuming you have placements in her school, if not run the seed data)
- Click the "Placements" nav option
- This will display the index page of placements for that school
- Click on the link to view the first placement
- This will direct you to the show page of this placement.
- Click the "Remove placement" link
- This should redirect you the "Are you sure?" page
- Click the …
=> School user can remove placements

app/services/concerns/regional_areas.rb, app/services/gias_csv_importer.rb, db/seeds.rb
- Improve speed of Seed Data running
- Improve GIAS CSV Importer when assigning region
- Improve speed of Seed Data running
- Schools are assigned regions is bulk, not iterated over.
- Run `bundle exec rake db:drop db:create db:setup`
- Running seed data should be quicker.
https://trello.com/c/LnEuYhc0/165-seed-data-efficiency-and-clean-up
=> Improve seed data efficiency

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/forms/claim/provider_form.rb, app/models/claim.rb, db/migrate/20240307100355_add_created_by_to_claims.rb, db/schema.rb, spec/factories/claims.rb, spec/forms/claim/provider_form_spec.rb, spec/models/claim_spec.rb
We need to know who created the claim, a polymorphic column will accommodate users and support users creating claims
- Migration
- Claims Controller changes
- Claim provider form changes
Create a claim
Check if the claim belongs to the current user in the rails console
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/5d405fbb-3c78-41b4-8f83-a337dcb60c7c
=> Add created_by to Claim

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/initializers/semantic_logger.rb
- Add semantic logging to app.
- Add semantic logging to app.
- run `bin/dev` 
- console should show logging
https://trello.com/c/Fs6nUjyw/173-integrate-with-kibana-for-application-logs
=> Add semantic logger to service

app/components/pagination_component.html.erb, app/components/pagination_component.rb, app/controllers/claims/schools/users_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/controllers/claims/support/schools/users_controller.rb, app/controllers/claims/support/support_users_controller.rb, app/views/claims/schools/claims/index.html.erb, app/views/claims/schools/mentors/index.html.erb, app/views/claims/schools/users/index.html.erb, app/views/claims/support/schools/claims/index.html.erb, app/views/claims/support/schools/users/index.html.erb, app/views/claims/support/support_users/index.html.erb, spec/components/pagination_component_spec.rb, spec/components/previews/pagination_component_preview.rb
Some index pages don't have paginations and there is some logic around them so I thought to create a component for it.
Pagination Component
Claims Index pages
Pull this on local
Change pagination records per page in the pagy initializer
Check all index pages have pagination
=> Add Pagination to claims and create Pagination component

app/helpers/routes_helper.rb, spec/components/placement/status_tag_component_spec.rb, spec/forms/placements/mentor_form_spec.rb, spec/helpers/hosting_environment_helper_spec.rb, spec/helpers/placements/support/organisations_helper_spec.rb, spec/helpers/routes_helper_spec.rb, spec/models/mentor_spec.rb, spec/models/placement_mentor_join_spec.rb, spec/models/placement_spec.rb, spec/models/placements/school_spec.rb, spec/models/provider_spec.rb, spec/models/school_spec.rb, spec/models/service_update_spec.rb, spec/models/subject_spec.rb, spec/models/user_membership_spec.rb, spec/models/user_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb
As part of learning more about our codebase I opted to go through the application file by file and compare them to their corresponding `*_spec.rb` files. Increasing our code coverage where there were missed or outdated tests seemed like an easy value add whilst I was onboarding.
- Updated some tests to add missed methods and associations
- Added new spec files where none were present
Run the test suite and make sure all tests are passing and that I have not made any stylistic decisions that go against the app's code style.
[Investigate and improve test coverage](https://trello.com/c/psXhmCl9)
=> Update app tests

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/models/claim.rb, config/locales/en/claims/pages.yml, config/locales/en/claims/schools/claims.yml, spec/models/claim_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb, spec/system/claims/start_page_spec.rb
After product review a few content changes were necesasary and a scope to order by created_at DESC has been added
Locals
Scopes
Review code
=> Order claims by created_at DESC and content changes

app/helpers/footer_helper.rb, app/helpers/routes_helper.rb, app/views/claims/pages/accessibility.html.erb, app/views/claims/pages/cookies.html.erb, app/views/claims/pages/terms.html.erb, config/locales/en/claims/pages.yml, config/routes/claims.rb, spec/helpers/routes_helper_spec.rb, spec/system/claims/accessibility_spec.rb, spec/system/claims/cookies_page_spec.rb, spec/system/claims/start_page_spec.rb, spec/system/claims/terms_page_spec.rb
Some of the content will change after content review but most of it will remain in place
- Accessibility & cookies & terms pages
Review the content on these pages.
Prototype: https://itt-mentoring-beta-dev-a238297da236.herokuapp.com/accessibility
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/c06401c2-2a1a-4f80-8d4f-0d56a5c05d09
=> Accessibility, Cookies and Terms pages

adr/00006-geocoding-schools.md
- Add ADR documentation for Geocoding using the Geocoder gem
- Add ADR documentation for Geocoding using the Geocoder gem
https://trello.com/c/dLqmhkGQ/192-adr-for-decision-to-use-geocoder-gem-to-geocode-schools
=> Add ADR for geocoding

app/helpers/footer_helper.rb, app/helpers/routes_helper.rb, app/views/claims/pages/privacy.html.erb, config/locales/en/claims/pages.yml, config/routes/claims.rb, spec/system/claims/privacy_page_spec.rb
Privacy page
Footer helper
Review content
=> Privacy page

app/views/claims/schools/claims/confirm.html.erb, config/locales/en/claims/schools/claims.yml
Just a small content change on the claim confirm page. 
Translations
Review Changes
=> Change content on claim confirmation page

Makefile, global_config/dv_review.sh, terraform/application/.terraform.lock.hcl, terraform/application/config/dv_review.tfvars.json, terraform/application/config/dv_review_Terrafile, terraform/application/config/dv_review_app_env.yml, terraform/application/variables.tf
In order to test infrastructure changes, it's useful to deploy the app to a dev cluster
Create the dv_review environment
- Deploy a dev cluster
- Deploy app using: make dv_review terraform-apply CLUSTER=clusterx
https://trello.com/c/WTWtPR8H
=> [906] Create dv_review environment

app/assets/stylesheets/application.scss, app/assets/stylesheets/lists.scss, app/helpers/footer_helper.rb, app/helpers/routes_helper.rb, app/views/claims/pages/grant_conditions.html.erb, config/locales/en/claims/pages.yml, config/locales/en/layouts/footer.yml, config/routes/claims.rb, spec/system/claims/grant_conditions_spec.rb
We need to add a guidance to our claims service
guidance
list with dash
Review content
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/bbd60811-9796-4f82-baf6-af2515a9e0eb
=> Add grant conditions to claims

app/helpers/footer_helper.rb, app/helpers/routes_helper.rb, config/locales/en/layouts/footer.yml, spec/helpers/footer_helper_spec.rb, spec/helpers/routes_helper_spec.rb
This should make the footer helper a bit easier to scale for both services.
footer_helper.rb
=> Refactor footer helper to accommodate both services

app/controllers/claims/schools/claims_controller.rb, app/helpers/application_helper.rb, app/models/claim.rb, app/views/claims/schools/claims/show.html.erb, app/views/claims/support/schools/claims/show.html.erb, db/migrate/20240322145705_add_submitted_by_to_claim.rb, db/schema.rb, spec/factories/claims.rb, spec/models/claim_spec.rb, spec/system/claims/schools/claims/view_claim_spec.rb, spec/system/claims/support/schools/claims/view_claim_spec.rb
We need to show who submitted the claim on the claims show page.
Migration
views
Submit a claim and visit the claim show page
Visit a draft claim show page.
=> Add submitted_by to claim

.github/workflows/build_and_deploy.yml, Makefile, global_config/sandbox.sh, terraform/application/config/sandbox.tfvars.json, terraform/application/config/sandbox_Terrafile, terraform/application/config/sandbox_app_env.yml
Create a sandbox environment for ITTMS (school-placements/track-and-pay)
- Add terraform configuration for sandbox environment
- Add environment variables for the sandbox environment
- Update Makefile with the sandbox env 
- Add sandbox to the workflow
https://track-and-pay-sandbox.teacherservices.cloud,
https://manage-school-placements-sandbox.teacherservices.cloud
https://trello.com/c/5Op8qKHP/1666-ittms-create-sandbox-environment
=> Create sandbox environment

docs/data-model.md
- Currently the data model is out of date.
- Update the data model with table column information and update relationships.
- View changes at https://github.com/DFE-Digital/itt-mentor-services/blob/a676e99fc6c23b38e63c8d457fd991398c8a84f7/docs/data-model.md
https://trello.com/c/fmiJ2anE/184-update-the-data-model-document
=> Update data model

Gemfile, Gemfile.lock, terraform/application/config/qa_app_env.yml, terraform/application/config/staging_app_env.yml
We want to track transaction times
Setup qa and staging with skylight gem, following the docs https://www.skylight.io/support/environments#enabling-additional-environments
Secret keys have been added to the secret vault
=> Add skylight to qa and staging

.github/workflows/deploy.yml
Added new workflow which can be used to manual deployments
New workflow for manual deployments.
The work will be used for review and qa this can be expanded for other environments.
https://trello.com/c/C1sBpxLz/1717-ittms-manual-deployment-workflow
=> Added workflow for manual deployments

.github/workflows/deploy.yml
Bug fix to pass sha for docker tag
Removed hardcoding for docker tag
=> Bug fix to pass sha

.github/workflows/build_and_deploy.yml
The staging environmene was not added to the deployment workflow because of the ITHC.
It should now be added back and deployed alongside QA and sandbox.
Add staging to deployment workflow
[](https://trello.com/c/gKyQAvWi/1724-ittms-add-staging-to-deployment-workflow)
=> Add staging to deployment workflow

.github/workflows/deploy.yml
Slack notification condition is not working
Updated if condtion for slack notification
https://trello.com/c/C1sBpxLz/1717-ittms-manual-deployment-workflow
=> Bug fix for Slack trigger

.github/workflows/build_and_deploy.yml, Makefile, global_config/production.sh, terraform/application/.terraform.lock.hcl, terraform/application/application.tf, terraform/application/config/production.tfvars.json, terraform/application/config/production_Terrafile, terraform/application/config/production_app_env.yml, terraform/application/database.tf, terraform/application/terraform.tf, terraform/application/variables.tf, terraform/domains/environment_domains/.terraform.lock.hcl, terraform/domains/environment_domains/config/production.tfvars.json, terraform/domains/environment_domains/config/production_Terrafile, terraform/domains/environment_domains/main.tf
WHY: The prod environment is the most important and public facing
HOW: By creating Makefile entry and adding other tf resource files
Added the prod environment to ITTMS
Added prod environment by making makefile entry and adding tf resources
make development terraform-kubernetes-apply 
https://trello.com/c/3jvfiAei/1667-ittms-create-production-environment
ensure links work
ensure dfe sign in works
ensure monitoring works
ensure pipeline works
=> Added production environment

README.md
- A requirement to qualify for Skylight OSS.
- It's also nice to see the status at a glance in the repo.
- Add the Skylight status for this app to the README.md.
- Click on the badge.
=> Add Skylight status badge to README.md

terraform/application/config/production.tfvars.json, terraform/application/config/sandbox.tfvars.json, terraform/application/config/staging.tfvars.json, terraform/application/statuscake.tf, terraform/application/terraform.tf, terraform/application/variables.tf
added statuscake to prod and staging
to add status cake alerts 
statuscake resources are created for prod and staging
https://trello.com/c/j0ZXrApw/1726-ittms-statuscake-monitoring
=> added statuscake alerts

terraform/application/config/production.tfvars.json, terraform/application/config/staging.tfvars.json
Enabled azure backup storage for staging
Enabled azure backup storage for staging
=> Enabled azure backup storage for staging

.github/workflows/database-backup.yml
Workflow for production database backup.
Created New Workflow and scheduled early morning 3 AM to take DB backups to azure storage.
Test is done on this feature branch  : https://github.com/DFE-Digital/itt-mentor-services/actions/runs/8874816721/job/24362956458
https://trello.com/c/QXV3IPgZ/1743-backup-ittms-production-database
=> Production db backup workflow

terraform/application/application.tf
Ship logs to store them and query them in the Logit ELK stacks
Enable Logit in web and worker apps
- Access Kibana in test: https://kibana-uk1.logit.io/s/b2876053-0173-44fc-983d-99567292ba31/
- Search for the review app logs: `kubernetes.deployment.name: "itt-mentor-services-551"`
https://trello.com/c/xLqKFk6U
=> [1685] Ship logs to Logit.io

app/views/claims/schools/_grant_conditions.html.erb
From feedback received from our partners, we need to update the grant conditions.
- Update the payment terms in the grant conditions.
- Compare content to the [prototype](https://itt-mentoring-beta-dev-a238297da236.herokuapp.com/grant-conditions).
=> Update grant conditions content

app/views/claims/pages/start.en.html.erb, app/views/claims/schools/grant_conditions/show.html.erb, config/locales/en/claims/schools/mentors.yml, config/locales/en/claims/support/schools/mentors.yml, spec/system/claims/schools/mentors/add_a_mentor_spec.rb, spec/system/claims/start_page_spec.rb, spec/system/claims/support/schools/mentors/support_user_adds_a_mentor_spec.rb
We need to update the content on various pages from our content review.
- Update content to match the [prototype changes](https://github.com/DFE-Digital/itt-mentoring-beta-prototype/pull/98).
- Compare the changes here with the prototype.
=> Update content from content review

app/views/claims/schools/users/check.html.erb, app/views/claims/support/schools/check.html.erb, app/views/claims/support/schools/users/check.html.erb, config/locales/en/claims/schools/users.yml, config/locales/en/claims/support/schools.yml, config/locales/en/claims/support/schools/claims.yml, config/locales/en/claims/support/schools/users.yml, config/locales/en/claims/support/support_users.yml, config/locales/en/claims/support/users.yml, spec/system/claims/schools/users/invite_a_user_to_a_school_spec.rb, spec/system/claims/schools/users/view_users_spec.rb, spec/system/claims/support/schools/add_a_school_spec.rb, spec/system/claims/support/schools/add_a_school_without_javascript_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/invite_a_user_to_a_school_spec.rb, spec/system/claims/support/support_users/add_a_support_user_spec.rb, spec/system/claims/support/support_users/re_add_a_discarded_support_user_spec.rb
We want our `Add` buttons that create records to be named `Save`
Views
Locals
Specs
Review changes and review app
=> Change Add buttons to Save buttons

terraform/application/config/dv_review_app_env.yml, terraform/application/config/production_app_env.yml, terraform/application/config/qa_app_env.yml, terraform/application/config/review_app_env.yml, terraform/application/config/sandbox_app_env.yml, terraform/application/config/staging_app_env.yml
This PR refactors the YAML files which provide environment variables into the Azure hosting environments. I've moved the variables together into logical groupings, and have added comments to explain the purpose of each one.
I've done this to try and give some more structure to these files, since they were quite hard to read and inconsistently formatted between different environments.
I have:
- Added comments to describe what the environment variables are used for
- Reordered keys into logical groupings
I have not changed the keys or values of any environment variables.
You can verify that no changes have been made by running:
```bash
for file in terraform/application/config/*_app_env.yml; do
env_before=$(git show HEAD^:"$file" | yq '... comments="" | sort_keys(..)')
env_after=$(cat …
```
=> Refactor YAML files for environment variables

app/views/placements/pages/landing-page.md, app/views/placements/pages/start.html.erb
- Content changes to start/landing page.
- Changes to content in landing-page markdown
- visit http://placements.localhost:3000/
https://trello.com/c/JNdq8MBI/348-start-page-update
=> Updates to start page content

app/views/claims/support/schools/mentors/new.html.erb, config/locales/en/claims/support/schools/mentors.yml, spec/system/claims/support/schools/mentors/support_user_adds_a_mentor_spec.rb
Not much, just content update
Removed help trn link
Add school name to the page
Review changes
=> Update content for support add mentor

Gemfile, Gemfile.lock, config/initializers/strong_migrations.rb
- Add [strong migrations](https://github.com/ankane/strong_migrations) gem
- Add [strong migrations](https://github.com/ankane/strong_migrations) gem to Gemfile
- https://trello.com/c/lf6ymXqb/367-add-the-strongmigrations-gem
=> Add strong migrations gem

db/migrate/20240520141009_add_parent_subject_to_subjects.rb, db/migrate/20240520141421_add_subject_to_placements.rb
- Quick fix for migrations written before adding strong migrations gem.
=> Quick fix to get migrations to run

app/services/placements/importers/provider_users_importer.rb, app/services/placements/importers/school_users_importer.rb, spec/fixtures/placements/importers/provider_users.csv, spec/fixtures/placements/importers/school_users.csv, spec/services/placements/importers/provider_users_importer_spec.rb, spec/services/placements/importers/school_users_importer_spec.rb
We need a way to import our initial users into the application. We have sent out emails including MS forms that feed a CSV file in the background. Now we just need a way to get them into the system.
Grab one of these CSV templates or create your own if you're feeling spicy:
| URN | First name | Last name | Email address |
|------| -----------|-----------|---------------|
| 114433 | John | Smith | j.smith@example.com |
| UKPRN | First name | Last name | Email address |
|--------| -----------|-----------|---------------|
| 10052837 | Jane | Doe | j.doe@example.com |
**_NB: This assumes you have run the GIAS importer and not made any major changes to your provider and/or school data. If you have you'll need to supply your own valid URN & UKPRN respectively._**
[Build a Rake task to onboard …
=> Create school users importer

Dockerfile
Fix issues with docker file https://github.com/DFE-Digital/itt-mentor-services/actions/runs/9206073139/job/25324002911?pr=673
- Update docker file to use postgres14
- Pin ruby image to 3.3.1-alpine3.20
=> Update and pin versions in dockerfile

docs/environment-variables-in-azure.md
This PR adds documentation for managing environment variables in Azure-hosted environments.
[See the rendered document](https://github.com/DFE-Digital/itt-mentor-services/blob/document-env-vars-and-secrets/docs/environment-variables-in-azure.md) ✨
=> Document how to configure environment variables

app/views/placements/placements/show.html.erb, app/views/placements/schools/placements/index.html.erb, app/views/placements/schools/placements/show.html.erb
- Add status to provider placements index, and school placements index and show pages
- Add `Placement::StatusTagComponent` to school/provider show and index pages where missing
Visit:
_Provider_ (Sign in as Patricia)
https://manage-school-placements-678.test.teacherservices.cloud/placements/c700572d-8ab9-4f39-b549-e8dd6f5aecfa
-------
_School_ (Sign in as Anne)
https://manage-school-placements-678.test.teacherservices.cloud/schools/00038dc8-f45d-4ca9-8c8a-99a4d92f465c/placements
https://manage-school-placements-678.test.teacherservices.cloud/schools/00038dc8-f45d-4ca9-8c8a-99a4d92f465c/placements/442c1599-7ced-490a-accf-2dce3ca7e1c9
https://trello.com/c/h0IUe0YA/377-add-status-to-placements-views-for-schools
_Provider (Placements show page)_
_School (Placements index and show page)_
=> Add missing status to provider placement show and school placement index and show pages

app/views/claims/pages/privacy.en.html.erb
We want to update the Privacy page content.
- Update the `/privacy` page content.
- Compare the content and links to [the prototype](https://itt-mentoring-beta-dev-a238297da236.herokuapp.com/privacy).
=> Update Claims privacy page content

app/controllers/placements/schools/placements_controller.rb, app/views/placements/schools/placements/remove.html.erb, app/views/placements/schools/placements/show.html.erb, config/locales/en/placements/schools/placements.yml, spec/system/placements/schools/placements/delete_a_placement_spec.rb, spec/system/placements/schools/placements/edit_a_provider_spec.rb, spec/system/placements/schools/placements/edit_mentors_spec.rb, spec/system/placements/schools/placements/view_a_placement_spec.rb
- A selection of changes to the Placements show page.
- Change "Remove placement" to "Delete placement"
- Condition link changes for:
- Mentors: 
- School with no mentors: Add a mentor
- School with mentors: Select a mentor
- Placement with mentor: Change
- Providers:
- School with no partner providers: Add a partner provider
- School with partner providers: Assign a provider
- Placement with provider: Change
- Navigate to "Placements" using the Navbar
- Click on a Placement
- Check the buttons change and act accordingly to the different conditions
https://trello.com/c/UhKboGKs/389-school-user-placement-details-page
_Changes from "Remove" to "Delete"_
_Conditional Links_
- Mentors
- School has no mentors (Add a mentor)
- Placement has no mentor/mentors …
=> Changes to the placements details page

app/views/placements/schools/mentors/check.html.erb, app/views/placements/schools/mentors/new.html.erb, app/views/placements/support/schools/mentors/check.html.erb, app/views/placements/support/schools/mentors/new.html.erb, config/locales/en/placements/schools/mentors.yml, config/locales/en/placements/support/schools/mentors.yml, spec/system/placements/schools/mentors/user_adds_mentor_spec.rb
- To align with the prototype
- New/Find Teacher
- Change H1 to “Find teacher”
- Add a regular-sized label to the TRN input: “Teacher reference number (TRN)” 
- Check your answers
- I confirm that {mentor name} has been informed that the Department for Education will store their information in line with the [privacy notice](https://github.com/DFE-Digital/itt-mentor-services/compare/jc/content_changes_to_add_mentor_journey?expand=1#) and have provided them with a copy of this notice for reference.
- The ‘privacy notice’ link should go to the privacy page (content has not yet been provided for this page).
- Navigate to "Mentors" using the Navbar
- Click the "Add mentor" button
- Check the page appears with the correct Title, Caption and Input label
- Fill out …
=> Content changes to add mentor pages

app/controllers/placements/providers/partner_schools_controller.rb, app/controllers/placements/schools/partner_providers_controller.rb, app/controllers/placements/support/providers/partner_schools_controller.rb, app/controllers/placements/support/providers_controller.rb, app/controllers/placements/support/schools/partner_providers_controller.rb, app/controllers/placements/support/schools_controller.rb, app/views/placements/providers/partner_schools/check.html.erb, app/views/placements/schools/partner_providers/check.html.erb, app/views/placements/support/providers/check.html.erb, app/views/placements/support/providers/partner_schools/check.html.erb, app/views/placements/support/schools/check.html.erb, app/views/placements/support/schools/partner_providers/check.html.erb, app/views/shared/organisations/_organisation_details.html.erb, config/locales/en/shared/organisations/organisation_details.yml
- Add change link (which act as back links) to organisation related "Check your answers" pages.
- Provider -> Add partner school
- School -> Add partner provider
- (Support) Provider -> Add partner school
- (Support) School -> Add partner provider
- (Support) Add organisation -> ITT provider
- (Support) Add organisation -> School
- Follow the flows of each process (See context)
- When reaching the "Check your answers" page, click the "Change" links, to test they redirect you back to the previous page (with pre-filled input boxes)
https://trello.com/c/WilfnHVe/407-add-a-partner-school-provider-%E2%86%92-check-your-answers-page
- School -> Add partner provider
- Provider -> Add partner school
- (Support) Provider -> Add partner school
- (Support) School -> Add partner provider
- (Support) …
=> Add change links across org check pages

app/models/placement.rb
- Fix to allow data migrations to run on review apps.
=> Fix for data-migrations with enums in review apps

app/views/placements/providers/users/show.html.erb
The link styling is not consistent with other areas of the application
- Add a user
- View the user
- See that the remove link matches the rest of the app
[Fix styling of the "Remove user" link for partner users](https://trello.com/c/UGeobjCs)
|Before|After|
|------|-----|
| ![image](https://github.com/DFE-Digital/itt-mentor-services/assets/16797406/31f0289a-b016-4d33-87fc-46920b2def67) | ![image](https://github.com/DFE-Digital/itt-mentor-services/assets/16797406/d0c059d3-2bc5-4add-a179-ad3f7d270402) |
=> Update link styling to match other areas of the app

app/services/placements/importers/provider_users_importer.rb, app/services/placements/importers/school_users_importer.rb, spec/services/placements/importers/provider_users_importer_spec.rb, spec/services/placements/importers/school_users_importer_spec.rb
=> Fix UserInvite calls

app/models/claims/provider.rb, app/models/claims/school.rb, app/models/placements/provider.rb, app/models/placements/school.rb, app/models/provider.rb, app/models/school.rb, db/migrate/20240607104802_add_trigram_index_to_schools.rb, db/migrate/20240607105222_add_trigram_index_to_providers.rb, db/schema.rb, spec/factories/providers.rb, spec/factories/schools.rb, spec/models/claims/provider_spec.rb, spec/models/claims/school_spec.rb, spec/models/placements/provider_spec.rb, spec/models/placements/school_spec.rb, spec/models/provider_spec.rb, spec/models/school_spec.rb
Increase the perfomance of the `pg_search_scope` for schools and providers
Verify that searching for schools/providers is faster
[Optimise performance of the pg_search queries for Provider and School autocompletes](https://trello.com/c/osnppX7v/459-optimise-performance-of-the-pgsearch-queries-for-provider-and-school-autocompletes)
=> Add GIN indexes for the trigram searches used by pg_search

config/locales/en/user_mailer.yml, spec/mailers/user_mailer_spec.rb, spec/system/placements/providers/partner_schools/add_a_partner_school_spec.rb, spec/system/placements/providers/partner_schools/add_a_partner_school_without_javascript_spec.rb, spec/system/placements/providers/partner_schools/remove_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_without_javascript_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_remove_a_partner_school_spec.rb
We are expanding all acronyms in the application
- Verify the content has changed according to content design
[Updates to email notification content](https://trello.com/c/NQBLORCF/471-updates-to-email-notification-content)
=> Update email notification subject for adding/removing partner schools

app/views/placements/schools/placements/edit_provider.html.erb, config/locales/en/placements/schools/placements.yml
- Context changes to the Mentor and Provider guidance.
- Navigate to Placements using the Navbar
- Check the following pages to check the context of the guidance:
- Add placement -> Mentor
- Manage placement ->  Mentor
- Manage placement -> Provider
https://trello.com/c/gEKQEfNX/437-content-changes-guidance-text
_Add placement -> Mentor_
_Manage placement ->  Mentor_
_Manage placement -> Provider_
=> Update mentor and provider guidance

app/views/placements/schools/mentors/new.html.erb, app/views/placements/support/schools/mentors/new.html.erb, config/locales/en/placements/schools/mentors.yml, config/locales/en/placements/support/schools/mentors.yml, spec/system/placements/schools/mentors/user_adds_mentor_spec.rb, spec/system/placements/support/schools/mentors/support_user_adds_a_mentor_spec.rb
- Update to TRN guidance
_As Anne (School User)_
- Navigate "Mentors" using the Navbar
- Click "Add mentor"
- Check the Guidance
_As Colin (Support User)_
- Select a School
- Navigate "Mentors" using the Navbar
- Click "Add mentor"
- Check the Guidance
https://trello.com/c/UgbEBlDB/439-content-change-add-a-mentor-trn-details-component
_As support user_
_As school user_
=> Update TRN guidance

app/helpers/routes_helper.rb, spec/helpers/routes_helper_spec.rb
- Replace feedback URL with https://forms.office.com/e/2dZ8gck5Zg
- Click the "feedback" link
- Check it redirects the user to the correct form
https://trello.com/c/L9GzXXxT/489-update-the-feedback-link
=> Replace the feedback url

app/models/claims/provider.rb, app/models/placement.rb, app/models/placements/provider.rb, app/models/placements/schools/placements/build/placement.rb, app/models/provider.rb, db/migrate/20240611145750_add_indexes_to_placements.rb, db/migrate/20240611151728_add_indexes_to_provider.rb, db/schema.rb, spec/factories/placements.rb, spec/factories/providers.rb, spec/models/claims/provider_spec.rb, spec/models/placement_spec.rb, spec/models/placements/provider_spec.rb, spec/models/placements/schools/placements/build/placement_spec.rb, spec/models/provider_spec.rb
- Add index to placements `[:year_group]`
- Add index to providers `[:organisation_type]` 
https://trello.com/c/udznhfVk/488-add-database-indexes-to-support-placements-search-filters
=> Add indexes to help improve filters and searches

app/models/dfe_sign_in_user.rb
- Refactor DfESignInUser model to make Sign In more performant.
- Login in as the various personas.
- Check they redirect to the correct persona's pages
https://trello.com/c/sVIdpOZ1/487-refactor-dfesigninuseruser-to-reduce-the-number-of-database-queries-it-performs
=> Refactor DfE Sign In User

app/helpers/footer_helper.rb, app/views/placements/pages/terms_and_conditions.md, config/locales/en/placements/pages.yml, config/routes/placements.rb, spec/helpers/footer_helper_spec.rb
- Add Terms and Conditions static page
- Click "Terms and conditions" in the footer
- Check the content of the Terms and conditions page
https://trello.com/c/IBzXvu07/482-add-the-terms-and-conditions-page
=> Add terms and conditions static page

docs/placements/bulk-onboard-schools-and-providers.md
How to run the CSV importers on Azure infrastructure.
[See the rendered Markdown document](https://github.com/DFE-Digital/itt-mentor-services/blob/document-how-to-run-import/docs/placements/bulk-onboard-schools-and-providers.md) ✨
=> Document how to import schools and providers

config/locales/en/user_mailer.yml, spec/mailers/user_mailer_spec.rb
As requested by our product manager & content designer.
=> Update heading text in user invitation email

app/controllers/placements/schools/placements/build_controller.rb, app/controllers/placements/schools/school_contacts_controller.rb, app/slack_notifiers/placements/application_slack_notifier.rb, app/slack_notifiers/placements/placement_slack_notifier.rb, app/slack_notifiers/placements/school_slack_notifier.rb
We would like to have real time alerts when users onboard their school or add a new placement
- Verified locally with pair programming
[Create Slack notifiers for new placements and onboarded schools](https://trello.com/c/Ddlsk1kp/498-create-slack-notifiers-for-new-placements-and-onboarded-schools)
=> Create placements slack notifier

Makefile, terraform/application/.terraform.lock.hcl, terraform/application/config/production.tfvars.json, terraform/application/config/sandbox.tfvars.json, terraform/application/config/staging.tfvars.json, terraform/application/statuscake.tf
Add school placements endpoint's to statuscake monitoring.
Endpoints added to staging, sanbox and production
Endpoints added to staging, sanbox and production.
Terraform Plan  Sanbox  :  Adding resources related statuscake and monitoring alerts
Terraform Plan  Staging  :  Adding resources related statuscake and monitoring alerts
Terraform Plan  Production  : Adding resources related statuscake.
Terraform Plan  Production 👍 
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
module.statuscake[0].statuscake_ssl_check.main["https://manage-school-placements.education.gov.uk"] will be created
+ resource "statuscake_ssl_check" "main" {
+ check_interval …
=> Added school placements endpoints to statuscake monitoring

README.md
The README is outdated.
- Update service descriptions.
- Update live environment tables.
Review the [updated README](https://github.com/DFE-Digital/itt-mentor-services/blob/dd/update-readme/README.md).
=> Update service descriptions and live environment tables

spec/system/placements/placements/searching_for_a_placement_spec.rb, spec/system/placements/placements/view_a_placement_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
- Remove the unnecessary JS in Placements tests
=> Remove the unnecessary JS in placements testing

spec/system/placements/placements/searches_filter_options_for_placements_spec.rb
- Improve test coverage of using the search bars in Placement filters to reduce the number of displayed options.
=> Increase coverage of searching filter options

app/controllers/placements/schools/mentors_controller.rb, app/controllers/placements/support/schools/mentors_controller.rb
- Consolidate Placements Mentor Controllers, so `app/controllers/placements/support/schools/mentors_controller.rb` inherits from `app/controllers/placements/schools/mentors_controller.rb`
- Change code so `app/controllers/placements/support/schools/mentors_controller.rb` inherits from `app/controllers/placements/schools/mentors_controller.rb`, reducing duplicated code.
https://trello.com/c/lDtLgwPX/524-consolidate-the-mentors-controllers-for-school-users-and-support-users
=> Consolidate mentor controllers

config/initializers/good_job.rb
- Add sentry errors for GoodJob.
- Add code to GoodJob config to send errors to Sentry
https://trello.com/c/sOBGkliq/560-add-sentry-error-reporting-to-good-job
=> Add sentry errors for goodjob

spec/system/infinite_redirect_spec.rb
- Add coverage for testing infinite redirect
https://trello.com/c/4Jimr5Kr/574-add-test-coverage-for-the-infinite-redirect-scenario
=> Add coverage for infinite redirect

.github/pull_request_template.md
The checklist has not been useful for developers. It is not specific to our service and important things to check should be checked with a CI process.
- Remove the "Things to check" checklist from the PR template.
- Review this PR description?
No Trello card.
No relevant screenshots.
=> Remove "Things to check" from PR template

docs/data-model.md
- Update the ERD 
- Currently the ERD is out of date.
- View the ERD Diagram on the Data Model doc
https://trello.com/c/hoj9z5bo/638-update-model-documentation
=> Update ERD diagram

spec/rails_helper.rb
- Fix for creating ClaimsWindows in rspec using rails helper
=> Fix for rails helper adding claims windows

app/components/autocomplete_select_form_component.html.erb, app/components/autocomplete_select_form_component.rb, app/views/placements/wizards/add_partnership_wizard/_partnership_step.html.erb, config/locales/en/placements/providers/partner_schools/add_partner_school.yml, config/locales/en/placements/schools/partner_providers/add_partner_provider.yml, config/locales/en/placements/support/providers/partner_schools/add_partner_school.yml, config/locales/en/placements/support/schools/partner_providers/add_partner_provider.yml, config/locales/en/placements/wizards/add_partnership_wizard.yml, spec/system/placements/providers/partner_schools/add_a_partner_school_spec.rb, spec/system/placements/providers/partner_schools/add_a_partner_school_without_javascript_spec.rb, spec/system/placements/schools/partner_providers/add_a_partner_provider_spec.rb, spec/system/placements/schools/partner_providers/add_a_partner_provider_without_javascript_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_without_javascript_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_adds_a_partner_provider_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_adds_a_partner_provider_without_javascript_spec.rb
- Content changes for the add partner school and partner provider forms.
- Changes to captions, H1 and hint text for adding partner school and partner provider forms to align with [Lucid](https://lucid.app/lucidspark/262e5d35-0c1f-4f90-aa60-c3b00a9a53ef/edit?invitationId=inv_fe53fead-7afb-41fa-b89f-6c57958d9867&interceptingPaymentFlow=1&page=0_0#)
- Click "Partner providers" in the Navbar
- Click "Add partner provider" button
- The content shown in caption, H1 and hint text should be as requested.
---------
- Sign in as Patricia (Partnership User)
- Click "Partner school" in the Navbar
- Click "Add partner school" button
- The content shown in caption, H1 and hint text should be as requested.
---------
- Click on a school
- …
=> Content changes for partner provider and partner school form flow

app/controllers/placements/schools/placements_controller.rb, app/queries/placements/placements_query.rb, app/services/placements/organisation_finder.rb
It occured to @JamieCleare2525 and I that there may be N+1 issues within placements
Resolve any N+1 issues that were present.
- Not much to check here, no changes to the user experiences. Test suite should be sufficient.
[Remove N+1 queries](https://trello.com/c/Z337yDTv/685-add-bullet-gem)
=> Remove N+1 queries

terraform/application/.terraform.lock.hcl, terraform/application/terraform.tf, terraform/domains/environment_domains/.terraform.lock.hcl, terraform/domains/environment_domains/main.tf, terraform/domains/environment_domains/terraform.tf, terraform/domains/infrastructure/.terraform.lock.hcl, terraform/domains/infrastructure/terraform.tf
Work around a bug in postgres and keep up-to-date
- Update all terraform providers
- Migrate environment_domains to terrafile for consistency
make production terraform-plan DOCKER_IMAGE_TAG=1854eb92f4ef2972b5479015db04b4c2967acfc3
make domains-infra-plan
make production domains-plan
https://trello.com/c/moH45K2M
=> [1839] Update terraform providers

app/models/claims/provider.rb, app/models/placements/provider.rb, app/models/provider.rb, db/schema.rb, spec/factories/providers.rb, spec/models/claims/provider_spec.rb, spec/models/placements/provider_spec.rb, spec/models/provider_spec.rb
It seems that our database schema has gone out of sync at some point. I want to correct the database schema to how it should be by re-running all migrations.
- Ran `rails db:migrate:reset` locally to correct the database state.
- Ran `rails db:migrate:reset` locally to correct the database state.
- There should be no changes to `db/schema.rb`.
=> Clean up migration artifacts

.github/workflows/build_and_deploy.yml
Our standard practice is to run SNYK scanning against build images
Add snyk to build step
Check build workflow log
https://trello.com/c/9g2RL16e/1996-add-snyk-scan-to-cicd
=> Add snyk scan to build workflow

app/models/placements/academic_year.rb
- Add placement specific functionality for AcademicYear model. 
- Create a namespaced vesion of the AcademicYear model that currently exists. 
- App should run as expected. 
- No user facing changes to review.
https://trello.com/c/dpZC4Qlt/702-create-placementsacademicyear-model
=> Create Placements::AcademicYear model

config/analytics.yml, db/data/20240822142444_backfill_placements_academic_year.rb, db/data_schema.rb, db/migrate/20240822141750_add_academic_year_ref_to_placements.rb, db/migrate/20240822142059_add_academic_year_index_to_placements.rb, db/schema.rb
Placements now have a concept of their academic year, this work allows us to reference that data from the placements model.
- Adds the academic year column to placements
- Backfills the placements with the current academic year
- Adds the `academic_year_id` column to the analytics file
- Smoke test the app, there are no user facing changes.
[Associate Placement to Placements::AcademicYear](https://trello.com/c/avhLfMpn/704-associate-placement-to-placementsacademicyear)
=> [Part 1] Associate placements to placements academic year

db/seeds.rb, spec/services/claims/provider/generate_csv_spec.rb
- Seed data fix for missed adding an academic year to placements.
- run `bundle exec rake db:drop db:create db:setup` in terminal
- The seed data should run without validation errrors
```
itt-mentor-services % bundle exec rake db:drop db:create db:setup
W, [2024-08-28T09:37:01.813368 #68427]  WARN -- Skylight: [SKYLIGHT] [6.0.4] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
2024-08-28 09:37:01.865225 I [68427:7260 semantic_logger.rb:7] Rails -- Application logging to STDOUT
Skipping DfE::Analytics initialization
Dropped database 'itt_mentor_services_development'
Dropped database 'itt_mentor_services_test'
Created database 'itt_mentor_services_development'
Created …
```
=> Fix seed data for placement academic year

spec/models/placements/academic_year_spec.rb
Now that the academic year has changed this test failing.
[Fix failing specs on main](https://trello.com/c/EUkyleY7/737-fix-failing-specs-on-main)
=> Fixes failing test in main

db/seeds.rb
The Claims service seeds are failing as we've gone into the new academic year.
- Add the first initial claim window to the seeds.
- Deployments will now work successfully.
=> Update claim window seed

.github/workflows/database-backup.yml, .github/workflows/postgres-ptr.yml, .github/workflows/postgres-restore.yml
Improvements to DR workflows after the DR testing
Updates to backup and restore workflows
- make inputs clearer
- add summary info to workflow output
- allow backup file name override
- manual backup adds 'adhoc' to file name by default, to distinguish from scheduled backup 
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10705032412
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10705158666
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10705315652
https://trello.com/c/cAyHpYMs/2008-dr-test-workflow-updates
=> DR test workflow improvements

.github/workflows/database-backup.yml, .github/workflows/disable-maintenance.yml, .github/workflows/enable-maintenance.yml, .github/workflows/postgres-ptr.yml, .github/workflows/postgres-restore.yml, terraform/application/application.tf
Some recommended fixes from the recent DR test
- add summaries to the maintenance page workflows, which include a list of temp ingresses
- add time completed to DR workflow summaries
- add "send_traffic_to_maintenance_page = false" to terraform application resource to make it easier to find during a DR
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10740836920
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10737646150
make qa terraform-plan
https://trello.com/c/EJSGwGdM/2022-fixes-from-ittms-dr-test-2
=> Recommended fixes from DR test 2

.github/workflows/database-backup.yml
The backup-postgres input was renamed in https://github.com/DFE-Digital/github-actions/pull/98
Update the argument to the action
See the same workflow in TRS: https://github.com/DFE-Digital/teaching-record-system/actions/runs/11167470580
https://trello.com/c/zfjlevny
=> [2034] Update backup DB workflow

app/views/placements/pages/landing-page.md
- Update the content shown on the landing page.
- Update the text on the landing page to that requested in the designs https://dfedigital.atlassian.net.mcas.ms/wiki/spaces/MSP/pages/4548788225/Service+start+page
- View the service landing page.
https://trello.com/c/GWcDeWw5/863-update-the-service-start-page
=> Update service start page

.github/workflows/database-backup.yml, .github/workflows/maintenance.yml, .github/workflows/postgres-ptr.yml, .github/workflows/postgres-restore.yml
Need to update service workflows after updates to related github-actions
Updates to DR workflows, backup db, restores, maintenance
to be merged **after** github-actions pr is merged
Run against updated github-actions branch using the staging env
- backup: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11328445134
- ptr: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11328145369
- ptr backup: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11328519109
https://trello.com/c/JPtELArk/2082-template-github-action-workflows
=> Updates to DR workflow github-actions

.github/workflows/build_and_test.yml, db/seeds.rb
- Update github workflow to run test suite in parallel
- Update github workflow to run test suite in parallel
https://trello.com/c/GD8jT0Pz/868-run-rspec-tests-in-parallel
=> CI changes for parallel testing

db/seeds.rb
- Fix for seed data not running on review apps
- Add condition for seed data to run on review apps
=> Run seed data on review apps

app/models/claims/claim.rb
Now that we have the Claims::TrainingAllowance class we're able to rely on the `remaining_hours` method for this calculation, which allows us to move all of the logic for calculating training allowances to this single source of truth.
I've refactored the `Claims::Claim#valid_mentor_training_hours?` method to use the recently introduced [Training Allowance](https://github.com/DFE-Digital/itt-mentor-services/blob/fc203633fe368d8b6403235efbc16e7ed99c0912/app/models/claims/training_allowance.rb) calculator.
This has allowed me remove another hardcoded reference to the previous training allowance of 20 hours, and instead lean in to the calculator class as being our source of truth for that information.
Try submitting claims for the same mentor + provider combination in two different browser …
=> Calculate Claim validity using Training Allowance

bin/specs-to-refactor
This should make it easier to keep the Trello card up to date.
1. Run the command:
```
bin/specs-to-refactor
```
2. Copy and paste the output into the Trello card:
https://trello.com/c/TayQl2rn/244-refactor-system-specs-to-conform-to-new-style-guide
3. Our card is up to date! 🙌🏻
=> Add a script to list specs that need refactoring

app/models/claims/sampling.rb, config/analytics.yml, db/migrate/20241205142845_create_samplings.rb, db/schema.rb, spec/factories/claims/samplings.rb
This table connects the audit log and provider sampling together.
No user facing functionality, or impact at this stage, so this is purely a code review.
[[Sampling] Create Claims::Sampling model](https://trello.com/c/ltHDEJL7/988-sampling-create-claimssampling-model)
=> Create the `samplings` table and associated files.

app/models/claims/payment.rb, app/models/claims/payment_claim.rb, config/analytics.yml, db/migrate/20241216155501_create_claims_payments.rb, db/migrate/20241216155651_create_claims_payment_claims.rb, db/schema.rb, spec/factories/claims/payment_claims.rb, spec/factories/claims/payments.rb, spec/models/claims/payment_claim_spec.rb, spec/models/claims/payment_spec.rb
In preparation for the claims payment flow and activity logs, we need the payment models in place.
- Add the `payments` table and `payment_claims` table.
- View the ER diagram
=> Add claims payment models

Gemfile, Gemfile.lock
=> Lock undercover to the previous version due to bug that was introduced

app/controllers/claims/clawback/claims_controller.rb, app/mailers/claims/esfa_mailer.rb, app/models/claims/clawback.rb, app/services/claims/clawback/create_and_deliver.rb, app/services/claims/clawback/generate_csv_file.rb, app/views/claims/clawback/claims/error.html.erb, app/views/claims/clawback/claims/index.html.erb, config/locales/en/claims/clawback/claims.yml, config/routes/claims.rb, spec/factories/claims/clawback.rb, spec/mailers/claims/esfa_mailer_spec.rb, spec/models/claims/clawback_spec.rb, spec/services/claims/clawback/create_and_delivery_spec.rb, spec/services/claims/clawback/generate_csv_file_spec.rb, spec/services/claims/payment/create_and_deliver_spec.rb, spec/services/claims/sampling/create_and_deliver_spec.rb, spec/system/claims/clawback/claims/esfa_user_downloads_a_clawback_csv_with_expired_token_spec.rb, spec/system/claims/clawback/claims/esfa_user_downloads_a_clawback_csv_with_invalid_record_token_spec.rb, spec/system/claims/clawback/claims/esfa_user_downloads_a_clawback_csv_with_invalid_token_spec.rb, spec/system/claims/clawback/claims/esfa_user_downloads_clawback_csv_with_valid_token_spec.rb
- Add Clawback services:
- CreateAndDeliver
- GenerateCSVFile
- Add Clawback services:
- CreateAndDeliver
- GenerateCSVFile
- Add routes so users can request the CSV
https://trello.com/c/urwCoaL0/1013-clawbacks-create-sendanddeliver-service
=> Create send and deliver service

config/analytics.yml, config/analytics_blocklist.yml, config/analytics_hidden_pii.yml
Add mentor & user first name and last name to `analytics_hidden_pii.yml` so that this data can be used to identify who made claims.
- Check that the files have been updated as specificed
[Update analytics blocklist](https://trello.com/c/XrzeBDtf/337-update-analytics-blocklist)
=> Update analytics blocklist

terraform/domains/environment_domains/output.tf
adding workflows for domain deployment to build workflows 
add missing output for terraform domain env run.  
review the actions to see the workflows being running. 
review code and decide on best architecture
can see failure caused by missing terraform
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/12906091060/job/35987486421
[Implement CI/CD for domains on all services](https://trello.com/c/unElJf6I/2168-implement-ci-cd-for-domains-on-all-services)
=> CI-CD for domains

config/locales/en/claims/provider_mailer.yml, spec/mailers/claims/provider_mailer_spec.rb
Update the midnight change to 11:59pm
=> Update "midnight" to "11:59pm" on provider mailer

Gemfile
- Temp move Factorybot and Faker to resolve issues with mailer previews.
=> Temp move factory bot and faker to fix mailer previews

Gemfile
Reverts DFE-Digital/itt-mentor-services#1399
=> Revert "Temp move factory bot and faker to fix mailer previews"

spec/services/claims/clawback/generate_csv_file_spec.rb, spec/system/placements/support/support_users/support_user_can_not_remove_themselves_as_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_removes_a_support_user_spec.rb
- Refactor `spec/system/placements/support/support_users/support_user_removes_a_support_user_spec.rb` to use the new style guide.
https://trello.com/c/VlHzIcV3/420-refactor-spec-system-placements-support-supportusers-supportuserremovesasupportuserspecrb
=> Refactor spec/system/placements/support/support_users/support_user_removes_a_support_user_spec.rb

Gemfile, Gemfile.lock, app/views/claims/support/settings/index.html.erb, app/views/placements/support/settings/index.html.erb, config/analytics_blocklist.yml, config/features.rb, config/initializers/flipper.rb, config/locales/en/placements/support/settings.yml, config/routes.rb, db/migrate/20250224091909_remove_flipflop_features.rb, db/migrate/20250224092828_create_flipper_tables.rb, db/schema.rb, docs/feature-flags.md, spec/system/claims/clawback/claims/esfa_user_downloads_clawback_csv_with_valid_token_spec.rb, spec/system/placements/support/support_user_views_feature_flags_spec.rb
We are rolling out to a new area for our private beta and we may wish to test different features in each of our areas. Due to this we need a way to enable features for certain actors.
- Navigate to Settings
- Click on "Feature flags (opens in a new tab)"
- Add a feature flag to ensure everything works
[Investigate feature flag granularity and dashboard](https://trello.com/c/KfHzMUgf/439-investigate-feature-flag-granularity-and-dashboard)
=> Add feature flags for actors

app/views/wizards/placements/multi_placement_wizard/_school_contact_step.html.erb, config/locales/en/wizards/placements/multi_placement_wizard.yml, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_bulk_adds_placements_for_the_primary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_all_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_specific_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_successfully_completes_the_actively_looking_journey_without_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_a_subject_with_child_subjects_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_the_secondary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_does_not_enter_any_school_contact_details_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_no_and_completes_the_interested_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_yes_and_completes_the_interested_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_does_not_enter_any_school_contact_details_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb
- Content changes for School Contact step of MultiPlacementWizard
https://trello.com/c/YOLN8zyZ/465-content-changes-to-school-contact-step-of-multiplacementwizard
=> Content changes for contact step

spec/support/capybara.rb
- Pin Capybara browser version to 128
=> Pin capybara browser version to 128

app/mailers/claims/user_mailer.rb, config/locales/en/claims/user_mailer.yml, spec/mailers/claims/user_mailer_spec.rb, spec/mailers/previews/claims/user_mailer_preview.rb
Bringing content in line with content review feedback
- Review screenshot/review app
[Update claim created email content](https://trello.com/c/PhV1MsJ8/476-update-claim-created-email-content)
=> Update claim_submitted_notification email content

app/controllers/claims/schools/mentors/add_mentor_controller.rb, app/views/wizards/claims/add_mentor_wizard/_check_your_answers_step.html.erb, config/locales/en/claims/schools/mentors.yml, config/locales/en/claims/support/schools/mentors.yml, config/locales/en/wizards/claims/add_mentor_wizard.yml, spec/system/claims/schools/mentors/add_a_mentor_spec.rb, spec/system/claims/support/schools/mentors/support_user_adds_a_mentor_spec.rb
Aligning content after content review.
Review screenshots/review app
[Update content in the claims add mentor flow](https://trello.com/c/v4DpAW07/478-update-content-in-the-claims-add-mentor-flow)
=> Update add mentor journey content

app/controllers/claims/schools/users/add_user_controller.rb, app/views/wizards/claims/add_user_wizard/_check_your_answers_step.html.erb, config/locales/en/claims/schools/users/add_user.yml, config/locales/en/wizards/claims/add_user_wizard.yml, spec/system/claims/schools/users/invite_a_user_to_a_school_spec.rb, spec/system/claims/schools/users/view_users_spec.rb, spec/system/claims/support/schools/invite_a_user_to_a_school_spec.rb
Alinging with latest content review
Review screenshots/review app
[Update content in the claims add user flow](https://trello.com/c/VGlSRZmG/480-update-content-in-the-claims-add-user-flow)
=> Update add user journey content

.github/workflows/build_and_deploy.yml, .github/workflows/delete_review_app.yml, .github/workflows/deploy.yml, Makefile
Update review app resource naming to include -pr- as per our normal standard
Update environment in the Makefile
make review terraform-plan and check the deployed review app for this PR
=> Add pr in resource naming for review apps

app/views/claims/pages/accessibility.en.html.erb, app/views/placements/pages/accessibility.md
Update the accessibility statements for the claim and placement services to the latest version
- Updates the claim service accessibility statement text
- Updates the placement service accessibility statement text
- Placements: View [this link](https://manage-school-placements-pr-1471.test.teacherservices.cloud/accessibility) and compare against the copy in the attached Trello card.
- Claims: View [this link](https://track-and-pay-pr-1471.test.teacherservices.cloud/accessibility) and compare against the copy in the attached Trello card.
[Update accessibility statements for Claim Funding and Manage School Placement services](https://trello.com/c/7QCXWhZG/321-update-accessibility-statements-for-claim-funding-and-manage-school-placement-services)
=> Update accessibility statements

app/controllers/placements/organisations_controller.rb, app/controllers/placements/providers/placements_controller.rb, app/views/placements/providers/find/school_details.html.erb, app/views/placements/providers/placements/_filter.html.erb, config/locales/en/placements/providers/find.yml, config/locales/en/placements/providers/placements.yml, db/schema.rb, spec/system/placements/organisations/view_organisations_spec.rb, spec/system/placements/providers/find/provider_user_views_a_placements_already_organised_school_spec.rb, spec/system/placements/providers/find/provider_user_views_a_school_with_previous_filled_unfilled_placements_spec.rb, spec/system/placements/providers/find/provider_user_views_an_open_to_hosting_school_spec.rb, spec/system/placements/providers/find/provider_user_views_an_unfilled_placements_school_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_phase_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_school_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_subject_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_with_multiple_filters_spec.rb, spec/system/placements/providers/placements/provider_user_searches_for_school_filter_option_spec.rb, spec/system/placements/providers/placements/provider_user_searches_for_subject_filter_option_spec.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb
=> Implement feedback from PM & redirect to find page

app/controllers/placements/providers/find_controller.rb, app/forms/placements/schools/filter_form.rb, app/queries/placements/schools_query.rb, app/views/placements/providers/find/_filter.html.erb, config/locales/en/placements/providers/find.yml, config/locales/en/placements/providers/placements.yml, spec/forms/placements/schools/filter_form_spec.rb, spec/queries/placements/schools_query_spec.rb, spec/system/placements/providers/find/provider_user_filters_by_schools_i_work_with_spec.rb
=> Add schools I work with filter

app/controllers/placements/partnerships/add_partnership_controller.rb, app/controllers/placements/partnerships_controller.rb, app/views/placements/providers/find/_filter.html.erb, app/views/placements/providers/find/placements.html.erb, config/locales/en/placements/providers/find.yml, spec/system/placements/providers/find/provider_user_views_a_placements_already_organised_school_spec.rb, spec/system/placements/providers/find/provider_user_views_a_school_with_previous_filled_unfilled_placements_spec.rb, spec/system/placements/providers/find/provider_user_views_an_unfilled_placements_school_spec.rb, spec/system/placements/providers/partner_schools/add_a_partner_school_spec.rb, spec/system/placements/providers/partner_schools/add_a_partner_school_without_javascript_spec.rb, spec/system/placements/providers/partner_schools/remove_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_without_javascript_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_deletes_a_partner_school_spec.rb
=> Remove provider school email

app/jobs/claims/slack/daily_roundup_job.rb, app/models/claims/provider.rb, app/services/claims/claim/submit.rb, app/slack_notifiers/claims/claim_slack_notifier.rb, spec/jobs/claims/slack/daily_roundup_job_spec.rb, spec/models/claims/provider_spec.rb, spec/services/claims/claim/submit_spec.rb, spec/slack_notifiers/claims/claim_slack_notifier_spec.rb
=> Reduce claims slack spam

app/views/placements/pages/landing-page.md, app/views/sessions/new.html.erb
Update the content on the start page and DfE sign in pages to reflect the latest beta rollout.
- Updates page content
- Review page content
[Update service start page
](https://trello.com/c/jtC053uj/570-update-service-start-page)
=> Update start page and DfE sign in content

app/views/placements/school_user_mailer/user_membership_created_notification.text.erb, spec/mailers/placements/school_user_mailer_spec.rb
- Updates to the onboarding email.
- Updates to the onboarding email.
- Navigate to "Settings"
- Click "Emails"
- Click "user_membership_created_notification (opens in new tab)"
- You should see the email with amended changes.
=> updates to onboarding email

spec/support/govuk_component_matchers.rb, spec/system/placements/support/support_user_views_emails_spec.rb
- Refactor support user views emails spec
https://trello.com/c/zx0QwcDb/673-refactor-spec-system-placements-support-viewemailsspecrb-to-align-with-new-style-guide
=> Refactor support user views emails spec

app/controllers/placements/schools/hosting_interests/add_hosting_interest_controller.rb, app/controllers/placements/schools/hosting_interests/edit_hosting_interest_controller.rb, app/controllers/placements/schools/placements/add_multiple_placements_controller.rb, app/controllers/placements/schools/placements/add_placement_controller.rb, app/controllers/placements/schools/potential_placements/edit_potential_placements_controller.rb, app/models/placement.rb, app/models/placements/support_user.rb, app/models/placements/user.rb, app/wizards/placements/add_hosting_interest_wizard.rb, app/wizards/placements/add_placement_wizard.rb, app/wizards/placements/edit_hosting_interest_wizard.rb, app/wizards/placements/multi_placement_wizard.rb, config/analytics.yml, db/migrate/20250529144041_add_creator_to_placements.rb, db/schema.rb, spec/factories/placements.rb, spec/models/placement_spec.rb, spec/models/placements/support_user_spec.rb, spec/models/placements/user_spec.rb, spec/wizards/placements/add_hosting_interest_wizard_spec.rb, spec/wizards/placements/add_placement_wizard_spec.rb, spec/wizards/placements/edit_hosting_interest_wizard_spec.rb, spec/wizards/placements/edit_potential_placements_wizard_spec.rb, spec/wizards/placements/multi_placement_wizard_spec.rb
- Add `creator` to `placements` so we can track and audit who created a placement.
- Add `creator` to the `placements` model.
https://trello.com/c/F1JetoBb/688-add-creator-to-placements
=> Add creator to placements

app/queries/claims/claims_query.rb
I noticed that whilst the support console speed had improved, I felt that it could still be a little faster.
- Added eager loading to improve load times further
- Review code, minor change
[Add eager loading to further improve performance](https://trello.com/c/z8RhuQUv/755-add-eager-loading-to-further-improve-performance)
=> Utilise eager loading to improve load times a little more!

.github/workflows/restore-deleted-postgres.yml
- add new functionality: a new workflow to recover a deleted postgres db
- add new workflow to recover a deleted postgres db
https://github.com.mcas.ms/DFE-Digital/itt-mentor-services/actions/runs/17290425464/job/49076254130
https://trello.com/c/QANXFMhR/2447-add-recover-deleted-postgres-workflow
N/A
=> feat(2447): ITTMS:  new workflow to recover deleted postgres db

spec/support/capybara.rb
=> Revert browser change
