DFE-Digital/itt-mentor-services

.env.example, Gemfile, Gemfile.lock, docker-compose.yml
To avoid using bare metal dependencies or dependency managers, such as `brew`, add PostgreSQL to a `docker-compose.yml` file which can be spun up in docker containers using `docker-compose up`.
- Add `docker-compose.yml` file to configure software dependencies, such as PostgreSQL.
- Add `dotenv-rails` gem to configure environment variables in `.env` files.
=> Add docker-compose.yml file for database dependency

.erb-lint.yml, Gemfile, Gemfile.lock, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable_entity.html.erb, app/views/layouts/application.html.erb, bin/lint
- Added erb linting to the `bin/lint` script
- The configuration in `.erb-lint.yml` largely mirrors that in [register](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/.erb-lint.yml) and [publish](https://github.com/DFE-Digital/publish-teacher-training/blob/main/.erb-lint.yml) 
- I've disabled `Layout/LineLength` -- I think this this is restrictive in `erb` files where there is often a lot of text and indentation. But I'm happy to change this if other disagree. Or we could change the acceptable line length for erb files to something longer than the standard 140 characters. 
- Publish enforces double quotes in `erb` files, and I've gone with that for our codebase as well for consistency. (publish does not do this)
- I haven't included `better_html` because I'm following …
=> Erb linting implementation

Gemfile, Gemfile.lock
The `govuk_design_system_formbuilder` has a new version, 5.0.0. As we are spinning a new service probably better to start with most up to date tools.
Update `govuk_design_system_formbuilder`
`bin/setup`
=> Update govuk_design_system_formbuilder to 5.0.0

Gemfile, Gemfile.lock, README.md, app/controllers/account_controller.rb, app/controllers/application_controller.rb, app/controllers/personas_controller.rb, app/controllers/sessions_controller.rb, app/models/dfe_sign_in_user.rb, app/models/persona.rb, app/models/user.rb, app/views/account/index.html.erb, app/views/personas/index.html.erb, config/initializers/inflections.rb, config/initializers/persona.rb, config/locales/en.yml, config/routes.rb, db/migrate/20231208153214_create_users.rb, db/schema.rb, db/seeds.rb, spec/factories/persona.rb, spec/factories/users.rb, spec/features/personas/sign_in_as_persona_spec.rb, spec/models/dfe_sign_in_user_spec.rb, spec/models/persona_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/requests/personas_spec.rb, spec/requests/sessions_spec.rb
Adding the "Anne" persona for User login without DfE Sign In
- run `bundle exec rake db:seed` to generate the Persona/User for Anne
- Add `User` and `Persona` models
- Migration to add `users` to the database
- Create `personas` index page
- Create `account` page
https://trello.com/c/yZSxLwtM/17-set-up-persona-based-login
https://github.com/DFE-Digital/itt-mentor-services/assets/17162488/a67d9294-ebfa-4c9f-bf0e-2ede9d3d2573
=> Add Anna Persona for Sign In

Gemfile, Gemfile.lock, config/features.rb, db/migrate/20231212134422_create_features.rb, db/schema.rb, docs/feature-flags.md
This work comes after the [investigation ticket](https://trello.com/c/j2HF4dBc). Based on that work, the following specification was agreed:
- Use [Flipflop gem](https://github.com/voormedia/flipflop) instead of home rolling a solution
- Feature flags will be stored in the database (ie, the :active_record Flipflop strategy), not in Redis.
- As we do not know the specific requirements for the UI (eg who will use it, what authentication is required, how it will look), we will not implement at this stage.
- Feature flags will be turned on / off via rake tasks
Implementation of the feature flag gem [Flipflop](https://github.com/voormedia/flipflop)
Read the instructions  in `feature-flags.md`. Does it make sense and can you make it work on your machine as expected?
[Trello …
=> Implement basic feature flag and documentation

.env.example, .env.test, app/controllers/application_controller.rb, app/controllers/claims/pages_controller.rb, app/controllers/placements/pages_controller.rb, app/helpers/application_helper.rb, app/views/claims/pages/index.html.erb, app/views/layouts/application.html.erb, app/views/placements/pages/index.html.erb, config/locales/claims/en/layouts/application.yml, config/locales/placements/en/layouts/application.yml, config/routes.rb, config/routes/claims.rb, config/routes/placements.rb, spec/features/personas/sign_in_as_persona_spec.rb, spec/requests/pages_spec.rb, spec/requests/sessions_spec.rb, spec/system/home_page_spec.rb
We want to split routing between the "School Placements" and "Track & Pay" services within the Rails application. In production, these URLs are likely to be `manage-school-placements.service.gov.uk` and `claim-funding-for-general-mentors.service.gov.uk`.
- School Placements have confirmed that "Placements" is their desired top-level namespace.
- Track & Pay have confirmed that "Claims" is their desired top-level namespace.
- Add 2 routing files for the separate services, `config/routes/claims.rb` and `config/routes/placements.rb`
- Update `app/views/layouts/application.html.erb` to use service name header based on `current_service` helper.
By updating your local `/etc/hosts` file with the following lines, you can access both services without running a proxy server:
```
127.0.0.1 …
```
=> Add host-based routing constraints

.env.example, .gitignore, Gemfile, Gemfile.lock, app/models/gias_school.rb, app/services/gias_csv_importer.rb, app/services/service_pattern.rb, db/migrate/20231213110952_create_gias_schools.rb, db/schema.rb, lib/tasks/gias_update.rake, spec/factories/gias_schools.rb, spec/fixtures/test_gias_import.csv, spec/models/gias_school_spec.rb, spec/models/user_spec.rb, spec/services/gias_csv_importer_spec.rb, spec/tasks/gias_update_spec.rb
We need to import GIAS data into our app. The GIAS service does not have
an official API. What they do have is a CSV that they publish every day
and we can download this CSV and parse the data.
To do this, we have introduced a rake task `rake gias_update` which will
download the CSV file for that day in the tmp folder and upsert the data
into our DB. All in all we have about 24k GiasSchool records created
containing schools and MATS that are still open. The file will be removed
after the task is done.
- New rake task
- New ENV variable to hold the GIAS URL
- CSV Import
- Generic Service pattern
To run this on local:
1. bundle install
2. copy `GIAS_CSV_BASE_URL` to your env file
3. rake gias_update
https://trello.com/c/5t52nESP/53-import-gias-schools
- The task takes about 20 seconds on my …
=> Import Gias

config/routes.rb
We want to control the sign-in path based on the `SIGN_IN_METHOD` env variable. This will allow us to have a different sign-in path in production and staging to the one on dev and QA.
SIGN_IN_METHOD logic in routes file 
- Pull on local
- CHANGE `SIGN_IN_METHOD` value to anything but `persona`
- Go to `/personas` or the `/auth/developer` paths
https://trello.com/c/Df7kSskC/72-persona-select-page-should-only-be-accessible-in-the-qa-and-development-environments
=> Restrict login path based on SIGN_IN_METHOD

docs/data-model.md
This PR updates the data model to document how we could split Organisations (Schools or Providers) and Users between the different services provided by our app.
✨ [View the rendered document](https://github.com/DFE-Digital/itt-mentor-services/blob/update-erd-for-service-split/docs/data-model.md) to see the diagram
https://trello.com/c/qHWnixO0/71-update-the-erd-to-reflect-our-understanding-of-user-and-organisation-onboarding
=> Update ERD for service split

app/models/claims/school.rb, app/models/claims/user.rb, app/models/gias_school.rb, app/models/persona.rb, app/models/placements/school.rb, app/models/placements/support_user.rb, app/models/placements/user.rb, app/models/provider.rb, app/models/school.rb, app/models/user.rb, config/initializers/persona.rb, db/migrate/20231214141009_create_schools.rb, db/migrate/20231214142055_create_providers.rb, db/migrate/20231216101427_add_support_user_to_users.rb, db/migrate/20231216101536_add_service_enum_to_user.rb, db/migrate/20231216102842_add_index_to_users_on_email_and_service.rb, db/schema.rb, db/seeds.rb, docs/data-model.md, spec/factories/persona.rb, spec/factories/providers.rb, spec/factories/schools.rb, spec/models/claims/school_spec.rb, spec/models/claims/user_spec.rb, spec/models/persona_spec.rb, spec/models/placements/schools_spec.rb, spec/models/placements/support_user_spec.rb, spec/models/placements/user_spec.rb, spec/models/provider_spec.rb, spec/models/school_spec.rb
Setting up some of the basic data structures before proceeding with feature work. 
I decided it made sense to do this as a separate PR before proceed with logging in as a support user.
No UI changes. The only change to existing functionality is to add the service to the seeded personas.
Pull and run the migrations and seed the database.
Have a look at the erd in this PR -- they should reflect the agreed approach. https://github.com/DFE-Digital/itt-mentor-services/pull/30
Note: Not everything in the erd is here -- I haven't included the membership model because that is outside of the scope of what I'm working on (support users will have access to all the schools and providers, not through membership). I can add it for completeness if people think it would be useful. Otherwise, happy for …
=> Add User, School, Provider models and default scopes

adr/00003-testing-practices.md
We want to align on our testing practices to make testing both easier to write and to review.
- Add ADR related to Testing Practices
- There's a lot of other testing practices we may want to agree on. Feel free to suggest additions.
- Click [here](https://github.com/DFE-Digital/itt-mentor-services/blob/adr/testing-practices/adr/00003-testing-practices.md) to preview the ADR.
https://trello.com/c/jzu6Vgel/69-write-up-adr-for-testing-practices
=> Initial draft for testing practices ADR

app/assets/stylesheets/application.sass.scss, app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_page_banner.scss, app/views/layouts/application.html.erb, config/application.rb, config/locales/claims/en/models/hosting_environment.yml, config/locales/placements/en/models/hosting_environment.yml, lib/hosting_environment.rb, spec/lib/hosting_environment_spec.rb
We want to add a phase banner that will indicate to our users that this app is in Beta. The banner title is dynamic based on the environment we are in and both claims and placements can control the content of it.
- Phase banner Styles
- Translations
- HostingEnvironment module
- The link in the banner only redirects to the current page, we need to talk to product about where we want that link to go. It was not in the scope of this story
Run the app on local and you should see the `Development` phase banner
https://trello.com/c/ivbin1aW/73-add-beta-banner-to-app
Development:
Production:
=> Add phase banner to the app

Gemfile.lock, app/controllers/application_controller.rb, app/models/dfe_sign_in_user.rb, spec/models/dfe_sign_in_user_spec.rb
The School Placements service has two user models: `Placements::User` and `Placements::SupportUser < Placements::User`. We decided that support users will need slightly different behaviour from 'regular' users – for example, they'll need access to _all_ Organisations rather than only those they have Memberships to.
I've updated the `current_user` method so that it returns the most appropriate User type for the circumstances. If the user is in the Placements service and is a Support User, then we'll return a `Placements::SupportUser` object.
I'm implementing in the hope that it'll simplify the implementation of PR #42 which needs to distinguish between regular users and support users. For more context, see this comment thread: https://github.com/DFE-Digital/itt-mentor-services/pull/42#discu …
=> Make `current_user` return a `Placements::SupportUser` for support users

spec/rails_helper.rb
The following deprecation notice was being shown when running the RSpec test suite:
```
Rails 7.1 has deprecated the singular fixture_path in favour of an array
```
We should set `config.fixture_paths = []` instead of `config.fixture_path`.
However, we don't actually use ActiveRecord fixtures. We prefer to use FactoryBot. So I've fixed the deprecation, but then have commented out the line since it's not something we use.
If we need to enable it in the future, I've fixed the deprecation notice so we should be able to simply uncomment the line.
=> Remove deprecation notice from tests

Gemfile.lock
Different Apple Silicon & MacOS versions have different platform versions. With the different machines we are working on as a team, conflicts often occur.
Change the bundle platform to support all versions of `arm64-darwin`.
Try running `bundle install` on any Apple Silicon Mac and it should not error nor update the platforms list.
https://trello.com/c/livsdvzX/84-update-gemfilelock-platforms-list-to-support-all-macs
=> Update bundler platforms to include all versions of arm64-darwin

spec/support/capybara.rb
We want to configure Capybara to use the `:rack_test` driver by default and the `:chrome_headless` driver when js is required.
Add Capybara configuration.
BAT reference can be found here: https://github.com/DFE-Digital/apply-for-teacher-training/blob/dd2212514ff076ddb6b423bdfac31615a7013406/spec/support/capybara.rb
https://trello.com/c/Bq7BJB6G/85-add-capybara-configuration?filter=label:Dev
=> Configure Capybara to use rack_test driver by default in system specs

.env.example, .env.test, Gemfile, Gemfile.lock, app/assets/stylesheets/application.sass.scss, app/controllers/placements/support/provider_suggestions_controller.rb, app/controllers/placements/support/providers_controller.rb, app/javascript/accredited_provider.js, app/javascript/application.js, app/javascript/autocomplete.js, app/javascript/utils/request_helper.js, app/services/accredited_provider_api.rb, app/views/layouts/application.html.erb, app/views/placements/support/providers/check.html.erb, app/views/placements/support/providers/new.html.erb, config/locales/en.yml, config/locales/placements/en/layouts/application.yml, config/routes/placements.rb, package.json, spec/models/provider_spec.rb, spec/rails_helper.rb, spec/services/accredited_provider_api_spec.rb, spec/support/capybara.rb, spec/system/home_page_spec.rb, spec/system/placements/providers/support_user_adds_a_provider_spec.rb, spec/system/service_updates_page_spec.rb, terraform/application/config/review.tfvars.json, yarn.lock
Support users should be able to "Onboard" Providers from the Publish API
Based on https://sp-beta-pr-27.herokuapp.com/support/organisations/new/provider
- API service for collecting Provider data from Publish API
- Controllers/Views for New/Check/Create Providers
- run `bundle install`
- run `yarn install`
- Visit `http://placements.localhost:3000/support/providers/new`
- Type a few letters into the text input (e.g "CT")
- Select an option from the dropdown list.
- _This should take you to the "Check your answers" page_
- Click "Add organisation"
https://trello.com/c/9W5FDi7E/67-add-a-new-provider
_Happy Path(Provider doesn't exist)_
https://github.com/DFE-Digital/itt-mentor-services/assets/17162488/3ab112c6-2ed7-47cd-8e6c-a69d78650bba
_Unhappy …
=> Placements Support Add Providers

app/views/placements/support/organisations/index.html.erb, config/locales/en.yml
Currently Support Users (Placements) can't access the Provider search/add pages unless the know the URL.
Add a button to the Placements Support Organisation page, to allow Users to easily access the Provider pages.
Click the "Add Organisation" button. This should redirect the user to the Provider Search page.
https://trello.com/c/kbAPMIAD/86-add-links-for-add-organisation-to-support-user-homepage
=> Add link to Add Organisation

spec/features/personas/sign_in_as_a_placements_user_persona_spec.rb
This follows on from:
https://trello.com/c/9QbPxRYT/65-login-as-a-support-user-and-see-organisations
That card introduced the concept of authorising users to make sure they’re allowed to access the support pages.
Test coverage was added for the ‘happy path’ here:
https://github.com/DFE-Digital/itt-mentor-services/pull/42/files#diff-16ef8afeb06e825ad8f0273956ec59c3b035897c63887ee09dfc5635b2becad8
However the ‘unhappy path’ has not been covered yet.
Change sign_in_as_a_placements_user_persona_spec.rb file
Review changes
https://trello.com/c/BTZ50gR8/83-add-test-coverage-for-unauthorised-users-trying-to-access-the-placements-support-area
=> Test unhappy path for sign in placements support user

config/locales/en.yml
=> Correct spelling of organisation

.env.example, app/services/gias_csv_importer.rb, config/environments/development.rb, lib/tasks/gias_update.rake, spec/services/gias_csv_importer_spec.rb
Previously with `Logger`, there was noise added to the terminal when running the specs. Because of this we want to use Rails.logger instead, in production and development
- New env variable to print logs to STDOUT
- Dev env logger in line with production
- Temporarily silent the Active Record logger when upserting all the GiasSchools, This only adds noise to the logs when running the `gias_update` task in production.
Run rspec on local and there should be no logs from the Gias Import
https://trello.com/c/HWeQQRQT/94-user-rails-logger
- Ignore the auth logs
- Before:
- After:
=> Use Rails.logger instead of Logger

config/initializers/capybara.rb
RSpec reports are currently interrupted by a deprecation warning coming from Capybara.
Monkey-patch the `Rack::Handler` to `Rackup::Handler` when `Rails.env.test?` is `true`.
Try running `bundle exec rspec`. There should no longer be any logs interrupting the report.
Beautiful!
=> Silence deprecation warning by monkey-patching Rack for Capybara

.github/CODEOWNERS
- We want to reduce manual effort required from developers when requesting reviews.
- We also want to ensure that the relevant parties are notified about PRs that are ready for review.
Add a foundational `CODEOWNERS` file to kick off ownership of files we know to belong to a specific team. Shared code is still in limbo.
This will need to be merged in before GitHub will start automatically requesting reviews as it needs to be on the base branch of the PR.
> If you create a pull request from a fork, and the base branch is in the upstream repository, then the pull request will use the CODEOWNERS file from that branch in the upstream repository. If the base branch is a branch within your fork, then the pull request will use the CODEOWNERS file from that branch in your fork, but this will only …
=> Add foundational CODEOWNERS file

.github/workflows/deploy.yml
When system tests fail, Capybara automatically takes a screenshot of the page to help developers debug the context of the failure. This was introduced in 6ca32a1c3189c480ffa589c6116c3ad8f0acbc9d.
This commit configures the GitHub Actions CI job to store those screenshots as test artifacts. This makes them available to developers following a failed build.
This implementation was inspired by DFE-Digital/apply-for-teacher-training#8848 (thanks!)
1. Here's an example test failure:  
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/7425203018
2. Scroll to the bottom of the page and you'll see an 'Artifacts' section with a 'failure-screenshots' file.
3. Download the file and open it to see the screenshots.
https://trello.com/c/4UcgqmW7/100-store-failure-screenshots-as-test-artefac …
=> Store failure screenshots as test artifacts in CI

config/initializers/omniauth.rb, config/routes.rb
When the `SIGN_IN_METHOD` environment variable isn't set, fallback to persona based sign in.
This resolves an issue where the docker image could not be built because the `assets:precompile` step was failing with the error:
```
> [builder 10/11] RUN RAILS_ENV=production SECRET_KEY_BASE=required-to-run-but-not-used     bundle exec rails assets:precompile:
16 11.84 bin/rails aborted!
16 11.85 KeyError: key not found: "SIGN_IN_METHOD" (KeyError)
16 11.85 /app/config/initializers/omniauth.rb:4:in `fetch'
16 11.85 /app/config/initializers/omniauth.rb:4:in `<main>'
16 11.85 /app/config/environment.rb:5:in `<main>'
16 11.85 Tasks: TOP => assets:precompile => environment
16 11.85 (See full trace by running task with --trace)
```
1. Check out this branch.
2. Try building the app as a Docker image: …
=> Default to "persona" sign in method

app/controllers/application_controller.rb, app/controllers/claims/schools_controller.rb, app/helpers/routes_helper.rb, app/views/claims/schools/index.html.erb, app/views/claims/support/schools/index.html.erb, spec/requests/sessions_spec.rb, spec/system/claims/view_organisations_spec.rb, spec/system/placements/view_organisations_spec.rb
In claims we need to redirect our users to the organisations index page. Some users do have only one organisation(school) so for those users we will redirect them to the school show page, we do this via another redirect in the schools controller just to make sure a user with one school doesn't land on the organisation(school) index page.
This change also affects placements where we will always redirect the user after sign in to the organisations index page, allowing placements to add their logic in their controllers
Also I didn't want to add too much logic in the application controller.
Application controller
Scholl Controller
Claims:
- Sign in as a user with one organisation
- You should be redirected to the org show page
- Sign in as a multiple school user like Mary
- Should be …
=> Redirect users to organisations index/show after sign in

app/controllers/claims/schools_controller.rb, app/views/claims/schools/_additional_details.html.erb, app/views/claims/schools/_contact_details.html.erb, app/views/claims/schools/_ofsted_details.html.erb, app/views/claims/schools/_school_details.html.erb, app/views/claims/schools/_send_details.html.erb, app/views/claims/schools/show.html.erb, config/locales/claims/en.yml, config/locales/en.yml, spec/system/claims/view_school_spec.rb
Previously the show page of a school was populated with static data, this commit uses the school record to populate the page.
Updated show view and added a few partials similar to placements
Sign in as any user
Go to the school show page
=> Fill in the show page of a school.

app/controllers/claims/support/schools_controller.rb, app/controllers/placements/support/providers_controller.rb, app/controllers/placements/support/schools_controller.rb, app/forms/provider_onboarding_form.rb, app/forms/school_onboarding_form.rb, app/javascript/school.js, app/views/claims/support/schools/check.html.erb, app/views/claims/support/schools/new.html.erb, app/views/placements/support/providers/new.html.erb, app/views/placements/support/schools/check.html.erb, app/views/placements/support/schools/new.html.erb, config/locales/en.yml, spec/forms/provider_onboarding_form_spec.rb, spec/forms/school_onboarding_form_spec.rb, spec/models/provider_spec.rb, spec/system/placements/providers/support_user_adds_a_provider_spec.rb
Currently we are seeing a number of issues with forcing ourselves to use a CRU/D for onboarding Providers and Schools onto the different services.
Replacing the models used in the different controllers with form objects standardises the approach to onboarding external records, and reduces unwanted validating errors appearing when completing the onboarding form.
- Introduces form objects (ProviderForm, SchoolForm) for onboarding (flipping the relevant service flag to `true`)
of Provider and School records.
[ ] Test onboarding a provider on the `Placements` service.
[ ] Test onboarding a school on the `Placements` service.
[ ] Test onboarding a school on the `Claims` service.
https://trello.com/c/xg3Ylg0f/104-refactor-school-provider-onboarding-journeys-to-use-form-objects-pattern …
=> Rework onboarding with form objects for schools and providers

app/controllers/placements/support/organisations_controller.rb, app/forms/organisation_onboarding_form.rb, app/views/placements/support/organisations/new.html.erb, config/locales/en.yml, spec/forms/organisation_onboarding_form_spec.rb
To continue with our mindset of using form objects when not working with actual models/records, refactor the `Placements::Support::OrganisationsController` to work an `OrganisationOnboardingForm`
Introduce an `OrganisationOnboardingForm` to work when selecting the type on organisation which is being on boarded.
https://trello.com/c/Z0wd50sA/113-refactor-support-organisation-controller-to-use-organisationonboardingform-object
=> Rework Placements Support Org Controller to work with form objects

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_organisation_list_item.scss, app/assets/stylesheets/search-form.scss, app/components/organisation_list_item.html.erb, app/components/organisation_list_item.rb, app/controllers/application_controller.rb, app/controllers/claims/support/schools_controller.rb, app/helpers/application_helper.rb, app/models/school.rb, app/views/claims/support/schools/index.html.erb, app/views/shared/_search_form.html.erb, config/initializers/pagy.rb, config/locales/claims/en/support/schools.yml, config/locales/en.yml, spec/system/claims/view_schools_as_support_user_spec.rb
We need to allow our support users to search schools by their names or postcodes. This commit adds this functionality with pg search.
It also adds pagy, for pagination and a search form partial that can be reused in other places.
We won't be implementing filters in this PR.
- New pg search scope
- Refactored the support/schools controller a bit
- search form partial
- pagy gem
- Sign in as Colin in claims
- Search for a school by its name or postcode
- Clear the search by using the small `X` icon or by clicking `Clear search`
- Search for a school that doesn't exist.
Prototype;
https://itt-mentoring-beta-94341ca35a2c.herokuapp.com/support/organisations
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/9d47c063-0560-43b5-ac04-957fd73f0c86
=> Add Search capabilities to claims/support/schools

app/views/placements/support/schools/show.html.erb
Bug: School name in page title has escaped characters eg 
sanitize school name in page title
Look at a school with an apostrophe in the title. The name should be rendered correctly in the page title
https://trello.com/c/kbx9B460
Before 
After:
=> sanitise html in page title

app/views/claims/support/schools/index.html.erb, spec/system/claims/support/schools/view_a_school_spec.rb
The links on the support schools page link to the non-support school pages.
- Update links to support school page paths
- Update system spec to walk through the user journey to avoid regressions
- Sign in as support user
- Click on a school
- It should take you to the `/support/schools/{id}` page
=> Update school links in Claims support schools index page

app/views/layouts/application.html.erb, config/locales/en/placements/layouts/application.yml, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb
The success flash message was missing the "Success" title
Use Govuk Notification banner for flash message. 
Add an organisation and see the correct banner
https://trello.com/c/V8PMOjlm
Before:
After
=> Use success notification banner for flash

app/views/claims/support/schools/new.html.erb, app/views/placements/support/providers/new.html.erb, app/views/placements/support/schools/new.html.erb
Currently the error handling wrapper on the autocomplete forms (School/Provider on Claims/Placements) does not wrap around the input.
**Before**
**After**
Claims/Schools
Placements/Providers
Placements/Schools
https://trello.com/c/6KvckHhS/133-bug-error-formatting-on-organisation-search-box
=> Fix error wrapper for autocomplete

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, config/locales/en/sessions.yml
We want to add in DfE Sign In. Whilst the external setup is still pending, here is the UI.
- Update `/sign_in` page UI.
- Add `service_name` helper for convenience.
- You'll need to comment out the `before_action :redirect_to_personas, only: [:new]` line in the `SessionsController` to view the page.
=> Add UI for the sign in page

app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_autocomplete.scss, app/views/claims/support/schools/new.html.erb, app/views/placements/support/providers/new.html.erb, app/views/placements/support/schools/new.html.erb
The autocomplete dropdown is missing the font used by DfE GOV.UK.
Added CSS to account for the missing font and styling on the autocomplete.
https://trello.com/c/quVSHgvA/137-update-add-the-missing-autocomplete-component-fonts
**Before**
**After**
=> Add missing CSS for autocomplete

.env.production
Terraform currently needs to add an ENV configuration file for these values. By adding the `.env.production`, we can avoid the need for terraform env var configuration for public static values.
- Add an `.env.production` file.
Running the app with `RAILS_ENV=production` should populate the `ENV` values from `.env.production`.
=> Add production plaintext env vars

spec/system/claims/create_claim_spec.rb, spec/system/claims/view_claims_spec.rb
We recently added a change to how we can setup the host for system specs.
Adopt the new method of setting up system specs for the claims service.
`bundle exec rspec` should pass.
=> Update create_claim_spec and view_claims_spec to use service: configuration keyword

.github/CODEOWNERS
Most non-namespaced files typically warrant a review from both teams. We want to make it implicit that a review is requested by default.
- Update CODEOWNERS
This may be radical blanket approach that covers a lot of unnecessary directories, but I've included them for good measure. For example, the tmp and log directories.
To remove a team, add a row explicitly assigning ownership to the correct team.
- If you're using VS Code, [this extension](https://marketplace.visualstudio.com/items?itemName=jasonnutter.vscode-codeowners) helps with previewing code ownership quite a bit.
=> Default most of the project to shared code ownership

app/views/placements/support/providers/users/index.html.erb, app/views/placements/support/schools/users/index.html.erb, config/locales/en/placements/support/providers/users.yml, config/locales/en/placements/support/schools/users.yml
Support users in placements should see an empty state when viewing an organisation with no users
adds empty state to user lists (providers and schools)
Sign in as placements Colin
Add an organisation
Look at that organisation's users list
You should see the empty state "There are no users for..." instead of an empyt table.
None
=> Empty state for user lists in placements

app/controllers/errors_controller.rb, app/controllers/sessions_controller.rb, app/views/sessions/new.html.erb, config/locales/en/sessions.yml, spec/system/claims/support/schools/view_a_school_spec.rb, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb
Right now, we skip a step from our intended production flow by redirecting to the `/personas` page. If we are to treat persona selection as an OmniAuth method, we should mirror the sign-in flows.
- Stop redirecting to `/personas` automatically.
- Skip authentication when rendering error pages.
- You should be able to access the `/sign-in` path.
| DfE Sign In | Persona |
| ----------- | -------- |
| ![CleanShot 2024-01-26 at 13 38 37](https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/2081e760-85db-4c40-a708-0a3ffc6a5fa1) | ![CleanShot 2024-01-26 at 13 39 04](https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/39a24fb1-cc89-47e6-9581-ddbf540cb2d0) |
=> Align sign-in flows for DfE Sign In and Persona

app/views/placements/support/schools/users/show.html.erb
A primary navigation was missing from the support user view of a school user
adds primary navigation to support user view of a school user 
Sign in a placements support user. Navigate to a school that has users. Click on a user's name. The primary navigation should be there with "Organisations" shown as active.
https://trello.com/c/bEiwUqo0
Before:
After:
=> add-missing-school-user-navigation

.env.test, .github/workflows/build_and_test.yml, app/controllers/concerns/claims/belongs_to_school.rb, app/controllers/placements/support/organisations/users_controller.rb, app/models/claims/school.rb, app/models/claims/support_user.rb, app/models/claims/user.rb, app/models/concerns/acts_as_support_user.rb, app/models/placements/provider.rb, app/models/placements/school.rb, app/models/placements/support_user.rb, app/models/placements/user.rb, app/models/user.rb, spec/models/claims/school_spec.rb, spec/models/claims/user_spec.rb, spec/models/placements/provider_spec.rb, spec/models/placements/school_spec.rb, spec/models/placements/user_spec.rb, spec/models/user_spec.rb, spec/system/claims/create_claim_spec.rb, spec/system/claims/view_claims_spec.rb
As [STI has been adopted for the User class](https://github.com/DFE-Digital/itt-mentor-services/pull/168), we can now fully lean into the practice of using only namespaced models and with Rails' _magic_ ✨, implicit namespaces for associations.
- Drop `.claims` and `.placements` scopes from User. A User can be one or the other, never both, therefore we can rely on calling `Claims::User` and `Placements::User` for `User.claims` and `User.placements`.
```ruby
class Claims::User < User
has_many :schools # This will use the current namespace and look for Claims::School by default.
end
```
- Try going through flows. Nothing should break.
- Try the following in your console:
```ruby
ApplicationRecord.logger.silence do
[
Claims::User.all.flat_map(&:schools).all? { _1.class == Claims::School }, …
```
=> Add SupportUser class and use implicit association class casting

.gitignore
We want to add `.env.*.local` files for local configuration. This allows us to distinctly setup our development and test environments without a shared `.env.local`.
Add `.env.*.local`
Replacing `.env` or `.env.local` with `.env.development.local` should work locally.
=> Gitignore all .env.*.local files

terraform/application/config/qa_app_env.yml
QA currently doesn't set the `HOSTING_ENV` during deployment.
Add `HOSTING_ENV=qa` to the QA deployment environment variables.
Hmm, trust that QA picks up its environment variables from `qa_app_env.yml`, like review does from `review_app_env.yml`?
=> Set HOSTING_ENV for QA

app/controllers/claims/support/schools_controller.rb, app/controllers/placements/support/providers_controller.rb, app/controllers/placements/support/schools_controller.rb, app/forms/provider_onboarding_form.rb, app/forms/school_onboarding_form.rb, app/javascript/controllers/autocomplete_controller.js, app/views/claims/support/schools/check.html.erb, app/views/claims/support/schools/new.html.erb, app/views/placements/support/providers/check.html.erb, app/views/placements/support/providers/new.html.erb, app/views/placements/support/schools/check.html.erb, app/views/placements/support/schools/new.html.erb, spec/forms/provider_onboarding_form_spec.rb, spec/forms/school_onboarding_form_spec.rb, spec/system/claims/support/schools/add_a_school_spec.rb, spec/system/claims/support/schools/add_a_school_without_javascript_spec.rb, spec/system/placements/support/providers/support_user_adds_a_provider_spec.rb, spec/system/placements/support/providers/support_user_adds_a_provider_without_javascript_spec.rb, spec/system/placements/support/schools/support_user_adds_a_school_spec.rb, spec/system/placements/support/schools/support_user_adds_a_school_without_javascript_spec.rb
Back links on the Provider and School onboarding (Claims and Placements) "Check your answers" pages need to redirect back to the "New" onboarding forms, with the user's selection pre-filled. 
Once directed back, and the form is pre-filled, clicking continue should submit the form and take the user back to the "Check your answers" page.
Due to an issue with the [accessible-autocomplete](https://github.com/alphagov/accessible-autocomplete), additional javascript and changes to how options are rendered needed to be added to `app/javascript/controllers/autocomplete_controller.js`. Otherwise, the result of using `defaultValue` results in an `undefined` option appearing in the dropdown.
See https://github.com/alphagov/accessible-autocomplete/issues/424 for more details.
- Back links on the …
=> Resolve issue with autocomplete pre-filling back link

config/routes/placements.rb
Placements should also redirect away from the "pages#index" page as it is a placeholder.
https://github.com/DFE-Digital/itt-mentor-services/pull/195 fails due to Placements not being redirected away from the "pages#index" page.
- `/` should redirect to `/sign-in`
You should no longer be able to access the `pages#index` page.
=> Redirect placements service root to sign in page

.github/workflows/pull_request.yml
As a developer that frequently uses the `git commit --fixup` command. I don't want these commits to ever be merged into `main`.
- Add a GitHub action to prevent "fixup" commits from being merged into `main`.
- You could branch off of this branch and create a fixup commit by adding a change and committing with `git commit --fixup @` (`@` is an alias for `HEAD`)
=> Ensure no fixup commits are merged into main

.env.example
PLACEMENTS_DFE_SIGN_IN_CLIENT_ID is missing from `.env.example`
Add PLACEMENTS_DFE_SIGN_IN_CLIENT_ID to `.env.example`
=> Add PLACEMENTS_DFE_SIGN_IN_CLIENT_ID to env file

app/controllers/placements/support/support_users_controller.rb, app/helpers/routes_helper.rb, app/views/placements/support/support_users/check.html.erb, app/views/placements/support/support_users/index.html.erb, app/views/placements/support/support_users/new.html.erb, app/views/placements/support/support_users/show.html.erb, config/locales/en/placements/support/support_users.yml, config/routes/placements.rb, spec/system/placements/support/support_users/support_user_adds_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_views_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_views_support_users_spec.rb
Support Users will be able to onboard other support users (placements).
- Add the controllers/views/routes to allow Placement Support Users to add other Support Users.
(On Placements Service)
- Login in as Support User Colin
- Click "Users" in the navigation
- This will display a list of Support Users (including Colin)
- Click "Add user"
- Fill in the form, using an email address ending in "@education.gov.uk"
- (Feel free to test form validation)
- This will direct you to the "Check your answers" page
- Click "Add user"
- User should be added successfully
- Click on the name of the new Support User you have added
- This will direct you the the Support User show page.
- You should see the User's details here.
https://trello.com/c/qmhJnd3t/143-support-user-crud …
=> Add CRU for Placement Support Users

.github/workflows/build_and_test.yml
This reverts commit 929aeb4b0a3d3aa6c4f129f1050a28917c3c865c.
I accidentally committed this to the `main` branch rather than my feature branch – oops!
I've now configured the branch protection rules to block pushing directly to `main`.
=> Revert "WIP: list currently installed gems"

README.md
We currently do not have a list of our live environments documented.
Add "Live Environments" section to `README.md`.
See rendered markdown here: https://github.com/DFE-Digital/itt-mentor-services/blob/dd/add-live-environments-to-readme/README.md
or view copy below:
| Name       | URL | Purpose | AKS Namespace |
| ---------- | --- | ------- | ------------- |
| Production | *pending* | Public site | bat-production |
| Sandbox    | *pending* | Demo environment for end-users | bat-production |
| Staging    | *pending* | For internal use by DfE for testing - Production-like environment | bat-staging |
| QA         | [Track & Pay](https://track-and-pay-qa.test.teacherservices.cloud) / [School Placements](https://manage-school-placements-qa.test.teacherservices.cloud) | For internal use by DfE …
=> Add Live Environments to README

app/controllers/placements/organisations/users_controller.rb, app/policies/application_policy.rb, app/policies/placements/user_policy.rb, app/views/placements/_primary_navigation.html.erb, app/views/placements/providers/show.html.erb, app/views/placements/providers/users/check.html.erb, app/views/placements/providers/users/index.html.erb, app/views/placements/providers/users/new.html.erb, app/views/placements/providers/users/remove.html.erb, app/views/placements/providers/users/show.html.erb, app/views/placements/schools/show.html.erb, app/views/placements/schools/users/check.html.erb, app/views/placements/schools/users/index.html.erb, app/views/placements/schools/users/new.html.erb, app/views/placements/schools/users/remove.html.erb, app/views/placements/schools/users/show.html.erb, config/locales/en/placements/primary_navigation.yml, config/locales/en/placements/providers/users.yml, config/locales/en/placements/schools/users.yml, config/routes/placements.rb, spec/policies/placements/user_policy_spec.rb, spec/system/placements/organisations/users/user_removes_other_users_from_organisation_spec.rb, spec/system/placements/organisations/users/user_views_other_users_spec.rb
Users should be allowed to remove other users from their organisations
They should *not* be allowed to remove themselves.
Controllers, views, specs for users 
Also moved the "Change organisation" component to the primary nav for non-support users. So the views are just a little cleaner and less repetitive.
Login as a placements user (non support)
View the user you are logged in as 
You should *not* see the Remove user link
Go back
View a user that is not you.
You should see the Remove user link
And you should be able to remove the user.
Do this all for both providers and schools.
https://trello.com/c/294x8A8L
https://github.com/DFE-Digital/itt-mentor-services/assets/44073106/c8419fb7-59b5-48af-9bdf-b2e204e0c2ea
=> lb/Allow non-support users to remove other users

.github/workflows/build_and_test.yml, .gitignore, Gemfile, Gemfile.lock, spec/spec_helper.rb
We've spotted a few cases of missing test coverage. While I'm not a "100% coverage" purist, I do think it's healthy for us to have access to coverage reports so we have an overall awareness of our test coverage.
I've added two gems:
1. [SimpleCov](https://github.com/simplecov-ruby/simplecov) – the standard code coverage tool used in Ruby apps
2. [Undercover](https://github.com/grodowski/undercover) – a tool that will analyse the coverage report generated by SimpleCov, and produce friendly & readable warnings when we've forgotten to add test coverage in our branch
I've configured the CI workflow to upload the SimpleCov HTML code coverage report as a build artefact. This makes it really easy for us to see a detailed coverage report for our branches.
I've also added Undercover to the …
=> Detect code coverage regressions in CI

app/controllers/claims/support/claims_controller.rb, app/models/mentor.rb, app/views/claims/support/claims/index.html.erb, app/views/claims/support/claims/show.html.erb, config/locales/en.yml, config/locales/en/activerecord.yml, config/locales/en/claims/support/claims.yml, spec/models/mentor_spec.rb, spec/models/user_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb, spec/system/claims/support/claims/view_claims_spec.rb
This is more of a proof of concept, we don't have a claims index and show page designs yet.
- Support Claims index and show
- Support claims controller methods
- Go onto the review app
- Sign in as support user
- Go to claims tab
- View the claims
- Click on a claim
- Click the back button
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/4fd8f297-f7ef-4321-a3cc-4635b5b29f32
=> Basic Support Claims index and show page

spec/policies/placements/user_policy_spec.rb, spec/spec_helper.rb
Re-format policy testing in Rspec to follow the example shown in [Pundit Documentation](https://github.com/varvet/pundit?tab=readme-ov-file#policy-specs).
=> Spec polices follow pundit documented format

spec/spec_helper.rb
We have a few ungrouped types of files in our coverage report.
- Add additional simple-cov coverage groups:
- Components
- Decorators
- Forms
- Policies
- Services
- There should only be 1 remaining ungrouped file, [ServiceUpdate::View](https://github.com/DFE-Digital/itt-mentor-services/blob/main/app/assets/components/service_update/view.rb).
- I've written up a ticket to move this file into the correct directory: https://trello.com/c/Q2xVj8lC/177-move-the-serviceupdateview-component-into-our-app-components-directory
=> Add coverage groups for Components, Decorators, Forms, Policies, and Services

config/initializers/money.rb
We currently see the following deprecation warning:
```
[WARNING] The default rounding mode will change from `ROUND_HALF_EVEN` to `ROUND_HALF_UP` in the next major release. Set it explicitly using `Money.rounding_mode=` to avoid potential problems.
```
We'd like to remove this warning.
- Explicitly set the rounding mode of the Money objects to `HALF_UP`. Any partial "pence" amounts will be rounded up to a full pence.
- This deviates from the existing default behaviour, but it will have no impact on our current logic.
The newly configured value now differs from the previous default. As we don't currently do any multiplication or division with money, there will be no changes in behaviour. Moving forward, decimal point subunits will be rounded up.
=> Update the Money configuration to silence deprecation warnings

app/views/layouts/application.html.erb
Our page titles should end with "GOV.UK"
- Add a hardcoded "GOV.UK" string to the `application.html.erb` title tag.
- All pages should end in "GOV.UK"
=> Add GOV.UK to page titles

.rubocop.yml, spec/models/claims/school_spec.rb, spec/models/claims/user_spec.rb, spec/models/placements/provider_spec.rb, spec/models/placements/school_spec.rb, spec/models/placements/user_spec.rb, spec/models/provider_spec.rb, spec/system/claims/support/schools/add_a_school_without_javascript_spec.rb, spec/system/claims/view_claims_spec.rb, spec/system/placements/support/providers/support_user_adds_a_provider_without_javascript_spec.rb, spec/system/placements/support/schools/support_user_adds_a_school_without_javascript_spec.rb
This PR follows on from #227, which configured RuboCop to use rules from the [rubocop-govuk](https://github.com/alphagov/rubocop-govuk) gem.
Some rules which couldn't be autocorrected were disabled, to be fixed in follow-up PRs.
This PR enables the `RSpec/LetSetup` cop and fixes linting failures.
https://trello.com/c/IzTz6Nvs/170-add-linter-rules-for-rspec
=> Enable cop RSpec/LetSetup

app/controllers/claims/schools/claims_controller.rb, app/decorators/claim_decorator.rb, app/forms/claim_form.rb, app/models/claim.rb, app/views/claims/schools/claims/_mentors_form.html.erb, app/views/claims/schools/claims/_providers_form.html.erb, app/views/claims/schools/claims/show.html.erb, app/views/claims/support/claims/show.html.erb, config/locales/en/activerecord.yml, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/support/claims.yml, db/migrate/20240208141742_claim_belongs_to_provider.rb, db/schema.rb, spec/decorators/claim_decorator_spec.rb, spec/factories/claims.rb, spec/models/claim_spec.rb, spec/system/claims/create_claim_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb
We decided that a claim can only have one provider. This PR changes the form and the db relation to be a belongs_to, optional because of the way the form works now, we create a claim when landing on on providers form.
Claim has_one mentor_training
Claim has_one provider
Change claim form
Change suppport claim show  
Go onto the review app and create a claim
Then view that claim as a support user
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/5a14e3ff-5119-4c6b-963c-558c59c01347
=> Claim belongs to provider

.rubocop.yml, spec/forms/user_invite_form_spec.rb, spec/helpers/placements/support/schools_helper_spec.rb, spec/mailers/user_mailer_spec.rb, spec/models/claim_spec.rb, spec/models/claims/school_spec.rb, spec/models/claims/support_user_spec.rb, spec/models/dfe_sign_in_user_spec.rb, spec/models/membership_spec.rb, spec/models/mentor_spec.rb, spec/models/mentor_training_spec.rb, spec/models/placements/provider_spec.rb, spec/models/placements/school_spec.rb, spec/models/placements/support_user_spec.rb, spec/models/provider_spec.rb, spec/models/region_spec.rb, spec/models/school_spec.rb, spec/models/user_spec.rb, spec/requests/heartbeat_spec.rb, spec/services/placements/organisation_finder_spec.rb, spec/services/remove_user_service_spec.rb, spec/system/placements/organisations/add_users_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb, spec/system/service_updates_page_spec.rb
We want to enable all the rspec rules in rubocop that are not enabled https://github.com/DFE-Digital/itt-mentor-services/blob/main/.rubocop.yml#L42-L53
This PR enables `RSpec/ContextWording` which expects the context description to be like `Context description should match /^when\b/, /^with\b/, /^without\b/,
/^and\b/, or /^but\b/`
Enable the rule
Change all specs that break this rule
Review
Do the tests pass?
Maybe have a brew after?
=> Enable RSpec/ContextWording rubocop rule

.rubocop.yml, config/environments/test.rb, spec/forms/user_invite_form_spec.rb, spec/lib/hosting_environment_spec.rb, spec/services/remove_user_service_spec.rb, spec/services/user_invite_service_spec.rb, spec/system/claims/invite_a_user_to_a_school_spec.rb, spec/system/claims/support/schools/invite_a_user_to_a_school_spec.rb, spec/system/claims/support/support_users/remove_a_support_user_spec.rb, spec/system/placements/organisations/add_users_spec.rb, spec/system/placements/organisations/users/user_removes_other_users_from_organisation_spec.rb, spec/system/placements/support/support_users/support_user_removes_a_support_user_spec.rb, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb
We ant to enable all the rspec rules for rubocop.
This PR removes unverified doubles
Have a loop
The tests should pass!
=> Lb/enable RSpec/VerifiedDoubles

.rubocop.yml, spec/forms/organisation_onboarding_form_spec.rb, spec/mailers/support_user_mailer_spec.rb, spec/mailers/user_mailer_spec.rb, spec/models/membership_spec.rb, spec/models/provider_spec.rb, spec/models/user_spec.rb, spec/policies/claims/school_policy/scope_spec.rb, spec/policies/claims/support_user_policy_spec.rb, spec/policies/placements/support_user_policy_spec.rb, spec/policies/placements/user_policy_spec.rb, spec/services/accredited_provider/api_spec.rb, spec/services/accredited_provider/importer_spec.rb, spec/services/dfe_sign_in/user_update_spec.rb, spec/services/gias_csv_importer_spec.rb, spec/services/placements/organisation_finder_spec.rb, spec/services/remove_user_service_spec.rb, spec/services/support_user/invite_spec.rb, spec/services/support_user/remove_spec.rb, spec/services/user_invite_service_spec.rb, spec/tasks/gias_update_spec.rb
Enabling more rubocop rules.
Enabling the NamedSubject rule for rubocop and fixing tests that were violating the rule
passing tests
=> Enable NamedSubject rule

.rubocop.yml
This is no longer needed since we've now fixed-up all the RuboCop failures.
This completes the work started in #227, and iteratively fixed-up in #233, #238, #239, #240, #241, #242, #243.
=> Remove temporary comment in RuboCop config file

app/views/claims/schools/users/new.html.erb, app/views/claims/support/schools/new.html.erb, app/views/claims/support/schools/users/new.html.erb, app/views/placements/support/organisations/new.html.erb, app/views/placements/support/providers/new.html.erb, app/views/placements/support/providers/users/new.html.erb, app/views/placements/support/schools/new.html.erb, app/views/placements/support/schools/users/new.html.erb, config/locales/en/claims/schools/users.yml, config/locales/en/claims/support/schools.yml, config/locales/en/claims/support/schools/users.yml, config/locales/en/placements/support/organisations.yml, config/locales/en/placements/support/providers.yml, config/locales/en/placements/support/providers/users.yml, config/locales/en/placements/support/schools.yml, config/locales/en/placements/support/schools/users.yml
The page titles should be prefixed with "Error: " when there is an error on the form. 
As far as i could find, I have conditionally added "Error: " to the relevant page titles. 
I haven't added it to the Claims form  at all because there aren't page titles yet and I think this is very much in draft form. 
Sign in to on of the services as a support user
Whenever you create an error on a form you should see an the page title change to have the word "Error: " 
Do the same for the other service 
And then both again as a normal user
Let me know if I missed anything.
before: 
after
=> Add "Error: " to the page title when there is an error on the form

.rubocop.yml
The `frozen_string_literal` was introduced in Ruby 2.3 to prepare codebases for an anticipated breaking change in Ruby 3, where String objects would be frozen by default.
However [that decision was reverted ahead][1] of the release of Ruby 3. So the change never happened, and the magic comment is mostly considered to be 'code cruft' nowadays.
Some IDEs and tools are still configured to automatically add the `frozen_string_literal` magic comment, so I've enabled this RuboCop rule to ensure they don't accidentally sneak in to the codebase.  This will avoid the need for PRs like #245 in future.
[1]: https://bugs.ruby-lang.org/issues/11473#note-53
=> Don't use the frozen_string_literal magic comment

app/forms/claim_form.rb, spec/factories/claims.rb, spec/forms/claim_form_spec.rb
Refactor ClaimForm to align with documents https://github.com/DFE-Digital/itt-mentor-services/blob/main/docs/conventions/form_objects.md
Changes to code to align with documentation https://github.com/DFE-Digital/itt-mentor-services/blob/main/docs/conventions/form_objects.md and to inherit from ApplicationForm
https://trello.com/c/LO9nzf2O/201-align-claimform-with-documentation
=> Refactor claim form to align with docs

app/controllers/placements/schools/mentors_controller.rb, app/controllers/placements/support/schools/mentors_controller.rb, app/views/placements/schools/_primary_navigation.html.erb, app/views/placements/schools/mentors/index.html.erb, app/views/placements/support/_secondary_navigation.html.erb, app/views/placements/support/schools/mentors/index.html.erb, config/locales/en/placements/schools/mentors.yml, config/locales/en/placements/support/schools/mentors.yml, spec/system/claims/support/schools/mentors/view_mentors_spec.rb, spec/system/placements/schools/mentors/view_mentors_spec.rb, spec/system/placements/support/schools/mentors/support_user_views_mentors_spec.rb, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb
- Add Mentor index page for Placements Support Users
- Add Mentor index page for Placements School Users
- Controllers/Views/etc for Placements Support Users to view a list of mentors for a school
- Controllers/Views/etc for Placements School Users to view a list of their schools mentors
(Placements service only)
- Sign in as Support User Colin
- Click to view a school (with mentors)
- Click the "Mentors" tab in the secondary nav
- This should show the index page for Mentors on that school.
- Sign in as School User Anne
- Click the "Mentors" tab in the primary nav
- This should show the index page for Mentors for Anne's school.
- https://trello.com/c/RJuJqfy0/222-as-a-support-user-i-want-to-see-a-list-of-all-mentors-belonging-to-a-school
- …
=> Add placements mentor index pages

Gemfile, Gemfile.lock
We need to update the crown logo.
> Why the GOV.UK crown is changing
> Following the coronation of King Charles III, the royal cypher has been updated by the Royal Household. Announced in September 2022, this means many logos, crests and other symbols of state are being updated in line with the new design.
> Within government, this work is led by the Government Communications Service, who are liaising with the Royal Household. In line with wider changes to government symbols, the GOV.UK crown will be updated to reflect the new royal cypher and we have partnered with GCS to plan and deliver the changes.
Update the govuk gems and receive the updates to the crown logo.
=> Update the Crown logo - Update govuk gems to 5.1.0

app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, config/application.rb
This project doesn't use Action Cable, so I've removed the boilerplate code. We can always add it again later if we find a need for Action Cable.
It's unused and untested code.
When I generate a code coverage report locally, these files are flagged as untested. For some reason, code coverage reports generated in CI consider these files to be covered, although I'm not sure why because there are no tests which exercise it. 🤷🏻
=> Remove Action Cable boilerplate code

app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/models/dfe_sign_in_user.rb, spec/helpers/application_helper_spec.rb, spec/models/dfe_sign_in_user_spec.rb
This PR is a refactor which aims to clarify and simplify the way `current_service` is passed and defined within the app.
I'm doing this as a precursory refactor ahead of [setting up GoodJob](https://trello.com/c/9uy2ArZJ/217-draft-set-up-active-job). I'm doing this so I can access the current user within `routes.rb` – which has access to `request.session`, but cannot access the `current_user` controller helper method – so a suitable constraint can be applied for accessing the GoodJob admin dashboard.
It makes two main changes:
1. Define a single source of truth – by removing a duplicate implementation of `current_service`.
2. Stop passing `current_service` into the user's session – it was unnecessary, and was the source of a potential bug.
This is a refactor with no functional changes, so …
=> Refactor: Create a single source of truth for `current_service`

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/initializers/good_job.rb, config/routes.rb, config/scheduled_jobs.yml, db/migrate/20240219162226_create_good_jobs.rb, db/schema.rb, spec/support/dfe_sign_in_user_helper.rb, spec/system/good_job_dashboard_spec.rb
We need to be able to run asynchronous background tasks and scheduled jobs. To do this, we can use [GoodJob](https://github.com/bensheldon/good_job) which provides a backend adapter for [Active Job](https://guides.rubyonrails.org/active_job_basics.html).
GoodJob is similar to [Sidekiq](https://github.com/sidekiq/sidekiq) except it's backed by the existing Postgres database that the app already depends on. It keeps our stack simple by avoiding the need to set up Redis instances, as Sidekiq would require.
GoodJob also supports [cron-style scheduled jobs](https://github.com/bensheldon/good_job?tab=readme-ov-file#cron-style-repeatingrecurring-jobs) out of the box, akin to what you'd get from adding [sidekiq-scheduler](https://github.com/sidekiq-scheduler/sidekiq-scheduler) or …
=> Set up GoodJob for Active Job

app/forms/application_form.rb, spec/forms/support_user_invite_form_spec.rb, spec/forms/user_invite_form_spec.rb
As `ApplicationForm` only includes the `ActiveModel::Model` module, it makes more sense to avoid the external dependency of `ActiveRecord`.
- Change the validation error from `ActiveRecord::RecordInvalid` to `ActiveModel::ValidationError`.
=> Change validation error from ActiveRecord::RecordInvalid to ActiveModel::ValidationError

config/locales/en/claims/schools/primary_navigation.yml, spec/system/claims/authenticate_user_spec.rb, spec/system/claims/schools/view_school_spec.rb
The prototype has since been updated to show "Organisation details" instead of "Details".
- Update User's school primary navigation item text to "Organisation details".
- Visit `/schools/:school_id/*` and see "Organisation details" in the primary navigation.
|        | Screenshot |
| ------ | ---------- |
| Before | ![CleanShot 2024-02-22 at 12 52 06](https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/c414e13d-d82a-430d-b3e5-c2fb4cc3c664) |
| After  | ![CleanShot 2024-02-22 at 12 52 58](https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/0c1e4dcf-b40f-43ba-be5a-9c1fdf3ef9e4) |
=> Update text for organisation details link

app/components/primary_navigation_component.html.erb, app/controllers/application_controller.rb, app/controllers/claims/schools/users_controller.rb, app/controllers/claims/support/schools/users_controller.rb, app/controllers/claims/support/support_users_controller.rb, app/controllers/placements/support/organisations/users_controller.rb, app/controllers/placements/support/support_users_controller.rb, app/policies/application_policy.rb, app/policies/claims/support_user_policy.rb, app/policies/claims/user_policy.rb, app/policies/placements/support_user_policy.rb, app/policies/placements/user_policy.rb, app/views/claims/schools/users/remove.html.erb, app/views/claims/schools/users/show.html.erb, app/views/claims/support/schools/users/new.html.erb, app/views/claims/support/schools/users/remove.html.erb, app/views/claims/support/schools/users/show.html.erb, config/locales/en/claims/schools/users.yml, config/locales/en/claims/support/schools/users.yml, config/routes/claims.rb, spec/system/claims/schools/users/remove_a_user_spec.rb, spec/system/claims/support/schools/users/remove_a_user_spec.rb, spec/system/claims/support/schools/users/view_a_users_details_spec.rb
We need to be able to remove users from schools.
- Add remove flows for both Users and Support Users.
- Updated `ApplicationPolicy` to create sensible defaults.
- The `update?` method is not used within the `UsersController` scope and `undercover` is blocking changes, therefore, we will keep the default `update?` as `false` for now.
- Try adding a User and removing them.
- You shouldn't be able to remove yourself from a school when signed in as a non-support User.
| Change | Screenshot |
| ------ | ---------- |
| Added "Remove user" link | ![CleanShot 2024-02-22 at 10 55 54](https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/9cf0a26e-405b-407c-9785-f56452098c57) |
| Added `/schools/:school_id/users/:user_id/remove` path | ![CleanShot 2024-02-22 at 10 56 …
=> Remove School Users

config/routes/placements.rb
Whilst running `rails routes`, I saw some routes that jumped out with an `expect` constraint.
- Fix typo from `expect` to `except`.
- Tests pass.
- Correct routes are added.
=> Fix placements routing typo

app/helpers/placements/routes/organisations_helper.rb, app/helpers/routes_helper.rb, spec/helpers/placements/routes/organisations_helper_spec.rb
Whilst looking through the application logic I noticed that we had a lot of specific route helpers that would ideally be refactored to avoid creating _n_ helpers whenever new routes are required, however to refactor the logic we should first make sure the logic is separated and tested.
Moved the relevant route helpers into their own file and added tests. One invalid route was found whilst adding tests and addressed.
The application should continue to work as expected, I identified that one helper `check_placements_organisation_users_path(organisation)` was returning an error upon testing and have updated the logic in what I believe to be the correct way, this should be checked.
N/A I do not have access to Trello yet.
=> Refactors the placement route helpers in routes_helper.rb

spec/factories/subject.rb
Change Subject Factory code from `Faker::String.random(length: 2)` to `Faker::Alphanumeric.alpha(number: 2)`.
Faker::String.random(length: 2) => " 蛏" / "횝\u{5BD40}" / "铍Y"
Faker::Alphanumeric.alpha(number: 2) => "ax" / "dw" / "hd"
- Change Subject Factory code from `Faker::String.random(length: 2)` to `Faker::Alphanumeric.alpha(number: 2)`.
=> Fix factory subject code

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_content_header.scss, app/assets/stylesheets/components/_footer.scss, app/components/content_header_component.html.erb, app/components/footer_component.html.erb, app/components/footer_component.rb, app/helpers/footer_helper.rb, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb, config/locales/en/layouts/footer.yml, spec/components/footer_component_spec.rb, spec/components/previews/application_component_preview.rb, spec/components/previews/footer_component_preview.rb
We want to show "help" information and useful links.
- Add a custom `FooterComponent` that extends the `GovukComponent::FooterComponent` to add a `meta_pre_content` slot.
- The component html template is copied over directly from the component library. This means we will not receive automatic updates to this component's layout moving forward.
- I will reach out to Peter Yates to query whether we could add this additional slot in officially or not.
- Update the Footer content.
- View the review app.
- See the new footer content.
- The customised Footer component is copied from the `GovukComponent::FooterComponent`.
- [build_meta_links](https://github.com/x-govuk/govuk-components/blob/main/app/components/govuk_component/footer_component.rb#L65) is overridden to avoid calling view helpers …
=> Add Page Footer Content

app/controllers/claims/schools/claims/mentor_trainings_controller.rb, app/controllers/claims/schools/claims/mentors_controller.rb, app/controllers/claims/schools/mentors_controller.rb, app/forms/application_form.rb, app/forms/claim/mentor_training_form.rb, app/forms/claim/mentors_form.rb, app/models/claim.rb, app/models/mentor.rb, app/models/mentor_training.rb, app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/mentor_trainings/edit.html.erb, app/views/claims/schools/claims/mentors/_form.html.erb, config/locales/en/activemodel.yml, config/locales/en/activerecord.yml, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/schools/claims/mentor_trainings.yml, config/routes/claims.rb, spec/forms/claim/mentor_training_form_spec.rb, spec/forms/claim/mentors_form_spec.rb, spec/models/claim_spec.rb, spec/models/mentor_spec.rb, spec/models/mentor_training_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb
The mentor training hours form will come after the user selects the mentors for the claim. It will cycle through the mentors who don't have mentor training hours.
A column has been added to the mentor_training table, `custom_hours_completed`. This is for capturing the custom hours the user can input.
After inputting all the hours for the mentors the form will redirect to the check claim page.
The form also handles the paths of the backlinks and the success redirects.
`Claims::Schools::Claims::MentorTrainingsController`
`Claim::MentorTrainingForm`
Changes to `Claim::MentorsForm`
Changes to claims#check page
Pull or go on review app
Create a claim with a few mentors
Add mentor hours
Change the mentor hours on check page
Change the mentors on check page
Leave inputs blank to get errors
Play …
=> Add mentor training hours to claim form

app/controllers/claims/schools/claims_controller.rb, app/helpers/application_helper.rb, app/models/claim.rb, app/policies/claim_policy.rb, app/services/claim/submit.rb, app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/confirm.html.erb, app/views/claims/schools/claims/index.html.erb, config/locales/en/claims/schools/claims.yml, config/routes/claims.rb, db/migrate/20240229140214_add_columns_to_claims.rb, db/schema.rb, spec/factories/claims.rb, spec/helpers/application_helper_spec.rb, spec/models/claim_spec.rb, spec/services/claim/submit_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb
This is the last step in the create claim flow, the submit a claim functionality. For now we decided to use a Random number of 8 digits for the reference. This PR also adds a submitted_at datetime column to claim model
Migration
New Claims::Submit service
New Submit Page
Random 8 digits reference
Pull or go on review app
Go through the `Add claim` flow and submit a claim
You should get a reference back
And the claim you just created should be on the index page of the school/claims
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/4451e9eb-906c-496e-af53-38abf645964e
=> Claim Submit and generate reference

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims/mentor_trainings_controller.rb, app/controllers/claims/support/schools/claims/mentors_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/services/claims/submit.rb, app/views/claims/support/schools/claims/_form.html.erb, app/views/claims/support/schools/claims/check.html.erb, app/views/claims/support/schools/claims/edit.html.erb, app/views/claims/support/schools/claims/index.html.erb, app/views/claims/support/schools/claims/mentor_trainings/edit.html.erb, app/views/claims/support/schools/claims/mentors/_form.html.erb, app/views/claims/support/schools/claims/mentors/edit.html.erb, app/views/claims/support/schools/claims/mentors/new.html.erb, app/views/claims/support/schools/claims/new.html.erb, config/locales/en/claims/support/schools/claims.yml, config/locales/en/claims/support/schools/claims/mentor_trainings.yml, config/locales/en/claims/support/schools/claims/mentors.yml, config/routes/claims.rb, spec/services/claims/submit_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb
This is using the claim form already in place with a few tweaks like the support user cannot submit a claim, it just adds a claim in a draft status
- Support school claims form controllers
- Fix school claims check back link
- Changed Claim::Submit service to work with both support and not support claim forms
Pull or go onto the review app
Login as support user
Go into a school
Create a claim
Edit claim on the check page
Add the claim
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/6789d888-8703-4413-bfe5-6e1650f96222
=> Add claim form to support/school/claims

config/scheduled_jobs.yml
- Due to an issue when collecting the GIAS CSV at midnight (https://manage-school-placements-qa.test.teacherservices.cloud/good_job/jobs/d3c3adf2-f4b7-4c9b-a0cb-5bf50e17195e?locale=en#discrete_execution_31b2f310-cc1a-45f2-aa35-675ec692837c), change the schedule to run at the end of the day.
- Change the `gias_school_sync` scheduled job to run at 23:30.
=> Change schedule for GIAS sync job

app/assets/stylesheets/app-related-aside.scss, app/assets/stylesheets/application.scss, app/controllers/claims/support/application_controller.rb, app/helpers/routes_helper.rb, app/views/claims/pages/start.html.erb, config/locales/en/claims/pages.yml, config/routes/claims.rb, spec/support/dfe_sign_in_user_helper.rb, spec/system/claims/sign_in_page_spec.rb, spec/system/claims/start_page_spec.rb, spec/system/claims/support/schools/view_a_school_spec.rb, spec/system/claims/support/support_users/add_a_support_user_spec.rb, spec/system/claims/support/support_users/remove_a_support_user_spec.rb, spec/system/claims/support/support_users/view_a_support_user_spec.rb, spec/system/claims/support/support_users/view_support_users_spec.rb
The start page will be the new root_path of the claims domain, some changes have been made to accomodate this like specs or redirects
New root_path
New start page
Go to claims root_path
Inspect the start page
Click Start now
Sign in as before
Prototype: https://itt-mentoring-beta-94341ca35a2c.herokuapp.com/
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/acfc1b27-09f1-4819-b54e-dfcf0bd2145d
=> Add Claims Start Page

docs/connect-to-azure.md
Fix a typo in `docs/connect-to-azure.md`:
```diff
- 4. Click "Active" on `s189-teacher-services-cloud-test`.
+ 4. Click "Activate" on `s189-teacher-services-cloud-test`.
```
[Before](https://github.com/DFE-Digital/itt-mentor-services/blob/7dd1470fa03bb22489cee17904211df76b0f6e3b/docs/connect-to-azure.md) | [After](https://github.com/DFE-Digital/itt-mentor-services/blob/af3c7825568295b21e367212d516261471db2982/docs/connect-to-azure.md)
=> Fix a typo in the Azure doc

README.md, config/locales/en/claims.yml, config/locales/en/claims/pages.yml, config/locales/en/claims/support/support_users.yml, docs/data-model.md, spec/mailers/support_user_mailer_spec.rb, spec/mailers/user_mailer_spec.rb, spec/smoke_tests/claims/home_page_spec.rb, spec/system/claims/authenticate_user_spec.rb, spec/system/claims/sign_in_page_spec.rb, spec/system/claims/sign_out_as_claims_user_spec.rb, spec/system/claims/start_page_spec.rb, spec/system/claims/support/support_users/add_a_support_user_spec.rb, spec/system/claims/support/support_users/re_add_a_discarded_support_user_spec.rb, spec/system/claims/support/support_users/remove_a_support_user_spec.rb, spec/system/error_pages_spec.rb
Our service is now called `Claim funding for mentor training` this changes the translations to reflect this
Translations
Specs
Emails
Review the changes
=> Change claims service name

app/models/claims/school.rb, app/models/placements/school.rb, app/models/school.rb, app/models/trust.rb, app/services/gias/csv_importer.rb, db/migrate/20240311101329_create_trusts.rb, db/migrate/20240311101900_add_trust_to_school.rb, db/schema.rb, spec/factories/schools.rb, spec/factories/trusts.rb, spec/fixtures/gias/import_with_invalid_schools.csv, spec/models/claims/school_spec.rb, spec/models/placements/school_spec.rb, spec/models/school_spec.rb, spec/models/trust_spec.rb, spec/services/gias/csv_importer_spec.rb
It has become apparent in our user research that adding the ability to automatically add schools when in a trust would improve UX. Additionally this will give us more data-points for collecting information on the uptake and usage of this service.
Run the migrations to ensure they have been added properly, then run the `Gias::SyncAllSchoolsJob.perform_now` two times via your local console to ensure that the sync completes successfully. Finally, run a query to see that `Trust` data has been created and associated to schools.
[](https://trello.com/c/guVHJIOC)
=> Create Trust model & populate via GIAS sync

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/helpers/application_helper.rb, app/models/claim.rb, app/services/claims/submit.rb, spec/factories/claims.rb, spec/helpers/application_helper_spec.rb, spec/models/claim_spec.rb, spec/services/claims/submit_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/view_a_schools_claims_spec.rb
`Claim::Submit` service now accepts params hash. This way we can leave the `submitted_at` nil when a support user creates a claim. The support user cannot submit a claim.
This PR also fixes an edge case when there is a claim with a reference already in place and we submit that claim, instead of creating another reference we use the existing one.
Claim::Submit service
ApplicationHelper
Views
Specs
Create a claim as a support user
The date submitted should be blank
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/d8a01577-a25d-477e-b528-d2208b3ee39a
=> Leave date submitted blank for support claim

app/components/claim/status_tag_component.rb, app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/forms/claim/provider_form.rb, app/models/claim.rb, db/migrate/20240313102047_add_statuses_to_claim.rb, db/migrate/20240313104342_remove_draft_from_claim.rb, db/schema.rb, spec/factories/claims.rb, spec/forms/claim/provider_form_spec.rb, spec/models/claim_spec.rb, spec/services/claims/submit_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/schools/claims/view_claim_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb, spec/system/claims/support/claims/download_claims_csv_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb, spec/system/claims/support/claims/view_claims_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/view_a_schools_claims_spec.rb, spec/system/claims/support/schools/claims/view_claim_spec.rb
Previously, the claim status is determined by a boolean draft column on the claims table. As requirements have changed this is not supporting the functionality we need.
We need an `internal` status because we create a claim in DB when the user adds a mentor to a claim. Those claims should not be shown to the user.
The user should see claims that are `draft` or `submitted`, the other two statuses added in this commit.
We could have used the claim values to calculate the status of the claim but the logic would not scale very well so an enum seemed like the correct choice here.
These statuses should also help us with implementing policies.
Migrations to add status enum and remove draft boolean (There is no live data so we don't need to migrate data)
Set the correct status in the claim form …
=> Refactor claim statuses

.github/workflows/build_and_test.yml, config/environments/test.rb
It was noticed that the code coverage differed between local test and the CI test.
This was occurring due to `ENV["CI"].present?` being false when running rspec locally vs. running rspec on the CI. There is a great article on this exact issue https://reinteractive.com/articles/CI-simplecov-and-coverage-discrepancies and I have followed their advice.
If the CI passes without exploding, check the the code coverage report matches your local environment.
[Work out why our code coverage figures are inconsistent](https://trello.com/c/n3bFhqTT)
=> Match CI and local code coverage

app/services/publish_teacher_training/subject/import.rb, spec/factories/claims.rb, spec/factories/placements.rb, spec/factories/providers.rb, spec/factories/subject.rb, spec/models/provider_spec.rb, spec/services/claims/submit_spec.rb, spec/services/publish_teacher_training/provider/importer_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb, spec/system/placements/schools/placements/remove_a_placement_spec.rb, spec/system/placements/schools/placements/view_a_placement_spec.rb, spec/system/placements/schools/placements/view_placements_list_spec.rb
We’ve been using symbols and strings interchangeably for our enumerables within the application, this task will convert all string usages to symbols.
Updates all string uses for the `Claim#status`, `Placement#status`, `Subject#subject_area` and `Provider#provider_type` enumerables.
There should be no noticeble changes in the application, all tests should continue to pass as normal.
[Prefer symbols for enumerables](https://trello.com/c/k7B8irib)
=> Use symbols for enums

app/models/claim.rb, spec/models/claim_spec.rb
A claim should belong to a `Claims::School` not a `School` model as it's really for the claims domain.
`belongs_to :school, class_name: "Claims::School"`
Review code
=> Claim should belong to a Claims::School

app/controllers/application_controller.rb, app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/policies/claim_policy.rb, app/views/claims/support/schools/claims/check.html.erb, config/locales/en/claims/pages.yml, config/locales/en/claims/support/schools/claims.yml, config/routes/claims.rb, spec/policies/claim_policy_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/start_page_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb
Claim policies
The claim form didn't have any policies, meaning a claim could have been
updated or submitted twice by a user if they would know the url.
This PR fixes these edge cases.
It also will redirect the user to root path if he doesn't have access to a resource. This is because redirecting back to request.referrer can cause a redirection loop if the `request.referrer` is not a path the user has access to as well.
Claim policies
`Claims::Support::Schools::ClaimsController` submit action
Redirect to root_path if no access, only for claims domain
Try to submit the claim twice by clicking on the back button on the confirm page
Try to edit a submitted claim. 
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/065235b6-5b99-4f70-949b-d20542ceaeaa
=> Claim policies

app/views/claims/pages/start.html.erb, app/views/sessions/new.html.erb, config/locales/en/claims.yml, spec/system/claims/start_page_spec.rb, spec/system/error_pages_spec.rb
Change claims contact email from `becomingateacher@digital.education.gov.uk` to `ittmentor.funding@education.gov.uk`
translations
=> Change claims contact email

spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb
These specs were creating more schools than necessary in the database.
- Change `create(:claims_mentor)` call to `build(:claims_mentor)` call. This avoids preemptively creating the mentors with a school associated.
- Also, move up the mentor initialisation to put emphasis that they are being passed through to the `create(:claims_school)` call.
- Specs should pass.
- Only 1 school should be created in the changed files specs.
=> Build Mentors and pass them through to School in spec

Gemfile, Gemfile.lock, app/models/claims/claim.rb, app/models/claims/mentor_training.rb, config/application.rb, db/migrate/20240325095831_install_audited.rb, db/schema.rb, spec/models/claims/claim_spec.rb, spec/models/claims/mentor_training_spec.rb, spec/spec_helper.rb
We also need to permit ActiveSupport time classes in application.rb to allow audits with datetime values. 
Using these audits will come in a separate PR
Added gem
Migration
Audited claim and mentor training
Pull on local
Create some claims
View the audits in console with `claim.own_and_associated_audits` 
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/3ceb59e5-dbd8-4a96-813a-e03a7ea652fb
=> Add auditing to claim and mentor training

spec/rails_helper.rb
The smoke tests should not need access to a database. Fixtures tap into pre-filling data in a database. Without a database, this fails, even with the nulldb adapter.
- Avoid setting up fixtures when the ENV `SMOKE_TEST` is `"true"`.
Smoke tests should pass.
=> Don't setup fixtures when running smoke tests

app/views/claims/pages/grant_conditions.html.erb
We want to increase the clarity of the funding table to note that it is "per mentor" and not "per school".
- Add "per mentor" to table column header
Review the screenshot.
=> Update column header on grant conditions page

config/routes/claims.rb
We can reduce the verbosity of our route definitions here.
- Move `pages` routes into a `scope` block.
- Specs all pass.
=> Move page routes into a scope block

app/views/claims/schools/claims/show.html.erb, config/locales/en/claims/schools/claims.yml, spec/system/claims/schools/claims/view_claim_spec.rb
Normal users need to be able to submit a claim from the claims details. We can reuse the claim policy to enforce this.
Added submit claim button
Submit a draft claim from claims details page
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/1e6432e6-3c50-41b1-bf9c-214773e4ccc0
=> Add submit button to draft claim details for normal users

app/controllers/claims/schools/claims_controller.rb, app/forms/claim/mentor_training_form.rb, app/models/claims/claim.rb, app/services/claims/claim/remove_empty_mentor_training_hours.rb, spec/factories/mentor_trainings.rb, spec/models/claims/claim_spec.rb, spec/services/claims/claim/remove_empty_mentor_training_hours_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb
Previously, if a user didn't input mentor hours after adding a mentor
from the check page of the claim form and click the back link. A mentor
without hours would be added to the claim.
This commit will remove any mentors without hours when the user lands on
the check page of a claim. Fixing the issue
Also, this commit will redirect back to the check page when trying to
edit mentor training hours and clicking the back link
if the claim is ready to be checked. Previously the user would need to
cycle through all the mentor hours.
Claim model methods
Claims controller check mentor
Back link redirect for mentor training hours form
Specs
Create a claim
On the check page change the mentors
Add a mentor and click continue
Hit the back link to not input any training hours
Hit the back link again …
=> Fix claim back links

app/forms/claim/provider_form.rb, app/models/claims/claim.rb, app/policies/claims/claim_policy.rb, db/migrate/20240402144630_rename_claim_internal_to_internal_draft.rb, db/schema.rb, spec/factories/claims.rb, spec/forms/claim/provider_form_spec.rb, spec/models/claims/claim_spec.rb, spec/policies/claims/claim_policy_spec.rb, spec/services/claims/claim/create_draft_spec.rb, spec/services/claims/claim/submit_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb
This is not live data so chaining it in this way should be fine.
`internal_draft` claims status is a much better status than just `internal`
Run migration
Check your existing internal claims.
=> Rename claim status internal to internal_draft

app/controllers/claims/support/claims_controller.rb, app/queries/application_query.rb, app/queries/claims/claims_query.rb, spec/queries/application_query_spec.rb, spec/queries/claims/claims_query_spec.rb
We want to provide a maintainable approach to complex queries, such as Search and Filter capabilities.
- Add an `ApplicationQuery` class as a base class for creating query objects.
- Review the example `Claims::ClaimsQuery` class and it's drop-in replacement usage.
- Review the `ApplicationQuery`.
- Think of how you would use the existing `ApplicationQuery` and patterns in `Claims::ClaimsQuery` to add your own query objects.
=> Add Claims::ClaimsQuery for complex filtering

spec/services/claims/claim/remove_empty_mentor_training_hours_spec.rb
The PR that changed the claim status https://github.com/DFE-Digital/itt-mentor-services/pull/434 broke a spec that used the old status. This PR fixes the spec
Spec Claims::Claim::RemoveEmptyMentorTrainingHours
Do specs pass?
=> Fix spec after updating claim status enum

app/helpers/routes_helper.rb, app/views/claims/pages/feedback.html.erb, app/views/layouts/application.html.erb, config/routes/claims.rb, spec/helpers/routes_helper_spec.rb
Since we've decided to use MS forms for the feedback form, we've decided to link out to it here.
- Update "feedback" link in phase banner to external MS form.
- Link should open the MS form for "Give feedback on Claim funding for mentor training" in a new tab.
=> Add external link to the feedback form

app/jobs/claims/remove_internal_draft_claims_job.rb, app/services/claims/claim/remove_internal_drafts.rb, config/scheduled_jobs.yml, spec/jobs/claims/remove_internal_draft_claims_job_spec.rb, spec/services/claims/claim/remove_internal_drafts_spec.rb
Internal draft claims are claims that are incomplete, these claims can be created
by a user who doesn't submit/add a claim. Meaning they didn't go through the whole
claim form, they stopped half way.
These claims will just be in our DB if we don't remove them, they cannot be
picked up again.
This commit adds a job to remove the internal draft claims every day after
midnight. We only remove the internal draft claims that have been last updated
`1 day ago`, just in case we remove a claim that's in the process of being submitted.
Remove internal draft claims job and service
Specs
Sign in as Colin
Create a few internal draft claims with `updated_at` more than 1 day ago
Go to http://claims.localhost:3000/good_job/cron_entries?locale=en
Run the `Claims::RemoveInternalDraftClaimsJob` manually …
=> Remove internal_draft claims after midnight

app/controllers/application_controller.rb, app/controllers/claims/pages_controller.rb, app/controllers/sessions_controller.rb, spec/system/claims/start_page_spec.rb
Once signed in, clicking on the navbar logo took users to the "start" page. This meant that they were taken _out_ of the service, even when signed in.
We want users to stay inside of the service if they're signed in.
- User is redirected to their `after_sign_in_path` when visiting the `root_path` while signed in.
- Specs pass.
- Review the specs or try in a review app.
=> Redirect users to their respective homepages when visiting the root path

terraform/application/config/staging_app_env.yml
In staging, we can point to _other_ staging environments. This will ensure production services are intact while we perform any testing.
- Update `PUBLISH_BASE_URL` to point to `staging.api.publish-teacher-training-courses.service.gov.uk`
- Try updating your local setup to point to `staging.api.`, it should work as it does now.
=> Change staging PUBLISH_BASE_URL app env to point to staging environment

.env.test, config/routes/claims.rb, config/routes/placements.rb, lib/hosting_environment.rb, spec/system/claims/schools/claims/create_claim_spec.rb
We need to allow multiple entry domains per service. This is because we want to have access to the apps both behind Azure Front Door and directly to the application.
The app will function as-is without the new `#{service}_HOSTS` env vars, but to allow multiple entry domains, you must use the plural `_HOSTS` env var alongside the `_HOST` env var.
The `#{service}_HOST` env var is used for the base url of email link hrefs.
- Add `CLAIMS_HOSTS` and `PLACEMENTS_HOSTS` comma-separated env vars.
**Case 1**
- Don't add any additional env vars to your setup. It should "just work" as-is. The review app should also work without env var changes.
**Case 2**
- Pull down the code.
- Add the following env vars:
```dotenv
CLAIMS_HOSTS=claims.localhost,claims-2.localhost …
```
=> Allow multiple hosts for each service

app/components/autocomplete_select_form_component.html.erb, app/components/autocomplete_select_form_component.rb, app/forms/provider_onboarding_form.rb, app/forms/school_onboarding_form.rb, app/views/claims/support/schools/new.html.erb, app/views/placements/support/providers/new.html.erb, app/views/placements/support/schools/new.html.erb, config/locales/en/components/autocomplete_select_form_component.yml, spec/components/autocomplete_select_form_component_spec.rb, spec/components/previews/autocomplete_select_form_component_preview.rb, spec/forms/provider_onboarding_form_spec.rb, spec/forms/school_onboarding_form_spec.rb
- For ease of coding and reuse. An AutocompleteSelectFormComponent has replaced the repetitive code.
- Implement AutocompleteSelectFormComponent
- Replace existing duplicated code to use AutocompleteSelectFormComponent
_(Claims)_
- Test Onboarding Schools
_(Placements)_
- Test Onboarding Schools
- Test Onboarding Providers
_Previews available at_
http://placements.localhost:3000/rails/view_components
http://placements.localhost:3000/rails/view_components/autocomplete_select_form_component/provider_onboarding_form
http://placements.localhost:3000/rails/view_components/autocomplete_select_form_component/school_onboarding_form
http://claims.localhost:3000/rails/view_components
http://claims.localhost:3000/rails/view_components/autocomplete_select_form_com …
=> Add autocomplete select component

config/initializers/omniauth.rb, lib/hosting_environment.rb, spec/lib/hosting_environment_spec.rb
We need the dsi redirect to be more flexible, to allow more hosts to user DFE sign in so this commit just gets the base url from the request i.e. http://host:port and we can append `auth/dfe/callback` to it.
Omniauth dsi redirect URL
HostingEnvironment methods cleanup 
Use DFE sign-in on your local
It should work as normal
=> Refactor dsi redirect in omniauth

README.md
As we've updated our environments, we should keep the [README.md](https://github.com/DFE-Digital/itt-mentor-services/blob/3c8a2b8db36ea0d01dfd57d6a15b520a8f1fa270/README.md) up to date.
- Update links to Claims' QA, Staging, and Sandbox environments.
URLS should all be valid.
=> Update Claims deployment environments in README.md

app/controllers/sessions_controller.rb, app/models/dfe_sign_in_user.rb, spec/models/dfe_sign_in_user_spec.rb, spec/system/claims/sign_out_as_claims_user_spec.rb, spec/system/placements/sign_out_as_a_placements_user_spec.rb
Previously, the sign out link didn't actually comunicated with DSI to
log out the user. It would still keep them logged in, on their end.
This commit will send a request to DSI to logout the user and redirect
back to our own sign out path
New logout URL in the app
The logout URL has changed in the DSI console, for both placements and claims
Sign in with dfe sign in on local
Sign out
You should get the sign in form again
Current:
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/c28adb19-ca9b-4802-983a-19b02007f81d
Previously:
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/2dd9c9f6-6693-494d-9297-62011e7d5a5b
=> Allow DSI user to actually sign out

app/assets/stylesheets/filter-form.scss, app/assets/stylesheets/search-form.scss, app/javascript/controllers/filter_controller.js, app/javascript/controllers/index.js, app/views/claims/support/claims/_filter.html.erb, app/views/claims/support/claims/index.html.erb, config/locales/en.yml
The filters need to disappear and a show filter button needs to be
showed on a mobile view. This commit adds a basic stimulus controller
that will show/hide the filters using some CSS classes.
This should replicate how the prototype handles different screen sizes
Stimulus controller
Filter CSS changes
Go on support claims index and resize your window. It should be relatively responsive.
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/70d70754-3138-4039-a061-d9b77547fe80
=> Make the claims filters responsive

app/services/claims/mentor/calculate_remaining_mentor_training_hours_for_provider.rb, app/services/claims/mentor/calculate_total_mentor_training_hours_for_provider.rb, spec/services/claims/mentor/calculate_remaining_mentor_training_hours_for_provider_spec.rb, spec/services/claims/mentor/calculate_total_mentor_training_hours_for_provider_spec.rb
We need to add a validation to prevent a user from submitting claims that exceed the limit they can claim per provider.
This PR introduces a service to perform the calculations required to add the validation above.
> how many hours a mentor has spent training (which can be up to a maximum of 20 hours, per accredited ITT provider)
- Move the `Claims::CalculateTotalMentorTrainingHoursForProvider` to `Claims::Mentor::CalculateTotalMentorTrainingHoursForProvider`.
- Add a `Claims::Mentor::CalculateRemainingMentorTrainingHoursForProvider` service.
- Check the logic and specs are correct.
=> Add service to calculate remaining hours available to claim for a mentor

app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_heading.scss, app/views/claims/schools/claims/show.html.erb, app/views/claims/support/claims/_details.html.erb, app/views/claims/support/claims/show.html.erb, app/views/claims/support/schools/claims/show.html.erb, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/support/claims.yml, config/locales/en/claims/support/schools/claims.yml, spec/system/claims/schools/claims/view_claim_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb, spec/system/claims/support/schools/claims/view_claim_spec.rb
The claim details pages need to be updated to the latest design.
- Update the claim details page.
- Create a partial to share between support pages.
- Claim details pages look the same throughout the app.
- School / Claim
- Support / School / Claim
- Support / Claim
=> Update Claim details pages

app/controllers/sessions_controller.rb, config/routes.rb, spec/requests/sessions_spec.rb, spec/support/dfe_sign_in_user_helper.rb, spec/support/omniauth.rb, spec/system/claims/sign_in_as_a_claims_user_spec.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb
In very edge cases, DSI will send an auth/failure request to our app with a message.
We need to handle this gracefully so we redirect the user to the sign in page, sign him our if they are signed in and display a message.
We also send a request to Sentry.
New route and sessions controller method
Go to /auth/failure
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/70d7cf0d-da5b-4a94-a049-bb6ee0f8df49
=> Add auth/failure route

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/forms/claims/claim/provider_form.rb, config/locales/en/activemodel.yml, spec/forms/claims/claim/provider_form_spec.rb
The `Claims::Claim::ProviderForm` can be simplified.
- Use `validates` directly. No need for custom validators.
- No need to forward the errors from the underlying model to the form object.
- It still works as expected.
- Tests pass.
=> Use the FormObject directly when adding a provider to a claim

config/locales/en/activerecord.yml, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb
We need to provide a clearer error message when users submit decimal numbers.
- Update error message text.
- Try entering a non-whole number into the claim mentor hours completed input.
=> Update not_an_integer error message for mentor training hours

app/mailers/application_mailer.rb, spec/mailers/application_mailer_spec.rb, terraform/application/config/qa_app_env.yml, terraform/application/config/sandbox_app_env.yml, terraform/application/config/staging_app_env.yml
We need to use https in prod
Update ApplicationMailer to use "https" protocol for default url options in production
https://trello.com/c/ptxQVbba/234-update-applicationmailer-to-use-https-protocol-for-default-url-options-in-production
=> Update ApplicationMailer to use "https" protocol for default url options in production and add CLAIM_HOST

app/controllers/api/placements/provider_suggestions_controller.rb, app/controllers/api/placements/school_suggestions_controller.rb, app/controllers/api/provider_suggestions_controller.rb, app/controllers/api/school_suggestions_controller.rb, app/forms/placements/partnership_form.rb, app/models/placements/partnership.rb, app/views/placements/providers/partner_schools/new.html.erb, app/views/placements/schools/partner_providers/new.html.erb, spec/forms/placements/partnership_form_spec.rb, spec/models/placements/provider_spec.rb, spec/models/placements/school_spec.rb
- Allow any Provider/School to be linked in a partnership, regardless of if they have been onboarded to the Placements service.
- Delete Placements specific API controllers.
- Changes to model and form, to allow ANY `Provider` and `School` to be joined in partnership, regardless of Placements service onboarding.
_For Provider_
- Sign in as Provider User Patricia
- Click "Partner schools" from top Navigation.
- Click "Add partner school"
- You should now be able to search from a full list of Schools (Not just those onboarded on the Placements service)
- Continue through the check and creation process
- You should now see a Partnership has been made with the selected school (even if they are not onboarded onto the Placements service)
_For School_
- Sign in as School User …
=> Allow user to select ANY school or provider to create a partnership

app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/show.html.erb, app/views/claims/support/claims/_details.html.erb, app/views/claims/support/schools/claims/check.html.erb, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/support/claims.yml, config/locales/en/claims/support/schools/claims.yml, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/schools/claims/view_claim_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb, spec/system/claims/support/schools/claims/view_claim_spec.rb
We need to ensure we show the claim amount breakdown on a claim
Add the hourly rate and total hours to the claim views
- Create, edit and view claims as a support user
- Create, edit and view claims as a normal user
https://trello.com/c/BDuId4kG/403-as-a-user-support-user-i-want-to-see-the-breakdown-of-the-claim-amount
=> As a User & Support User, I want to see the breakdown of the claim amount

.env.example, Dockerfile, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/analytics.yml, config/analytics_blocklist.yml, config/analytics_pii.yml, config/initializers/dfe_analytics.rb, config/scheduled_jobs.yml, spec/services/concerns/service_pattern_spec.rb, terraform/application/config/production_app_env.yml, terraform/application/config/qa_app_env.yml, terraform/application/config/sandbox_app_env.yml, terraform/application/config/staging_app_env.yml
This will send data on every web request and whenever a table in config/analytics is updated/created. Regardless of domain. We don't have a way to distinguish between them at the moment, though the web requests do contain the domain.
A scheduled job is also going to run every day after midnight to keep in sync the BigQuery data with our own data.
We will send data to dfe-analytics in Production, Sandbox, Staging and QA.
I have included every table that we have apart from the ones that our gems generate. Some contain personal information, they have been included in `config/analytics_pii.yml` to handle the sensitive information. 
Dfe analytics setup
Review code.
This will only work when the envs have the secret keys
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/afbe1544- …
=> Add dfe-analytics

app/views/claims/schools/claims/confirm.html.erb, config/locales/en/claims/schools/claims.yml, config/locales/en/layouts/application.yml
We want to tell users that the feedback link will open in a new tab.
- Update feedback link text to include `(opens in a new tab)`.
- Check screenshots and compare to prototype.
=> Update feedback link text to tell user that it will open in a new tab

Gemfile, Gemfile.lock
The 1.12.4 has some changes that breaks the importing of entities to BigQuery. I will raise an issue with the dfe-analytics team but for now 1.12.3 should work for us.
The issue seems to be in this PR https://github.com/DFE-Digital/dfe-analytics/pull/132
The SQL syntax seems to be incorrect looking at https://dfe-teacher-services.sentry.io/issues/5259551627/events/76d8bafa5cc44fa3b063a78fbfeb4183/
```
ActiveRecord::StatementInvalid
PG::SyntaxError: ERROR:  syntax error at or near "2024" (ActiveRecord::StatementInvalid)
LINE 7: ...ships".updated_at) < DATE_TRUNC('milliseconds', ''2024-04-26...
```
Downgrade the gem to 1.12.3
Review
=> Downgrade dfe-analytics to 1.12.3

app/assets/stylesheets/application.scss, app/assets/stylesheets/utils/_all.scss, app/assets/stylesheets/utils/_overflow.scss, app/views/claims/schools/claims/index.html.erb
Wider tables are overflowing on mobile devices.
- Add a `utils` scss directory.
- ~Add a `responsive-table` utility class. Inspired from Bootstrap.~
- Add a `overflow-auto` utility class. Inspired from TailwindCSS. This allows the utility to be atomic and used in any component that requires this utility.
- Visit the `/schools/:school_id/claims` path with some claims on mobile. Only the table should be scrollable.
If well received, this may be a contender for an option (or default) of the `govuk_table` helper/component.
https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/68744b69-ed7e-48a9-a425-0acbe4ecdfba
=> Add Proof of Concept for responsive tables

app/components/claims/claim/mentors_form/disclaimer_component.rb, app/controllers/claims/schools/claims/mentors_controller.rb, app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims/mentors_controller.rb, app/forms/claims/claim/mentors_form.rb, app/forms/claims/claim/provider_form.rb, app/queries/claims/mentors_with_remaining_claimable_hours_query.rb, app/services/claims/mentor/calculate_remaining_mentor_training_hours_for_provider.rb, app/views/claims/schools/claims/mentors/_form.html.erb, app/views/claims/support/schools/claims/mentors/_form.html.erb, config/locales/en/activemodel.yml, config/locales/en/claims/schools/claims/mentors.yml, config/locales/en/claims/support/schools/claims/mentors.yml, config/locales/en/components/claims/claim/mentors_form/disclaimer_component.yml, spec/components/claims/claim/mentors_form/disclaimer_component_spec.rb, spec/components/previews/claims/claim/mentors_form/disclaimer_component_preview.rb, spec/forms/claims/claim/mentors_form_spec.rb, spec/forms/claims/claim/provider_form_spec.rb, spec/forms/claims/support/claim/mentors_form_spec.rb, spec/spec_helper.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/edit_draft_claim_spec.rb
When a mentor has no remaining claimable hours, they cannot be added to a claim. To avoid confusion and limit paths of error, we want to remove them from a School's list of selectable mentors when they have claimed all of their claimable hours across all schools.
- Refactored the `Claims::Claim::MentorsForm` to avoid the need to propagate errors.
- We need to send in the blanks to trigger validations.
- Show only mentors with remaining hours to claim in the claim flow.
- Changed the `Claims::Mentor::CalculateRemainingMentorTrainingHoursForProvider` service to accept a `claim` argument and find the relevant `mentor_training` record from `mentor` and `provider`.
- Add a claim with a mentor and claim all 20 hours for that mentor.
- Try to make a claim for the same provider. The mentor should …
=> Only show mentors with remaining claimable hours in claim flow

app/services/user/invite.rb, app/services/user/remove.rb, config/features.rb, spec/services/user/invite_spec.rb, spec/services/user/remove_spec.rb, spec/system/placements/organisations/users/add_users_spec.rb, spec/system/placements/organisations/users/user_removes_other_users_from_organisation_spec.rb, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb
- Due to a plan to onboard users/organisations onto the placements services prior to Day 1 release, we wish to disable onboarding emails being dispatched when being created/removed from the placements service.
- Added a feature flag condition to disable onboarding emails for the placements service.
_Enabled_
- run `bin/rake "flipflop:turn_on[user_onboarding_emails, active_record]"`
- Follow the onboarding process for a user for a school/provider
- An email should be dispatched (check https://www.notifications.service.gov.uk/)
_Disabled_
- run `bin/rake "flipflop:turn_off[user_onboarding_emails, active_record]"` (Default is **OFF**)
- Follow the onboarding process for a user for a school/provider
- An email should **NOT** be dispatched (check https://www.notifications.service.gov.uk/) …
=> Add feature flag to disable onboarding emails

app/controllers/placements/support/schools/placements_controller.rb, app/views/placements/support/schools/_secondary_navigation.html.erb, app/views/placements/support/schools/placements/index.html.erb, config/locales/en/placements/support/schools/placements.yml, config/routes/placements.rb, spec/system/placements/support/schools/placements/support_user_views_placements_spec.rb
Support users need to be able to view the placements that a school has in the support area.
Check out the code locally, log in as Colin, selected an organisation and view the placements tab.
[Placement index page for support users](https://trello.com/c/TXGNEorg)
=> Placement index page for support [1/4]

terraform/application/statuscake.tf
WHY: Status cake is not needed in all environments
HOW: By creating a new variable as enable_monitoring is not one to one
Status cake is not needed in all environments
Add new toggle variable for statuscake as enable_monitoring is not one to one with it
check statuscake is not on qa
https://trello.com/c/j0ZXrApw/1726-ittms-statuscake-monitoring
=> Added a toggle for statuscake

config/environments/production.rb
This will ensure the app always uses secure cookies and Strict-Transport-Security headers but allow for non-secure requests at the application layer as we encrypt traffic at our ingress layer.
- Set `config.force_ssl = true` and `config.assume_ssl = true` in `config/environments/production.rb`.
- Visit the review app.
- Check the headers.
- The cookie should have `secure` set on it.
- The `Strict-Transport-Security` header should be set.
- https://trello.com/c/FJUKdouv/417-when-the-session-cookie-is-set-it-should-be-marked-secure
- https://trello.com/c/gTL5sMZj/418-setup-our-security-headers
=> Force and assume SSL

config/initializers/content_security_policy.rb
We should only allow assets to be loaded in from our own domain.
- Add CSP headers.
- As we don't have any code pulling in assets from 3rd parties, our app should work as intended.
https://trello.com/c/gTL5sMZj/418-setup-our-security-headers
=> Add CSP headers

app/controllers/placements/support/schools/placements_controller.rb, app/views/placements/support/schools/placements/index.html.erb, app/views/placements/support/schools/placements/show.html.erb, config/locales/en/placements/support/schools/placements.yml, spec/system/placements/support/schools/placements/support_user_views_a_placement_spec.rb, spec/system/placements/support/schools/placements/support_user_views_placements_spec.rb
Support users need to be able to view the placements that a school has in the support area.
[Placement show page for support users](https://trello.com/c/jlfU86Ym)
=> Placement show page for support [2/4]

app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/show.html.erb, config/locales/en/claims/schools/claims.yml, spec/system/claims/schools/claims/submit_draft_claim_spec.rb
When a User submits a claim, they must always be presented with the declaration first.
- Add "grant conditions" prerequisite to claim declaration.
- When a User submits a "draft" claim, they will be taken to the check page with the declaration.
- Create a "draft" claim as a Support User.
- Submit that "draft" claim as the end User.
- You should see the declaration.
=> Require user declaration when submitting draft claims

config/locales/en/layouts/footer.yml, spec/helpers/footer_helper_spec.rb
- We won't commit to 1-day responses.
- The privacy policy is a privacy notice.
- Remove "one day" clause from footer email SLA.
- Update footer item from "Privacy policy" to "Privacy notice".
- Review screenshot.
=> Update footer email SLA & footer item wording

app/components/organisation_list_item.html.erb, app/components/organisation_list_item.rb, app/views/claims/schools/index.html.erb, app/views/placements/support/organisations/index.html.erb
We need to update the styling to match the prototype designs.
- Use `govuk_list` helper instead of plain html. Use the `spacing: true` option.
- Add a `show_details` flag to the `OrganisationListItem` component.
- Review screenshots.
- Review the `OrganisationListItem` component.
- For a future PR, we _could_ diverge into a `Claims::SchoolListItem` component.
Removed "organisation type".
=> Update styling and content of school lists

app/components/placement/summary_component.html.erb, app/components/placement/summary_component.rb, app/controllers/placements/providers/placements_controller.rb, app/decorators/placement_decorator.rb, app/views/placements/providers/placements/_mentor_details.html.erb, app/views/placements/providers/placements/_school_details.html.erb, app/views/placements/providers/placements/index.html.erb, app/views/placements/providers/placements/show.html.erb, config/locales/en/placements/providers/placements.yml, config/routes/placements.rb, spec/components/placement/summary_component_spec.rb, spec/components/previews/placement/summary_component_preview.rb, spec/system/placements/providers/placements/view_a_placement_spec.rb
- Add show page for Providers to view the details of a placement
- Added routes/controllers/views/etc. to allow Provider users the ability to view a placement.
- Sign in as Provider User Patricia
- Select a placement
https://trello.com/c/IYG33bcm/286-build-placement-details-page-for-providers-from-search-results-page
=> Add show page for provider placements

app/helpers/table_helper.rb, app/views/claims/pages/cookies.html.erb, app/views/claims/schools/_grant_conditions.html.erb, app/views/claims/schools/claims/index.html.erb, app/views/claims/schools/mentors/index.html.erb, app/views/claims/schools/users/index.html.erb, app/views/claims/support/schools/claims/index.html.erb, app/views/claims/support/schools/mentors/index.html.erb, app/views/claims/support/support_users/index.html.erb, app/views/placements/organisations/users/_list.html.erb, app/views/placements/providers/partner_schools/index.html.erb, app/views/placements/schools/mentors/index.html.erb, app/views/placements/schools/partner_providers/index.html.erb, app/views/placements/schools/placements/index.html.erb, app/views/placements/support/providers/users/index.html.erb, app/views/placements/support/schools/mentors/index.html.erb, app/views/placements/support/schools/placements/index.html.erb, app/views/placements/support/schools/users/index.html.erb, app/views/placements/support/support_users/index.html.erb
We want to make sure tables are _always_ accessible on mobile and don't cause a page overflow.
- Add a `app_table` helper that wraps a `govuk_table` in a `div` with the `overflow-auto` class.
This makes the table responsive and viewable across all screen sizes.
- Try navigating throughout the services on mobile. Tables should be scrollable when they overflow and not scrollable when they do not overflow.
=> [RFC] Create app_table helper to extend govuk_table helper

config/routes/claims.rb, spec/helpers/footer_helper_spec.rb
We want to use dashed paths.
- Change the `grant_conditions` path from `/grant_conditions` to `/grant-conditions`.
The "Grant Conditions" should now be accessible via `/grant-conditions` instead of `/grant_conditions`.
=> Update grant conditions path to "/grant-conditions"

app/components/autocomplete_select_form_component.html.erb, app/components/autocomplete_select_form_component.rb, app/controllers/placements/schools/placements_controller.rb, app/decorators/placement_decorator.rb, app/models/placement.rb, app/models/placements/provider.rb, app/models/placements/schools/placements/build/placement.rb, app/views/placements/schools/placements/edit_provider.html.erb, app/views/placements/schools/placements/show.html.erb, config/analytics.yml, config/locales/en/placements/schools/placements.yml, config/routes/placements.rb, db/migrate/20240424100627_add_provider_to_placement.rb, db/schema.rb, spec/decorators/placement_decorator_spec.rb, spec/factories/placements.rb, spec/models/placement_spec.rb, spec/models/placements/provider_spec.rb, spec/models/placements/schools/placements/build/placement_spec.rb, spec/system/placements/schools/placements/edit_a_provider_spec.rb, spec/system/placements/schools/placements/view_a_placement_spec.rb
School users should be able to select a provider for their placements then they know which provider will be assigned. This is an optional choice.
- Create a new placement
- Click on the placement on the index page
- Click on Change in the provider row
- Select a provider
- Click on continue
[Add Provider to Placement](https://trello.com/c/BSK7vNUk/269-provider-placements)
=> Add Provider to Placement

.env.example, .env.test, app/controllers/claims/schools/mentors_controller.rb, app/controllers/claims/support/schools/mentors_controller.rb, app/forms/claims/mentor_form.rb, app/services/claims/mentor_builder.rb, app/services/teaching_record/get_teacher.rb, app/services/teaching_record/rest_client.rb, app/views/claims/schools/mentors/check.html.erb, app/views/claims/schools/mentors/new.html.erb, app/views/claims/support/schools/mentors/check.html.erb, app/views/claims/support/schools/mentors/new.html.erb, config/locales/en/activemodel.yml, config/locales/en/claims/schools/mentors.yml, config/locales/en/claims/support/schools/mentors.yml, spec/jobs/teaching_record/sync_mentor_job_spec.rb, spec/services/claims/mentor_builder_spec.rb, spec/services/teaching_record/get_teacher_spec.rb, spec/system/claims/schools/mentors/add_a_mentor_spec.rb, spec/system/claims/support/schools/mentors/support_user_adds_a_mentor_spec.rb, terraform/application/config/dv_review_app_env.yml, terraform/application/config/production_app_env.yml, terraform/application/config/qa_app_env.yml, terraform/application/config/review_app_env.yml, terraform/application/config/sandbox_app_env.yml, terraform/application/config/staging_app_env.yml
We want the user to input a date of birth when adding a mentor.
Otherwise its easy to guess your way to a trn and revealing personal
information about teachers.
The teacher record api can do this validation for us we just need to
update the version that we use and pass the DOB to the teacher record
api.
New Claims Mentor builder
New DOB field
New env variable and edits to specs
Add a mentor as a normal and support user
Try to add mentors you already added.
Dob with trn examples
```
```
`TEACHING_RECORD_API_MINOR_VERSION` needs to be at least `20240416`
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/e209ae63-95ff-4ab9-b9d6-b998cee9c5cc
=> Ask for DOB when adding a claim mentor

app/controllers/heartbeat_controller.rb, spec/requests/dfe_analytics_spec.rb
DfE Analytics automatically logs every web request received by the application. This happens because the top-level `ApplicationController` includes the `DfE::Analytics::Requests` concern, meaning every controller automatically inherits this behaviour.
For the most part, this is desirable behaviour. As described in the [dfe-analytics][1] README, the gem provides an _opinionated_ integration which is designed to send _every_ web request into BigQuery.
However, the `/healthcheck` endpoint is a special case. This endpoint is hit very frequently by our infrastructure layer to make sure the app is up, running, and healthy. From checking request logs, it looks like this is hit once every second.
It's not valuable to record these healthcheck requests in BigQuery. In fact it's quite wasteful of …
=> Disable DfE Analytics for the healthcheck endpoint

app/controllers/heartbeat_controller.rb
A quick follow-on from #566. It [was suggested](https://ukgovernmentdfe.slack.com/archives/CQCHZUZ0F/p1714484008292679?thread_ts=1714483199.696549&cid=CQCHZUZ0F) that a simpler way to skip DfE Analytics would be to simply avoid inheriting from `ApplicationController` altogether.
Refactors the HeartbeatController (which powers the `/healthcheck` endpoint) so it doesn't inherit from the `ApplicationController`.
This simplifies the controller because it no longer needs to explicitly skip undesirable functionality such as user authentication or integration with DfE Analytics.
This controller doesn't need all the magic and niceties of regular user-facing controllers.
By inheriting from [ActionController::API][1], the controller will now be as lightweight as possible. Which is ideal for this …
=> Skip ApplicationController on healthcheck endpoint

app/helpers/routes_helper.rb, spec/helpers/routes_helper_spec.rb
The claims feedback link was pointing to the wrong form URL.
https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Becoming%20a%20Teacher/twd-mentoring/Private%20Beta/Content/For%20Jen%20(content%20designer)%20to%20check%20over%20ahead%20of%20go%20live.docx?d=w3830e4992cb645ed836565c712546840&csf=1&web=1&e=xeitVH&nav=eyJjIjoxNDgzNTI0NzMwfQ
- Update the feedback link's url
- Feedback link should now open https://forms.office.com/e/0E3277Kqpi
=> Update the claims feedback url

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/models/claims/claim.rb, app/policies/claims/claim_policy.rb, app/views/claims/schools/claims/rejected.html.erb, app/views/claims/support/schools/claims/rejected.html.erb, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/support/schools/claims.yml, config/routes/claims.rb, spec/models/claims/claim_spec.rb, spec/policies/claims/claim_policy_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb
We have a race condition where a user can create a claim for a mentor before someone else trying to do the same thing.
So you can end up with more mentor training hours per provider than the maximum 20 hours allowed, per provider.
This PR adds a validation step in the submit and draft controller actions and redirect the user to a reject page when this happens
This PR adds a validation step in the submit and draft controller actions and redirect the user to a reject page when this happens.
Validation method on the claim model. This should not be used as a `validates` method, we want to have control over when this is called.
New reject route and page
Try replicating the example below 👇🏻 
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/ba188aee-e8d6-4074-a0f4-dcc509a2bc74
=> Reject claims with invalid mentor training hours

config/initializers/money.rb, spec/components/claim/card_component_spec.rb
We want to always show `.00` in monetary values.
- Set `no_cents_if_whole` to `false`.
- Whole pound values should now show `.00`. i.e. `£123` will be displayed as `£123.00`
=> Always show pence, even when amount is a whole pound

.github/workflows/build_and_deploy.yml, .github/workflows/delete_review_app.yml
Context
The review apps delete workflow gets cancelled atimes due to concurrency
Changes proposed in this pull request
basing the concurrency on the PR number like other services
Guidance to review
close the pr and see if it deletes and reopen later
Link to Trello card
https://trello.com/c/FIHMmqbA/1788-ittms-fix-delete-review-app
=> Fix review app cancelling issue

app/controllers/claims/schools/claims/mentors_controller.rb, app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/mentors/_form.html.erb, app/views/claims/support/schools/claims/check.html.erb, app/views/claims/support/schools/claims/mentors/_form.html.erb, config/locales/en/claims/schools/claims/mentors.yml, config/locales/en/claims/support/schools/claims/mentors.yml, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb
When a User attempts to select mentors for a claim that have all fully been claimed for with the provider selected, we should show a message that stops users from proceeding further.
- Add a variant of the mentor select page that shows an error message when 
- Update `spec/system/claims/support/schools/claims/create_claim_spec.rb` to only create a single school. This removes the flakiness of this spec suite when it randomly creates 2 schools with the same name.
- Fully claim all hours for a school's mentors against a provider.
- Try to claim for a mentor against that provider.
- It should say that you have no mentors you can claim for.
https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/13de0a64-6395-4472-a110-44646b26aea2
=> Add mentors empty state page for claim flow

app/views/layouts/application.html.erb, app/views/layouts/component_preview.html.erb
Our `<script>` tags are failing to run due to the introduced CSP headers. Introducing a `nonce` attribute will allow our inline script to run.
Read more: https://content-security-policy.com/nonce/
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https: 'nonce-0a72447c9cb151a11bd8f9e838221385'". Either the 'unsafe-inline' keyword, a hash ('sha256-B7RcigeAzKunsdJAeUuN6QlBWFIF5z5Tq/oPFk4GrLM='), or a nonce ('nonce-...') is required to enable inline execution.
```
This will then prevent the `govuk-frontend-supported` class from being added to the document body.
```
SupportError: GOV.UK Frontend initialised without `<body class="govuk-frontend-supported">` from template `<script>` snippet
```
Which prevents GOV.UK …
=> Add nonce to <script> tags to comply with CSP header

config/analytics.yml, config/analytics_blocklist.yml
BigQuery doesn't handle the pii information. Previously we were sending
this information and this caused the production pipeline to fail.
Adding them to the block list should fix this because we won't send pii
information
analitycs.yml files
Review code
=> Remove pii information from analytics.yml

app/views/claims/support/schools/claims/rejected.html.erb
Previously we were using the primary navigation for normal users in the support rejected page
Render correct partial
Add a claim for mentors that have been claimed for already, for that provider
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/db8b6606-cc46-460f-aa26-67460f0ff295
Before this change
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/44314372-845e-4177-8396-bb03b3549d61
=> Fix claims rejected page for support

app/models/user.rb, spec/models/user_spec.rb
When inputting user details, we want to make sure there are no extra spaces around their name or email address and their email address should always be lowercase.
- Trim whitespaces around `User#first_name` and `User#last_name`.
- Trim whitespaces and downcase `User.email`.
- Try adding a user with extra spaces around the inputted data.
- It should go through without issue.
=> Normalize User first_name, last_name, and email attributes

config/locales/en/claims/support/claims.yml, spec/system/claims/support/claims/view_claims_spec.rb
Oli, Lizzie and I were looking at the support section of the website and we found this spelling error.
Fix the spelling of 'provider'
Assume it's correct!
=> It's provider, not prvoider

app/controllers/placements/schools/placements/build_controller.rb, app/views/placements/schools/placements/build/add_mentors.html.erb, app/views/placements/schools/placements/build/add_phase.html.erb, app/views/placements/schools/placements/build/add_subject.html.erb, app/views/placements/schools/placements/build/check_your_answers.html.erb, spec/system/placements/schools/placements/add_a_placement_spec.rb
Navigation was becoming complex and confusing for users on a simple creation page.
- Updated the navigation flows based off of a discussion with design. It was decided that the back button duplicates the browser back button and the continue button always moves through steps for creating a placement, regardless of where you start the flow.
- The continue button will now always move to the next step, regardless of whether you've clicked on change. A primary school will always step through Subject -> Mentor -> Check your answers.
- The back button will mimic the browser back button
[Update Add a Placement navigation](https://trello.com/c/3thwfUqj/264-update-add-a-placement-navigation)
=> Update placement navigation

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/forms/claims/claim/mentor_training_form.rb, app/forms/claims/support/claim/mentor_training_form.rb, app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/mentors/edit.html.erb, app/views/claims/support/claims/_details.html.erb, app/views/claims/support/schools/claims/check.html.erb, app/views/claims/support/schools/claims/mentors/edit.html.erb, config/routes/claims.rb, spec/forms/claims/claim/mentor_training_form_spec.rb, spec/forms/claims/support/claim/mentor_training_form_spec.rb
Previously the claims mentors edit route was not a collection so when editing the mentor list on the claim the url was `/schools/:school_id/claims/:claims_id/mentors/:mentor_id/edit`
Now is `/schools/:school_id/claims/:claims_id/mentors/edit` as we are editing a collection of mentors not a particular one
Changed mentors route
Create a claim and edit the mentors on the check page.
The URL should not contain any mentor id
Do the same as support user
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/f4e7a42b-9c9e-460c-bfe9-464909461787
=> Fix the claim mentors route

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/forms/claims/claim/mentors_form.rb, app/forms/claims/claim/provider_form.rb, app/forms/claims/support/claim/mentors_form.rb, app/forms/claims/support/claim/provider_form.rb, app/models/claims/claim.rb, app/services/claims/claim/review.rb, app/views/claims/schools/claims/edit.html.erb, app/views/claims/schools/claims/mentors/edit.html.erb, app/views/claims/support/schools/claims/edit.html.erb, app/views/claims/support/schools/claims/mentors/edit.html.erb, config/analytics.yml, db/migrate/20240501065503_add_reviewed_by_user_to_claim.rb, db/schema.rb, spec/factories/claims.rb, spec/forms/claims/claim/mentors_form_spec.rb, spec/forms/claims/support/claim/mentors_form_spec.rb, spec/forms/claims/support/claim/provider_form_spec.rb, spec/models/claims/claim_spec.rb, spec/services/claims/claim/review_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/edit_draft_claim_spec.rb
When creating a claim you can end up on the edit page of a claim, or mentors list.
These edit pages were programmed to always go to the check page, so when a user would click them it would try to redirect them to the check page.
This commit fixes this with a reviewed boolean field which is set to true when the user lands on the check page.
We use this boolean to know where to redirect the user, back to the check page or through the steps ending on the index page.
Once a user lands on the check page, the back buttons should always redirect him to the check page.
Reviewed boolean
Change back links
Change update success path(The continue buttons) 
Create a claim and right before getting to the check page, click the back links all the way to the index page
Create a claim and right before …
=> Fix back link when creating a claim

terraform/domains/infrastructure/.terraform.lock.hcl, terraform/domains/infrastructure/config/zones.tfvars.json
Add new DNS zone for  manage-school-placements.
Added 'manage-school-placements.education.gov.uk' to domains.
Verify DNS zone with name from azure portal : manage-school-placements.education.gov.uk 
https://trello.com/c/XVe4ftpa/1723-school-placement-domain
=> Zone manage-school-placements added

app/controllers/placements/support/support_users_controller.rb, config/routes/claims.rb
We want our claims support_users path to be support-users
Routes change
Small placements redirect bug
Review changes
=> Changed claims support_users to support-users path

app/views/claims/pages/accessibility.en.html.erb, app/views/claims/pages/cookies.en.html.erb, app/views/claims/pages/grant_conditions.html.erb, app/views/claims/pages/privacy.en.html.erb, app/views/claims/pages/terms.en.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, config/locales/en/claims/pages.yml
We want a way for the user to get back to the home page from our static pages. So the breadcrumbs will contain the current page and a home page.
The home page link will go to the school/claims index page if normal the user is logged in.
For support users it will redirect to organisations index page. This is because we redirect from the root path to these pages if a user is signed in.
Pages controller, views, locals
Go through the static pages and check the breadcrumbs
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/74c7e7b8-78e6-42f3-b0f0-7bcce573bb6e
=> Add breadcrumbs to our static pages

app/controllers/claims/schools/claims/mentor_trainings_controller.rb, app/controllers/claims/schools/claims/mentors_controller.rb, app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims/mentor_trainings_controller.rb, app/controllers/claims/support/schools/claims/mentors_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/models/claims/claim.rb, app/policies/claims/claim_policy.rb, app/services/claims/claim/create_revision.rb, app/services/claims/claim/update_draft.rb, app/services/claims/mentor/calculate_remaining_mentor_training_hours_for_provider.rb, app/services/claims/mentor/calculate_total_mentor_training_hours_for_provider.rb, app/views/claims/schools/claims/check.html.erb, app/views/claims/support/claims/_details.html.erb, app/views/claims/support/schools/claims/check.html.erb, config/analytics.yml, config/routes/claims.rb, db/migrate/20240419100125_add_revisions_to_claims.rb, db/migrate/20240422135851_remove_claim_reference_unique_constraint.rb, db/schema.rb, spec/factories/claims.rb, spec/models/claims/claim_spec.rb, spec/services/claims/claim/create_revision_spec.rb, spec/services/claims/claim/update_draft_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/edit_draft_claim_spec.rb
In testing the claim form we concluded that we cannot edit the same claim record on the check page when creating a claim.Issues were found when the user would click the back buttons to go back to the check page after completing half their changes. The changes they did were being saved. Even if they backed off from doing them.
To solve this issue and many others, we are implementing a revision system on the claim.
Creating a revision every time a user wants to edit a claim from the check page. If they back off half way through their changes we revert back to the last valid claim revision.
This implementation will increase the audit records and possibly pollute some of them with `system changes` i.e. changes to `previous_revision_id` which the user doesn't care about.
This should fix the …
=> Implement claim revisions on claim form

app/mailers/application_mailer.rb, spec/mailers/support_user_mailer_spec.rb, spec/mailers/user_mailer_spec.rb
We want our tests to behave as close as possible to production. Therefore, the `test` environment should behave like `production` when possible.
- Only prefix hosting environment to emails sent from non-production, non-test environments.
- View the tests.
- Try sending an email :)
=> Don't prefix email subjects in the test environment

app/controllers/placements/schools/placements/build_controller.rb, app/controllers/placements/schools/placements_controller.rb, app/decorators/placement_decorator.rb, app/views/placements/providers/placements/_mentor_details.html.erb, app/views/placements/schools/placements/edit_provider.html.erb, app/views/placements/schools/placements/show.html.erb, app/views/placements/support/schools/placements/show.html.erb, config/locales/en/placements/schools/placements.yml, spec/components/placement/summary_component_spec.rb, spec/decorators/placement_decorator_spec.rb, spec/system/placements/providers/placements/view_a_placement_spec.rb, spec/system/placements/schools/placements/add_a_placement_spec.rb, spec/system/placements/schools/placements/edit_a_provider_spec.rb, spec/system/placements/schools/placements/edit_mentors_spec.rb, spec/system/placements/schools/placements/view_a_placement_spec.rb, spec/system/placements/schools/placements/view_placements_list_spec.rb, spec/system/placements/support/schools/placements/support_user_views_a_placement_spec.rb
Now that designs have been provided the "build" version of the page needs updating to match.
Create a placement
View the placement
Click on change next to provider
Make your changes
Click on continue
[Update managing a provider for a placement](https://trello.com/c/vlDrAZt1/301-update-adding-a-provider-to-a-placement)
=> Update placement provider management

app/mailers/application_mailer.rb, app/mailers/support_user_mailer.rb, app/mailers/user_mailer.rb, app/services/support_user/remove.rb, config/locales/en/support_user_mailer.yml, config/locales/en/user_mailer.yml, spec/mailers/application_mailer_spec.rb, spec/mailers/support_user_mailer_spec.rb, spec/mailers/user_mailer_spec.rb, spec/system/claims/schools/users/invite_a_user_to_a_school_spec.rb, spec/system/claims/support/schools/invite_a_user_to_a_school_spec.rb, spec/system/claims/support/support_users/add_a_support_user_spec.rb, spec/system/claims/support/support_users/re_add_a_discarded_support_user_spec.rb, spec/system/claims/support/support_users/remove_a_support_user_spec.rb, spec/system/placements/organisations/users/add_users_spec.rb, spec/system/placements/organisations/users/user_removes_other_users_from_organisation_spec.rb, spec/system/placements/support/support_users/support_user_adds_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_re_adds_a_discarded_support_user_spec.rb, spec/system/placements/support/support_users/support_user_removes_a_support_user_spec.rb, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb
When we updated the email templates for launch, we snuck in some tech debt by hardcoding the "Claims" service name.
We now need to update the templates to respect which service is calling them.
/* In the future, we may need separate templates/mailer classes for each service.
- Update templates to use `service` and `service_name` where suitable.
- Specs pass.
- @DFE-Digital/school-placements is happy? :D
=> Update email templates to respect service names

app/controllers/placements/schools/placements/build_controller.rb, app/views/placements/schools/placements/build/check_your_answers.html.erb, spec/system/placements/schools/placements/add_a_placement_spec.rb
If a school had no mentors we'd end up with an empty page, this change makes sure that the page is never shown if no mentors have been added.
Removes the add mentors page if none exist.
Remove all mentors and create a placement, make sure it works as expected.
["Add a placement" – skip the "mentors" step if the org has no mentors](https://trello.com/c/r4KlVY8Z/303-add-a-placement-skip-the-mentors-step-if-the-org-has-no-mentors)
=> Skip placement mentors if none exist

app/views/claims/schools/_grant_conditions.html.erb
The support email address was not rendered in the grant conditions, section 9. Had a minor typo. `<%` instead of `<%=`.
- Update heading sizes for grant conditions partial.
- Fix small typo.
- Check if heading sizes match the prototype. Sizes, not classes.
- Content in section 9 should now be equal.
=> Update grant conditions heading sizes and update support email

terraform/domains/environment_domains/.terraform.lock.hcl, terraform/domains/environment_domains/config/production.tfvars.json, terraform/domains/environment_domains/config/qa.tfvars.json, terraform/domains/environment_domains/config/sandbox.tfvars.json, terraform/domains/environment_domains/config/staging.tfvars.json
Added manage-school-placements domains  for qa,sandbox and staging
New domians for manage-school-placements for all environments.
https://trello.com/c/XVe4ftpa/1723-school-placement-domain
=> Added doamins  for qa,sandbox and staging

app/controllers/placements/providers/placements_controller.rb, app/forms/placements/placements/filter_form.rb, app/queries/placements/placements_query.rb, app/views/placements/providers/placements/_filter.html.erb, config/locales/en/placements/providers/placements.yml, spec/forms/placements/placements/filter_form_spec.rb, spec/system/placements/providers/placements/view_placements_list_spec.rb
Schools need to be able to filter by their partner providers to help them find placements
Adds a new partner providers filter to the find a placement page
Log in as Patricia and navigate to placements. Selecting the filter will only show partner schools. Both the clear all filters and the partner schools pill will clear this filter.
[Change 'partner school' filter to a toggle](https://trello.com/c/bOmsoFoY)
=> Add partner school toggle

app/controllers/placements/schools/placements/build_controller.rb, app/controllers/placements/schools/placements_controller.rb, app/models/placements/school_contact.rb, app/policies/placement_policy.rb, app/views/placements/schools/placements/index.html.erb, config/locales/en/activerecord.yml, config/locales/en/placements/schools/placements.yml, spec/factories/schools.rb, spec/models/placements/school_contact_spec.rb, spec/policies/placement_policy_spec.rb, spec/system/placements/organisations/view_organisations_spec.rb, spec/system/placements/schools/placements/add_a_placement_spec.rb, spec/system/placements/schools/school_contacts/add_a_school_contact_spec.rb, spec/system/placements/schools/school_contacts/edit_a_school_contact_spec.rb
- Prevent school users from adding placements until they have added School Contact details
- Policy to allow/prevent school users adding placements until a School Contact has been added.
- Prevent School Contact records being destroyed.
- _Assumption is Anne's school does not have a school contact_
- Navigate to the placements index page.
- You should see "You must add the ITT placement contact email before adding a placement"
- Follow the process to add a School Contact
- Navigate to the placements index page.
- You should now see a button to allow you to "Add placement"
https://trello.com/c/8EZ9v87N/326-stop-schools-from-creating-placements-if-the-itt-placement-contact-is-missing
_No school contact_
_With school contact_
=> Prevent school user add placements until school contacts are added

app/controllers/placements/pages_controller.rb, app/helpers/footer_helper.rb, app/views/placements/pages/cookies.html.erb, app/views/placements/pages/cookies.md, config/locales/en/placements/pages.yml, config/routes/placements.rb, spec/helpers/footer_helper_spec.rb, spec/system/placements/cookies_page_spec.rb
- Add cookies page to the placements service footer.
- Markdown file of cookies page content.
- HTML cookies page.
- Visit http://placements.localhost:3000/cookies
https://trello.com/c/S8Pzj9iv/337-footer-content-cookies
=> Add cookies page

app/controllers/placements/pages_controller.rb, app/helpers/footer_helper.rb, app/views/placements/pages/accessibility.md, app/views/placements/pages/show.html.erb, config/locales/en/placements/pages.yml, config/routes/placements.rb, spec/helpers/footer_helper_spec.rb, spec/system/placements/accessibility_page_spec.rb
- Add static accessibility policy page.
- Add accessibility policy markdown.
- Change routes to use `action: :show` with a `page:` argument.
visit http://placements.localhost:3000/accessibility
https://trello.com/c/LZ3Nu1rt/339-footer-content-accessibility-statement
=> Add accessibility policy page

app/views/placements/schools/placements/build/add_subject.html.erb, spec/system/placements/schools/placements/add_a_placement_spec.rb
Secondary subject selection should now be a single choice
With a secondary school create a placement and see that there are now radio buttons.
[Use radio buttons on the secondary subjects list for placements](https://trello.com/c/Obwp4oYQ)
=> Convert secondary subject checkboxes to radios

terraform/application/config/production_app_env.yml, terraform/application/config/qa_app_env.yml, terraform/application/config/sandbox_app_env.yml, terraform/application/config/staging_app_env.yml
We need to configure our Rails app to accept traffic for the `manage-school-placements.education.gov.uk` hostname and route it to the correct service.
I've added environment variable configuration for the School Placements domain name that will be used for private beta.
Configure the hostnames as follows:
| Environment | Hostname                                          |
|-------------|---------------------------------------------------|
| QA          | qa.manage-school-placements.education.gov.uk      |
| Staging     | staging.manage-school-placements.education.gov.uk |
| Sandbox     | sandbox.manage-school-placements.education.gov.uk |
| Production  | manage-school-placements.education.gov.uk         |
This mirrors the hostname configuration used by the Funding Mentors service.
I'm not …
=> Add config for the School Placements domain name

app/controllers/claims/schools/users_controller.rb, app/controllers/claims/schools_controller.rb, app/controllers/claims/support/schools/mentors_controller.rb, app/controllers/claims/support/schools/users_controller.rb, app/controllers/claims/support/schools_controller.rb, app/models/mentor.rb, app/models/user.rb, app/views/claims/support/schools/claims/_form.html.erb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/schools/mentors/view_mentors_spec.rb, spec/system/claims/schools/users/view_users_spec.rb, spec/system/claims/schools/view_school_spec.rb
We want to order most of our (Claims) index pages alphabetically.
- Order providers in Claim flow by name.
- Order users in index pages (support-user/end-user) by name.
- Order mentors in index pages (support-user/end-user) by name.
- Order schools in index pages (support-user/end-user) by name.
- The pages noted above should all be ordered by their names in alphabetical order.
=> Order resources by name on index pages

app/controllers/claims/schools/claims_controller.rb, app/policies/claims/claim_policy.rb, app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/remove.html.erb, app/views/claims/schools/claims/show.html.erb, config/locales/en/claims/schools/claims.yml, config/routes/claims.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/remove_draft_claim_spec.rb, spec/system/claims/schools/claims/submit_draft_claim_spec.rb, spec/system/claims/schools/claims/view_claim_spec.rb
This mainly removes the change links on the check page for the draft claim, when a normal user tries to submit a draft claim.
The change links are on the show page now.
This is for a draft claim for normal users
Added remove functionality to show claim
The check page does not have change links if the claim is draft
The show page has change links 
Submit a draft claim on the review app
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/b0b3f0a2-ce1e-46f0-9a87-a9fdef51a01c
=> Update declaration page for draft claim

.env.test, app/services/claims/claim/submit.rb, app/slack_notifiers/application_slack_notifier.rb, app/slack_notifiers/claims/application_slack_notifier.rb, app/slack_notifiers/claims/claim_slack_notifier.rb, lib/slack_notifier.rb, spec/lib/slack_notifier_spec.rb, spec/services/claims/claim/submit_spec.rb, spec/slack_notifiers/application_slack_notifier_spec.rb, spec/spec_helper.rb
We want to know when a Claim has been made.
- Introduce a `SlackNotifier` library class.
The `SlackNotifier` is app-agnostic and is therefore placed in the `lib` directory.
The API signature mirrors `ActionMailer` and therefore should provide a very familiar developer experience.
We could update the class to use a `defaults` method, as `ActionMailer` does, to set default values on the `message` call.
Where `to` needs to be an array of email addresses for `ActionMailer`, `SlackNotifier` should be able to configure a `to` of a Slack channel ID. Alternatives, we could name the parameter `channel`. We also provide a `endpoint_url` value that acts as the _delivery_method_ (or SMTP configuration) comparable.
- To provide a clear separation of concerns between app-specific code vs app-agnostic …
=> Add Claims service Slack notification when a Claim has been submitted

app/views/placements/providers/placements/show.html.erb, spec/system/placements/providers/placements/view_placements_list_spec.rb
https://trello.com/c/VDSgNUdW
When a user sets filters when finding a placement they are lost if the user views the placement and presses the back button.
- Navigate to Placements
- Set some flters
- View a placement
- Press the back button
- Confirm that filters are still present
[The 'back' link on the placement details page should remember the user's search parameters](https://trello.com/c/VDSgNUdW)
=> Convert to browser back button behaviour to retain filters

app/slack_notifiers/application_slack_notifier.rb
The `ApplicationSlackNotifier` is failing when `ENV["PORT"]` is missing.
The `ApplicationSlackNotifier` should default to no specific port, i.e. be port-less (port 80 by default on browsers).
- Use `ENV["PORT"]` instead of `ENV.fetch("PORT")` and allow `nil` for missing `PORT` env var.
- Remove `PORT` from your local env vars, it should now work fine.
- The host for urls built in the slack notifier will be `claims.localhost` instead of `claims.localhost:3000` (if your PORT is set to 3000). In Production, this is the intended behaviour.
=> [BUGFIX] Prevent ApplicationSlackNotifier from failing when PORT is missing

app/models/placement.rb, app/models/placements/placement_additional_subject.rb, app/models/placements/schools/placements/build/placement.rb, app/models/subject.rb, config/analytics.yml, db/migrate/20240520141009_add_parent_subject_to_subjects.rb, db/migrate/20240520141421_add_subject_to_placements.rb, db/migrate/20240520143732_create_placement_additional_subjects.rb, db/schema.rb, spec/factories/placements.rb, spec/factories/placements/placement_additional_subjects.rb, spec/factories/subjects.rb, spec/models/placement_spec.rb, spec/models/placements/placement_additional_subject_spec.rb, spec/models/placements/schools/placements/build/placement_spec.rb, spec/models/subject_spec.rb
- With the redesign to include "Additional Subjects", the data model has been changed to allow the following:
- Subjects belongs to a Parent Subject (optional)
- A Subject has many Child Subjects
- A Placement belongs to a Subject (optional for now, but filled by `after_save`)
- A Placement has many Placement Additional Subjects
- A Placement has many Additional Subjects, through Placement Additional Subjects
- Changes to Subject and Placement models to allow for Placements to have Additional Subjects
- Changes to Placement so that it belongs to a Subject
in the rails console:
```ruby
placement = Placement.new(school: Placements::School.last, subjects: [Subject.last])
placement.save!
placement.subject # This should return the same record as Subject.last
``` …
=> Update subject and placement data model for additional subjects

app/views/placements/schools/school_contacts/check.html.erb
- Fix to School Contact "Cancel" button on "Check your answers" page.
- Cancel button on School Contact "Check your answers" page, should redirect you back to Organisation Details page.
https://github.com/DFE-Digital/itt-mentor-services/assets/17162488/10698acd-aad1-4246-be83-0f89beaa4d82
=> Fix school contact cancel button

app/assets/stylesheets/components/claim/card.scss
We want to ensure the status tag is always on the top-right corner of the card.
- Remove the flex-wrap.
- Check the screenshot.
- or try adding a claim to a school with a long name in the review environment of this PR.
=> Stop wrapping the claim card header section

app/views/claims/schools/claims/show.html.erb, spec/system/claims/schools/claims/view_claim_spec.rb
Previously, the change button was shown on the show page for submitted claim, this button needs to only show for draft claims
This doesn't mean that users can change submitted claims. There are policies that don't permit this.
Show the button only on for draft claims
Go on show page of a submitted claim1
https://github.com/DFE-Digital/itt-mentor-services/assets/11318084/4302fc15-f7db-4aca-abae-bee2f16b74d4
=> Fix claim show page for normal users

app/services/publish_teacher_training/subject/import.rb, db/data/20240522123948_update_modern_language_child_subjects.rb, db/data_schema.rb, spec/services/publish_teacher_training/subject/import_spec.rb
- Changes to update Subjects, related to the "Modern Languages", to associated them with the parent subject "Modern Languages" 
- `PublishTeacherTraining::Subject::Import` considers `ModernLanguagesSubject` its own subject area.
- `PublishTeacherTraining::Subject::Import` assigns subjects within the `ModernLanguagesSubject` subject area with the parent subject "Modern Languages"
- Added Data Migration to backfill database with child subject associations for "Modern Languages" associated subjects.
- run `bundle exec rake data:migrate`
- This will backfill and language subjects with the parent subject "Modern Languages"
- in the rails console run: `Subject.find_by(name: "Modern Languages").child_subjects`
- This should return [French, German...]
- run `bundle exec rake db:drop db:create …
=> Add data migration to associate modern language child subjects

db/data/20240523154417_backfill_placements_with_subject.rb, db/data_schema.rb
- Add data migration to backfill all placements where they are missing a `subject_id`.
- Add data migration to backfill all placements where they are missing a `subject_id`.
run: `bundle exec rake data:migrate`
All Placements should now have a `subject_id`
https://trello.com/c/xIgJ213c/365-re-model-placement-subjects-part-1
=> Backfill placement subject_id

app/views/placements/support/_secondary_navigation.html.erb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_remove_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/view_a_partner_school_as_support_user_spec.rb, spec/system/placements/support/providers/partner_schools/view_partner_school_list_as_support_user_spec.rb, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb
The sub navigation for support users hasn't matched designs for a while, these changes bring the build back into line with the prototypes.
- Select a provider from the organisation list
- See that the sub navigation matches the designs
- Select a school from the organisation list
- See that the sub navigation matches the designs     
[Tidy up redundant navbar items across the app](https://trello.com/c/BFBK5fqz)
Support viewing a provider:
Support viewing a school:
=> Update sub nav items

config/locales/en/placements.yml, spec/mailers/user_mailer_spec.rb, spec/system/error_pages_spec.rb
- Change support email address to `[Manage.SchoolPlacements@education.gov.uk](mailto:Manage.SchoolPlacements@education.gov.uk)`
- Check the footer of the Placements service.
https://trello.com/c/brM05Q5W/412-update-the-support-email-link-in-the-footer
=> Change placements support email address

app/views/placements/schools/placements/build/check_your_answers.html.erb, config/locales/en/placements/schools/placements.yml
- Correct "Check your answers" page title
- Remove "- Add placement" from title displayed on the page.
https://trello.com/c/mgdfYe6F/388-add-placement-check-your-answers-page
_Before_
_After_
=> Remove ' - Add placement' from title

.env.test, spec/mailers/support_user_mailer_spec.rb, spec/mailers/user_mailer_spec.rb, spec/slack_notifiers/application_slack_notifier_spec.rb
The PORT env var is not expected in production, so we should mirror that behaviour in test.
- Remove `PORT` from `.env.test`
- Tests should pass. Ports should be missing.
=> Remove PORT from .env.test

app/views/placements/placements/show.html.erb, app/views/shared/schools/_school_contact_details.html.erb, config/locales/en/placements/providers/placements.yml, db/seeds.rb, spec/system/placements/placements/view_a_placement_spec.rb
- Changes to Provider view of Placements to align with the [Prototype](https://bat-school-placements-18b07385d8a1.herokuapp.com/provider-users/v1/placement-detail)/[Figma](https://www.figma.com/design/0MJTBT9nHaU0zBUWMwOeUQ/School-placements?node-id=60827-35576&t=WsTpsQU82FIlOzFP-0)
- Add ITT placement contact to Placement show page
- Minimise School Details to Location and Additional Details
- Navigate to "Placements" using the Navbar
- Click any placement to view it's details
- Placement details should display the ITT contact details, Location and Additional Details
https://trello.com/c/4tDFWDZ6/405-provider-%E2%86%92-placement-details-page
=> Update placement show page for providers

app/controllers/placements/schools/placements/build_controller.rb, app/decorators/placement_decorator.rb, app/models/placement.rb, app/models/placements/schools/placements/build/placement.rb, app/policies/placement_policy.rb, app/views/placements/schools/placements/build/add_year_group.html.erb, app/views/placements/schools/placements/build/check_your_answers.html.erb, app/views/placements/schools/placements/show.html.erb, app/views/placements/support/schools/placements/show.html.erb, config/analytics.yml, config/locales/en/placements/schools/placements.yml, config/routes/placements.rb, db/migrate/20240528153905_add_year_group_to_placement.rb, db/schema.rb, spec/decorators/placement_decorator_spec.rb, spec/factories/placements.rb, spec/models/placement_spec.rb, spec/models/placements/schools/placements/build/placement_spec.rb, spec/system/placements/schools/placements/add_a_placement_spec.rb
Adds the year group selection for primary schools so that they can specify which age range the placement is for.
Log in as Anne
Add a placement
Select your subject
Select your year group
Select your mentor
Review your answers and check that the year group is correct
Change the year group
Continue back to the Check your answers page
Confirm the year group has been updated
Add a 'year group' step to the 'add placement' journey
=> Add year group journey

app/javascript/controllers/autocomplete_controller.js
Currently the school selection concatenates data togther into a space separated string. For readability we have decided that it should be a comma separated string. Additionally `null` values were slipping through into the results, these have been removed.
Log in as Colin
Add an organisation
Search for "York Ste"
See that the data is comma separated and that no `null` values are present
[Add a comma & hide "null" values](https://trello.com/c/Wt2OCdhk)
=> Update school search boxes to add comma's and remove null values

app/mailers/user_mailer.rb, config/locales/en/user_mailer.yml, spec/mailers/user_mailer_spec.rb
The Placements service requires different email content.
- Split content based on service.
This unblocks placements.
Moving forward, the likelihood of our emails being equal seems low. I suggest we split out into `Claims::___Mailer` and `Placements::___Mailer` classes. Not for this PR.
=> Split email heading content per service

app/views/claims/schools/claims/_form.html.erb
A bug slipped through and was detected in a flaky spec.
- Order Providers by name alphabetically on the end-user's side.
- Providers are ordered correctly.
=> Fix ordering of providers by name on end-user side

Makefile
Fix tag on resource group s189p01-ittmsdomains-rg and Fix Makefile.
Fix tag on resource group s189p01-ittmsdomains-rg changes on make file.
Verify tags on  s189p01-ittmsdomains-rg , it should have Product:ITT mentor services
https://trello.com/c/FS1Th32O/1842-fix-ittms-azure-tag
=> Removed set-azure-resource-group-tags which is not required

spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb
The claims/support/schools/claims/change_claim_on_check_page spec was checking against nil values, this is not really good practice.
This PR fixes this by removing the specs doing this as they don't really add value. The intention was to not create new claims when editing a claim as a support user but this is done in the support [edit_draft_claim_spec](https://github.com/DFE-Digital/itt-mentor-services/blob/1f2ca6611e926ab533913e679d1a8cf80c06e4fa/spec/system/claims/support/schools/claims/edit_draft_claim_spec.rb#L168-L171)
claims/support/schools/claims/change_claim_on_check_page
Review code
Before:
After:
=> Fix support claims spec warning

app/javascript/controllers/placements_filter_search_controller.js
- Fix to placements filter search JS, so when searching a filter it doesn't remove pre-selected checkboxes
- Remove line 70, to stop toggleItems unchecking checkboxes.
- Sign in as Patricia.
- Navigate to "Placements" in Navbar.
- Select a checkbox in either the schools or subjects filters.
- Type into the search bar of that filter.
- Clear the search filter.
- The selected filter should still be checked.
https://trello.com/c/EDAUUu7h/446-search-filter-component-fix-a-bug-where-the-inline-search-unchecks-previously-checked-options
https://github.com/DFE-Digital/itt-mentor-services/assets/17162488/0b535878-71e7-46d2-82b9-9183948da45d
=> Fix to placment filter search js

app/forms/placements/placements/filter_form.rb, app/javascript/controllers/placements_filter_search_controller.js, app/queries/placements/placements_query.rb, app/views/placements/placements/_filter.html.erb, spec/forms/placements/placements/filter_form_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
- Remove Establishment group from search filter
- Sign in as Patricia
- Navigate to "Placements" in Navbar
- Establishment group should no longer appear in the filters
https://trello.com/c/3vV6Jzc1/432-remove-the-establishment-group-search-filter
=> Remove establishment group search filter

config/locales/en/placements/support/primary_navigation.yml, config/locales/en/placements/support/support_users.yml, spec/system/placements/support/organisations/support_filtering_and_searching_for_organisation_spec.rb, spec/system/placements/support/organisations/support_user_selects_an_organisation_type_to_add_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_without_javascript_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_remove_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/view_a_partner_school_as_support_user_spec.rb, spec/system/placements/support/providers/partner_schools/view_partner_school_list_as_support_user_spec.rb, spec/system/placements/support/providers/support_user_adds_a_provider_spec.rb, spec/system/placements/support/providers/support_user_adds_a_provider_without_javascript_spec.rb, spec/system/placements/support/schools/mentors/support_user_adds_a_mentor_spec.rb, spec/system/placements/support/schools/mentors/support_user_removes_a_mentor_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_adds_a_partner_provider_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_adds_a_partner_provider_without_javascript_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_removes_a_partner_provider_spec.rb, spec/system/placements/support/schools/partner_providers/view_a_partner_provider_as_support_user_spec.rb, spec/system/placements/support/schools/partner_providers/view_partner_school_list_as_support_user_spec.rb, spec/system/placements/support/schools/placements/support_user_removes_a_placement_spec.rb, spec/system/placements/support/support_users/support_user_adds_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_re_adds_a_discarded_support_user_spec.rb, spec/system/placements/support/support_users/support_user_removes_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_views_a_support_user_spec.rb, spec/system/placements/support/support_users/support_user_views_support_users_spec.rb, spec/system/placements/support/users/support_user_invites_a_new_user_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb
Having "Users" twice in the navigation was causing confusion and it was decided that we'd update the primary navigation "Users" to "Support users"
- Verify that there is a Support users link
- Navigate to Support users
- Verify that the button now says "Add support user"
- Go through the add journey to make sure everything is consistent
[Rename "Users" to "Support users" in the support console](https://trello.com/c/kacBdWq8)
=> Rename "Users" to "Support users" in the support console

app/views/placements/support/schools/mentors/check.html.erb
- Fix broken change like on Mentor check your answers page
- Navigate to "Mentors" in navbar
- Click the "Add mentor" button
- Complete the Add mentor form
- Once on the "Check your answers" page, check the "Change" links redirect back to the previous page.
https://trello.com/c/zbmPhroZ/447-fix-a-broken-change-link-in-the-support-console
https://github.com/DFE-Digital/itt-mentor-services/assets/17162488/0d087cb6-cd4b-4eeb-a147-0b322030b973
=> Fix broken change link

app/views/placements/placements/index.html.erb, config/locales/en/placements/providers/placements.yml
Grammatical correctness.
- Click on Placements
- See that the text changes based on how many results you have after filtering
[Use pluralisation for placement search results subheading](https://trello.com/c/r4ebHq8P)
=> Use pluralisation for placement search results subheading

app/controllers/placements/schools/placements_controller.rb, app/views/placements/schools/placements/edit_mentors.html.erb, app/views/placements/schools/placements/edit_provider.html.erb, config/locales/en/placements/schools/placements.yml, spec/requests/placements/schools/placements/placements_spec.rb, spec/support/capybara.rb, spec/system/placements/schools/placements/edit_a_provider_spec.rb, spec/system/placements/schools/placements/edit_mentors_spec.rb
Validation already exists in the add a placement flow, but when editing mentors the validation is missing. Whilst this did not cause an issue with the data, it did provide a lack of consistency for users.
Adds the validation to the change mentor flow.
Log in as Anne
View a placement
Change the mentor
Deselect all checkboxes
Click on continue
See validation message
[Bug: When managing/editing a placement's mentor, selecting nothing does not error](https://trello.com/c/3FHL9VvO/408-bug-when-managing-editing-a-placements-mentor-selecting-nothing-does-not-error)
=> Add validation to change mentor flow

app/controllers/placements/schools/placements/build_controller.rb, app/controllers/placements/schools/placements_controller.rb, app/models/placement.rb, app/views/placements/schools/placements/edit_year_group.html.erb, app/views/placements/schools/placements/show.html.erb, config/locales/en/placements/schools/placements.yml, config/routes/placements.rb, spec/models/placement_spec.rb, spec/requests/placements/schools/placements/placements_spec.rb, spec/system/placements/schools/placements/edit_a_year_group_spec.rb
For placements in a primary subject, the user should additionally specify the year group of the placement.
- Create a primary placement
- View the placement after creation
- Click on change next to the year group
- Select a new year group
- Click on continue
- Verify the year group has changed
[Add 'year group' to the School → Placement details page](https://trello.com/c/7UuaXb9A)
=> Add 'year group' to the School → Placement details page

app/controllers/placements/placements_controller.rb, app/forms/placements/placements/filter_form.rb, app/queries/placements/placements_query.rb, app/views/placements/placements/_filter.html.erb, config/locales/en/placements/placements.yml, spec/forms/placements/placements/filter_form_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
So providers can find primary placements by their year group.
- Create a new primary placement
- Log out
- Navigate to Placements
- Filter on the year group for the placement you created as Anne
- Verify that the placement is visible after filtering the results
[Add a search filter for 'year group'](https://trello.com/c/9uXzUI7r)
=> Add a search filter for 'year group'

app/controllers/placements/placements_controller.rb, app/forms/placements/placements/filter_form.rb, app/queries/placements/placements_query.rb, app/views/placements/placements/_filter.html.erb, config/locales/en/placements/placements.yml, spec/forms/placements/placements/filter_form_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
Designs have been updated to support a radio button selection of filters instead of just available placements
- Make a note of the organisation
- Log out
- Create a placement, assign it to the same organisation that Patricia is in
- Create a second placement assigned to a different organisation
- Log out
- Navigate to Placements
- Verify that Available placements is selected by default, all placements should be available
- Change the filter to Assigned to me, there should be 1 unavailable placement
- Change the Placements to show filter to all placements, there should be 2 unavailable placements
[Implement the 'Placements to show' search filter](https://trello.com/c/pwv8cvSD)
=> Placements to show filter

app/views/placements/support/providers/partner_schools/remove.html.erb, app/views/placements/support/schools/partner_providers/remove.html.erb, app/views/placements/support/schools/placements/remove.html.erb
Content has been reviewed across the app for inconsistencies, this brings the app back in line with designs.
- Remove a placement, check the text
- Remove a partner provider, check the text
- Remove a partner school, check the text
[Support console – include organisation name in page captions](https://trello.com/c/LI149XK9)
=> Support console – include organisation name in page captions

app/models/dfe_sign_in_user.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb
- Users with SupportUser accounts, should be logged in as Support Users over their other accounts.
- Change `app/models/dfe_sign_in_user.rb` to log the user in as their SupportUser, over their other accounts.
⚠️ Can't be tested in Review, as it uses Personas instead of DfE ⚠️ 
- Create two accounts using the same email address (One Placements::SupportUser, One Placements::User)
- Sign in via DfE Sign In
- The user should see the Support User interface
https://trello.com/c/GF1dL3p7/458-when-someone-has-both-a-user-and-a-support-user-account-prefer-their-support-account
=> Users with support accounts should login in as support users over other user accounts

app/controllers/api/provider_suggestions_controller.rb, app/controllers/api/school_suggestions_controller.rb, app/javascript/controllers/autocomplete_controller.js, spec/system/placements/providers/partner_schools/view_partner_schools_list_spec.rb, spec/system/placements/schools/partner_providers/view_partner_providers_list_spec.rb, spec/system/placements/support/providers/partner_schools/view_partner_school_list_as_support_user_spec.rb, spec/system/placements/support/schools/partner_providers/view_partner_school_list_as_support_user_spec.rb
During our bug party, we noticed the autocomplete suggestions were very unresponsive when provided by an Ajax endpoint.
This PR optimises the way suggestions are requested by the client, and the response that the server returns. Together with PR #735, this should greatly improve the performance and perceived responsiveness of the autocomplete component.
1. [Reduce the debounce timeout on autocompletes](https://github.com/DFE-Digital/itt-mentor-services/commit/35000d03ea0a338cfaa09bcffa965bd42636a695)
2. [Optimise the size of autocomplete responses](https://github.com/DFE-Digital/itt-mentor-services/commit/9db546bc486abc84425460ca930eb791317abb8f)
I also [fixed a flaky test](https://github.com/DFE-Digital/itt-mentor-services/commit/543033dd296898adf9d876eba207ffa7c4218597) which seemed to …
=> Optimise school and provider autocompletes

app/decorators/placement_decorator.rb, spec/system/placements/placements/view_placements_list_spec.rb
When we filter down the placements we also clip out their additional subjects. The simplest way to resolve this issue is to reload the record when we need the additional subject names. We do not want to reload the record when dealing with the add a placement flow as the record is not saved at this point and no filters can be applied.
- Navigate to placements
- Filter on one of the MFLs, e.g. "French"
- Verify that the full title of the placement is displayed.
[Placement title changes on MFL placements when filtering by language subjects](https://trello.com/c/FnhiFmsk/466-placement-title-changes-on-mfl-placements-when-filtering-by-language-subjects)
=> Fix additonal subject names after filter

app/views/placements/placements/index.html.erb, spec/system/placements/placements/view_placements_list_spec.rb
- Fix issue where clicking "Clear search" (on the placements page) does not make the filters persist.
- Add filter arguments to the Search Form partial.
- Navigate to "Placements" in the Navbar
- Select some filters
- Click "Apply filters"
- Enter a location into the "Enter a location" search input (such as "London")
- Click "Search"
- Filters and Search location should persist
- Click "Clear search"
- The filters should still persist.
https://trello.com/c/CutFfUgX/465-confirm-interaction-for-clear-filters-vs-clear-search-links-and-implement
https://github.com/DFE-Digital/itt-mentor-services/assets/17162488/d44ef2d2-48a4-4399-a8ea-0602f631a613
=> Fix issue with clear search removing selected  filters

app/views/placements/placements/_filter.html.erb
Filters on the placements search page should appear in the following order:
- Placements to show
- Subject
- Primary year group
- Partner schools
- School
This should be the sort order for both filters and ‘selected filters’ in the sidebar.
- Navigate to Placements
- Check the order of the filters against the list above 👆 
[Update the ordering of search filters](https://trello.com/c/OYMDKQxL/433-update-the-ordering-of-search-filters)
=> Re-order the filters for providers

app/models/dfe_sign_in_user.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb
Fix issue with DfE Sign In for QA, when no `dfe_sign_in_uid` is given in params
- Check if `dfe_sign_in_uid` is present when using DfE sign in
- Sign in as the different Personas
https://trello.com/c/fY3TaaSQ/477-fix-a-bug-in-qa-where-non-support-users-got-signed-in-as-support
=> Fix issue with DFE sign in

app/controllers/placements/support/support_users_controller.rb, spec/requests/placements/providers/users_spec.rb, spec/requests/placements/schools/users_spec.rb, spec/requests/placements/support/support_users_spec.rb
I noticed we weren't covering the "support user cannot delete themselves" scenario, and so it was possible to remove the authorization code and the tests would still pass.
I've added request specs to prove that users must be authorized when deleting other users. It also proves that users cannot delete themselves.
I also noticed that we were running `authorize @support_user` twice on the `Placements::Support::SupportUsersController#destroy` action, so I've tidied that up.
Do the tests pass?
Discovered while working on: https://trello.com/c/URtV1kGv/403-make-find-placements-the-default-page-for-providers
=> Add test coverage for user deletion

app/views/placements/pages/landing-page.md, app/views/placements/schools/placements/index.html.erb, config/locales/en/forms/organisation_onboarding_form.yml, config/locales/en/placements/placements.yml, config/locales/en/placements/schools.yml, config/locales/en/placements/schools/placements.yml, config/locales/en/placements/schools/school_contacts.yml, config/locales/en/placements/support/organisations.yml, config/locales/en/shared/schools/school_contact_details.yml, config/locales/en/shared/schools/school_details.yml, spec/forms/organisation_onboarding_form_spec.rb, spec/system/placements/placements/view_a_placement_spec.rb, spec/system/placements/schools/placements/add_a_placement_spec.rb, spec/system/placements/schools/school_contacts/add_a_school_contact_spec.rb, spec/system/placements/schools/school_contacts/edit_a_school_contact_spec.rb, spec/system/placements/support/organisations/support_user_selects_an_organisation_type_to_add_spec.rb
After a content sweep it was decided that acronyms should be removed.
- Check changes against content designs
[Replace use of ITT acronym in service](http://placements.localhost:3000/schools/000b2c51-9c1c-41b2-bd40-8f79f8ae8be1/placements)
=> Replace itt across service

app/controllers/placements/schools/placements/build_controller.rb, app/views/placements/schools/placements/build/add_additional_subjects.erb, app/views/placements/schools/placements/build/add_mentors.html.erb, app/views/placements/schools/placements/build/add_phase.html.erb, app/views/placements/schools/placements/build/add_subject.html.erb, app/views/placements/schools/placements/build/add_year_group.html.erb, app/views/placements/schools/placements/build/check_your_answers.html.erb, spec/system/placements/schools/placements/add_a_placement_spec.rb
The back button was not working as expected during the bug party.
- Add a placement
- Fill in the form until you get to check your answers
- Click on the back button until you return to the placements page
[Confirm interaction for the 'back' link during the 'Add placement' journey – and implement it](https://trello.com/c/6ofqSDIW/464-confirm-interaction-for-the-back-link-during-the-add-placement-journey-and-implement-it)
=> Update add a placement back button

app/helpers/footer_helper.rb, app/views/placements/pages/cookies.md, app/views/placements/pages/privacy.md, app/views/placements/schools/mentors/check.html.erb, app/views/placements/support/schools/mentors/check.html.erb, config/locales/en/placements/pages.yml, spec/helpers/footer_helper_spec.rb
We do not have a privacy notice
- Check the privacy notice link in the footer
- Navigate to Mentors
- Add a mentor
- Continue through to Check your answers
- Check the privacy notice link on the check your answers page
- Log out
- Select an organisation
- Navigate to Mentors
- Add a mentor
- Continue through to Check your answers
- Check the privacy notice link on the check your answers page
[Add the privacy policy page](https://trello.com/c/PPR4AtAk/455-add-the-privacy-policy-page)
=> Add privacy notice

app/helpers/footer_helper.rb, spec/helpers/footer_helper_spec.rb
The guidance footer item is not needed for the placements service
- Log in as anyone
- Confirm the guidance footer item is gone
[Remove the 'Guidance' footer link](https://trello.com/c/ZuEG8sK0/483-remove-the-guidance-footer-link)
=> Remove guidance from the placements footer

app/forms/placements/mentor_form.rb
- Move validation in MentorForm, so it appears in the order: TRN, DOB
- Navigate to "Mentors" using the Navbar
- Click "Add mentor"
- Check the validation appears in to order of inputs.
https://trello.com/c/WKiF870U/484-add-mentor-%E2%86%92-change-the-order-of-validation-messages-shown-in-the-error-summary
=> Swap mentor form validation

app/controllers/placements/schools/school_contacts_controller.rb, app/models/placements/school_contact.rb, app/views/placements/schools/school_contacts/_form.html.erb, app/views/placements/schools/school_contacts/check.html.erb, app/views/shared/schools/_school_contact_details.html.erb, config/analytics.yml, config/locales/en/placements/schools/school_contacts.yml, config/locales/en/shared/schools/school_contact_details.yml, db/data/20240607144521_split_school_contact_name_into_first_and_last_name.rb, db/data_schema.rb, db/migrate/20240607135849_add_first_name_and_last_name_to_school_contact.rb, db/schema.rb, db/seeds.rb, spec/factories/placements/school_contacts.rb, spec/models/placements/school_contact_spec.rb, spec/system/placements/placements/view_a_placement_spec.rb, spec/system/placements/schools/school_contacts/add_a_school_contact_spec.rb, spec/system/placements/schools/school_contacts/edit_a_school_contact_spec.rb
- Swap "Full name" `(:name)` for "First name" and "Last name" on School Contact 
(Aligning with [strong migrations](https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column) the `name` will be removed in another PR)
- Add `first_name` column to 'school_contacts'
- Add `last_name` column to 'school_contacts'
- Swap "Full name" with "First name" and "Last name" inputs on SchoolContact forms
- Swap "Full name" with "First name" and "Last name" in school contact details partial
- Navigate to "Organisation detail"
- The School Contact details shown should be `first_name`, `last_name` and `email`
- Click any of the "Change" links
- The form should have inputs for ONLY `first_name`, `last_name` and `email`
- Change the inputs for …
=> Part 1 add first and last name to school contact

config/locales/en/activemodel.yml, config/locales/en/placements/schools/partner_providers.yml, config/locales/en/placements/support/providers.yml, config/locales/en/placements/support/schools/partner_providers.yml, spec/components/autocomplete_select_form_component_spec.rb, spec/components/previews/autocomplete_select_form_component_preview.rb, spec/forms/placements/partnership_form_spec.rb, spec/forms/provider_onboarding_form_spec.rb, spec/system/placements/schools/partner_providers/add_a_partner_provider_spec.rb, spec/system/placements/schools/partner_providers/add_a_partner_provider_without_javascript_spec.rb, spec/system/placements/support/organisations/support_user_selects_an_organisation_type_to_add_spec.rb, spec/system/placements/support/providers/support_user_adds_a_provider_spec.rb, spec/system/placements/support/providers/support_user_adds_a_provider_without_javascript_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_adds_a_partner_provider_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_adds_a_partner_provider_without_javascript_spec.rb
Acronyms within the service should be written out in full
[Write out acronyms in full](https://trello.com/c/0zCQZ26z/442-write-out-acronyms-in-full)
=> Convert provider messaging to long form

app/forms/placements/mentor_form.rb, config/locales/en/activemodel.yml, spec/forms/placements/mentor_form_spec.rb
- Add validation for MentorForm, so that the Date of Birth is in the past.
- Navigate to "Mentors" using the Navbar
- Click "Add mentor"
- Enter a Date of Birth in the future (e.g 23/05/2044)
https://trello.com/c/3kcGzw2M/485-add-mentor-%E2%86%92-validate-dob-so-it-cannot-be-in-the-future
=> Validate DOB is in the past

app/forms/placements/mentor_form.rb, app/views/placements/schools/mentors/new.html.erb, spec/forms/placements/mentor_form_spec.rb, spec/system/placements/schools/mentors/user_adds_mentor_spec.rb, spec/system/placements/support/schools/mentors/support_user_adds_a_mentor_spec.rb
When entering an invalid TRN or Date of Birth whilst adding a mentor, the date of birth does not persist.
- Add a mentor
- Enter a number into one of the three date of birth fields
- Click continue
- See a validation error and your entry has persisted
[Add mentor → preserve partially entered DOB fields](https://trello.com/c/c7hMIOEu/486-add-mentor-%E2%86%92-preserve-partially-entered-dob-fields)
=> Persist date of birth on validation error

app/controllers/placements/organisations_controller.rb, app/controllers/placements/providers/partner_schools_controller.rb, app/controllers/placements/providers/users_controller.rb, app/helpers/placements/routes/organisations_helper.rb, app/views/placements/organisations/index.html.erb, config/routes/placements.rb, spec/helpers/placements/routes/organisations_helper_spec.rb, spec/system/placements/organisations/view_organisations_spec.rb, spec/system/placements/providers/remembering_the_current_provider_spec.rb
Take provider users to the placements search page when they sign in.
https://trello.com/c/URtV1kGv/403-make-find-placements-the-default-page-for-providers
=> Redirect providers to placements

app/views/sessions/new.html.erb
Requested as part of the 'Manage school placements' launch day.
https://trello.com/c/aHTwXv9H/497-start-page-content-for-users-who-have-not-yet-been-onboarded
=> Add content to the sign-in page

spec/system/claims/support/schools/view_a_school_spec.rb
This spec would regularly flake because the school names clashed.
We should not rely on Faker to provide unique values. If tests are dependent on unique values then we should specify the names directly.
Give the schools names so they're always unique.
=> Fix a flaky system spec in Claims

app/views/placements/placements/index.html.erb, config/locales/en/placements/placements.yml, spec/system/placements/placements/searching_for_a_placement_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
Update the content shown when no placements are found.
https://trello.com/c/KOoB10aO/373-10-confirm-content-for-no-placements
| Before | After |
| --- | --- |
| ![Before](https://github.com/DFE-Digital/itt-mentor-services/assets/7735945/194ad441-b9e9-49e3-934a-c30f2c23c9f6) | ![After](https://github.com/DFE-Digital/itt-mentor-services/assets/7735945/5b3581d9-3a90-442f-91c7-efb15a950a6c) |
=> Update "no results" message for placements search

app/views/placements/schools/mentors/new.html.erb, app/views/placements/support/schools/mentors/new.html.erb, config/locales/en/activerecord.yml, config/locales/en/placements/schools/mentors.yml, config/locales/en/placements/support/schools/mentors.yml, spec/models/mentor_spec.rb, spec/services/claims/mentor_builder_spec.rb, spec/services/mentor_builder_spec.rb, spec/spec_helper.rb, spec/system/claims/schools/mentors/add_a_mentor_spec.rb, spec/system/claims/support/schools/mentors/support_user_adds_a_mentor_spec.rb, spec/system/placements/schools/mentors/user_adds_mentor_spec.rb, spec/system/placements/support/schools/mentors/support_user_adds_a_mentor_spec.rb
Content changes:
- Add hint text to the TRN field in the 'add mentor' journey
- Remove content from the 'Help with the TRN' details component – since it now appears as hint text instead
- Clarify the error message shown when the TRN is entered in an invalid format.
I've applied these changes to both the school user and support user 'add mentor' journeys.
In addition to the content changes, I've also configured RSpec with a `example_status_persistence_file_path` so we can now use the `--only-failures` option. This should make it quicker to re-run the test suite with a quick feedback loop when fixing failures from across the app.
Read more about how to use `--only-failures` in the RSpec docs:
https://rspec.info/features/3-13/rspec-core/command-line/only-failures/ …
=> Update TRN guidance and error message

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/placements/organisations_controller.rb, app/controllers/placements/placements_controller.rb, app/controllers/placements/schools/placements/build_controller.rb, app/jobs/trim_expired_sessions_job.rb, app/models/dfe_sign_in_user.rb, app/views/placements/schools/placements/build/add_mentors.html.erb, app/wizards/placements/add_placement/steps/mentors.rb, config/analytics.yml, config/application.rb, config/scheduled_jobs.yml, db/migrate/20240617152221_add_sessions_table.rb, db/schema.rb, spec/jobs/trim_expired_sessions_job_spec.rb, spec/wizards/placements/add_placement/steps/mentors_spec.rb
> [!IMPORTANT]  
> **Care should be taken when deploying this change. To reduce the risk of disrupting live user sessions, it should be deployed out of hours.**
>
> Users will be signed out because their existing sessions will be discarded. However the app is currently low-traffic enough that an out of hours deployment seems like a reasonable mitigation.
Currently we use the cookie session store. This is the default session store which comes out of the box with Rails. The cookie store mostly works fine and is a good default, but there is one major drawback: storage space is limited to ~4 KB.
From experience, it's surprisingly easy to use up that space. Features such as multi-step forms (a.k.a. wizards) will often depend on using the session as temporary storage – and since such forms …
=> Store sessions in the database

config/analytics.yml, config/analytics_blocklist.yml
The database table to hold sessions should have been added to the DfE Analytics blocklist in #781. This is a follow-up commit to add it.
This will stop user sessions being sent in to BigQuery.
=> Add sessions table to the DfE Analytics blocklist

terraform/application/config/staging.tfvars.json
stg postgres is triggering cpu alerts, and looks to be underpowered.
Upgrade db from B_Standard_B1ms to B_Standard_B2s
make staging terraform-plan
```
~ resource "azurerm_postgresql_flexible_server" "main" {
name                          = "s189t01-ittms-stg-pg"
~ sku_name                      = "B_Standard_B1ms" -> "B_Standard_B2s"
```
https://trello.com/c/ZiMrcySC/1882-stg-posgtres-db-cpu-alerts
=> Upgrade stg postgres db to B_Standard_B2s

app/controllers/placements/schools/placements/build_controller.rb, app/views/placements/schools/placements/build/add_phase.html.erb, app/wizards/placements/add_placement/steps/phase.rb, config/locales/en/activemodel.yml, config/locales/en/placements/schools/placements.yml, spec/wizards/placements/add_placement/steps/phase_spec.rb
The wizard is becoming unmanageable and unmaintainable it, we need to begin refactoring the logic to fix these issues before further development is needed.
- Log into a school that is not secondary or primary
- Add a placement
- Confirm the phase selection is visible
- Check that it matches in check your answers
- There should be no discernable changes to the journey
[Decompose the Placements Build model into Wizard Steps](https://trello.com/c/EoYfSgYr/502-decompose-the-placements-build-model-into-wizard-steps)
=> Decompose add phase

config/locales/en/placements/schools/placements.yml, spec/system/placements/schools/placements/add_a_placement_spec.rb
- Change flash message when adding a placements to "Placement published"
- Create a placement
- Check the flash message reads "Placement published"
https://trello.com/c/ti0JnrPh/518-change-the-add-placement-success-flash-message
=> Change add placement flash message

app/views/placements/schools/placements/build/check_your_answers.html.erb, config/locales/en/placements/schools/placements.yml, spec/system/placements/schools/placements/add_a_placement_spec.rb
I'm implementing these changes ahead of an anticipated refactor of the 'Add placement' multi-step form. The changes in this PR reduce the coupling between the spec and the current implementation, making it more compatible with upcoming implementation changes.
See individual commits and their commit messages for details.
There are no visual changes.
This is a preparatory refactor for: https://trello.com/c/FiYvPVpK/516-refactor-add-placement-controller-into-a-wizard
=> Improve readability of "change" links and refactor the "Add placement" spec

config/locales/en/placements/schools/placements.yml
- Update the inset text on the Check your answers page
- Create a new placement, but stop on the Check your answers page
- The inset text should read:
- When a placement is published, it will be visible to teacher training providers. You can edit your placement after it is published.
https://trello.com/c/Gq2hSY8E/519-update-the-inset-text-on-add-placement-%E2%86%92-check-your-answers
=> Update placements check your answers text

app/controllers/application_controller.rb, app/controllers/placements/placements_controller.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb
When using a deep link into the application the user would always been redirected to the root path after sign in, we want to send them to their requested page instead.
- Log in as any user
- Navigate to a page in the application
- Copy the URL
- Log out
- Paste the URL
- Log in
- You should be on the same URL you requested
[After signing in, redirect users back to the page they originally requested](https://trello.com/c/CA5fcgyX/513-after-signing-in-redirect-users-back-to-the-page-they-originally-requested)
=> Redirect users after sign in

app/controllers/application_controller.rb
Addresses comment: https://github.com/DFE-Digital/itt-mentor-services/pull/807/files#r1658957291
As per commit 3f37281c7560bdb031b5baf5db73353dd7c3292a
=> Always use strings for session keys

spec/requests/placements/providers/users_spec.rb, spec/requests/placements/schools/placements/placements_spec.rb, spec/requests/placements/schools/users_spec.rb, spec/requests/placements/support/support_users_spec.rb, spec/requests/placements/support/user_authorisation_spec.rb, spec/support/dfe_sign_in_user_helper.rb
I've updated the `sign_in_as` test helper method so it can be used for both system specs and request specs.
Since they're both operating under different contexts, authentication needs to be mocked differently depending on the type of test.
=> Support request specs in the `sign_in_as` helper

config/initializers/dfe_analytics.rb, terraform/application/application.tf, terraform/application/config/review_app_env.yml
This is part of a wider BigQuery Assurance piece to to harden the security around BigQuery.
It allows the use of OAuth mechanism for authentication to BigQuery rather than relying on plain text JSON API Keys.
Enable Azure workload identity federation within DfE Analytics.
Set GOOGLE_CLOUD_CREDENTIALS secret in the key vault for each environment. 
See [Dfe Analytics GEM](https://github.com/DFE-Digital/dfe-analytics) for further details.
This change involves the following steps
- Set GOOGLE_CLOUD_CREDENTIALS by downloading from GCP. This should be done for each environment.
- Enable WIF in the Azure Infrastructure
- Enable WIF in the App. We can remove references to the the JSON API Key at the same time
- Enable WIF in the Review App and test sending of data to BIgQuery. This can be …
=> Rollout workload identity federation to all envs

app/views/claims/pages/start.en.html.erb, app/views/claims/schools/claims/index.html.erb, app/views/claims/support/schools/claims/index.html.erb, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/support/schools/claims.yml, spec/system/claims/start_page_spec.rb
We want to highlight the closing date of submitting claims as we near the closing date.
- Add closing data disclaimer banner to start page and school's claims pages (Users and Support Users).
- Correct closing date time formatting.
- Banner should only appear on `/`, `/schools/:school_id/claims`, and `/support/schools/:school_id/claims` pages.
=> Add closing date disclaimer banners

app/controllers/claims/support/mailers_controller.rb, app/controllers/claims/support/settings_controller.rb, app/controllers/placements/support/mailers_controller.rb, app/controllers/placements/support/settings_controller.rb, app/views/claims/support/_primary_navigation.html.erb, app/views/claims/support/mailers/index.html.erb, app/views/claims/support/settings/index.html.erb, app/views/placements/support/_primary_navigation.html.erb, app/views/placements/support/mailers/index.html.erb, app/views/placements/support/settings/index.html.erb, config/application.rb, config/locales/en/claims/support/mailers.yml, config/locales/en/claims/support/primary_navigation.yml, config/locales/en/claims/support/settings.yml, config/locales/en/placements/support/mailers.yml, config/locales/en/placements/support/primary_navigation.yml, config/locales/en/placements/support/settings.yml, config/routes/claims.rb, config/routes/placements.rb, spec/mailers/previews/claims/support_user_mailer_preview.rb, spec/mailers/previews/claims/user_mailer_preview.rb, spec/mailers/previews/placements/support_user_mailer_preview.rb, spec/mailers/previews/placements/user_mailer_preview.rb, spec/system/claims/support/view_emails_spec.rb, spec/system/placements/support/view_emails_spec.rb
We want to be able to visualise what emails we have.
- Add a Settings page to Claims support console.
- Add a link to Background Jobs.
- Add a page for listing out emails.
Does @DFE-Digital/school-placements want this too? I can add it in.
I have opted to **NOT** using the default `/rails/mailers` path for listing out the emails, for 2 reasons:
1. I want the experience to align with the look at feel of the rest of the Support console.
2. I want to filter emails by service.
https://trello.com/c/5qfMu8ZG/544-look-into-getting-email-previews-live
| Page | Screenshot |
| ---- | ---------- |
| Settings | ![image](https://github.com/DFE-Digital/itt-mentor-services/assets/4231530/3af31b51-8a9e-47a2-a333-a76936db0a0e) |
| Emails list | ![image](https://github.com/DFE-Digital/itt-mentor-services/as …
=> Add support settings

app/views/claims/pages/start.en.html.erb, app/views/claims/schools/claims/index.html.erb, app/views/claims/support/schools/claims/index.html.erb
We want to stop showing the claims closing date notification banner once the claims window has closed.
We will then have time to manually remove this dead code any time past July 20, 2024.
- Only show the banner before July 20, 2024.
Try changing the `Date.parse("20 July 2024").future?` line to `Date.parse("8 July 2024").future?`. This will return `false` and therefore the banner will show until it becomes the 20th.
=> Hide claims closing date banner when claim window has closed

Gemfile, Gemfile.lock
Good Job jobs are failing due to queued jobs not being ready for v4.
Production returns `false` when `GoodJob.v4_ready?` is called.
```ruby
GoodJob.v4_ready? # => false
```
- Revert commit ca906d6203099137b6e7c6072e3fcdb78d220ce8.
- https://github.com/bensheldon/good_job?tab=readme-ov-file#upgrading-v3-to-v4
=> Revert "Bump good_job from 3.29.3 to 4.0.1"

config/analytics_blocklist.yml, db/migrate/20240711104406_create_good_job_settings.rb, db/migrate/20240711104407_create_index_good_jobs_jobs_on_priority_created_at_when_unfinished.rb, db/migrate/20240711104408_create_good_job_batches.rb, db/migrate/20240711104409_create_good_job_executions.rb, db/migrate/20240711104410_create_good_jobs_error_event.rb, db/migrate/20240711104411_recreate_good_job_cron_indexes_with_conditional.rb, db/migrate/20240711104412_create_good_job_labels.rb, db/migrate/20240711104413_create_good_job_labels_index.rb, db/migrate/20240711104414_remove_good_job_active_id_index.rb, db/migrate/20240711104415_create_index_good_job_jobs_for_candidate_lookup.rb, db/migrate/20240711104416_create_good_job_execution_error_backtrace.rb, db/migrate/20240711104417_create_good_job_process_lock_ids.rb, db/migrate/20240711104418_create_good_job_process_lock_indexes.rb, db/migrate/20240711104419_create_good_job_execution_duration.rb, db/schema.rb
We need to perform some database migrations to prepare for the upgrade from Good Job v3 to v4. This will allow us to re-apply the upgrade in #828, which was reverted by #838.
> [!NOTE]  
> **This PR does not upgrade Good Job to v4.** It prepares the database for v4, but these changes are still compatible with v3.99.1 which is currently in use.
I've followed the instructions in [the upgrade guide][1]. The database migrations were automatically generated by the gem.
I've also updated the DfE Analytics blocklist to exclude the newly added fields.
Run the migrations in this pull request, then open a Rails console and run:
```
GoodJob.v4_ready?
```
It should return `true`.
https://trello.com/c/vneRTcpO/554-review-and-merge-dependabot-prs
[1]: …
=> Prepare the database for Good Job v4

config/initializers/good_job.rb
I've configured Good Job to clean up old jobs ~~3 days~~ 4 days after they've executed.
By default, Good Job preserves jobs for 14 days. However since we use Active Job so heavily (thanks to the DfE Analytics gem), it seems sensible to drop this to avoid unnecessarily filling up the database.
I figured ~~3 days~~ 4 days is a sensible amount of time to keep jobs around for. That way, we can still investigate or debug jobs for a few days (including on Mondays after the weekend) before they drop off the radar.
=> Clean up old jobs after 4 days

app/controllers/placements/providers_controller.rb, app/controllers/placements/schools_controller.rb, spec/system/placements/providers/view_provider_details_spec.rb
- Add tests for Provider -> Organisation details
- Add tests for Provider -> Organisation details
- Remove unnecessary safe navigation
https://trello.com/c/3csGsS2l/544-add-test-coverage-for-the-organisation-details-pages-for-schools-and-providers
=> Add test coverage for provider organisation details

app/services/mentor_builder.rb, spec/support/shared_examples/mentor_builder.rb, spec/system/placements/schools/mentors/user_adds_mentor_spec.rb
- Fix issue when users don't include a Date of Birth when finding a Mentor.
- Return `mentor` when `date_of_birth` is not a `Date`. Preventing call to TeachingRecord API
- Navigate to "Mentors" using the NavBar
- Click "Add mentor"
- Input a TRN (e.g 1234567)
- DO NOT input a Date of birth
- Page should show "Enter a date of birth" error. (The page itself should not error)
https://trello.com/c/qy0lfp2s/551-fix-error-when-submitting-the-mentor-form-with-an-empty-dob
=> Fix issue when no DOB included in mentor search

adr/00009-wizards.md, docs/conventions.md, docs/conventions/wizards.md
We've adopted a wizard pattern for building multi-step forms in the School Placements service.
This adds documentation of how we build them, and an ADR to document how we ended up establishing this pattern.
Adds the following documents:
- [adr/00009-wizards.md](https://github.com/DFE-Digital/itt-mentor-services/blob/wizard-documentation/adr/00009-wizards.md) ✨
- [docs/conventions/wizards.md](https://github.com/DFE-Digital/itt-mentor-services/blob/wizard-documentation/docs/conventions/wizards.md) ✨
https://trello.com/c/ZfCxhaLn/541-document-our-use-of-the-wizard-pattern
=> Add documentation for building wizards

app/views/placements/wizards/add_placement_wizard/_mentors_step.html.erb
- Fix broken error link on Add placement -> Mentor step
- When using a `govuk_check_boxes_fieldset` the first `govuk_check_box` must have attribute `link_errors: true`
https://www.rubydoc.info/gems/govuk_design_system_formbuilder/GOVUKDesignSystemFormBuilder/Builder#govuk_check_boxes_fieldset-instance_method
- Follow the process of adding a Placement
- When you reach the mentor step, DO NOT SELECT A MENTOR OR 'Not yet know'
- When the error message appears at the top of the page, click this link.
- This should focus you on the checkboxes for selecting a mentor.
https://trello.com/c/xAVoTsgb/545-fix-broken-link-in-error-summary-on-the-add-placement-%E2%86%92-mentors-step-page
https://github.com/user-attachments/assets/02f92104-6677-4890-a135-fe9efc308cf2
=> Fix error link in add placement mentor step

spec/mailers/previews/placements/user_mailer_preview.rb
- Add Partnership Creation Notification preview
- Add Partnership Destroyed Notification preview
- Navigate to "Settings" in Navbar
- You should see:
- partnership_created_notification (opens in new tab)
- partnership_destroyed_notification (opens in new tab)
- Click each of the above to preview each email.
https://trello.com/c/1TykvLa6/562-add-email-previews-for-partnership-notifications
=> Add preview emails for partnerships

app/views/claims/support/mailers/index.html.erb, app/views/placements/support/mailers/index.html.erb
Back links were missing from the mailer pages.
- Add back links to the mailer pages.
- Mailer page back links should be correct.
=> Add back links to support settings mailer pages

app/services/gias/csv_importer.rb, db/data/20240719081853_update_rest_of_england_hourly_rate.rb, db/data_schema.rb
The hourly rate for funding in the "Rest of England" region is incorrect. It's been set to **£43.18** when it should actually be **£43.80**.
This was raised in the Slack thread: https://ukgovernmentdfe.slack.com/archives/C0657JE64HX/p1721373699390679
This PR does two things:
1. Updates the funding rate that has been hardcoded in the GIAS CSV importer.
2. Adds a data migration to update the rate on the existing Region record.
I've had to add a data migration because the hardcoded value in the GIAS CSV importer is only used once, the first time the Region records are created.
Once deployed, the data migration [will run automatically](https://github.com/DFE-Digital/itt-mentor-services/blob/0d91ade75204aa41ebc3e9fc0f2c52bac6393f0f/Dockerfile#L79) and update the hourly rate for the "Rest of …
=> Fix an incorrect hourly rate in the Funding Mentors service

app/slack_notifiers/placements/placement_slack_notifier.rb
The Slack notifier links are incorrect and do not redirect us to the placement when opening the link.
- Trigger a slack notification via the console
- Check that the link opens the placement when logged in as Colin
[Fix broken link in Slack notifications for new placements](https://trello.com/c/0WgwLppQ/575-fix-broken-link-in-slack-notifications-for-new-placements)
=> Update incorrect url path for new placement slack notification

app/views/claims/pages/start.en.html.erb, app/views/claims/schools/claims/index.html.erb, app/views/claims/support/schools/claims/index.html.erb, spec/system/claims/start_page_spec.rb
The window has now closed. We want to remove the notification banner and update the start page content slightly.
- Remove notification banners about window closing dates.
- Update start page content.
=> Update claims start page

app/controllers/claims/schools/claims_controller.rb, app/controllers/claims/support/schools/claims_controller.rb, app/forms/claims/claim/provider_form.rb, app/models/claims/claim.rb, app/policies/claims/claim_policy.rb, db/data/20240722123910_add_claim_window_to_claims.rb, db/data_schema.rb, spec/factories/academic_years.rb, spec/factories/claims.rb, spec/factories/claims/claim_windows.rb, spec/forms/claims/claim/provider_form_spec.rb, spec/forms/claims/support/claim/provider_form_spec.rb, spec/models/claims/claim_spec.rb
Now that we have a `claim_window` association on the `Claim` model, we can start associating the claim windows when a claim is created.
- Back-populate claim windows onto all existing claims.
- When a claim is being created, assign the current claim window to the claim being created.
- Locally, try creating a Claim. It will associate the "current" claim window to the claim.
=> Populate claim windows on claims

spec/models/claims/claim_window_spec.rb
The `ClaimWindow` unit test specs started to fail. This is due to the dates being hard-coded around the time of development. A `freeze` metadata _should_ have been there, but it was forgotten 🤦‍♂️ 
- Add `freeze` metadata into time-based ClaimWindow unit tests
- Tweak some dates for consistency.
=> Fix ClaimWindow unit specs

app/views/placements/wizards/add_partnership_wizard/_check_your_answers_step.html.erb, spec/system/placements/providers/partner_schools/add_a_partner_school_spec.rb, spec/system/placements/schools/partner_providers/add_a_partner_provider_spec.rb
- Fix issue with incorrect step used in change link in partnerships
- Follow the process to create a partner provider UNTIL the check your answers page
- Click "Change"
- You should be redirected back to the Provider selection page.
https://github.com/user-attachments/assets/3df5f9b7-accd-4abb-ae9d-4f639a11cbbc
=> Fix change link on partnership check your answers

db/seeds.rb
- Added academic years to seed file.
- Added claims windows to seed file.
seeds.rb added academic years and added claims windows.
- Run in terminal "bundle exec rake db:drop db:create db:setup".
- You should see an academic year record for previous, current, and next academic year.
- You should see two claims windows for the current academic year.
https://trello.com/c/mS6wI3Ib/239-add-academic-years-and-claim-windows-to-seeds-file
=> Add academic years and claims windows to seed file

.github/workflows/build_and_deploy.yml, .github/workflows/deploy.yml, Dockerfile, terraform/application/application.tf
We've been experiencing issues with review apps due to the way database migrations are run by the deployment pipeline.
Migrations currently run inline within the web app container. The web app is started with the command `rails db:migrate && rails server`, which is a straightforward but slightly hacky way to run migrations before starting the server. It works on the assumption that your web app is the only service which depends on the database schema being up to date.
However in our case, we have a separate service called [Good Job](https://github.com/bensheldon/good_job) which runs alongside the web app to process background jobs. This service also has a dependency on the same Postgres database that our web app uses. Therefore it's important that our deployment pipeline runs migrations …
=> Add a migration step to the deployment

app/controllers/placements/schools/placements_controller.rb, app/controllers/placements/support/schools/placements_controller.rb, app/views/placements/support/schools/placements/can_not_remove.html.erb, app/views/placements/support/schools/placements/confirm_remove.html.erb, app/views/placements/support/schools/placements/show.html.erb, config/locales/en/placements/support/schools/placements.yml, spec/system/placements/support/schools/placements/support_user_deletes_a_placement_spec.rb
- Align support's placement functionality with what currently exists for school users
- Prevent support users from deleting placements if they are assigned to a provider.
- Select a school with placements
- Click on a placement
- (Assign a provider to the placement if one is not assigned)
- Click "Delete placement"
- You should see a page with text explaining why you can not delete this placement
https://trello.com/c/7ZEGQQ4a/648-prevent-support-from-deleting-assigned-placements
https://github.com/user-attachments/assets/0708d6ba-dd87-4b07-895b-571d20c8d7ed
=> Prevent support from deleting assigned placements

app/controllers/placements/schools/placements_controller.rb, app/views/placements/placements/_placement_details.html.erb, app/views/placements/placements/show.html.erb, app/views/placements/schools/placements/preview.html.erb, app/views/placements/schools/placements/show.html.erb, app/views/placements/wizards/add_placement_wizard/_check_your_answers_step.html.erb, app/views/placements/wizards/add_placement_wizard/_preview_placement_step.html.erb, app/wizards/placements/add_placement_wizard.rb, app/wizards/placements/add_placement_wizard/preview_placement_step.rb, config/locales/en/placements/placements.yml, config/locales/en/placements/schools/placements.yml, config/locales/en/placements/wizards/add_placement_wizard.yml, config/routes/placements.rb, spec/support/shared_examples/system/placements/add_a_placement_wizard.rb, spec/system/placements/schools/placements/view_a_placement_spec.rb, spec/wizards/placements/add_placement_wizard/preview_placement_step_spec.rb, spec/wizards/placements/add_placement_wizard_spec.rb
School users wish to be able to see how providers can view their placements
- Refactors the provider placement details to use a partial
- Adds a new endpoint for previewing existing placements
- Adds a new preview placement step in the add placement journey
- View an existing placement
- Click on "preview this placement"
- Create a new placement
- On the check your answers page, click on "preview placement"
[Implement placement preview functionality](https://trello.com/c/FzZvWF1J/617-implement-placement-preview-functionality)
=> Placement preview

app/controllers/placements/providers/partner_schools/placements_controller.rb, app/views/placements/providers/partner_schools/_sub_navigation.html.erb, app/views/placements/providers/partner_schools/placements/index.html.erb, app/views/placements/providers/partner_schools/placements/show.html.erb, app/views/placements/providers/partner_schools/show.html.erb, app/views/placements/wizards/add_placement_wizard/_check_your_answers_step.html.erb, config/locales/en/placements/providers/partner_schools.yml, config/locales/en/placements/schools/placements.yml, config/routes/placements.rb, spec/system/placements/providers/partner_schools/placements/view_a_placement_for_partner_school_spec.rb, spec/system/placements/providers/partner_schools/placements/view_placements_for_partner_school_spec.rb
Adds a placements index and show page when viewing a partner school as provider
- Navigate to partner schools
- Click on placements in the new sub nav
- Click on a placement
[Add a 'Placements' section to partner schools](https://trello.com/c/MqulMHHA/618-add-a-placements-section-to-partner-schools)
=> Partner placements

config/routes.rb, config/routes/placements.rb
- Remove unused routes.
- Based on running `bin/rails routes --unused` the following placements routes need to be removed:
```
Prefix Verb  URI Pattern                                            Controller#Action
api_placements_school_suggestions GET   /api/placements/school_suggestions(.:format)           api/placements/school_suggestions#index
api_placements_provider_suggestions GET   /api/placements/provider_suggestions(.:format)         api/placements/provider_suggestions#index
check_placements_support_school_placements GET   /support/schools/:school_id/placements/check(.:format) placements/support/schools/placements#check
```
https://trello.com/c/CBtCmcHU/656-remove-unused-placements-routes
=> Remove unused routes

app/models/academic_year.rb, app/services/claims/claim_window/build.rb, db/seeds.rb, spec/models/academic_year_spec.rb
- .for_date method added to academic year model to take an arbitrary date and find or generate a year with appropriate start and end dates. 
- Centralises the logic for academic year name, starts_on, and ends_on.
- Addition of .for_date method to academic year model. 
- Refactor of seeds.rb and claim/claim_window/build.rb to replace hardcoded dates.
- Review AcademicYear model.
- Review refactor of code in seeds.rb and claim_window/build.rb.
- Run `bundle exec rspec spec/models/academic_year_spec.rb`.
https://trello.com/c/qLLh08g6/635-refactor-the-academic-year-model-to-consolidate-hardcoded-magic-dates
=> Refactor academic year model to consolidate hardcoded magic dates

app/services/claims/provider/generate_csv.rb, spec/services/claims/generate_claims_csv_spec.rb, spec/services/claims/provider/generate_csv_spec.rb
- Create a Claims::Provider::GenerateCSV service for creating a CSV suitable for providers.
run in rails console:
⚠️ Generate some claims before running this ⚠️ 
```ruby
provider = Claims::Claim.last.provider
academic_year = AcademicYear.first # (or which ever academic year relates to your claims `AcademicYear.find(...)`)
Claims::Provider::GenerateCsv.call(provider: provider, academic_year: academic_year)
```
This will return a CSV containing all claims, totalled for each mentor/school.
https://trello.com/c/Wo014mtB/587-csv-extract-with-individual-mentor-claims
=> Create Claims CSV generator for providers

spec/lib/google/routes_api_spec.rb
The WebMock stubs for calls to the Google Routes API expected that the environment variable `GOOGLE_MAPS_API_KEY` was not set.
However it's entirely possible for this environment variable to be set on a developer's machine. And the test suite should still pass whether it's set or not.
Effectively ignore the value of the environment variable, by including it in both the implementation and the test stub. The test should now pass regardless of the variable's value or presence.
Do the tests still pass?
=> Fix test failures when GOOGLE_MAPS_API_KEY is set

spec/rails_helper.rb
- Prevent ClaimsWindows being created before smoke tests.
=> Prevent claims windows being created before smoke tests

app/views/placements/schools/placements/add_placement/edit.html.erb, app/views/placements/wizards/add_placement_wizard/_additional_subjects_step.html.erb, app/views/placements/wizards/add_placement_wizard/_mentors_step.html.erb, app/views/placements/wizards/add_placement_wizard/_phase_step.html.erb, app/views/placements/wizards/add_placement_wizard/_subject_step.html.erb, app/views/placements/wizards/add_placement_wizard/_year_group_step.html.erb, app/views/placements/wizards/edit_placement_wizard/_provider_step.html.erb, app/wizards/placements/add_placement_wizard/additional_subjects_step.rb, config/locales/en/placements/schools/placements.yml, config/locales/en/placements/support/schools/placements.yml, config/locales/en/placements/wizards/add_placement_wizard.yml, config/locales/en/placements/wizards/edit_placement_wizard.yml, spec/support/shared_examples/system/placements/add_a_placement_wizard.rb, spec/support/shared_examples/system/placements/edit_a_placement_wizard.rb
- Content changes to the Add/Edit placement flow.
- H1, caption and hint text changes in accordance with [Lucid](https://lucid.app/lucidspark/262e5d35-0c1f-4f90-aa60-c3b00a9a53ef/edit?invitationId=inv_fe53fead-7afb-41fa-b89f-6c57958d9867&page=0_0#)
- Follow the process to add a placement. (Ensure all H1, captions and hint text appear as shown in Lucid examples)
- Follow the process to edit a placement (Change Mentor, Year Group and Provider). (Ensure all H1, captions and hint text appear as shown in Lucid examples)
------------
- Follow the process to add a placement. (Ensure all H1, captions and hint text appear as shown in Lucid examples)
- Follow the process to edit a placement (Change Mentor, Year Group and Provider). …
=> Change captions and H1 content to questions on add placement flow

app/views/claims/schools/claims/_form.html.erb, app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/mentor_trainings/edit.html.erb
My IDE kindly informed me that we had some unclosed HTML tags.
- Close a few divs that were unclosed.
- Add a claim, there should be no discernable changes.
[Close divs](https://trello.com/c/TW1WvVMG/684-close-divs)
=> Close div tags

app/forms/mentor_form.rb, spec/support/shared_examples/mentor_form.rb
During UR, we witnessed a user using Speech-to-Text software. During the session, the user entered a TRN using their voice. The inputted text contained a "space" mid-way through the 7 digits.
To avoid this issue moving forward, we've decided to strip out all whitespaces.
- Normalise `#trn` attribute reader of the `MentorForm`, this ensures no whitespace is present when accessing the attribute.
- Try to add a Mentor with the following TRN/DoB:
- TRN: " 12 34 56 8"
- DoB: 12/11/1986
=> Remove whitespaces from TRN input field

app/controllers/placements/providers/partner_schools_controller.rb, app/views/placements/providers/partner_schools/remove.html.erb, app/views/placements/providers/partner_schools/show.html.erb, config/locales/en/placements/providers/partner_schools.yml, config/locales/en/placements/support/providers/partner_schools.yml, spec/system/placements/providers/partner_schools/remove_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_remove_a_partner_school_spec.rb
- Same design context as [#927](https://github.com/DFE-Digital/itt-mentor-services/pull/927).
**Partner school show page:**
- Update “Remove partner school” to “Delete partner school”
**Remove partner school confirmation page:**
- Update “Are you sure you want to remove this partner school?” to “Are you sure you want to delete this partner school?”
- Add paragraph text above the warning component:“The school will no longer be able to assign you to their placements.You can still view placements at this school.”
- Update the warning component text “removed” to “deleted”
- Update button text from “Remove partner school” to “Delete partner school”
**Destroy action in partner school controller**
- Updated success messaged to reflect removed -> deleted.
Sign in as Patricia (Provider User)
Click …
=> Content Changes to Provider User Journey - Remove Partner School (Remove -> Delete)

app/views/placements/support/schools/mentors/add_mentor/edit.html.erb, app/views/placements/wizards/add_mentor_wizard/_mentor_step.html.erb, app/views/placements/wizards/add_mentor_wizard/_no_results_step.html.erb, config/locales/en/placements/support/schools/mentors.yml, config/locales/en/placements/wizards/add_mentor_wizard.yml, spec/support/shared_examples/system/placements/add_a_placement_wizard.rb, spec/system/placements/schools/mentors/user_adds_mentor_spec.rb, spec/system/placements/support/schools/mentors/support_user_adds_a_mentor_spec.rb
Pages should give directions so that screen readers can be more helpful for their users.
- Updated Add mentor caption and page title
- Updated No mentor found caption and page title
Schools
- Add a mentor
- Veify page title and caption have changed
- Enter 1234565, 11, 1, 1111
- Verify the no results found page title and caption have changed
Support
- Add a mentor
- Veify page title and caption have changed
- Enter 1234565, 11, 1, 1111
- Verify the no results found page title and caption have changed
[Change captions and H1 questions in a form flow (Add mentor)
](https://trello.com/c/bXvkSRLt/679-change-captions-and-h1-questions-in-a-form-flow-add-mentor)
=> Update mentor captions for support and schools

app/views/placements/schools/placements/confirm_remove.html.erb, config/locales/en/placements/schools/placements.yml
- Same design context as [#927](https://github.com/DFE-Digital/itt-mentor-services/pull/927)
**"Remove placement" confirmation page**
- Add paragraph text above the warning component: “It is your responsibility to make sure that anyone relevant to organising this placement is aware it is being deleted.”
**"Cannot remove" placement page:**
- Update paragraph text to: “%{provider_name} must be removed from the placement before you can delete it.
- Review school user journey to delete a placement with a provider.
- Review school user journey to delete a placement without a provider.
- Run `bundle exec rspec spec/system/placements/schools/placements`
https://trello.com/c/Idp76WWF/665-improve-school-user-placement-journey-content
=> confirm remove and cannot remove paragraphs updated

app/decorators/school_decorator.rb, app/views/placements/providers/partner_schools/_delete.html.erb, app/views/placements/providers/partner_schools/remove.html.erb, app/views/placements/support/providers/partner_schools/remove.html.erb, app/views/placements/support/providers/partner_schools/show.html.erb, config/locales/en/placements/providers/partner_schools.yml, config/locales/en/placements/support/providers/partner_schools.yml, spec/system/placements/providers/partner_schools/remove_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_deletes_a_partner_school_spec.rb
- Content changes for Support User view of the Remove/Delete Partner school journey.
- Move content of `remove` page to a partial for use with both support user and school user.
- Click on a Provider (with Partner Schools)
- Click on "Partner schools" in the Navbar
- Click on the partner school you wish to remove
- Click "Delete partner school"
- You should see the content changes linked to [Lucid](https://lucid.app/lucidspark/262e5d35-0c1f-4f90-aa60-c3b00a9a53ef/edit?referringApp=slack&shared=true&page=0_0#)
Click "Delete partner school"
You should see the flash message "Partner school deleted"
https://trello.com/c/mPbpQoxa/694-support-console-improve-provider-user-partner-school-journey-content …
=> Content changes for Support User delete partner school

app/controllers/placements/schools/mentors_controller.rb, app/decorators/mentor_decorator.rb, app/helpers/placements/routes/placements_helper.rb, app/views/placements/schools/mentors/confirm_remove.html.erb, app/views/placements/schools/mentors/show.html.erb, app/views/placements/support/schools/mentors/confirm_remove.html.erb, app/views/shared/schools/mentors/_can_not_remove.html.erb, config/locales/en/placements/schools/mentors.yml, config/locales/en/placements/support/schools/mentors.yml, config/locales/en/shared/schools/mentors.yml, spec/decorators/mentor_decorator_spec.rb, spec/helpers/placements/routes/placements_helper_spec.rb, spec/system/placements/schools/mentors/remove_a_mentor_spec.rb, spec/system/placements/support/schools/mentors/support_user_removes_a_mentor_spec.rb
Inconsistent terminology causes confusion for users - if different words have the same action it adds cognitive load.
**Mentor show page:**
- Update “Remove mentor” to “Delete mentor”
**"Remove mentor" confirmation page:**
- Update “Are you sure you wish to remove this mentor?” to “Are you sure you want to delete this mentor?”
- Add paragraph: “You will no longer be able to assign %{mentor_name} to placements.”
- Update button text from “Remove mentor” to “Delete mentor”
**"You cannot remove this mentor" page:**
- Update “You can not remove this mentor” to “You cannot delete this mentor”
- Replace paragraph text with :“%{mentor_name} must be removed from current placements before you can delete them.They are currently assigned to: ” followed by a bulleted list of their currently assigned …
=> 'Remove mentor' changed to 'delete mentor' in school user journey

app/controllers/placements/schools/partner_providers_controller.rb, app/decorators/provider_decorator.rb, app/views/placements/schools/partner_providers/remove.html.erb, app/views/placements/schools/partner_providers/show.html.erb, config/locales/en/placements/schools/partner_providers.yml, config/locales/en/placements/support/schools/partner_providers.yml, spec/decorators/provider_decorator_spec.rb, spec/system/placements/schools/partner_providers/remove_a_partner_provider_spec.rb, spec/system/placements/support/schools/partner_providers/support_user_removes_a_partner_provider_spec.rb
Inconsistent terminology causes confusion for users - if different words have the same action it adds cognitive load.
**Partner provider show page**
- Update “Remove partner provider” to “Delete partner provider”
**"Remove partner" provider confirmation page:**
- Update “Are you sure you want to remove this partner provider?” to “Are you sure you no longer want %{provider_name} as one of your partner providers?”
- Add paragraph text above the warning component: “You will no longer be able to assign this provider to placements. They will remain assigned to current placements unless you remove them. "Placements with this provider are:"  followed by a bulleted list of their currently assigned placements which are hyperlinked to the placements and open in a new tab when clicked.
- Update the …
=> School user delete partner provider journey made more consistent (remove -> delete)

app/controllers/placements/organisations/users_controller.rb, app/views/placements/providers/users/remove.html.erb, app/views/placements/providers/users/show.html.erb, app/views/placements/schools/users/remove.html.erb, app/views/placements/schools/users/show.html.erb, config/locales/en/placements/providers/users.yml, config/locales/en/placements/schools/users.yml, config/locales/en/placements/support/providers/users.yml, config/locales/en/placements/support/schools/users.yml, spec/requests/placements/providers/users_spec.rb, spec/requests/placements/schools/users_spec.rb, spec/system/placements/organisations/users/user_removes_other_users_from_organisation_spec.rb, spec/system/placements/organisations/users/user_views_other_users_spec.rb, spec/system/placements/support/users/support_user_removes_a_user_spec.rb
- Same design context as [#927.](https://github.com/DFE-Digital/itt-mentor-services/pull/927)
- This PR encompasses two trello tickets as they share some tests.
**User show page:**
- Update “Remove user” to “Delete user”
**Remove user confirmation page:**
- Update “Are you sure you want to remove this user?” to “Are you sure you want to delete this user?”
- Add paragraph text above the warning component:“%{user_name} will no longer be able to view, create or manage placements at your school.”
- Update the warning component text from “removed” to “deleted”.
- Update the button text from “Remove user” to “Delete user”
**User show page:**
- Update “Remove user” to “Delete user”
**"Remove user" confirmation page:**
- Update “Are you sure you want to remove this user?” to “Are you sure you …
=> School and Provider user journey for deleting another user made more consistent (remove -> delete)

Gemfile, Gemfile.lock
=> Revert data_migrate down to 9.4.2 as 9.4.4 has been yanked

app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_inline_code.scss, app/assets/stylesheets/components/_tag.scss, app/controllers/claims/support/databases_controller.rb, app/services/claims/reset_database.rb, app/views/claims/support/databases/reset.en.html.erb, app/views/claims/support/settings/index.html.erb, config/locales/en/claims/support/databases.yml, config/locales/en/claims/support/settings.yml, config/routes/claims.rb, spec/services/claims/reset_database_spec.rb, spec/system/claims/support/reset_database_spec.rb
We regularly need to reset the claims database to perform UR and testing.
- Add a settings page that appears only in non-production environments to reset the Claims database.
- Create a claim
- Sign out and in as Colin (Support User)
- Navigate to the Settings page
- Click on "Reset Database"
- Confirm
- All claims should now have been deleted
=> Add settings page to reset claims data

.github/workflows/database-backup.yml, .github/workflows/postgres-ptr.yml, .github/workflows/postgres-restore.yml
Create and/or update workflows so we can use workflows for DR and DR testing
- update the database-workflow to use the backup-postgres github action
- add postgres-ptr workflow that uses the ptr-postgres github action
- add postgres-restore workflow that uses the restore-postgres-backup github action
Enable above workflows to run on demand and add the staging env as an option for the DR test
staging backup: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10487024842/job/29046518464 
https://trello.com/c/Yy7qyj4N/1985-ittms-create-dr-test-github-workflows
=> add github workflows for DR test

.github/workflows/database-backup.yml
For the postgres database backup workflow, add 'ptr' to the backup if we are backing up a PTR DB server
Update to database-backup github workflow
Run using branch
ptr - https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10506137213 
non-ptr - https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10506185399
=> Change postgres backup filename if ptr

.github/workflows/build_and_deploy.yml
Temporarily remove the QA env from the cicd automated build and deploy workflow,
so that accessibility testing can be performed and normal work can still continue.
Remove qa from non-prod matrix in the build-and-deploy workflow
check code
=> Remove qa from cicd for accessibility testing

app/models/placement.rb, app/models/placements/academic_year.rb, app/wizards/placements/add_placement_wizard.rb, db/migrate/20240822150107_change_academic_year_for_placements.rb, db/migrate/20240822150354_validate_change_academic_year_for_placements.rb, db/migrate/20240822150528_add_academic_year_foreign_key_to_placements.rb, db/migrate/20240822150613_validate_add_academic_year_foreign_key_to_placements.rb, db/schema.rb, spec/factories/academic_years.rb, spec/factories/placements.rb, spec/models/placement_spec.rb, spec/models/placements/academic_year_spec.rb
Placements now have a concept of their academic year, this work allows us to reference that data from the placements model.
- Add the `belongs_to` association to the `Placement` for `Placements::AcademicYear`
- Adds the `has_many` association to the `Placements::AcademicYear` for `Placement`
- Converts the `null: true` to `null: false` for the `academic_year_id` column
- Adds the foreign key for the `academic_year_id` column
- Populates all new placements via the placements wizard with the current academic year
- Smoke test the app, there are no user facing changes.
[Associate Placement to Placements::AcademicYear](https://trello.com/c/avhLfMpn/704-associate-placement-to-placementsacademicyear)
=> [Part 2] associate placements to placements academic year

app/wizards/placements/add_placement_wizard/terms_step.rb, spec/support/shared_examples/system/placements/add_a_placement_wizard.rb, spec/wizards/placements/add_placement_wizard/terms_step_spec.rb
- When a user selects all the terms during the add placement journey, this should convert to "Any time in the academic year"
- Add a clause in the `normalised_term_ids` method, to convert the value to "Any time in the academic year" when all terms are selected.
- Navigate to "Placements" using the Navbar
- Click "Add placement"
- Follow the add placement journey
- When you reach the "Select when the placement could be" step, select all the terms and continue the add placement journey
On the check your answers page, you will see the terms have been converted to "Any time in the academic year"
https://trello.com/c/YDmoo8mY/709-add-placement-wizard-if-all-three-expected-date-checkboxes-are-selected-convert-to-any-time …
=> Convert selecting all three terms on add placement journey

app/models/placements/term.rb, app/views/placements/wizards/add_placement_wizard/_check_your_answers_step.html.erb, app/views/placements/wizards/add_placement_wizard/_terms_step.erb, app/wizards/placements/add_placement_wizard.rb, app/wizards/placements/add_placement_wizard/terms_step.rb, config/locales/en/activemodel.yml, config/locales/en/placements/schools/placements.yml, config/locales/en/placements/wizards/add_placement_wizard.yml, spec/models/placements/term_spec.rb, spec/requests/placements/schools/placements/add_placement_spec.rb, spec/requests/placements/support/schools/placements/add_placement_spec.rb, spec/support/shared_examples/system/placements/add_a_placement_wizard.rb, spec/wizards/placements/add_placement_wizard/terms_step_spec.rb, spec/wizards/placements/add_placement_wizard_spec.rb
- Add a `TermsStep` to the `AddPlacementWizard`, so users can select the terms in which the placement could take place.
- Add `TermsStep` to the `AddPlacementWizard`
- Navigate to "Placements" using the Navbar
- Click "Add placement"
- Follow the add placement journey
- Before selecting a mentor, you should now see a page to select the terms
- Select a term and continue the add placement journey
- On the check your answers page, you will see the term/s you have selected 
https://trello.com/c/k8Fqqp62/708-add-placement-wizard-add-expected-date-step
=> Add term selection step to placements wizard

app/views/claims/pages/start.en.html.erb, spec/system/claims/start_page_spec.rb
The Claims start page content is now outdated. We want to update it to reflect the correct content based on the current dates.
- Update start page content.
- Content makes sense.
=> Update Claims start page content

.github/workflows/build_and_deploy.yml
Reverts DFE-Digital/itt-mentor-services#954
Deployments to the QA environment were temporarily disabled while an accessibility assessment was being carried out.
That assessment has now concluded, so we can re-enable deployments to the QA environment.
=> Re-enable deployments to the QA environment

terraform/application/application.tf
This was added in v9.4.2 of the `data_migrate` gem.
This should, in theory, be more effective when running migrations against existing environments. It's especially useful to use the `with_data` migration commands because it'll run schema changes and data changes sequentially in chronological order.
Run data migrations in-line with schema migrations.
=> Use `db:prepare:with_data` for database migrations

app/components/placement/summary_component.html.erb, spec/components/placement/summary_component_spec.rb
- Remove fields user research has deemed unnecessary by providers.
- Remove the gender field from placements/placements/index
- Remove the religious character field from placements/placements/index
- Remove the urban or rural field from placements/placements/index
- Gender, Religious character and Urban or rural should not appear in Placement details on the index page.
https://trello.com/c/aB1HgED5/715-provider-remove-religious-character-gender-and-urban-or-rural-fields-from-placements-index
=> Remove unnecessary fields from provider placements index view

app/controllers/placements/placements_controller.rb, app/decorators/academic_year_decorator.rb, app/forms/placements/placements/filter_form.rb, app/queries/placements/placements_query.rb, app/views/placements/placements/_filter.html.erb, app/views/placements/wizards/add_placement_wizard/_check_your_answers_step.html.erb, app/wizards/placements/add_placement_wizard/academic_year_step.rb, config/locales/en/placements/placements.yml, config/locales/en/placements/wizards/add_placement_wizard.yml, spec/decorators/academic_year_decorator_spec.rb, spec/factories/placements.rb, spec/forms/placements/placements/filter_form_spec.rb, spec/models/academic_year_spec.rb, spec/models/placements/academic_year_spec.rb
Now that placements have academic years, providers need the ability to filter by their desired academic year when choosing suitable placements
- Navigate to the placements index page
- Select "Next academic year (2024 to 2025)"
- Click on "Apply Filters"
- Verify that no placements are visible
- Log out
- Create a placement for the "Next academic year (2024 to 2025)"
- Log out
- Navigate to the placements index page
- Select "Next academic year (2024 to 2025)"
- Click on "Apply Filters"
- Verify that one placement is visible
[[Provider] Add academic year filter to placements index](https://trello.com/c/uI3kIWrK/712-provider-add-academic-year-filter-to-placements-index)
=> Add academic year filter to placements index

app/decorators/placement_decorator.rb, app/views/placements/schools/placements/_table.html.erb, app/views/placements/schools/placements/index.html.erb, config/locales/en/placements/schools/placements.yml, spec/decorators/placement_decorator_spec.rb, spec/system/placements/schools/placements/view_placements_list_spec.rb, spec/system/placements/support/schools/placements/support_user_views_placements_spec.rb
School users need to be able to see the expected date for their created placements.
- View placements
- Verify the changes are correct
[[School] Update placements index with academic year and placement date](https://trello.com/c/6pgdwKt3/706-school-update-placements-index-with-academic-year-and-placement-date)
=> Update placements index placement window

app/decorators/placement_decorator.rb, app/views/placements/schools/placements/_details.html.erb, config/locales/en/placements/schools/placements.yml, spec/system/placements/schools/placements/view_a_placement_spec.rb
In line with UI design changes, academic year and expected dates offer the school user the ability to provide more period-specific information about the placements they are listing.
- Add the 'Academic year' field to the placement show page
- Add the 'Expected date' field to the placement show page
- Add the change link to the edit placement wizard for the expected date field
- Log in as a Anne
- Click 'Add a placement'
- Create a placement, including selecting a term on the term step
- Return to the index 
- Click into the newly created placement
- Check that the relevant academic year shows
- Check the show page includes the name of the chosen term
- Repeat this but choose all three terms
- Check the show page includes 'Any time in the academic year'
- Repeat this but choose 'Any time …
=> UI changes to placements show page

app/components/placement/summary_component.html.erb, config/locales/en/components/placement/summary_component.yml, config/locales/en/placements/schools/placements.yml, spec/components/placement/summary_component_spec.rb
Providers need to see the academic year and expected date in the search results summary to assist them in finding the right placements.
- Add the academic year field to the placements/placements/index page.
- Add the expected date field to the placements/placements/index page.
- Add specs to cover this functionality
- Login as Patricia.
- View default search results on placements index, or do a new search.
- Review result summaries.
- You should see academic year and expected date now included in the summary table.
https://trello.com/c/s475bfon/714-provider-update-placements-index-with-academic-year-and-placement-date
=> UI changes to provider placements index

app/controllers/claims/support/claim_windows_controller.rb, app/forms/application_form.rb, app/forms/claims/claim_window_form.rb, app/forms/concerns/date_attributes.rb, app/models/claims/claim_window.rb, app/validators/date_presence_validator.rb, app/views/claims/support/claim_windows/edit.html.erb, app/views/claims/support/claim_windows/edit_check.html.erb, app/views/claims/support/claim_windows/new.html.erb, app/views/claims/support/claim_windows/new_check.html.erb, app/views/claims/support/claim_windows/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/activerecord.yml, config/locales/en/claims/support/claim_windows.yml, spec/forms/application_form_spec.rb, spec/forms/claims/claim_window_form_spec.rb, spec/models/claims/claim_window_spec.rb, spec/system/claims/support/create_a_claim_window_spec.rb, spec/system/claims/support/update_a_claim_window_spec.rb
Follows up on the committed task here: https://github.com/DFE-Digital/itt-mentor-services/pull/854#pullrequestreview-2186352476
We want to avoid automatically associating academic years to claim windows, as it reduces flexibility but also adds additional logic to the service.
- Require user selecting the academic year for a claim window.
- Add `Claims::ClaimWindowForm` form object to handle `Claims::ClaimWindow` validations.
- As the `belongs_to :academic_year` adds a `required` validation, a lot of error-movement is required to show the `:academic_year` error on the `:academic_year_id` field, which is present on the claim window form.
- Moving the claim window form data object from a model to a form object allows us to validate the form submission in isolation.
- Allow over year-long …
=> Select academic year when creating a claim window

app/controllers/placements/placements_controller.rb, spec/requests/placements/providers/placements_spec.rb
We noticed a situation where a user with two accounts (or sharing a browser) could log out and be redirected back to a page they shouldn't be able to see. This was specifically occuring when a provider logged out and a school user logged in.
- Log in as patricia
- Visit the placement page
- Log out
- You should now see the school placements page
[Redirect away from "/placements" if current organisation is not set
](https://trello.com/c/zf9X9KBB/722-redirect-away-from-placements-if-current-organisation-is-not-set)
=> Redirect to organisations_path if current organisation is absent

app/components/placement/summary_component.html.erb, app/views/placements/placements/_placement_dates.html.erb, app/views/placements/placements/_placement_details.html.erb, config/locales/en/placements/placements.yml, config/locales/en/placements/schools/placements.yml, spec/system/placements/placements/view_a_placement_spec.rb
Placement dates (academic year and expect dates) are useful to the provider when looking for suitable placements.
- Add the Placement dates section to the provider placement view.
- This section contains the academic year and expected date.
- Add specs to test this functionality.
- Login as Patricia
- View the list of placements
- Click through into any placement
- Review the placement dates section which should be the first section on the table
- It should include the academic year and the expected date
https://trello.com/c/OzeTYcdi/716-provider-update-placements-show-page
=> Add placement dates section to provider placements show page

app/controllers/placements/placements_controller.rb, app/forms/placements/placements/filter_form.rb, app/queries/placements/placements_query.rb, app/views/placements/placements/_filter.html.erb, config/locales/en/placements/placements.yml, spec/factories/placements/terms.rb, spec/forms/placements/placements/filter_form_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
Now that expected date has been added, providers need to be able to filter for their desired terms
- Navigate to the placements page
- Select a term from the Expected date filter
- Click on "Apply filters"
- Placements with that term, or "Any time in the academic year" will be visible
- Click on "Clear filters"
- All placements will now be visible
[[Provider] Add expected date filter to placements index](https://trello.com/c/R2P0M8B6/713-provider-add-expected-date-filter-to-placements-index)
=> Add expected date filter

app/services/claims/claim/generate_csv.rb, spec/services/claims/claim/generate_csv_spec.rb
ESFA has requested the type_of_establishment of each school in order to assist lookup the bank details of a School. If a school belongs to a local authority, their payment will go there.
The status field is required for ESFA to confirm that they have received Claims that are all in the correct status.
- Add the type_of_establishment field from School the Claims::Claim::GenerateCSV output.
- Add the status of the Claim to the Claims::Claim::GenerateCSV service.
- Log in as a school user and create a new claim.
- Log out and log in as support user Colin.
- Click on the claims tab.
- Press 'Download CSV' in the top-left corner of the claims index page.
- Review the resulting CSV file.
https://trello.com/c/drfnuwOA/741-add-typeofestablishment-and-status-to-claims-csv-download
=> Add status and type of establishment headers and outputs to CSV

terraform/application/config/production_app_env.yml, terraform/application/config/staging_app_env.yml
maintenance page temp ingress is incorrectly listed as -tmp instead of -temp in app env
Update CLAIMS_HOSTS and PLACEMENTS_HOSTS in staging & production app_env.yml
Check it matches the path in maintenance_page/manifests/env/ingress_temp*
make staging terraform-plan
make production terraform-plan
https://trello.com/c/YdpEced1/2007-fix-maintenance-temp-ingress
=> Fix maintenance page temp ingress url

app/models/placements/term.rb, spec/decorators/placement_decorator_spec.rb, spec/models/placements/term_spec.rb, spec/wizards/placements/add_placement_wizard/terms_step_spec.rb
Currently they’re being displayed in the reverse order. The order should be updated to match [the prototype](https://bat-school-placements-18b07385d8a1.herokuapp.com/school-users/v3/add-placement-window).
- Change the term order
- Update specs to reflect the change in order
- Log in as Anne/Colin
- Add a placement, check that the terms are now Autumn -> Spring -> Summer
- Edit the placment
- check that the terms are now Autumn -> Spring -> Summer
- Navigate to the placements page
- Check that the expected date filter is Autumn -> Spring -> Summer
[Fix the sort order of placement terms
](https://trello.com/c/4CBv1lHL/749-fix-the-sort-order-of-placement-terms)
Anne:
Colin:
Patricia:
=> Re-order terms names to Autumn -> Spring -> Summer

app/views/placements/wizards/add_mentor_wizard/_check_your_answers_step.html.erb, config/locales/en/placements/wizards/add_mentor_wizard.yml
This is a 🐛 
School journey:
- Add a mentor
- Enter mentor details: 1234565, 09 01 1991
- Click continue
- Caption should read "Add mentor"
Support journey:
- Add a mentor
- Enter mentor details: 1234565, 09 01 1991
- Click continue
- Caption should read "Add mentor - <school name>"
[Remove duplicate Add Mentor page caption](https://trello.com/c/JthFlmEa/760-remove-duplicate-add-mentor-page-caption)
Support
School
=> Remove duplicated caption

app/views/placements/wizards/add_placement_wizard/_mentors_step.html.erb, app/views/placements/wizards/add_placement_wizard/_terms_step.erb, spec/support/shared_examples/system/placements/add_a_placement_wizard.rb
Expected UI behaviour.
School user:
- Add a placement
- Verify that steps with checkboxes are not checked before you select an option
- Select the last option (Any time in the academic year/Not yet know)
- Navigate to Check your answers
- Change the terms/mentors and confirm that your selection is checked.
Support user:
- Add a placement
- Verify that steps with checkboxes are not checked before you select an option
- Select the last option (Any time in the academic year/Not yet know)
- Navigate to Check your answers
- Change the terms/mentors and confirm that your selection is checked.
['Add placement' wizard → checkboxes should be unchecked by default](https://trello.com/c/Dm5fbL0T/750-add-placement-wizard-%E2%86%92-checkboxes-should-b …
=> Add placement uncheck default checkboxes

config/locales/en/claims/schools/claims.yml, spec/system/claims/schools/claims/create_claim_spec.rb
We need to update the confirmation content with updated dates for the new claim window.
- Update the content of the claim confirmation page to be accurate with the upcoming claim window's payment dates.
- Content on the claim confirmation page should show "December 2024" as the expected payment dates.
=> Update claim confirmation content to latest dates

app/forms/concerns/date_attributes.rb, spec/forms/application_form_spec.rb
Date attributes are returning empty `IncompleteDate` objects when all date components are `nil`. This causes some strange behaviours, such as the the `Claims::ClaimWindowForm#initialize` method not setting the date attributes as they are not `nil`, they are `IncompleteDate` objects by default.
- A date attribute will return `nil` when all date components are `nil` instead of an `IncompleteDate` with all components as `nil`.
- Try editing a claim window.
- The date should now be pre-populated.
| Before | After |
| ------ | ----- |
| ![CleanShot 2024-09-04 at 11 20 54](https://github.com/user-attachments/assets/cbf48e5a-2278-4341-a3af-2c2a7a67a635) | ![CleanShot 2024-09-04 at 11 21 27](https://github.com/user-attachments/assets/da312654-3e0c-4059-a9de-f0ab34d07531) |
=> DateAttributes should return nil when all date components are nil

Dockerfile, config/initializers/okcomputer.rb
- Add the `SHA` environment variable the `Dockerfile`
- Add the `OkComputer::AppVersionCheck.new` to the `OkComputer` initialiser.
- Navigate to the `/healthcheck/all` endpoint and view the commit sha in the review app.
[Add a health check to show the currently deployed commit SHA
](https://trello.com/c/Bfhgfq76/777-add-a-health-check-to-show-the-currently-deployed-commit-sha)
=> Add commit SHA to the healthcheck endpoint

app/policies/placements/mentor_policy.rb, app/policies/placements/user_policy.rb
The joins in our policy scopes were returning duplicate records unintentioanlly, we've moved to subqueries to avoid this.
- There should be no discernable differences to users
- Test suite should pass
[Duplicates are appearing in the users list for schools and providers](https://trello.com/c/5Apc51qs/781-duplicates-are-appearing-in-the-users-list-for-schools-and-providers)
=> Use sub-queries in policy scopes

.github/actions/deploy-environment/action.yml, Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/spec_helper.rb
Upon upgrading to Rails 7.2, AR adapters need to be registered. The NullDb adapter has not been updated to support Rails 7.2.
By looking at our usage, we needed the nulldb adapter to prevent db queries from happening within smoke tests.
- Remove the NullDb adapater.
- Don't run fixtures nor maintain test schema when running smoke tests.
- Format the GA deploy action YAML file.
This gets around potentially multiple issues by running smoke tests specifically on the `specs/system/smoke_tests` directory.
=> Remove nulldb AR adapter

db/migrate/20240913144518_drop_data_migrations_table_if_exists.rb, db/schema.rb
We recently removed the `data_migrate` gem https://github.com/DFE-Digital/itt-mentor-services/pull/1022.
We should drop the `data_migrations` table if it exists. It will exist in environments, such as production, where the `data_migrations` table was added previously via the `data_migrate` gem.
On new machines it will be missing, hence the need for the `if_exists: true`.
- Drop the `data_migrations` table if it exists.
\-
=> Drop data_migrations table if exists

Gemfile, Gemfile.lock
Enables support for running RSpec tests inside your IDE (VS Code, in my case).
See [ruby-lsp-rspec][1] for an example of how this works.
Can be used in combination with the [Ruby LSP extension for VS Code][2].
[1]: https://github.com/st0012/ruby-lsp-rspec
[2]: https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp
=> Add Ruby LSP RSpec addon

app/models/claims/claim.rb, config/initializers/inflections.rb, db/migrate/20240913143256_add_sent_to_esfa_to_claim_status_enum.rb, db/schema.rb, spec/helpers/claims/claim_helper_spec.rb, spec/models/claims/claim_spec.rb
We've already sent some claims to ESFA. We want to create a distinction between these claims and the new claims that are submitted to the service. 
- Add the `sent_to_esfa` claim status.
Once this change is live, I'll SSH into the service to update the status of the claims that have already been sent to ESFA.
=> Add the "sent_to_esfa" claim status

.github/workflows/delete_review_app.yml
Allow the delete-review-app workflow to be run manually
Add workflow-dispatch to delete workflow
run on PR close: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/10791268716 
manual run: test after merge
=> add workflow dispatch to delete-review-app

app/components/claim/status_tag_component.rb, spec/components/claim/status_tag_component_spec.rb
We want to show "Sent to ESFA" in the status tags. It seems I've forgotten to add it to the `Claim::StatusTagComponent`'s list of accepted statuses.
- Add `sent_to_esfa` to the list of status colors in the `Claim::StatusTagComponent` view component.
- Add a set of tests to ensure the `Claim::StatusTagComponent` knows how to render all Claim statuses.
=> Add sent_to_esfa to the list of StatusTag statuses

app/components/content_header_component.html.erb
This change will contribute to resolving an identified accessibility issue relating to heading structure while maintaining the existing UI.
- In the content header component, replace the h4 header text with a span while keeping the same classes so the styling remains unchanged.
- Log in as a multi-org user.
- Choose any institution.
- Navigate to the organisation switcher at the top of the page (where you can find a 'change organisation' hyperlink).
- Check that the name of the school on the switcher appears with the correct styling.
- Use 'dev tools' in the browser to confirm that the component contains a 'span' in place of an 'h4'.
https://trello.com/c/yE34nofc/791-remove-h4-from-the-organisation-switcher-component
=> Replace H4 in content header component with span

app/views/placements/support/organisations/_filter.html.erb, app/views/placements/support/organisations/index.html.erb
This change fixes a bug through which the filter sidebar presented as a full-screen overlay on smaller viewports. It is now possible to show and hide the panel at the user's discretion.
- "Show filter" button added to the organisation index 
- Show/hide functionality added for side panel, including a 'Close' button
- Log in as support user.
- You will land on the organisation index page.
- Reduce browser window size until the smaller viewport settings appear.
- The "Show filter" button should appear.
- Click the "Show filter" button.
- The filter panel should appear on the right-hand side.
- Close the panel.
https://trello.com/c/5gqD2wIZ/790-fix-filter-panel-always-showing-and-obscuring-page-content
<br>
<br>
<br>
<br>
=> "Show filter" button added to Support user -> organisation index

app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_tag.scss, app/views/claims/support/databases/reset.en.html.erb, spec/system/claims/support/reset_database_spec.rb
We don't want to have tags within page titles.
- Swap out tag for plaintext.
- Add "environment" word in for clarity.
- Reset database page no longer shows a tag in the page title.
=> Remove the tag from the reset database page title

app/views/claims/support/databases/reset.en.html.erb, spec/system/claims/support/reset_database_spec.rb
The environment name should not be capitalized.
- Downcase the environment name.
- Environment name in the page title on the reset page is all lowercase letters.
=> Downcase the environment name on the Claims reset database page

app/services/claims/claim/generate_csv.rb, spec/services/claims/claim/generate_csv_spec.rb
We want to change the CSV headers to be more explicit whether they are an attribute of the claim or the school.
- Prefix un-prefixed headers with either `school_` or `claim_`.
- Change `date_submitted` to `claim_submission_date`.
- Add an additional blank `claim_unpaid_reason` header.
- Headers have been approved by Product.
=> Update Claims::Claim::GenerateCSV headers

app/views/claims/schools/mentors/check.html.erb, app/views/claims/support/schools/check.html.erb, app/views/claims/support/schools/mentors/check.html.erb, app/views/claims/support/schools/users/check.html.erb, app/views/placements/wizards/add_mentor_wizard/_check_your_answers_step.html.erb, app/views/placements/wizards/add_school_contact_wizard/_check_your_answers_step.html.erb, app/views/placements/wizards/add_support_user_wizard/_check_your_answers_step.html.erb, app/views/placements/wizards/add_user_wizard/_check_your_answers_step.html.erb, app/views/shared/organisations/_organisation_details.html.erb, app/views/shared/schools/_school_contact_details.html.erb
For all “Change” links in the app (i.e. across both services), make sure visually_hidden_text is present.
Re-use the ‘key’ text as the hidden text.
For example, if the summary list key is “First name” then the visually hidden text should also be “First name”. That will produce the link “Change First name” which means there is context for screen reader users.
- Have a look at the updated views in the review app and inspect the HTML to see the visually hidden text
[Add visually hidden text to all "change" links](https://trello.com/c/HQnpex17/788-add-visually-hidden-text-to-all-change-links)
=> Add missing `visually_hidden_text` to change links

app/javascript/controllers/filter_search_controller.js, spec/system/claims/support/claims/view_claims_spec.rb, spec/system/placements/placements/searches_filter_options_for_placements_spec.rb
This PR addresses one of the accessibility issues raised by an external accessibility audit of the app. The filter search inputs were missing an associated label, which meant their purpose wasn't clear to those using a screen reader.
I've added a visually hidden `<label>` tag to each search input.
This follows the approach taken by GOV.UK for their filter search inputs, as demonstrated by 'Organisation' filter on https://www.gov.uk/search/guidance-and-regulation
To make sure the `<input id="">` attribute is unique for each filter on the page, I've introduced an 'instance counter' variable to the filter-search Stimulus controller. This will be automatically incremented with each new instance of the controller, meaning it will always be unique.
I've also adjusted the system specs to make …
=> Add visually hidden labels to filter search inputs

app/models/placements/academic_year.rb, app/views/placements/schools/placements/show.html.erb, spec/models/placements/academic_year_spec.rb, spec/system/placements/schools/placements/navigate_placements_spec.rb
There’s a bug where the ‘Back’ link on the placement details page doesn’t return you to the correct tab on the placements index page.
This applies to school users where they have ‘Current year’ and ‘Next year’ tabs for switching between placements in different academic years.
- Navigate to placements
- Select "Next year (2025 to 2026)"
- View a placement
- Click back
- "Next year (2025 to 2026)" should still be selected
[School user → Placements → Placement details: Make sure the 'back' link retains the currently selected academic year tab
](https://trello.com/c/hbZ4f3rH/796-school-user-%E2%86%92-placements-%E2%86%92-placement-details-make-sure-the-back-link-retains-the-currently-selected-academic-year-tab)
=> Replace hardcoded link with `:back`

app/assets/stylesheets/components/_header.scss
There’s a styling bug with the responsive nav menu which occurs at specific viewport dimensions.
At 1x zoom level, this bug is present between viewport widths 640px – 768px.
- Open the inspect toolbar
- Set the viewport to the widths above
- Check the menu items no longer overlap
[Fix menu button overlaying menu content when zoomed](https://trello.com/c/x8noUE1P/789-fix-menu-button-overlaying-menu-content-when-zoomed)
https://github.com/user-attachments/assets/4bdbc399-fd7a-4028-8194-69876ba14e8e
=> Use mobile navigation on tablet viewports

app/models/claims/training_allowance.rb, spec/models/claims/training_allowance_spec.rb
Create a class that will calculate how much training can be claimed for a given mentor.
- Adds a new `Claims::TrainingAllowance` model that combines the features of several existing classes into a single class.
Work through the spec file and check that all of the possible scenarios are covered, alternatively this can be tested via a rails console with existing claims data to confirm the expected results.
[Introduce a Training Allowance object](https://trello.com/c/l2QqUCci/739-introduce-a-training-allowance-object)
=> Create training allowance object

app/assets/stylesheets/components/claim/card.scss, app/components/claim/card_component.html.erb, app/controllers/claims/support/claims_controller.rb, app/forms/claims/support/claims/filter_form.rb, app/models/academic_year.rb, app/models/claims/claim.rb, app/queries/claims/claims_query.rb, app/views/claims/schools/claims/check.html.erb, app/views/claims/schools/claims/show.html.erb, app/views/claims/support/claims/_details.html.erb, app/views/claims/support/claims/_filter.html.erb, app/views/claims/support/claims/index.html.erb, app/views/claims/support/schools/claims/check.html.erb, config/locales/en/claims/support/claims.yml, config/locales/en/components/claim/card_component.yml, spec/components/claim/card_component_spec.rb, spec/forms/claims/support/claims/filter_form_spec.rb, spec/models/academic_year_spec.rb, spec/models/claims/claim_spec.rb, spec/queries/claims/claims_query_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/schools/claims/view_claim_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb, spec/system/claims/support/claims/view_claims_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb
We want to be able to see which Academic year each claim was made against.
We also want to be able to filter claims by academic year in the support console.
- Navigate to the claims in the navigation
- Filter claims by the current academic year (2024 to 2025) 
- All claims should be displayed
- Clear all filters
- Filter claims by the next academic year (2025 to 2026)
- No claims should be displayed
- Clear the filter using the 2025 to 2026 pill
- All claims should be displayed
[How we identify which claims are associated with each academic year / claim window (support console)](https://trello.com/c/a3HYWhwk/793-how-we-identify-which-claims-are-associated-with-each-academic-year-claim-window-support-console)
=> Claims academic year filter

app/views/claims/support/claims/_filter.html.erb
Instead of "Sent To ESFA", we want the status filter to read as "Sent to ESFA" to match the status tags.
- Use `#humanize` instead of `#titleize` in the claims status filters.
Claim statuses in the claims filter should show "humanized" statuses, rather than "titleized".
=> Tweak claims status filters to use humanize instead of titleize

app/components/primary_navigation_component.rb, app/components/secondary_navigation_component.rb
A recent-ish change added `attr_reader :current` to the `SecondaryNavigationComponent` under the `private` scope.
We should move all `attr_reader` calls into a private scope for navigation components.
- Move `attr_reader` calls of navigation components into `private` scopes.
\-
=> Bring navigation component attr_readers into private scope

app/views/claims/schools/mentors/_remove_mentor.html.erb, app/views/claims/support/schools/mentors/_cannot_remove_mentor.html.erb, app/views/claims/support/schools/mentors/remove.html.erb
Undercover demands coverage to be satisfied.
[Add test missing test coverage for app/controllers/claims/support/schools/mentors_controller.rb
](https://trello.com/c/svKeX0OS/841-add-test-missing-test-coverage-for-app-controllers-claims-support-schools-mentorscontrollerrb)
=> Add missing test coverage

spec/models/claims/claim_spec.rb
Order is not important for this test as there is no order specified on the scope. This test failed because we order our default ordering is by UUID, meaning the array isn't guaranteed to be returned in order of creation.
We noticed this spec fail whilst pairing, and flaky tests can be frustrating!
- Review the changes
[Fix flaky test](https://trello.com/c/SnYxdLq3/840-fix-flaky-test)
=> Fix flaky spec

app/controllers/placements/application_controller.rb, config/environments/test.rb
Fix the issue causing the warning messages to avoid us having to disable the config for the warning,
[Re-enable raise_on_missing_callback_actions config](https://trello.com/c/YQgg4Tm4/822-re-enable-raiseonmissingcallbackactions-config)
=> Only verify_policy_scoped on controllers that have index actions

app/helpers/application_helper.rb
The `text_or_dash` help is no longer used and prevents `ApplicationHelper` from 100% coverage.
- Remove the `text_or_dash` helper method.
\-
=> Remove the text_or_dash helper

app/controllers/placements/application_controller.rb, app/controllers/placements/organisations_controller.rb, app/controllers/placements/providers/placements_controller.rb, app/models/placements/support_user.rb, app/models/placements/user.rb, app/policies/placement_policy.rb, app/policies/placements/mentor_policy.rb, app/policies/placements/provider/placement_policy.rb, app/policies/placements/user_policy.rb, app/policies/provider_policy.rb, app/policies/school_policy.rb, config/analytics_blocklist.yml, spec/models/placements/support_user_spec.rb, spec/models/placements/user_spec.rb, spec/policies/placement_policy_spec.rb, spec/policies/placements/mentor_policy_spec.rb, spec/policies/placements/provider/placement_policy_spec.rb, spec/policies/placements/user_policy_spec.rb, spec/policies/provider_policy_spec.rb, spec/policies/school_policy_spec.rb, spec/policies/user_membership_policy_spec.rb
- Remove the concept of `current_organisation` throughout the service
- Remove `current_organisation` attribute from user models
- Remove `current_organisation` from policies
- Test most of the features of the service to ensure nothing has broken.
https://trello.com/c/onvm1r3x/853-remove-the-concept-of-the-current-user-having-a-current-organisation
=> Remove current organisation

app/components/claims/claim/mentor_training_form/disclaimer_component.rb, app/forms/claims/claim/mentor_training_form.rb, spec/forms/claims/claim/mentor_training_form_spec.rb, spec/forms/claims/support/claim/mentor_training_form_spec.rb
These changes come off the back of a comment thread in a separate PR – see https://github.com/DFE-Digital/itt-mentor-services/pull/1062#discussion_r1787658239
We agreed that the changes I suggested were out of scope for that PR, so I've put them into a new one.
Now that we have a standalone 'training allowance' object, it feels unnecessary for the mentor training form to hide that object from the outside world through abstractions and wrapper methods.
- Refactor to remove confusingly named method `mentor_training_form.max_hours_equals_maximum_claimable_hours?`
- Move the logic from that method into the single place it was being used (i.e. the 'disclaimer' component)
- Avoid double-memoizing methods, this is not necessary
- Make methods private where possible
This PR is based upon #1062 …
=> Refactor methods on claims mentor training form

config/analytics.yml, config/analytics_blocklist.yml
We don't currently need the mentor TRN in our analytics platform.
- Stop sending mentor TRNs to BigQuery.
- TRNs are no longer sent.
=> Move mentor TRN to analytics blocklist

app/views/claims/schools/_grant_conditions.html.erb, config/locales/en/claims/pages.yml, config/locales/en/claims/schools/grant_conditions.yml, spec/system/claims/grant_conditions_spec.rb
Now that we've closed the final window for the 2023/24 academic year claims, we need to update the grant conditions page to the 24/25 academic year, along with dropping the "early adopter" wording.
- Update the Grant Conditions to match the [prototype](https://itt-mentoring-beta-dev-a238297da236.herokuapp.com/grant-conditions).
- The prototype and application content should match.
=> Update grant conditions

config/analytics.yml, config/analytics_blocklist.yml
DfE Analytics seems to be behaving strangely, for now, we want to remove all mentor fields from being sent.
- Requested change from Data team.
- Remove all mentor fields from DfE analytics.
- Add all mentor fields to DfE analytics blocklist.
\-
=> Move all mentor attributes into the analytics blocklist

app/components/claim/status_tag_component.rb, app/models/claims/claim.rb, db/migrate/20241009164610_rename_sent_to_esfa_claim_status_to_payment_in_progress.rb, db/schema.rb, spec/components/claim/status_tag_component_spec.rb, spec/helpers/claims/claim_helper_spec.rb, spec/models/claims/claim_spec.rb
After some revision, we've decided to exclude explicitly showing ESFA to users, as some (or many) may not be familiar with the acronym.
- Rename `sent_to_esfa` enum value of claim statuses to `payment_in_progress`.
- The `ESFA` acronym is still required in inflections, as it is also used in the migration file name/class mapping.
=> Rename sent_to_esfa claim status to payment_in_progress

app/constraints/claims_only_constraint.rb, app/constraints/support_user_constraint.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/routes.rb, spec/constraints/claims_only_constraint_spec.rb, spec/constraints/support_user_constraint_spec.rb, spec/helpers/application_helper_spec.rb, spec/requests/account_spec.rb, spec/system/placements/sign_in_as_a_placements_user_spec.rb
- Remove the account page from the placements service
- Remove 'Account' nav item from the header
- Remove '/account` from the routes for placements service
- Sign in as any user on the placements service
- The 'Account' item in the header nav should no longer appear.
- visiting `/account` should no longer work for the placements service.
https://trello.com/c/fsvC2q4R/858-remove-the-account-page-from-the-placements-service
=> Remove the account page from the placement service

app/views/claims/pages/start.en.html.erb, spec/system/claims/start_page_spec.rb
We want to update the Claims start page with new content from UR rounds in preparation for public beta.
- Update start page content.
- Removes dependency on claim windows.
- Content matches the [prototype](https://itt-mentoring-beta-dev-a238297da236.herokuapp.com/).
=> Update the claims start page content in preparation for public beta

app/components/placement/summary_component.html.erb, app/controllers/placements/providers/placements_controller.rb, app/forms/placements/placements/filter_form.rb, app/views/placements/providers/placements/_filter.html.erb, app/views/placements/providers/placements/index.html.erb, config/locales/en/placements/providers/placements.yml, spec/forms/placements/placements/filter_form_spec.rb, spec/system/placements/placements/searching_for_a_placement_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
These design changes are in preparation of a new travel time feature on the placements index page. 
- Page title and H1 change: “Find placements”.
- Location search bar moved to filter sidebar.
- Location search included as a selected filter tag. 
- Location search cleared by clearing filters.
- New paragraph tag shows "results sorted by" either alphabetical order or distance from the search location.
- Number of results move to results column.
- The structure of the titles of the search results has changed to [Subject] en dash [School name]. This means the links remain understandable for accessibility reasons, but puts the subject first.
- The size of the link becomes govuk-heading-m to make it stand out from the content and give visual hierarchy.
Please review the full travel time …
=> Placements index: Move location search to filter sidebar

app/decorators/school_decorator.rb, app/services/placements/travel_time.rb, config/analytics_blocklist.yml, spec/decorators/school_decorator_spec.rb, spec/services/placements/travel_time_spec.rb
We are adding travel duration between a user's search location and placement schools which appear in search results. A service object exists with drive and transit travel modes, but a walk travel mode is also needed. 
- Adapt the travel time service object to include walking time, as well as driving and transit.
- Only travel time needed. Remove distance from object.
Run the following travel time tests:
- `spec/services/placements/travel_time_spec.rb`
- `spec/lib/google/routes_api_spec.rb`
Run the school decorator test (modified to add walking duration as an attribute):
- `spec/decorators/school_decorator_spec.rb`
https://trello.com/c/TMFoYL9a/855-add-walking-time-to-travel-time-service-object
=> Add walking time to travel time service object

app/components/placement/summary_component.html.erb, app/components/placement/summary_component.rb, app/decorators/school_decorator.rb, app/views/placements/providers/placements/index.html.erb, config/locales/en/components/placement/summary_component.yml, lib/google/routes_api.rb, spec/system/placements/placements/searching_for_a_placement_spec.rb, spec/system/placements/placements/view_placements_list_spec.rb
User is able to see travel times from the destination they have entered.
**Placements index**
- A travel time section is added to the listing content.
- This displays travel time for Public transport, Driving, Walking.
- Format should be:
> - XX minutes (up to an hour)
> - XX hour XX minutes (1-2 hours)
> - XX hours XX minutes (2+ hours)
Please use this PR to review content changes for the travel time feature, including from https://github.com/DFE-Digital/itt-mentor-services/pull/1096.
- Login as a Provider User.
- You will land on the placements index page.
- Search a location for which there will be a result (e.g. a town or city close to seeded placements).
- Check that the location appears as a selected filter tag.
- Check that results are rendered as expected (is the results number …
=> Display travel time on placements in search results

Gemfile, Gemfile.lock, config/analytics_blocklist.yml, config/environments/production.rb, config/storage.yml, db/migrate/20241016120228_create_active_storage_tables.active_storage.rb, db/schema.rb, terraform/application/application.tf, terraform/application/config/production.tfvars.json, terraform/application/config/qa.tfvars.json, terraform/application/config/sandbox.tfvars.json, terraform/application/config/staging.tfvars.json, terraform/application/storage_account.tf, terraform/application/variables.tf
In preparation for the upcoming Payments/Sampling/Clawback flows, we want to be able to store CSV files attached to ActiveRecord records.
Namely, when we generate CSVs, we want to save a snapshot of the file sent to ESFA and Providers.
This PR implements the foundational ActiveStorage and Azure Storage functionality.
- Add Azure Storage to terraform configuration.
- Setup Rails' Azure Storage ActiveStorage service for testing.
- Add all ActiveStorage tables to the `analytics_blocklist.yml`.
I've run the following code to validate file read/write capabilities:
```ruby
class Claims::SupportUser < User
has_one_attached :avatar
end
support_user = Claims::SupportUser.last
support_user.avatar.attach(io: URI.open("https://avatars.githubusercontent.com/u/4231530?s=40&v=4"), filename: …
```
=> Add Azure Storage

app/models/placement.rb, config/locales/en/placements/schools/placements.yml, db/migrate/20241008153148_add_new_year_groups_to_placement_year_group.rb, db/schema.rb, spec/models/placement_spec.rb
We want to enable schools to add EY placements to increase uptake of the service
- Create a primary placement
- Select one of the new options
- Create the placement
- Filter by one of the new options
- Confirm the placement is visible
[Implement nursery for placement year groups
](https://trello.com/c/LFtTK5GZ/861-implement-nursery-for-placement-year-groups)
=> Add nursery and reception year group options

app/controllers/placements/application_controller.rb, app/controllers/placements/organisations/users_controller.rb, app/controllers/placements/organisations_controller.rb, app/controllers/placements/providers/partner_schools/placements_controller.rb, app/controllers/placements/providers/partner_schools_controller.rb, app/controllers/placements/providers/placements_controller.rb, app/controllers/placements/providers_controller.rb, app/controllers/placements/schools/mentors_controller.rb, app/controllers/placements/schools/partner_providers_controller.rb, app/controllers/placements/schools/placements_controller.rb, app/controllers/placements/schools_controller.rb, app/policies/placements/partnership/provider_policy.rb, app/policies/placements/partnership/school_policy.rb, app/policies/placements/provider_policy.rb, app/policies/placements/school_policy.rb, app/views/placements/organisations/index.html.erb, spec/policies/placements/partnership/provider_policy_spec.rb, spec/policies/placements/partnership/school_policy_spec.rb, spec/policies/placements/provider_policy_spec.rb, spec/policies/placements/school_policy_spec.rb
- Improve use of `policy_scope` throughout the controllers.
- Ensure all controller methods use `policy_scope` where possible.
- Sign in as each user type and test that all features still work as expected.
https://trello.com/c/Mi2stP5t/848-expand-and-improve-on-the-use-of-pundit-scopes
=> Improve coverage of policy scopes in controllers

.rubocop.yml, spec/support/shared_examples/system/placements/add_a_placement_wizard.rb, spec/support/shared_examples/system/placements/edit_a_placement_wizard.rb
- After some exploration, `shared_examples` aren't ideally suited to handle `system`/`feature` specs.
- As a result, the rubocop rules for `RSpec/Dialect` have been ignored for files in the `spec/support/shared_examples/system` directory.
- Rubocop rule for `RSpec/Dialect` is now ignored for files in the `spec/support/shared_examples/system` directory.
- Shared system tests now use `scenario` instead of `it`
https://trello.com/c/15g93JQU/870-configure-rubocop-so-shared-examples-can-use-system-spec-syntax
=> Update rubocop.yml to allow shared system spec to use scenario

app/assets/stylesheets/components/_all.scss, app/assets/stylesheets/components/_phase_banner.scss, app/views/claims/schools/_primary_navigation.html.erb, app/views/claims/support/_primary_navigation.html.erb, app/views/layouts/application.html.erb
- At the request of @ollietreend, remove the `app-phase-banner-no-border-bottom` css
Remove the `app-phase-banner-no-border-bottom` css
https://trello.com/c/gFl95hLX/886-remove-app-phase-banner-no-border-bottom-css
=> Remove the app-phase-banner-—no-border-bottom css

app/controllers/claims/support/support_users_controller.rb
We want to order Support Users by their name.
- Order Support Users by name.
- Visit the support users page.
- Add some support users.
- You should see them ordered alphabetically.
=> Order claims support users list by name

lib/google/routes_api.rb, spec/lib/google/routes_api_spec.rb
- The deprecation warning is triggered because `Rails.cache.fetch` calls `nil?` on the `Httparty::Response`. 
To resolve this, call `body` on the `Httparty::Response` and then convert it to JSON.
- Convert `Httparty::Response` body to `JSON` to stop deprecation issue.
- Run `bundle exec rspec spec/system`
- The HTTParty DEPRECATION warning should no longer appear.
https://trello.com/c/zOpZRPLt/889-resolve-httparty-deprecation-notices-in-system-specs
=> Fix issue with calling nil? on httparty response when caching

app/assets/stylesheets/components/_tag.scss
We want to avoid the above display from happening:
- Add `white-space: nowrap` to govuk tags.
- Visit the review app, there will be no wrapping of long status names.
=> Ensure GOVUK tags are inline

app/components/placement/summary_component.rb, app/controllers/placements/providers/placements_controller.rb, app/views/placements/providers/placements/index.html.erb, spec/system/placements/providers/placements/searching_for_a_placement_spec.rb, spec/system/placements/providers/placements/view_placements_list_spec.rb
Previously we called Placements::TravelTime in `summary_component.rb`, meaning we performed 3x API calls for every single listing shown on the page. At 25 listings per page, that’s 75 external calls to the Google Routes API.
This PR moves the service call to the placements controller so that `calculate_travel_time` is called once for the entire collection of results.
- Move `calculate_travel_time` (which calls the Placements::TravelTime service object) to the placements controller
- Remove logic from `summary_component.rb`
- Add additional response hashes to `routes_api` travel time stubs to reflect that a whole collection of results is now decorated and populated, as opposed to a single result
- Review placements controller and `calculate_travel_time` method
- Run test …
=> Optimise travel time performance 

app/models/placement.rb, app/models/placements/term.rb, spec/models/placement_spec.rb, spec/models/placements/term_spec.rb
- Fix issue when deleting placements which are associated with terms through placement windows.
- Add destroy dependancy on placement windows in placement and term models.
- Find or make a placement with an associated term. (Summer, Autumn or Spring)
- Delete the placement.
- This should be deleted without any issues.
https://trello.com/c/nqbJPqFn/898-investigate-and-resolve-placement-deletion-issue
https://github.com/user-attachments/assets/8543d211-150b-4db1-b23e-d38e20a23079
=> Fix issue deleting placements with windows

spec/rails_helper.rb, spec/support/govuk_component_matchers.rb, spec/system/placements/organisations/users/add_users_spec.rb, spec/system/placements/schools/mentors/view_a_mentor_spec.rb
Currently, many of our system specs rely on using the `expect(page).to have_content` matcher to assert that certain items are on the page. However this is fairly low-accuracy and likely to lead to false positives, because it only asserts that the content exists _somewhere_ on the page.
More often, we actually want to assert that the required content exists within a specific element or component on the page. I've therefore opened this PR to introduce some matchers to help us to write more specific system specs.
New RSpec matchers for use in system specs:
H1, H2 and H3 matchers for [GOV.UK-styled headings](https://design-system.service.gov.uk/styles/headings/).
```ruby
expect(page).to have_h1("Heading level one")
expect(page).to have_h2("Heading level two")
expect(page).to have_h3("Heading …
```
=> Add GOV.UK Component matchers for system specs

terraform/application/application.tf
We dropped the data_migrate gem in PR #1022, but it looks like we forgot to tidy up this reference to the gem.
This comment is no longer helpful since we no longer use the gem.
=> Remove redundant comment from Terraform config

spec/support/govuk_component_matchers.rb
Our matcher helpers should return `true` or `false` to allow us to use `to` and `not_to`
- Review changes in file
[Update matchers to return true or false](https://trello.com/c/Yi2Y602i/911-update-matchers-to-return-true-or-false)
=> Matchers return true or false

spec/system/claims/schools/claims/create_claim_spec.rb
This system spec was unpredictably passing and failing.
It looks like this was caused by pulling the 'last' record from the database, but not providing a sort order. You can't rely on the order of records in the database unless you specify one – especially since we use UUID strings as our primary keys.
In this case, there are two claims in the database which means sort order is important.
Sort records before retrieving the 'last' one.
Do the tests pass?
Done as part of this card: https://trello.com/c/TUWOipzZ/824-add-test-coverage-for-refresher-training-and-remove-some-hardcoded-training-allowance-limits
I've cherry-picked this fix into its own standalone PR.
=> Fix a flaky system spec

app/assets/stylesheets/components/_heading.scss, app/assets/stylesheets/components/claim/card.scss, app/components/claim/card_component.html.erb, app/views/claims/schools/claims/index.html.erb, app/views/claims/support/claims/show.html.erb, app/views/claims/support/schools/claims/index.html.erb, config/locales/en.yml, config/locales/en/claims/support/claims.yml, spec/components/claim/card_component_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb, spec/system/claims/support/claims/view_claims_spec.rb, spec/system/claims/support/schools/claims/view_a_schools_claims_spec.rb
We want to update the date format displayed on claim cards in the support console.
- Change date format of claim card submission dates to `:long`.
- Fix spacing / inline display of claim status in claim show pages.
- Visit the `/support/claims` and `/support/claims/:claim_id` pages.
- The dates on `/support/claims` should follow the `6 November 2024` format.
- The status tags of `/support/claims/:claim_id` should be inline.
- [Prototype](https://itt-mentoring-beta-dev-a238297da236.herokuapp.com/support/claims) for reference.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td colspan="2">
<code>/support/claims</code>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2">
<code>/support/schools/:school_id/claims</code> &amp; <code>/schools/:school_id/claims</code>
</td> …
=> Update claim card date format

app/models/claims/mentor_training.rb, spec/forms/claims/claim/mentors_form_spec.rb, spec/forms/claims/support/claim/mentors_form_spec.rb, spec/models/claims/claim_spec.rb, spec/models/claims/mentor_training_spec.rb, spec/models/claims/training_allowance_spec.rb, spec/services/claims/provider/generate_csv_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb, spec/system/claims/schools/mentors/mentor_associated_to_active_claim_spec.rb, spec/system/claims/support/claims/view_a_claim_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/mentors/mentor_associated_to_active_claim_spec.rb
While working to [add refresher training to the Claims service](https://trello.com/c/TUWOipzZ/824-add-test-coverage-for-refresher-training-and-remove-some-hardcoded-training-allowance-limits), I stumbled across a few specs which needed refactoring before I could easily implement the feature.
Some of the changes I've made here are cosmetic – for example, I've reformatted a spec to improve readability.
Other changes are more functional and far reaching in nature. For example, I've updated the associations on the Claim model so that Provider and Mentor are required. They were previously optional, but on closer inspection it only seemed to be required by the test suite, and was not actually a requirement of the app itself. In particular this seemed to be due to the way Claim records were …
=> Prefactor specs ahead of refresher training changes

app/forms/claims/claim/mentors_form.rb, app/models/claims/mentor_training.rb, spec/factories/claims/claim_windows.rb, spec/forms/claims/claim/mentors_form_spec.rb, spec/forms/claims/support/claim/mentors_form_spec.rb, spec/models/claims/mentor_training_spec.rb, spec/services/claims/provider/generate_csv_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb
This PR completes the implementation of functionality required for claiming refresher training. It's just the tip of the iceberg, and it follows on from #994, #1014, #1166, #1167, and #1168.
After this PR is merged, all the required logic and validation should be in place to support users claiming up to 20 hours of initial training, or up to 6 hours of refresher training, depending on whether or not the mentor has trained with that particular provider before.
> [!NOTE]  
> **There are still areas throughout the app which refer to a 20 hour limit of training.** This content will need updating ahead of refresher training becoming available to end users. This PR completes the development work required to support refresher training, but it doesn't update any content.
- **Make the validation …
=> Update validation rules to support claiming for refresher training

spec/support/govuk_component_matchers.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_academic_year_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_expected_date_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_placements_to_show_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_primary_year_group_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_school_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_schools_i_work_with_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_search_by_location_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_subject_spec.rb, spec/system/placements/providers/placements/provider_user_searches_for_school_filter_option_spec.rb, spec/system/placements/providers/placements/provider_user_searches_for_subject_filter_option_spec.rb
We have collectively decided on a new format for our system specs, as part of switching over to the new format we are picking "tricky" specs to see how they can be adapted. This collection of specs cover the provider user filters on the placements index page.
- Purely spec changes, review each file and make sure that nothing has been missed and add any style suggestions whilst we're still exploring exactly how our specs should be created.
[Refactor provider filter system specs to cucumber style](https://trello.com/c/IBTs1FiB/910-refactor-provider-filter-system-specs-to-cucumber-style)
=> Refactor provider filter system specs

maintenance_page/html/index2.html, maintenance_page/nginx.conf
ittms has two services and we want to display a different maintenance message depending on which service is being used.
configure the nginx.conf to go to different index pages based on the different server names of the two services
i applied a temporary commit to support running in review 
make review terraform-apply PR_NUMBER=1234
make review enable-maintenance GITHUB_TOKEN=ghp_xxxxxxxxx PR_NUMBER=1234
you can see it running in test at 
https://manage-school-placements-1234.test.teacherservices.cloud/
https://track-and-pay-1234.test.teacherservices.cloud/
and the title at the top is now the correct service 
also review code changes
running 
make review disable-maintenance GITHUB_TOKEN=ghp_xxxxxxxxx PR_NUMBER=1234
would switch back out of maintenance page mode
[Separate maintenance …
=> Separate maintenance messages

maintenance_page/nginx.conf
The nginx server was configured incorrectly.
This updates the config so the expected pages are rendered at the expected hostnames.
For context, see the Slack thread: https://ukgovernmentdfe.slack.com/archives/C011EM7HU85/p1732032598405959
- https://staging.claim-funding-for-mentor-training.education.gov.uk
- https://track-and-pay-staging.test.teacherservices.cloud
- https://staging.manage-school-placements.education.gov.uk
- https://manage-school-placements-staging.test.teacherservices.cloud
=> Fix the nginx config for maintenance pages

app/wizards/placements/add_organisation_wizard/organisation_options_step.rb, spec/wizards/placements/add_organisation_wizard/organisation_options_step_spec.rb
- When the session expires, the `organisations` on the `organisation_options_step` returns `nil` which breaks `.count`
- Change to the `organisations` method to return an empty array `[]` if `wizard.organisation_model.blank?`
https://trello.com/c/YXrsqbXO/955-fix-organisation-count-bug
=> Fix for organisation options step

app/models/claims/claim.rb, config/analytics.yml, db/migrate/20241202160112_add_sampling_reason_to_claim.rb, db/schema.rb, spec/factories/claims.rb, spec/models/claims/claim_spec.rb
The claims support console is being enhanced for claim management, as part of those changes a claim can be sampled and a sampling reason can be optionally provided. We need a place to store this sampling reason.
No UI elements included in this PR, a review of the files should be adequate.
[[Sampling] Add sampling_reason to claims table](https://trello.com/c/cw5vBlt2/971-sampling-add-samplingreason-to-claims-table)
=> Add `sampling_reason` to Claim

package.json
The various warnings when running `yarn build:css` clutter the important logs. Let's remove warnings from logs by default to highlight actual issues within our CI.
- Change the `--quiet-deps` flag to `--quiet` to silence all warnings.
- Run `yarn build:css`
| Before | After |
| ------ | ----- |
| ![CleanShot 2024-11-25 at 11 24 24](https://github.com/user-attachments/assets/15de400d-b71e-4fb9-a0b4-a4af19df7c44) | ![CleanShot 2024-11-25 at 11 24 56](https://github.com/user-attachments/assets/6151f6bf-1818-4c59-831b-42d1ada846f6) |
=> Silence all sass warnings by default

app/components/claim/card_component.html.erb, app/components/claims/claim/filter_form_component.html.erb, app/components/claims/claim/filter_form_component.rb, app/controllers/claims/support/claims/clawbacks_controller.rb, app/models/claims/claim.rb, app/views/claims/support/claims/clawbacks/index.html.erb, app/views/claims/support/claims/clawbacks/show.html.erb, app/views/claims/support/claims/index.html.erb, app/views/claims/support/claims/samplings/index.html.erb, config/locales/en/claims/support/claims/clawbacks.yml, config/locales/en/components/claim/card_component.yml, config/routes/claims.rb, spec/support/govuk_component_matchers.rb, spec/system/claims/support/claims/clawbacks/support_user_filters_clawback_claims_by_academic_year_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_filters_clawback_claims_by_provider_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_filters_clawback_claims_by_school_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_filters_clawback_claims_by_status_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_filters_clawback_claims_submitted_after_a_date_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_filters_clawback_claims_submitted_before_a_date_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_searches_for_a_clawback_using_a_reference_number_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_views_clawbacks_index_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_views_clawbacks_index_when_there_are_no_clawbacks_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_by_status_spec.rb, spec/system/claims/support/claims/sampling/support_user_views_sampled_claims_spec.rb, spec/system/claims/support/support_users/sampling/upload_data/support_user_uploads_sampling_data_spec.rb
- Support users can easily see claims which have a clawback status: `sampling_not_approved`, `clawback_requested`, or `clawback_in_progress`.
- Navigate to "Claims" in the primary nav
- Navigate to "Sampling" in the secondary nav
- You should only see claims claims which have the status `sampling_not_approved`, `clawback_requested`, or `clawback_in_progress`.
- Test the filters to ensure the claims can be filtered correctly.
https://trello.com/c/pwFyRdfK/981-clawbacks-index-page
=> Add clawback index page

app/components/claims/claim/filter_form_component.html.erb, app/controllers/claims/support/claims/samplings_controller.rb, app/models/claims/claim.rb, app/views/claims/support/claims/samplings/confirm_approval.html.erb, app/views/claims/support/claims/samplings/show.html.erb, config/locales/en/claims/support/claims.yml, config/locales/en/claims/support/claims/samplings.yml, config/routes/claims.rb, spec/system/claims/support/claims/sampling/support_user_approves_a_claim_spec.rb
- Create new show page for sampling claims: `app/views/claims/support/claims/samplings/show.html.erb`
- Add UI to display `claim_reason` if present
-  Add "Approve claim" button
- Add approval confirmation page
-  Add approval logic to update claim `status` from `sampling_in_progress` or `sampling_provider_not_approved` to `paid`
- Add success banner and return support user to the sampling index following an approval
- Use the review app to navigate through the flow
- Run the sampling system tests `spec/system/claims/support/claims/sampling`
- Review `spec/system/claims/support/claims/sampling/support_user_approves_a_claim_spec.rb` to check that it covers all aspects of the scenario and no …
=> Add claims support user sampling approval flow

app/models/claims/mentor_training.rb, config/analytics.yml, db/migrate/20241216150808_add_rejected_columns_to_mentor_trainings.rb, db/schema.rb, spec/factories/mentor_trainings.rb, spec/models/claims/mentor_training_spec.rb
- Add the following columns to the `mentor_trainings` table:
- rejected (Boolean)
- rejected_reason (Text)
- rejected_hours (Integer)
- https://trello.com/c/O19JNLcS/1001-add-rejected-columns-to-the-mentor-trainings-table
=> Add rejected columns to mentor trainings

app/models/claims/mentor_training.rb, config/analytics.yml, db/migrate/20241216161048_add_assured_columns_to_mentor_trainings.rb, db/schema.rb, spec/factories/mentor_trainings.rb, spec/mailers/claims/esfa_mailer_spec.rb, spec/models/claims/mentor_training_spec.rb
- Add the following columns to the mentor_trainings table:
- assured (Boolean)
- not_assured_reason (Text)
- https://trello.com/c/QYIhOaJW/1002-add-assured-columns-to-the-mentor-trainings-table
=> Add assured columns to mentor trainings

app/models/claims/claim_activity.rb, config/analytics.yml, db/migrate/20241217132410_create_claims_claim_activities.rb, db/schema.rb, spec/factories/claims/claim_activities.rb, spec/models/claims/claim_activity_spec.rb
We need to be able to track when claim processing activity is performed, who performed them, and associate the activity to the artifacts created.
- Add the `Claims::ClaimsActivity` model.
=> Add claim activity model

config/routes/claims.rb, spec/system/claims/support/claims/sampling/support_user_approves_a_claim_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_by_academic_year_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_by_provider_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_by_school_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_by_status_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_submitted_after_a_date_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_submitted_before_a_date_spec.rb, spec/system/claims/support/claims/sampling/support_user_searches_for_a_sampled_claim_using_a_reference_number_spec.rb, spec/system/claims/support/claims/sampling/support_user_views_sampled_claims_spec.rb, spec/system/claims/support/claims/sampling/upload_data/support_user_uploads_sampling_data_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_does_not_upload_a_file_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_containing_claims_not_with_the_status_sampling_in_progress_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_containing_invalid_references_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_not_containing_a_not_assured_reason_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_not_containing_all_the_mentors_associated_with_a_claim_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_not_containing_an_assured_status_for_each_mentor_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_provider_responses_for_claims_with_the_status_sampling_in_progress_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_the_wrong_file_type_as_provider_responses_spec.rb
- Update index page and show routes to match those for clawbacks:
Index:
`/support/claims/sampling/claims`
Show:
`/support/claims/sampling/claims/:claim_id`
- Visit the Sampling index and check that the URL matches the pattern above
- Visit a Sampling show page and check that the URL matches the pattern above
- Compare with clawback claims
https://trello.com/c/FA4AmkYg/1005-wire-up-remaining-sampling-logic
=> Amend show and index route for sampling claims

app/controllers/claims/support/claims/request_clawback_controller.rb, app/views/claims/support/claims/clawbacks/show.html.erb, app/views/claims/support/claims/request_clawback/edit.html.erb, app/views/wizards/claims/request_clawback_wizard/_check_your_answers_step.html.erb, app/views/wizards/claims/request_clawback_wizard/_clawback_step.html.erb, app/wizards/claims/request_clawback_wizard.rb, app/wizards/claims/request_clawback_wizard/check_your_answers_step.rb, app/wizards/claims/request_clawback_wizard/clawback_step.rb, config/locales/en/claims/support/claims.yml, config/locales/en/claims/support/claims/request_clawback.yml, config/locales/en/wizards/claims/request_clawback_wizard.yml, config/routes/claims.rb, spec/support/govuk_component_matchers.rb, spec/system/claims/support/claims/clawbacks/support_user_requests_a_clawback_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_views_clawbacks_index_spec.rb, spec/wizards/claims/request_clawback_wizard_spec.rb
Add the request clawback button to the claims show page on the clawbacks subnavigation menu. When clicking this button the user is taken to a form that request the number of hours to clawback and the reason for the clawback.
When this form is submitted the claim status is updated to “Clawback requested”.
- Sign in as "Colin"
- Click on "Claims" in the primary navigation menu
- Click on "Clawbacks" in the secondary navigation
- View show page of a claim with the status `sampling_not_approved` (tag reads "Claim not approved")
- Click "Request clawback"
- Enter required data on the "clawback details" page
- Proceed to the "confirm your answers" page and press "request clawback"
- Check that …
=> Add clawback wizard and functionality to change claim status

app/models/claims/mentor_training.rb, spec/models/claims/mentor_training_spec.rb
When this was implemented it undercover was failing and blocking the pipeline, now that it has been reverted we can re-add this validation.
[Add reason not assured validation](https://trello.com/c/ABxOVrK9/1009-add-reason-not-assured-validation)
=> Adds validation to the `not_assured_reason`

app/models/claims/mentor_training.rb, config/analytics.yml, db/migrate/20241220141331_update_mentor_trainings_for_clawbacks.rb, db/schema.rb, spec/factories/mentor_trainings.rb, spec/models/claims/mentor_training_spec.rb
Content and design changes mean that we need to update the way we model our data for clawbacks.
- Remove `hours_rejected` column from `mentor_trainings` table
- Add `hours_clawed_back` column to `mentor_trainings` table
- Add `reason_clawed_back` to column `mentor_trainings` table
- Remove `hours_rejected` validation from `Claims::MentorTraining` model
- Review the migration file.
- Run `mentor_trainings` validation tests.
https://trello.com/c/yxlrHhAt/1017-clawbacks-update-clawback-table-columns
=> Update clawback table columns

app/assets/stylesheets/components/claim/card.scss
The status tag of claims in claim cards are being stretched.
- Set `align-items` of the card header to `flex-start`.
- See screenshots.
| Before | After |
| ------ | ----- |
| ![CleanShot 2024-12-23 at 11 04 48@2x](https://github.com/user-attachments/assets/d6556df9-9859-4dda-abe8-80c31005f5bc) | ![CleanShot 2024-12-23 at 11 05 21@2x](https://github.com/user-attachments/assets/d2de69c3-1eb8-4226-8dea-6f9ae7403a74) |
=> Set claim card header css align-items to flex-start

app/helpers/claims/claim_helper.rb, app/views/claims/support/claims/samplings/show.html.erb, config/locales/en/claims/support/claims/samplings.yml, spec/helpers/claims/claim_helper_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_reason_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_marks_the_claim_as_provider_not_approved_spec.rb
- Add helper method to display the provider response on a provider rejected claim
https://trello.com/c/quUmLvF4/970-sampling-confirm-provider-rejected-claim-flow
=> Add helper for showing provider rejection reason

app/controllers/claims/sampling/claims_controller.rb, app/controllers/claims/support/claims/samplings/upload_data_controller.rb, app/jobs/claims/sampling/create_and_deliver_job.rb, app/mailers/claims/provider_mailer.rb, app/models/claims/claim_activity.rb, app/models/claims/provider_sampling.rb, app/services/claims/sampling/create_and_deliver.rb, app/services/claims/sampling/generate_csv_file.rb, app/views/claims/sampling/claims/error.html.erb, app/views/claims/sampling/claims/index.html.erb, app/wizards/claims/upload_sampling_data_wizard.rb, config/locales/en/claims/provider_mailer.yml, config/locales/en/claims/sampling/claims.yml, config/routes/claims.rb, spec/jobs/claims/sampling/create_and_deliver_job_spec.rb, spec/mailers/claims/provider_mailer_spec.rb, spec/models/claims/provider_sampling_spec.rb, spec/services/claims/sampling/create_and_deliver_spec.rb, spec/services/claims/sampling/generate_csv_file_spec.rb, spec/system/claims/sampling/claims/provider_user_downloads_sampling_csv_with_expired_token_spec.rb, spec/system/claims/sampling/claims/provider_user_downloads_sampling_csv_with_invalid_record_token_spec.rb, spec/system/claims/sampling/claims/provider_user_downloads_sampling_csv_with_invalid_token_spec.rb, spec/system/claims/sampling/claims/provider_user_downloads_sampling_csv_with_valid_token_spec.rb, spec/system/claims/support/claims/sampling/upload_data/support_user_uploads_sampling_data_spec.rb, spec/wizards/claims/upload_sampling_data_wizard_spec.rb
Now that all of the individual functionality of the sampling flow have been implemented we needed to tie them all together so that the correct processes happen after a support user has uploaded the sampling CSV.
[[Sampling] Create CreateAndDeliver service
](https://trello.com/c/7A8uP8OT/987-sampling-create-createanddeliver-service)
=> Create sampling send and deliver

app/controllers/claims/support/claims/clawbacks_controller.rb, app/policies/claims/support/claims/claim_policy.rb, app/policies/claims/support/claims/clawback_policy.rb, app/policies/claims/support/claims/clawbacks/claim_policy.rb, app/views/claims/support/claims/clawbacks/index.html.erb, app/views/claims/support/claims/clawbacks/new.html.erb, app/views/claims/support/claims/clawbacks/new_not_permitted.html.erb, config/locales/en/claims/support/claims/clawbacks.yml, config/routes/claims.rb, spec/policies/claims/support/claims/clawback_policy_spec.rb, spec/system/claims/support/claims/clawbacks/send_to_esfa/support_user_can_not_send_claims_to_esfa_spec.rb, spec/system/claims/support/claims/clawbacks/send_to_esfa/support_user_sends_claims_to_esfa_spec.rb
- Add interface for Support Users to send "Clawback requested" claims to ESFA
- Add views/controllers/etc. to allow Support Users the ability to send "Clawback requested" claims to ESFA
- Navigate to the Claims/Clawbacks using the Navbar and Secondary Navbar.
------
(When a claim exists with the status "Clawback requested")
- Click "Send claims to ESFA"
- Review the number of claims being sent to the ESFA
- Click "Send claims"
- You should see that you have successfully sent claims to the ESFA
--------
(When no claims exist with the status "Clawback requested)
- Click "Send claims to ESFA"
- You should see that "There are no claims to send for clawback"
https://trello.com/c/TZMeAwcx/1015-clawbacks-send-claims-to-esfa-functionality …
=> Send clawbacks to ESFA

app/views/claims/support/claims/payments/index.html.erb, app/views/claims/support/claims/samplings/_upload_buttons.html.erb, app/views/claims/support/claims/samplings/index.html.erb, config/locales/en/claims/support/claims/samplings.yml
- Fix issue with filters not appearing on the claims index pages when there are no results.
- Refactor code so that the filters still show, even when no results are found.
- Navigate to Claims using the Navbar
- Check each index sub page with no claims.
- The filters should appear on each page, despite there not being any claim results.
https://trello.com/c/D0Tj7nGT/335-show-filters-when-there-are-no-search-results
=> Fix filters show on claims index pages

app/models/claims/claim_activity.rb, app/views/claims/support/claims/claim_activities/index.html.erb, spec/models/claims/claim_activity_spec.rb
- Claim Activity records require an action, otherwise the activity log page breaks. Currently this is not validated.
- Add validation to `Claims::ClaimActivity` to ensure `action` is present.
(Assuming you have a number of `Claims::ClaimActivity` records in your database.
- Navigate to Claims -> Activity log in the nav bar.
- The page should not break whether or not you have a `csv_file` attached to the record.
_In the rails console_
- Try to create a `Claims::ClaimActivity` record without an `action`
- It should error due to the validation.
https://trello.com/c/viXc3m6A/338-fix-activity-log-when-csv-files-are-not-present
=> Validate presence of action in activity log and conditionally show CSV

app/models/claims/clawback.rb, app/models/claims/payment.rb, app/models/claims/payment_response.rb, app/models/claims/provider_sampling.rb, config/analytics.yml, db/migrate/20250108210737_add_downloaded_at_to_clawbacks.rb, db/migrate/20250108211108_add_downloaded_at_to_payment_responses.rb, db/migrate/20250108211304_add_downloaded_at_to_payments.rb, db/migrate/20250108211418_add_downloaded_at_to_provider_samplings.rb, db/schema.rb, spec/factories/claims/payment_responses.rb, spec/factories/claims/payments.rb, spec/factories/claims/provider_samplings.rb, spec/factories/clawbacks.rb, spec/models/claims/clawback_spec.rb, spec/models/claims/payment_response_spec.rb, spec/models/claims/payment_spec.rb, spec/models/claims/provider_sampling_spec.rb
- Add `downloaded_at` to models containing `csv_file` attachments.
- Add `downloaded_at` columns to:
- Claims::Clawback
- Claims::Payment
- Claims::PaymentResponse
- Claims::ProviderSampling
https://trello.com/c/pzSI6C8H/343-add-downloadedat-column-to-tables-with-csv-files
=> Add downloaded_at to models with csv_file attachments

app/controllers/claims/clawback/claims_controller.rb, app/controllers/claims/payments/claims_controller.rb, app/controllers/claims/sampling/claims_controller.rb, app/models/claims/clawback.rb, app/models/claims/payment.rb, app/models/claims/payment_response.rb, app/models/claims/provider_sampling.rb, spec/models/claims/clawback_spec.rb, spec/models/claims/payment_response_spec.rb, spec/models/claims/payment_spec.rb, spec/models/claims/provider_sampling_spec.rb, spec/system/claims/clawback/claims/esfa_user_downloads_a_clawback_which_has_already_been_downloaded_spec.rb, spec/system/claims/clawback/claims/esfa_user_downloads_clawback_csv_with_valid_token_spec.rb, spec/system/claims/payments/claims/download_claims_spec.rb, spec/system/claims/payments/claims/esfa_user_downloads_a_payment_spec.rb, spec/system/claims/sampling/claims/provider_user_downloads_sampling_csv_which_has_already_been_downloaded_spec.rb, spec/system/claims/sampling/claims/provider_user_downloads_sampling_csv_with_valid_token_spec.rb
- Users can only download CSV files once.
- When a user downloads a CSV, it assigns the time to the downloaded attribute.
- Test that the CSV links with tokens can only be downloaded once.
https://trello.com/c/6s7As2KA/346-only-allow-csvs-to-be-downloaded-once
=> Download only once

app/wizards/claims/request_clawback_wizard/mentor_training_clawback_step.rb, spec/wizards/claims/request_clawback_wizard/mentor_training_clawback_step_spec.rb
The number of hours for clawbacks must be greater than 0
- Request a clawback
- Enter 0 in Number of hours
- See the validation error
[Request clawback accepts 0 hours](https://trello.com/c/BaJbe25Q/348-request-clawback-accepts-0-hours)
=> Add validation for number of hours - must be greater than 0

config/locales/en/wizards/claims/provider_rejected_claim_wizard.yml, config/locales/en/wizards/claims/reject_claim_wizard.yml, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_mentor_who_is_being_rejected_by_the_provider_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_reason_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_does_not_enter_a_reason_why_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_marks_the_claim_as_provider_not_approved_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_changes_the_reason_the_school_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_does_not_enter_a_reason_why_the_school_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_marks_the_claim_as_rejected_spec.rb
The [square brackets] from the copy were mistakenly copied into the build.
- Manually reject a claim from a provider that has been requested for sampling
- Check for any instances of square brackets
- Manually reject a claim from a school that has been requested for sampling
- Check for any instances of square brackets
[Remove [square brackets] from mentor name
](https://trello.com/c/CR53Q1fB/350-remove-square-brackets-from-mentor-name)
=> Remove square brackets from mentor names

app/models/provider.rb, app/models/provider_email_address.rb, app/services/publish_teacher_training/provider/importer.rb, config/analytics.yml, db/migrate/20250114120009_create_provider_email_addresses.rb, db/migrate/20250114161953_migrate_provider_email_addresses.rb, db/schema.rb, spec/factories/provider_email_addresses.rb, spec/models/provider_email_address_spec.rb, spec/models/provider_spec.rb, spec/services/publish_teacher_training/provider/importer_spec.rb
- Migrate provider emails to new ProviderEmailAddress records
- Add model ProviderEmailAddress
- Change provider importer to create ProviderEmailAddress records
- run migrations
- ProviderEmailAddress table is added
- Provider emails are migrated to ProviderEmailAddress records
-------
- run `bundle exec rake db:drop db:create db:setup`
- Seed should use the import and create ProviderEmailAddress records
https://trello.com/c/FbmyXt7z/345-allow-providers-to-have-multiple-email-addresses
=> Migrate provider emails to ProviderEmailAddress records

.github/workflows/build_and_deploy.yml, .github/workflows/build_and_test.yml, .github/workflows/database-backup.yml, .github/workflows/delete_review_app.yml, .github/workflows/deploy.yml, .github/workflows/disable-maintenance.yml, .github/workflows/enable-maintenance.yml, .github/workflows/maintenance.yml, .github/workflows/postgres-ptr.yml, .github/workflows/postgres-restore.yml, .github/workflows/pull_request.yml
We've been having an array of failures related to our build pipelines and deployments. @saliceti has identified that the latest version of ubuntu is likely the culprit.
=> Pin ubuntu-22.04 for github workflows

db/seeds.rb
- Add `submitted` and `paid` claims to seed data
- Add code and methods to create `submitted` and `paid` claims for each school ( and provider ) within the seed data.
- run `bundle exec rake db:drop db:create db:setup`
- This should result in creating both `submitted` and `paid` claims.
https://trello.com/c/Tlf4e2qH/365-add-seeds-to-populate-claims-in-staging-and-local-environments
=> Extend seed data

app/views/claims/support/claims/samplings/show.html.erb, spec/system/claims/support/claims/sampling/mark_provider_rejected_claim_as_approved/support_user_approves_a_provider_rejected_sampling_claim_spec.rb
- Create an 'approve claim' button for a claim with the status of `sampling_provider_not_approved`
- Extend the functionality that exists for 'approve claim' for those with a status of `sampling_in_progress` which converts the status of `paid` once the support user has confirmed approval.
- Navigate to the claims > sampling index
- Click on a claim with the status "Provider not approved"
- View the show page and verify that an "Approve claim" button exists
- Click "Approve claim" and view the confirmation page
- Click "Approve claim" on this page
- Check that the claim no longer appears in the sampling index
- Check that the claim can be found in the "All claims" index …
=> Add approve claim button to provider rejected sampling claim

app/components/claim/status_tag_component.rb, spec/components/claim/status_tag_component_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_requests_a_clawback_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_views_clawbacks_index_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_mentor_who_is_being_rejected_by_the_provider_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_reason_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_does_not_enter_a_reason_why_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_does_not_select_any_mentors_rejected_by_the_provider_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_marks_the_claim_as_provider_not_approved_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_changes_the_reason_the_school_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_does_not_enter_a_reason_why_the_school_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_marks_the_claim_as_rejected_spec.rb, spec/system/claims/support/claims/sampling/support_user_approves_a_claim_spec.rb
We have decided to update the status labels to improve the understanding for support users
Update the Claim status labels to match the latest content changes:
Status: draft
Label: “Draft”
Tag colour: govuk-tag--yellow
status: submitted
Label “Submitted”
Tag colour: govuk-tag--turquoise
status: paid
Label “Paid”
Tag colour: govuk-tag--blue
status: payment_in_progress
Label “Payer payment review”
Tag colour: govuk-tag--yellow
status: payment_information_requested
Label “Payer needs information”
Tag colour: govuk-tag--turquoise
status: payment_information_sent
Label “Information sent to payer”
Tag colour: govuk-tag--yellow
status: payment_not_approved
Label “Rejected by payer”
Tag colour: govuk-tag--orange
status: sampling_in_progress
Label "Audit requested"
Tag colour: govuk-tag--yellow …
=> Update status colour tags according to latest designs

app/models/claims/claim.rb, app/policies/claims/claim_policy.rb, app/policies/claims/support/claim_policy.rb, spec/models/claims/claim_spec.rb, spec/policies/claims/claim_policy_spec.rb, spec/policies/claims/support/claim_policy_spec.rb
- Improve claims policies to prevent `Claims` being changed after they have been submitted.
- Add a `in_draft?` method to determine whether or not a claim is in `draft` or `internal_draft` status.
- Amend polices to use the `in_draft?` method.
- View the show page for claims in each status to make sure the change links only show for claims in the `draft` or `internal draft` status.
https://trello.com/c/Sl3Sqzod/351-claims-should-not-be-editable-after-being-submitted
_Internal draft_
_Draft_
_Submitted_
_Payment in progress_
_Paid_
_Sampling in progress_
_Provider not approved_
_Claim not approved_
_Clawback requested_
_Clawback in progress_
_Clawback complete_
=> Improve policies to prevent claims being changed after being submitted

spec/system/claims/support/claims/sampling/mark_provider_rejected_claim_as_approved/support_user_approves_a_provider_rejected_sampling_claim_spec.rb, spec/system/claims/support/claims/sampling/support_user_approves_a_claim_spec.rb
Update failing tests to match recent merged changes to status tag designs.
- Update specs expecting `provider_not_approved` to be pink. This is now turquoise.
- Update specs expecting `paid` to be green. This is now blue.
- Check that all specs are passing.
=> Update colour tags in failing specs

app/models/claims/training_allowance.rb, spec/models/claims/training_allowance_spec.rb
- Fix issue with Training Allowance only considering "Draft" and "Submitted" claims
- Change Training Allowance only considering "Draft" and "Submitted" claims
=> Fix training allowance to include more than just draft and submitted claims

app/mailers/claims/provider_mailer.rb, config/locales/en/claims/provider_mailer.yml, spec/mailers/claims/provider_mailer_spec.rb, spec/mailers/previews/claims/provider_mailer_preview.rb
- Changes to the email sent to Providers to get their response to sampling.
- Update the content of the email sent to Providers, in order to get their response to sampling, to match https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B82A70CE3-9BE3-42EC-A626-A7627B0FA211%7D&file=Provider%20quality%20assurance%20email%20-%20selected%20for%20sampling%20-%20January%202025.docx&action=default&mobileredirect=true
- Navigate to Settings -> Emails
- Click "sampling_checks_required (opens in new tab)
- Review the content
https://trello.com/c/aXHiohRq/357-update-sampling-email-content
https://github.com/user-attachments/assets/de325618-f849-41b2-9294-8dda36d88c2a
=> Changes to provider response request mailer

config/analytics.yml, config/analytics_blocklist.yml
We require these fields for tracking purposes
- Remove `mentors` table `id`, `created_at` and `updated` at from blocklist.
-  Add `mentors` table `id`, `created_at` and `updated` to analytics
Ensure that the added fields match the listed fields and that tests pass.
=> Add mentor columns to analytics

terraform/application/outputs.tf
Use ittms deployments as smoke test for the AKS platform deployment.
Currently failing: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/12890121135/job/35938967409
Use the new URL output format defined in the template
- make review terraform-init PR_NUMBER=1335
- terraform -chdir=terraform/application output external_urls
https://trello.com/c/F9hmE3if
=> [2151] Output terraform external urls

config/locales/en/activerecord.yml, spec/components/claim/status_tag_component_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_filters_clawback_claims_by_status_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_requests_a_clawback_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_views_clawbacks_index_spec.rb, spec/system/claims/support/claims/payments/reject_claim_payment_spec.rb, spec/system/claims/support/claims/payments/view_a_claim_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_mentor_who_is_being_rejected_by_the_provider_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_reason_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_does_not_enter_a_reason_why_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_does_not_select_any_mentors_rejected_by_the_provider_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_marks_the_claim_as_provider_not_approved_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_changes_the_reason_the_school_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_does_not_enter_a_reason_why_the_school_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_marks_the_claim_as_rejected_spec.rb, spec/system/claims/support/claims/sampling/mark_provider_rejected_claim_as_approved/support_user_approves_a_provider_rejected_sampling_claim_spec.rb, spec/system/claims/support/claims/sampling/support_user_approves_a_claim_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_by_status_spec.rb
Update status label names in line with latest designs.
Status labels updated to reflect new wording:
Status: draft
Label: “Draft”
status: submitted
Label “Submitted”
status: paid
Label “Paid”
status: payment_in_progress
Label “Payer payment review”
status: payment_information_requested
Label “Payer needs information”
status: payment_information_sent
Label “Information sent to payer”
status: payment_not_approved
Label “Rejected by payer”
status: sampling_in_progress
Label "Audit requested"
status: sampling_provider_not_approved
Label "Rejected by provider"
status: sampling_not_approved
Label "Rejected by school"
status: clawback_requested
Label "Ready for clawback"
status: clawback_in_progress
Label "Sent to payer for clawback"
status: clawback_complete
Label "Clawback complete"
Please …
=> Update status labels in line with latest designs

.github/workflows/build_and_deploy.yml
adding workflows for domain deployment to build workflows 
this is the updated build_and_deploy.yml adding calls to the deploy domains github actions. 
review the actions to see the workflows being running. 
review code and decide on best architecture
can see test runs for jobs added to  build_and_deploy.yml  run as separate test runs but doing plan not apply
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/12829975027
https://github.com/DFE-Digital/itt-mentor-services/actions/runs/12829975022 (this only fails because plan doesn't see output variable like apply so will success for appply)
[Implement CI/CD for domains on all services](https://trello.com/c/unElJf6I/2168-implement-ci-cd-for-domains-on-all-services)
=> CI-CD for domains

terraform/domains/environment_domains/output.tf
run domain environments always showing production urls
change to show urls or the environment 
tested on workstation 
`make qa domains-plan`
and shows 
Changes to Outputs:
```
~ external_urls = [
+ "https://qa.claim-funding-for-mentor-training.education.gov.uk",
+ "https://qa.manage-school-placements.education.gov.uk",
]
```
[Implement CI/CD for domains on all services](https://trello.com/c/unElJf6I/2168-implement-ci-cd-for-domains-on-all-services)
=> fix host zones to be for each domain environment 

terraform/application/config/dv_review.tfvars.json, terraform/application/config/pt_review.tfvars.json, terraform/application/config/review.tfvars.json, terraform/application/database.tf, terraform/application/variables.tf
Allow db schema load on review apps instead of running all migrations
Do not create the database in review to force rails to create it and load schema via db:prepare
Check review app
=> Make database creation optional

app/components/claims/claim/mentors_form/disclaimer_component.rb, app/views/claims/schools/claims/index.html.erb, app/views/claims/schools/claims/mentors/_form.html.erb, config/locales/en.yml, config/locales/en/claims/schools/claims.yml, config/locales/en/components/claims/claim/mentors_form/disclaimer_component.yml, spec/components/claims/claim/mentors_form/disclaimer_component_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb
The inset text was use incorrectly under the design system guidelines, we have updated to the text be in more semantically correct containers.
- Review the guidance on the claims index page
- Add a claim for a mentor with 20 hours
- Add a second claim and review details text
[Change inset text on claims homepage school user](https://trello.com/c/BmbYCCqx/384-change-inset-text-on-claims-homepage-school-user)
[Change inset text on Mentors page during add claim flow (school user)
](https://trello.com/c/vkRmDeDF/383-change-inset-text-on-mentors-page-during-add-claim-flow-school-user)
=> Update inset text

app/views/wizards/claims/upload_esfa_clawback_response_wizard/_confirmation_step.html.erb, app/views/wizards/claims/upload_payer_payment_response_wizard/_confirmation_step.html.erb, app/views/wizards/claims/upload_provider_response_wizard/_confirmation_step.html.erb, config/locales/en/wizards/claims/reject_claim_wizard.yml, config/locales/en/wizards/claims/upload_provider_response_wizard.yml, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_changes_the_reason_the_school_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_rejected/support_user_marks_the_claim_as_rejected_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_containing_claims_not_with_the_status_sampling_in_progress_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_containing_invalid_references_spec.rb
- Small text changes and limit CSV display to 5 rows.
https://trello.com/c/j4OHflJa/395-limit-number-of-csv-rows-when-uploading
https://www.figma.com/design/2dHqnhuBuiUNO4LNAGK5UG/Track-and-pay---Claim-funding-for-mentor-training?t=lf7E0BZN7BVSGH07-0
=> Bug fixes for things seen in user guide screenshot creation

app/views/wizards/claims/upload_esfa_clawback_response_wizard/_confirmation_step.html.erb, app/views/wizards/claims/upload_esfa_clawback_response_wizard/_upload_step.html.erb, app/views/wizards/claims/upload_payer_payment_response_wizard/_confirmation_step.html.erb, app/views/wizards/claims/upload_payer_payment_response_wizard/_upload_step.html.erb, app/views/wizards/claims/upload_provider_response_wizard/_confirmation_step.html.erb, app/views/wizards/claims/upload_provider_response_wizard/_upload_step.html.erb, config/locales/en/wizards/claims/upload_esfa_clawback_response_wizard.yml, config/locales/en/wizards/claims/upload_payer_payment_response_wizard.yml, config/locales/en/wizards/claims/upload_provider_response_wizard.yml, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_provider_responses_for_claims_with_the_status_sampling_in_progress_spec.rb
- Small changes to the claims CSV upload wizards.
=> Content changes to claim csv upload steps

app/controllers/claims/support/claims/payments_controller.rb, app/views/claims/support/claims/payments/_action_calculator.html.erb, app/views/claims/support/claims/payments/index.html.erb, config/locales/en/claims/support/claims/payments.yml, spec/system/claims/support/claims/payments/view_payments_claims_spec.rb
- Add actions calculator to the Payments index page.
- Add helper methods to calculate the number of claims in each stage of the payments process.
- Add view to show a helpful message regarding steps to take in the payments process.
https://trello.com/c/WGWUILGW/405-add-action-calculator-to-payments-page
=> Add actions calculator to the payments index

app/views/wizards/claims/provider_rejected_claim_wizard/_check_your_answers_step.html.erb, config/locales/en/wizards/claims/provider_rejected_claim_wizard.yml, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_mentor_who_is_being_rejected_by_the_provider_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_changes_the_reason_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_does_not_enter_a_reason_why_the_provider_rejected_the_mentor_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_does_not_select_any_mentors_rejected_by_the_provider_spec.rb, spec/system/claims/support/claims/sampling/mark_claim_as_provider_not_approved/support_user_marks_the_claim_as_provider_not_approved_spec.rb
We don't display the mentor names on the check your answers page for the provider rejection journey.
- Upload a claim to be audited
- Reject the claim
- Assert the the mentor headings in the check your answers page include their names
[Update rejected by provider copy](https://trello.com/c/hpcg3yQi/409-update-rejected-by-provider-copy)
=> Update provider mentor headers

app/controllers/placements/providers/placements_controller.rb, app/forms/placements/placements/filter_form.rb, app/queries/placements/placements_query.rb, app/views/placements/providers/placements/_filter.html.erb, config/locales/en/placements/providers/placements.yml, spec/forms/placements/placements/filter_form_spec.rb, spec/system/placements/providers/placements/provider_user_filters_placements_by_phase_spec.rb
This design change allows provider users to find placements in Primary or Secondary more easily.
- Add a phase filter option to the filter menu on the placements index.
- Add an accompanying filter tag when a phase filter is selected.
- Add functionality that changes other filter options depending on whether a phase filter has been selected (see expected behaviour below).
- Add system spec for new phase filter.
- Update filter form spec to include tests for expected phase filter behaviour.
- Toggle the phase filter options and test it against the below expected behaviour.
- Review new system spec and changes to filter form spec.
Same behaviour as when no checkboxes are selected (default state) ☝️
https://trello.com/c/oCkrtGGU/951-add-a-phase-filter-to-placements-search …
=> Add phase filter to placements search

config/locales/en/claims/support/claims/clawbacks/upload_esfa_response.yml, config/locales/en/claims/support/claims/samplings.yml, config/locales/en/claims/support/claims/samplings/upload_provider_response.yml, spec/system/claims/support/claims/clawbacks/upload_esfa_response/support_user_uploads_esfa_responses_for_claims_with_the_status_clawback_in_progress_spec.rb, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_provider_responses_for_claims_with_the_status_sampling_in_progress_spec.rb
It was not clear that the user needed to refresh the page to see updated claims
- Take a claim through the entire flow from payments to clawback
- Check that the success messages ask you to refresh the page after uploading a file
[Update upload success messages](https://trello.com/c/UaYxxVPo/413-update-upload-success-messages)
=> Update the success messages for uploading a CSV file

app/services/claims/sampling/create_and_deliver.rb, spec/services/claims/sampling/create_and_deliver_spec.rb
The data passed to `Claims::Sampling::CreateAndDeliver` is `{id:, sampling_reason:}`
See `app/wizards/claims/upload_sampling_data_wizard.rb`:
```
def claim_update_details
return [] if steps[:upload].blank?
csv_rows.map do |row|
claim = paid_claims.find_by!(reference: row["claim_reference"])
{
id: claim.id,
sampling_reason: row["sample_reason"],
}
end
end
```
- Fix for sampling reason being added to claims.
=> Fix for sampling reason

spec/mailers/previews/claims/esfa_mailer_preview.rb, spec/mailers/previews/claims/payment_mailer_preview.rb, spec/mailers/previews/claims/provider_mailer_preview.rb, spec/mailers/previews/claims/support_user_mailer_preview.rb, spec/mailers/previews/claims/user_mailer_preview.rb, spec/mailers/previews/placements/provider_user_mailer_preview.rb, spec/mailers/previews/placements/school_user_mailer_preview.rb, spec/mailers/previews/placements/support_user_mailer_preview.rb
- Fix all mailer previews.
- Previews should not use or rely on real data. 
- Change previews to use stubbed records.
- Navigate to Settings -> Emails
- Test all Email previews show without error
https://ukgovernmentdfe.slack.com/archives/C085GP37FPA/p1739891736255579
=> Fix all mailer previews

app/models/claims/claim.rb, app/views/wizards/claims/request_clawback_wizard/_check_your_answers_step.html.erb, config/locales/en/wizards/claims/request_clawback_wizard.yml, spec/models/claims/claim_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_requests_a_clawback_spec.rb
User research showed that there was a desire to see the original claim amount when requesting a clawback.
- Take a claim through to clawback
- Request a clawback
- Verify the information on the Check your answers step.
[Update clawbacks check your answers page](https://trello.com/c/e9wybGbW/415-update-clawbacks-check-your-answers-page)
=> Add total hours to clawback flow

spec/mailers/previews/claims/esfa_mailer_preview.rb, spec/mailers/previews/claims/payment_mailer_preview.rb, spec/mailers/previews/claims/provider_mailer_preview.rb, spec/mailers/previews/claims/support_user_mailer_preview.rb, spec/mailers/previews/claims/user_mailer_preview.rb, spec/mailers/previews/placements/provider_user_mailer_preview.rb, spec/mailers/previews/placements/school_user_mailer_preview.rb, spec/mailers/previews/placements/support_user_mailer_preview.rb
- Fix for mailer previews
- Mailer previews now us initialised records, instead of FactoryBot
=> Mailer previews use intialised records

app/views/wizards/claims/add_claim_wizard/_mentor_step.html.erb
The mentor disclaimer was incorrectly positioned on the "Add mentor" step for the add claim wizard.
- Add a placement
- Observe the location of the mentor disclaimer
[Move location of mentor disclaimer
](https://trello.com/c/eyYOGxEj/429-move-location-of-mentor-disclaimer)
=> Move mentor disclaimer to below checkboxes for adding a claim

app/mailers/claims/user_mailer.rb, app/wizards/claims/request_clawback_wizard.rb, config/locales/en/claims/user_mailer.yml, spec/mailers/claims/user_mailer_spec.rb, spec/mailers/previews/claims/user_mailer_preview.rb, spec/wizards/claims/request_clawback_wizard_spec.rb
- Content changes to the `Claims::UserMailer.claim_requires_clawback` mailer.
- Make content changes to the `Claims::UserMailer.claim_requires_clawback` mailer.
- Add code to trigger the `Claims::UserMailer.claim_requires_clawback` in the `Claims::RequestClawbackWizard`
- Navigate to Settings
- Click "Emails"
- Click "User Mailer" -> "claim_requires_clawback (opens in new tab)"
- Preview the content changes
https://trello.com/c/pl1BUzIb/425-update-clawback-email-to-schools
=> Copy change to the Clawback requested mailer

app/wizards/claims/upload_provider_response_wizard/upload_step.rb, spec/wizards/claims/upload_provider_response_wizard/upload_step_spec.rb
- Entering "Yes" causes an error when uploading a provider response.
- Audit some claims
- Upload a provider response with mixed case for the assured status, e.g. "YeS, TRUE, FAlse, No" and check that it works.
["Yes" in an invalid input for uploading provider response](https://trello.com/c/y8f8CNAV/431-yes-in-an-invalid-input-for-uploading-provider-response)
=> "Yes" in an invalid input for uploading provider response

app/decorators/organisation_decorator.rb, app/models/claims/provider.rb, app/models/placements/provider.rb, app/models/provider.rb, app/queries/provider_query.rb, app/services/publish_teacher_training/provider/importer.rb, app/views/wizards/placements/multi_placement_wizard/_help_step.html.erb, app/wizards/placements/multi_placement_wizard/help_step.rb, config/analytics_blocklist.yml, config/locales/en/wizards/placements/multi_placement_wizard.yml, db/migrate/20250226133003_add_longitude_and_latitude_to_providers.rb, db/schema.rb, spec/decorators/provider_decorator_spec.rb, spec/factories/providers.rb, spec/models/claims/provider_spec.rb, spec/models/placements/provider_spec.rb, spec/models/provider_spec.rb, spec/queries/provider_query_spec.rb, spec/services/publish_teacher_training/provider/importer_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_views_their_local_providers_spec.rb, spec/wizards/placements/multi_placement_wizard/help_step_spec.rb
- Add geocoding to Providers
- Geocoding added to providers
- Local providers added to the MultiPlacementWizard HelpStep
⚠️ You will need to enable the ":bulk_add_placements" flag ⚠️
- Choose "Not open to hosting placements"
- Follow the rest of the journey, until you reach the help page.
- You should be able to see the 2 closest providers to the school
https://trello.com/c/IMtlJJb2/442-add-geocoding-to-providers
=> Add geocoding to Providers

config/analytics.yml, config/analytics_blocklist.yml, config/analytics_hidden_pii.yml
We want to track the `trn` for analytics
- Check that tests pass
- Confirm that the specified field has been moved correctly
[Move TRN to PII list](https://trello.com/c/n1me3SsA/440-move-trn-to-pii-list)
=> Move the `mentors` `trn` column to analytics_hidden_pii.yml

app/wizards/placements/multi_placement_wizard.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_does_not_enter_any_school_contact_details_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_no_and_completes_the_interested_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_yes_and_completes_the_interested_journey_spec.rb, spec/wizards/placements/multi_placement_wizard_spec.rb
- Join the `actively_looking_steps` to the `interested` path when selecting "Yes" when asked to list placements.
- Add steps `actively_looking_steps` when "Yes" is selected on the List placements step.
⚠️ You will need to enable the ":bulk_add_placements" flag ⚠️
- Choose "Interested in hosting placements"
- Follow the rest of the journey - Pick "Yes" when asked "Would you like to list some placements to be seen by providers?"
- Follow the rest of the journey to create placements
- This should result in creating/updating your school's HostingInterest for next year
- This should result in any changes made to the school contact
- This should result in creating any placements set in the journey …
=> Connect the interested path to the actively looking steps

app/views/wizards/placements/multi_placement_wizard/_provider_step.html.erb, app/wizards/placements/multi_placement_wizard.rb, app/wizards/placements/multi_placement_wizard/provider_step.rb, config/locales/en/wizards/placements/multi_placement_wizard.yml, db/seeds.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_bulk_adds_placements_for_the_primary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_all_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_specific_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_successfully_completes_the_actively_looking_journey_without_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_a_subject_with_child_subjects_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_yes_and_completes_the_interested_journey_spec.rb, spec/wizards/placements/multi_placement_wizard/provider_step_spec.rb, spec/wizards/placements/multi_placement_wizard_spec.rb
- Add provider step to the `actively_looking` journey of the MultiPlacementWizard
- Add provider step and related views to the `actively_looking` journey of the MultiPlacementWizard
⚠️ You will need to enable the ":bulk_add_placements" flag ⚠️
- Choose "Interested in hosting placements"
- Follow the rest of the journey - You should now see the providers step (assuming you have providers with the name "Test Provider [0-9]"
- This should result in creating/updating your school's HostingInterest for next year
- This should result in any changes made to the school contact
- This should result in creating any placements set in the journey
- This should result in creating any partnerships between providers …
=> Add provider page to actively look path

app/wizards/placements/multi_placement_wizard/appetite_step.rb, config/locales/en/wizards/placements/multi_placement_wizard.yml, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_bulk_adds_placements_for_the_primary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_does_not_enter_a_placement_quantity_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_does_not_select_a_subject_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_enters_a_float_as_a_placement_quantity_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_enters_zero_as_a_placement_quantity_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_does_not_select_a_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_does_not_select_if_the_subjects_are_known_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_successfully_completes_the_actively_looking_journey_without_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_a_subject_with_child_subjects_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_the_secondary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_does_not_enter_a_placement_quantity_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_does_not_select_a_child_subject_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_does_not_select_a_subject_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_enters_a_float_as_a_placement_quantity_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_enters_zero_as_a_placement_quantity_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_does_not_enter_a_response_for_listing_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_does_not_enter_any_school_contact_details_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_no_and_completes_the_interested_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_yes_and_completes_the_interested_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_does_not_enter_any_school_contact_details_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_does_not_select_any_reasons_not_to_host_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_views_their_local_providers_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/school_user_does_not_select_an_appetite_spec.rb, spec/wizards/placements/multi_placement_wizard/appetite_step_spec.rb
- Content changes to the Appetite step of the MultiPlacementWizard
https://trello.com/c/R9RrkEEs/462-content-changes-for-appetite-step-of-multiplacementwizard
=> Content changes on appetite step

app/views/wizards/placements/multi_placement_wizard/_check_your_answers_step.html.erb, app/wizards/placements/multi_placement_wizard.rb, app/wizards/placements/multi_placement_wizard/check_your_answers_step.rb, config/locales/en/wizards/placements/multi_placement_wizard.yml, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_bulk_adds_placements_for_the_primary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_all_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_specific_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_successfully_completes_the_actively_looking_journey_without_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_a_subject_with_child_subjects_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_the_secondary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_yes_and_completes_the_interested_journey_spec.rb, spec/wizards/placements/multi_placement_wizard/check_your_answers_step_spec.rb, spec/wizards/placements/multi_placement_wizard_spec.rb
- Add Check your answers step to MultiPlacementWizard
- Add Check your answers step and views to MultiPlacementWizard
⚠️ You will need to enable the ":bulk_add_placements" flag ⚠️
- Choose "Interested in hosting placements"
- Follow the rest of the journey - You should now see the check your answers step
- This should result in creating/updating your school's HostingInterest for next year
- This should result in any changes made to the school contact
- This should result in creating any placements set in the journey
- This should result in creating any partnerships between providers you selected
https://trello.com/c/Elwp022x/463-check-your-answers-page-for-multiplacementwizard
=> Add check your answers to multiplacementwizard

app/controllers/placements/schools/placements/add_multiple_placements_controller.rb, config/locales/en/placements/schools/placements.yml, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/primary_phase_only/school_user_bulk_adds_placements_for_the_primary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_all_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_selects_specific_providers_when_bulk_adding_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/school_user_successfully_completes_the_actively_looking_journey_without_placements_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_a_subject_with_child_subjects_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_actively_looking/secondary_phase_only/school_user_bulk_adds_placements_for_the_secondary_phase_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_no_and_completes_the_interested_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_interested/school_user_selects_yes_and_completes_the_interested_journey_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb
- Content changes to the MultikPlacementWizard success message
https://trello.com/c/KWmzEFGm/464-update-success-message-for-multiplacementwizard
=> content changes to success message

app/views/wizards/claims/upload_sampling_data_wizard/_confirmation_step.html.erb, config/locales/en/wizards/claims/upload_sampling_data_wizard.yml
- Sampling/Auditing CSV upload page show "Only showing the first 5 rows"
- Sampling/Auditing CSV upload page show "Only showing the first 5 rows"
- https://trello.com/c/f9PvAZIs/466-row-count-when-uploading-csv-is-incorrect
=> Fix row count on claims sampling csv upload

adr/00010-onboarding-claims-schools.md
We need a way to "onboard" schools in the Claim funding service for each new academic year to make sure that they are eligible to claim.
- Adds a new ADR
- Review the content of the ADR
[Create claims onboarding ADR](https://trello.com/c/kVP7BiSR/472-create-claims-onboarding-adr)
=> Create onboarding claims schools ADR

app/models/placements/hosting_interest.rb, app/views/wizards/placements/multi_placement_wizard/_reason_not_hosting_step.html.erb, app/wizards/placements/multi_placement_wizard.rb, app/wizards/placements/multi_placement_wizard/reason_not_hosting_step.rb, config/analytics_blocklist.yml, config/locales/en/activemodel.yml, db/migrate/20250310101224_add_other_reason_not_hosting_to_hosting_interests.rb, db/schema.rb, spec/factories/hosting_interests.rb, spec/models/placements/hosting_interest_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_does_not_enter_a_reason_when_selecting_other_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/appetite_not_open/school_user_enters_another_reason_why_they_are_not_hosting_spec.rb, spec/wizards/placements/multi_placement_wizard/reason_not_hosting_step_spec.rb
- Make changes so the "Other" reason why the user is not hosting can be stored on the HostingInterest
- Migration to add `other_reason_not_hosting` column to `hosting_interests`
- Change name of input text_field to `other_reason_not_hosting`
- Choose "No - Let providers know I am not hosting and do not want to be contacted"
- Check "Other" and enter a reason
- Continue with the journey
=> Store other_reason_not_hosting in hosting interest

app/views/claims/schools/claims/index.html.erb, app/views/claims/schools/claims/show.html.erb, app/views/claims/support/claims/_details.html.erb, app/views/claims/support/schools/claims/index.html.erb, app/views/wizards/claims/add_claim_wizard/_mentor_training_step.html.erb, app/views/wizards/claims/add_claim_wizard/_provider_options_step.html.erb, app/views/wizards/claims/add_claim_wizard/_provider_step.html.erb, app/wizards/claims/add_claim_wizard.rb, app/wizards/claims/add_claim_wizard/provider_options_step.rb, app/wizards/claims/add_claim_wizard/provider_selection_step.rb, app/wizards/claims/add_claim_wizard/provider_step.rb, app/wizards/claims/edit_claim_wizard.rb, config/locales/en/activemodel.yml, config/locales/en/wizards/claims/add_claim_wizard.yml, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/schools/claims/edit_draft_claim_spec.rb, spec/system/claims/schools/claims/school_user_creates_a_claim_with_javascript_disabled_spec.rb, spec/system/claims/support/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/support/schools/claims/create_claim_spec.rb, spec/system/claims/support/schools/claims/edit_draft_claim_spec.rb, spec/system/claims/support/schools/claims/support_user_creates_a_claim_with_javascript_spec.rb, spec/wizards/claims/add_claim_wizard/provider_options_step_spec.rb, spec/wizards/claims/add_claim_wizard/provider_selection_step_spec.rb, spec/wizards/claims/add_claim_wizard_spec.rb, spec/wizards/claims/edit_claim_wizard_spec.rb
- Add provider search as part of the Claim Wizard.
- Use components in Provider and ProviderOptions steps of the AddClaimWizard and EditClaimWizard.
- Click "Add claim"
- Search for a provider
--------
(if JavaScript is disabled)
- You should see a radio button selection of providers
- Select the provider you want
--------
- The rest of the journey remains the same
https://trello.com/c/HwekgugS/470-iterate-on-the-provider-selection-when-creating-a-claim
https://github.com/user-attachments/assets/2ecd4e5f-7632-4ffa-a9cc-624bc3a60269
https://github.com/user-attachments/assets/bc22a62f-0ba9-404a-9576-bf1e2c5e6ba4
_Content change_
=> Add Provider search options to claim wizard

app/views/claims/schools/claims/show.html.erb, app/views/claims/schools/mentors/show.html.erb, app/views/claims/schools/users/show.html.erb, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/schools/mentors.yml, config/locales/en/claims/schools/users.yml
According to guidance from our content designer, all summary lists should have headings.
Note that I have not updated the system specs to include the addition of this new heading, this was by design. The system specs for this are are extremely old and very method driven. Given we are refactoring our system tests I have instead created tickets to address this properly in another PR.
[Refactor the claims mentor system tests](https://trello.com/c/ykwexbOH/484-refactor-the-claims-mentor-system-tests)
[Refactor the claims school system tests](https://trello.com/c/zPlmKTWb/485-refactor-the-claims-school-system-tests)
[Refactor the claims user system tests](https://trello.com/c/m96GMDk3/482-refactor-the-claims-user-system-tests)
Review screenshots
[Update the claims user show page …
=> Add details headers to summary lists for claim show pages

app/views/claims/schools/claims/index.html.erb, config/locales/en/claims/schools/claims.yml, spec/system/claims/schools/claims/view_claims_spec.rb
Updating based on a recent content review.
- Review screenshots/review environment
[Update content on the claims index page](https://trello.com/c/lnRfgtkr/474-update-content-on-the-claims-index-page)
=> Update claims index page with latest content changes

app/wizards/claims/upload_provider_response_wizard/upload_step.rb, spec/fixtures/claims/sampling/provider_responses/valid_provider_response_upload_with_white_space_in_assured_status.csv, spec/system/claims/support/claims/sampling/upload_provider_response/support_user_uploads_a_csv_not_containing_an_assured_status_with_white_space_spec.rb
When uploading a response from the provider "yes " was incorrecly indentified as an invalid input.
- Upload a provider response CSV (after auditing) with a value of "yes " for claim assured.
[Strip spaces from CSV fields before upload](https://trello.com/c/Qp1Gnq4F/505-strip-spaces-from-csv-fields-before-upload)
=> Strip whitespace from provider CSV upload

app/models/school.rb, app/models/school_sen_provision.rb, app/models/sen_provision.rb, app/services/gias/csv_importer.rb, config/analytics_blocklist.yml, config/initializers/inflections.rb, db/migrate/20250401094729_create_sen_provisions.rb, db/migrate/20250401100217_create_school_sen_provisions.rb, db/schema.rb, spec/factories/school_sen_provisions.rb, spec/factories/sen_provisions.rb, spec/fixtures/gias/import_with_trusts_and_regions.csv, spec/models/school_sen_provision_spec.rb, spec/models/sen_provision_spec.rb, spec/services/gias/csv_importer_spec.rb
- Add SEN provisions to schools as part of the GIAS Import.
- Create table for `sen_provisions`
- Create table for `school_sen_provisions`
- Amend `app/services/gias/csv_importer.rb` to create and assign SEN provisions to schools.
- run `bundle exec rake db:drop db:create db:setup`
- This should result in 13 SEN Provision records being created and approx 9099 School SEN Provisions join records.
https://trello.com/c/VFfGnu5j/400-import-sen-data-from-gias
=> Add SEN provisions to schools

app/views/claims/pages/start.en.html.erb, spec/system/claims/start_page_spec.rb
To help our users understand the service and the grant we can link to the published [gov.uk](http://gov.uk/) guidance - [Initial teacher training reform funding guidance - GOV.UK](https://www.gov.uk/government/publications/initial-teacher-training-reform-funding-guidance) in the related content section of the start page [Claim funding for mentor training - GOV.UK](https://claim-funding-for-mentor-training.education.gov.uk/)
- Adds a link to [Initial teacher training reform funding guidance - GOV.UK](https://www.gov.uk/government/publications/initial-teacher-training-reform-funding-guidance) on the start page
- Open the claims review app
- Ensure the link is visible in the related cotent section and goes to the right page
[Add grant guidance to the claim funding start page …
=> Add Initial teacher training reform funding guidance

app/controllers/claims/schools/claims/add_claim_controller.rb, app/controllers/claims/schools/claims_controller.rb, app/models/claims/school.rb, app/policies/claims/claim_policy.rb, app/views/claims/schools/claims/index.html.erb, app/views/claims/support/schools/claims/index.html.erb, config/locales/en/claims/schools/claims.yml, config/locales/en/claims/support/schools/claims.yml, spec/models/claims/school_spec.rb, spec/policies/claims/claim_policy_spec.rb, spec/system/claims/schools/claims/change_claim_on_check_page_spec.rb, spec/system/claims/schools/claims/create_claim_spec.rb, spec/system/claims/schools/claims/edit_draft_claim_spec.rb, spec/system/claims/schools/claims/school_user_creates_a_claim_with_javascript_disabled_spec.rb, spec/system/claims/schools/claims/submit_draft_claim_spec.rb, spec/system/claims/schools/claims/view_claim_spec.rb, spec/system/claims/schools/claims/view_claims_spec.rb
We added the groundwork to prevent schools from creating claims for academic years where they did not have any trained mentors in the register service. We now need to hook that policy up to the front end and related policies.
- Add an eligibily check to claims policy
- Remove the "Add claim" button and render some text to explain why a school cannot create a claim when ineligible
- See that you cannot create a claim
- Log out
- Onboard Anne's school
- Log out
- Confirm that you can now make a claim
[Prevent schools from creating claims if they have not been onboarded for the current claim window
](https://trello.com/c/IJVgLOZM/555-prevent-schools-from-creating-claims-if-they-have-not-been-onboarded-for-the-current-claim-window)
=> Prevent schools from creating claims when ineligible

app/mailers/claims/provider_mailer.rb, app/mailers/claims/user_mailer.rb, app/mailers/placements/provider_user_mailer.rb, app/mailers/placements/school_user_mailer.rb, app/mailers/placements/user_mailer.rb, spec/mailers/claims/provider_mailer_spec.rb, spec/mailers/claims/user_mailer_spec.rb, spec/mailers/placements/provider_user_mailer_spec.rb, spec/mailers/placements/school_user_mailer_spec.rb
We have the ability to track how people navigate to our application from the emails that we send, all of the infrastructure for this exists and we weren't utilising it.
- Add tracking links to all user facing URL's in emails.
- Log into both the claims and placements services as Colin
- Check each email and make sure that the links work
[Set-up email tracking tags to measure user engagement](https://trello.com/c/zRCkHO9E/373-set-up-email-tracking-tags-to-measure-user-engagement)
=> Add tracking links to all URL's in emails

terraform/domains/infrastructure/config/zones.tfvars.json
A new domain - claim-funding-for-itt-mentor-training.service.gov.uk needs to be added
A new dns zone via terraform configuration
The domain plan should be successful
https://trello.com/c/Y3u8I72m
=> Add claim funding dns zone

terraform/application/database.tf
The plpgsql extension is now enabled by default and is no longer required as a parameter.
- Remove plpgsql from `terraform/application/database.tf`
- Ensure that only plpgsql has been removed
=> Removes the plpgsql extension which is now enabled by default

terraform/application/config/production_app_env.yml, terraform/application/config/qa_app_env.yml, terraform/application/config/sandbox_app_env.yml, terraform/application/config/staging_app_env.yml, terraform/domains/environment_domains/config/production.tfvars.json, terraform/domains/environment_domains/config/qa.tfvars.json, terraform/domains/environment_domains/config/sandbox.tfvars.json, terraform/domains/environment_domains/config/staging.tfvars.json
Now that we have the claim-funding-for-itt-mentor-training service.gov.uk zone and it has been delegated, we need to create the environment sub domains.
Added subdomains for qa, staging, sandbox and production
make qa|staging|sandbox|production domains-plan
https://trello.com/c/Y3u8I72m/2315-create-claim-funding-service-domain
=> Add service.gov.uk environment domains

app/mailers/claims/user_mailer.rb, config/locales/en/claims/user_mailer.yml, spec/mailers/claims/user_mailer_spec.rb
Update invitation email (in service) for Claim users so they have all the required info to direct users on how to ensure the right person in their school has access to the service.
Update user mailer content
https://trello.com/c/lB5HJ7YZ/564-update-invitation-email-for-new-users
=> Update new user email with additional content

app/views/placements/schools/hosting_interests/add_hosting_interest/whats_next.html.erb, app/views/placements/schools/hosting_interests/add_hosting_interest/whats_next/_not_open.html.erb, app/views/wizards/placements/add_hosting_interest_wizard/_are_you_sure_step.html.erb, app/views/wizards/placements/add_hosting_interest_wizard/_reason_not_hosting_step.html.erb, app/views/wizards/placements/add_hosting_interest_wizard/not_open/_school_contact_step.html.erb, app/wizards/placements/add_hosting_interest_wizard.rb, app/wizards/placements/add_hosting_interest_wizard/are_you_sure_step.rb, app/wizards/placements/add_hosting_interest_wizard/not_open/school_contact_step.rb, app/wizards/placements/add_hosting_interest_wizard/reason_not_hosting_step.rb, config/locales/en/placements/schools/hosting_interests.yml, config/locales/en/wizards/placements/add_hosting_interest_wizard.yml, db/schema.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_does_not_enter_a_reason_when_selecting_other_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_does_not_enter_any_school_contact_details_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_does_not_select_any_reasons_not_to_host_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_enters_another_reason_why_they_are_not_hosting_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_does_not_enter_a_reason_when_selecting_other_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_does_not_select_any_reasons_not_to_host_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_enters_another_reason_why_they_are_not_hosting_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb, spec/wizards/placements/add_hosting_interest_wizard/are_you_sure_step_spec.rb, spec/wizards/placements/add_hosting_interest_wizard/reason_not_hosting_step_spec.rb
- Changes to the Red (Not open) path of EOI, as requested in https://www.figma.com/design/9eMfPnPEONmEPvimD3CYpz/MSP-Concepts?node-id=63713-34520&t=r3iQPZpM6zsQQv1o-0
- Changes to the content of the EOI Wizards, as requested in https://www.figma.com/design/9eMfPnPEONmEPvimD3CYpz/MSP-Concepts?node-id=63713-34520&t=r3iQPZpM6zsQQv1o-0
- Once on the EOI page, select "No - I can’t offer placements"
- Complete the journey, making sure that the content matches that requested in https://www.figma.com/design/9eMfPnPEONmEPvimD3CYpz/MSP-Concepts?node-id=63713-34520&t=r3iQPZpM6zsQQv1o-0
https://trello.com/c/IhDgfjDK/576-development-work-for-red-path-eoi-iteration-3
https://github.com/user-attachments/assets/28883fa2-11ac-4268-b8f3-fe5a65bf4381
=> Iteration 3 red path changes

app/views/placements/school_user_mailer/user_membership_created_notification.text.erb, config/locales/en/placements/school_user_mailer.yml, spec/mailers/placements/school_user_mailer_spec.rb, spec/system/placements/organisations/users/add_users_spec.rb, spec/system/placements/support/users/school_users/add_user/support_user_adds_a_new_user_to_a_school_spec.rb, spec/system/placements/support/users/school_users/add_user/support_user_adds_an_existing_user_to_a_school_spec.rb
We want to improve our content for new users to the service
- Updates the placements service invitation email content
- Click on Settings
- Click on Emails
- Click on [user_membership_created_notification (opens in new tab)](http://placements.localhost:3000/rails/mailers/placements/school_user_mailer/user_membership_created_notification)
=> Update placements invitation email

app/controllers/placements/schools/placements_controller.rb, app/views/placements/schools/placements/_details.html.erb, app/views/placements/schools/placements/confirm_unassign_provider.html.erb, app/views/wizards/placements/add_placement_wizard/_terms_step.erb, config/locales/en/placements/schools/placements.yml, config/routes/placements.rb, spec/models/claims/claim_spec.rb, spec/system/placements/schools/placements/all_through_school_user_adds_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_adds_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/schools/placements/secondary_school_user_adds_a_placement_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/schools/placements/user_publishes_a_placement_after_preview_spec.rb, spec/system/placements/support/schools/placements/all_through_school_support_user_adds_a_placement_spec.rb, spec/system/placements/support/schools/placements/primary_school_support_user_adds_a_placement_spec.rb, spec/system/placements/support/schools/placements/primary_school_support_user_edits_a_placement_spec.rb, spec/system/placements/support/schools/placements/secondary_school_support_user_adds_a_placement_spec.rb, spec/system/placements/support/schools/placements/secondary_school_support_user_edits_a_placement_spec.rb, spec/system/placements/support/schools/placements/support_user_publishes_a_placement_after_preview_spec.rb, spec/system/placements/support/schools/placements/view_placements/support_user_views_a_placement_with_a_provider_spec.rb, spec/system/placements/support/schools/placements/view_placements/support_user_views_a_placement_with_a_specific_term_spec.rb
- School users can now remove providers from their placements.
- Add controllers/routes/views so school users can remove providers from their placements.
⚠️ You will need a placement assigned to a provider ⚠️ 
- Click on the Placement assigned to a provider
- You should see a link "Unassign provider"
- Clicking "Unassign provider" will take you to a confirm page
- Clicking "Unassign provider" on the confirm page will remove the provider from the placement.
https://trello.com/c/riEuU3Aq/588-fixes-for-expected-date-showing-date-not-added-and-unassigning-a-provider
https://github.com/user-attachments/assets/95bba0b2-2669-448b-92f7-a897ebe83558
=> Add ability to remove providers from placements

app/views/placements/schools/placements/index.html.erb, spec/system/placements/schools/placements/view_placements_list_spec.rb, spec/system/placements/support/schools/placements/view_placements/support_user_views_a_placement_with_a_mentor_assigned_spec.rb, spec/system/placements/support/schools/placements/view_placements/support_user_views_a_placement_with_a_provider_spec.rb
- Return placements index to show "Any time in the academic year" instead of "Date not added"
- Return placements index to show "Any time in the academic year" instead of "Date not added"
https://trello.com/c/1biA1NVk/595-full-journey-card-template
=> Resolve issue with placements showing Date not added

app/controllers/placements/schools/placements/edit_placement_controller.rb, app/controllers/placements/schools/placements_controller.rb, app/mailers/placements/school_user_mailer.rb, app/services/placements/placements/notify_school/remove_provider.rb, app/views/placements/provider_user_mailer/placement_provider_removed_notification.text.erb, app/views/placements/school_user_mailer/placement_provider_removed_notification.text.erb, app/views/placements/schools/placements/_details.html.erb, app/views/placements/schools/placements/confirm_unassign_provider.html.erb, config/locales/en/placements/school_user_mailer.yml, config/locales/en/placements/schools/placements.yml, spec/mailers/placements/provider_user_mailer_spec.rb, spec/mailers/placements/school_user_mailer_spec.rb, spec/mailers/previews/placements/provider_user_mailer_preview.rb, spec/mailers/previews/placements/school_user_mailer_preview.rb, spec/services/placements/placements/notify_school/remove_provider_spec.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/support/schools/placements/primary_school_support_user_edits_a_placement_spec.rb, spec/system/placements/support/schools/placements/secondary_school_support_user_edits_a_placement_spec.rb, spec/system/placements/support/schools/placements/view_placements/support_user_views_a_placement_with_a_provider_spec.rb, spec/system/placements/support/schools/placements/view_placements/support_user_views_a_placement_with_a_specific_term_spec.rb
- Content changes to the placement provider removal pages
- Changes to the email providers receive when removed from the placement
- Added an email to school after removing a provider from a placement
https://trello.com/c/75ALAFzD/596-unassign-provider-from-placement
https://github.com/user-attachments/assets/0f17c65b-5762-47a7-804e-5b68bc1b8185
=> Content changes for placement provider removal

app/views/placements/school_user_mailer/user_membership_created_notification.text.erb, spec/mailers/placements/school_user_mailer_spec.rb
- Request made to add "This is a pilot service for schools and teacher training providers in Leeds and Essex." to onboarding email
https://trello.com/c/4jd0WEWB/546-onboard-all-schools-in-essex-to-the-service
=> Add text to onboarding email about pilot

app/views/wizards/placements/add_placement_wizard/_mentors_step.html.erb, config/locales/en/wizards/placements/add_placement_wizard.yml, spec/system/placements/schools/placements/all_through_school_user_adds_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_adds_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/schools/placements/secondary_school_user_adds_a_placement_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/schools/placements/user_publishes_a_placement_after_preview_spec.rb, spec/system/placements/support/schools/placements/all_through_school_support_user_adds_a_placement_spec.rb, spec/system/placements/support/schools/placements/primary_school_support_user_adds_a_placement_spec.rb, spec/system/placements/support/schools/placements/primary_school_support_user_edits_a_placement_spec.rb, spec/system/placements/support/schools/placements/secondary_school_support_user_adds_a_placement_spec.rb, spec/system/placements/support/schools/placements/secondary_school_support_user_edits_a_placement_spec.rb, spec/system/placements/support/schools/placements/support_user_publishes_a_placement_after_preview_spec.rb
Update the mentor screen as part of the content sweep
- Change the h1 content
- Change the hint text content
[Sweep: Change select a mentor screen](https://trello.com/c/O5mUOCTE/586-sweep-change-select-a-mentor-screen)
=> Update select mentor content

app/views/placements/schools/hosting_interests/add_hosting_interest/whats_next/_not_open.html.erb, app/views/wizards/placements/add_hosting_interest_wizard/_are_you_sure_step.html.erb, app/views/wizards/placements/add_hosting_interest_wizard/not_open/_school_contact_step.html.erb, app/wizards/placements/add_hosting_interest_wizard/reason_not_hosting_step.rb, config/locales/en/placements/schools/hosting_interests.yml, config/locales/en/wizards/placements/add_hosting_interest_wizard.yml, config/locales/en/wizards/placements/multi_placement_wizard.yml, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_and_declares_primary_and_secondary_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_child_subjects_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_quantities_for_potential_placements_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_specific_year_groups_or_subjects_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_does_not_enter_a_reason_when_selecting_other_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_does_not_enter_any_school_contact_details_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_does_not_select_any_reasons_not_to_host_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_enters_another_reason_why_they_are_not_hosting_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_interested/school_user_completes_the_interested_journey_and_declares_primary_and_secondary_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_interested/school_user_completes_the_interested_journey_without_declaring_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_does_not_enter_a_reason_when_selecting_other_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_does_not_select_any_reasons_not_to_host_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_enters_another_reason_why_they_are_not_hosting_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb, spec/wizards/placements/add_hosting_interest_wizard/reason_not_hosting_step_spec.rb
Updates the red path content in line with the latest content sweep.
- Updates h1's, hints and options for the red path
- Fixes a typo in the interested path
- Select "No - I can't offer placements"
- Review each page against the trello card content
[Iteration 4: Content changes to red path](https://trello.com/c/j4skuIaU/592-iteration-4-content-changes-to-red-path)
=> Update red path content

app/policies/claims/support/claim_policy.rb, spec/policies/claims/support/claim_policy_spec.rb
We have received many support requests for us to remove claims via the production console as schools are making mistakes and noticing them.
The standard process is for the claim to be sent to the ESFA and for them to spot the error and then reject the claim at the end of the academic year, however due to the way the training hours are set up and because schools are recognising their mistakes, it makes logical sense for support to be able to remove these claims and reduce work for people further down the line.
- Log is as Anne
- Add a claim
- Select Anne's organisation
- Click into the claim
- Remove the claim
[Allow support users to remove submitted claims](https://trello.com/c/U6doOHfD/632-allow-support-users-to-remove-submitted-claims)
=> Allow support to remove submitted claims

app/views/placements/schools/placements/show.html.erb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_spec.rb
After updating an individual placements, the back button doesn't take user to placement summary page but asks the user to complete the action again. This is incorrect as the user should use the change links should a detail need to be amended again. The school placements show page backlink should always point to the placements index.  The system spec for editing a placement has been extended to cover this behaviou.
Test the backlink. Run the specs. 
https://trello.com/c/Nfp4pzS5/602-back-return-location-after-adding-or-updating-an-individual-placement
=> Change back link href on schools placements show page

app/controllers/placements/schools/hosting_interests/add_hosting_interest_controller.rb, app/controllers/placements/schools/hosting_interests/edit_hosting_interest_controller.rb, config/locales/en/placements/schools/hosting_interests.yml, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_actively_looking/primary_phase_only/school_user_add_their_hosting_interest_and_bulk_adds_placements_for_the_primary_phase_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_actively_looking/school_user_adds_their_hosting_interest_and_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_actively_looking/secondary_phase_only/school_user_adds_their_hosting_interest_and_bulk_adds_placements_for_a_subject_with_child_subjects_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_actively_looking/secondary_phase_only/school_user_adds_ther_hosting_interest_and_bulk_adds_placements_for_the_secondary_phase_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_and_declares_primary_and_secondary_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_child_subjects_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_quantities_for_potential_placements_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_without_declaring_specific_year_groups_or_subjects_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_enters_another_reason_why_they_are_not_hosting_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_actively_looking/primary_phase_only/school_user_edits_their_hosting_interest_and_bulk_adds_placements_for_the_primary_phase_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_actively_looking/school_user_edits_their_hosting_interest_and_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_actively_looking/secondary_phase_only/school_user_edits_their_hosting_interest_and_bulk_adds_placements_for_a_subject_with_child_subjects_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_actively_looking/secondary_phase_only/school_user_edits_ther_hosting_interest_and_bulk_adds_placements_for_the_secondary_phase_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_interested/school_user_completes_the_interested_journey_and_declares_primary_and_secondary_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_interested/school_user_completes_the_interested_journey_without_declaring_potential_placement_details_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_enters_another_reason_why_they_are_not_hosting_spec.rb, spec/system/placements/schools/hosting_interest/edit_hosting_interst/appetite_not_open/school_user_successfully_completes_the_not_open_journey_spec.rb
Remove unused translations, amend tests to no longer expect success banners
Given we have the “What’s next“ pages, the flash messages are no longer needed.
Remove flash message from the add + update EOI journeys and update specs to no longer expect success banners. Remove translations that are no longer in use. 
Remove flash messages and amend specs.
https://trello.com/c/DCMUnXvl/624-remove-eoi-success-flash-banners
=> Remove flash message from EOI journeys

app/controllers/api/provider_suggestions_controller.rb, app/wizards/claims/add_claim_wizard/provider_step.rb, app/wizards/placements/add_organisation_wizard/organisation_step.rb, app/wizards/placements/add_partnership_wizard/partnership_step.rb, app/wizards/placements/edit_placement_wizard/provider_step.rb, spec/wizards/claims/add_claim_wizard/provider_step_spec.rb, spec/wizards/placements/add_organisation_wizard/organisation_step_spec.rb, spec/wizards/placements/add_partnership_wizard/partnership_step_spec.rb, spec/wizards/placements/edit_placement_wizard/provider_step_spec.rb
We currently display a `code` for providers that comes from another service, however this is not widely used or recognised and therefore doesn't work very well as an identifier.
I considered also adding `town` as we do for schools, however this isn't data that we store despite having a field for it.
- Create a placements
- Assign a provider to a placement
- Search for a provider
- Confirm that the postcode is show next to the provider name
['Organisation name' insufficient when searching for a partner](https://trello.com/c/eSOXNiQj/598-organisation-name-insufficient-when-searching-for-a-partner)
=> Display postcode on provider autocomplete

config/scheduled_jobs.yml
We need to schedule this job to run every day.
- Adds the `Claims::Slack::DailyRoundupJob` to the schedule at 16:00 each day
- Review the yaml and make sure it matches with the above ☝️ 
[Add daily claims roundup schedule](https://trello.com/c/6ymaqyZ7/643-add-daily-claims-roundup-schedule)
=> Add daily Slack roundup schedule

.env.example, .env.production, .env.test, spec/jobs/publish_teacher_training/provider/sync_all_job_spec.rb, spec/jobs/publish_teacher_training/subject/sync_all_job_spec.rb, spec/services/publish_teacher_training/provider/api_spec.rb, spec/services/publish_teacher_training/provider/importer_spec.rb, spec/services/publish_teacher_training/subject/api_spec.rb, spec/services/publish_teacher_training/subject/import_spec.rb, spec/tasks/subject_data_spec.rb
The publish API changed the URL they use, as a result it stopped workijng for us
- Updates the publish API url
- Drop your database
- Set it up again
- Run migrations
- Run seeds
- Everything should work without error again
[Update Publish API URL](https://trello.com/c/Uecc0VYo/650-update-publish-api-url)
=> Update the .env files to use new publish API url

app/services/concerns/regional_areas.rb
Whilst reviewing a support request it became apparent that our regional area codes were not mapped correctly. These codes are used do determine the funding that schools receive, so it is important that we correct this error.
This one is a bit of a pain to review, the only real way to do so is to check that each code matches the expected area against https://www.ons.gov.uk/explore-local-statistics/areas/E92000001-england
As part of this work I have run this test 3 times for every entry and I'm certain they're all correct now. You will not be able to find the 2 regional areas marked as "inactive" on this site, but google will give you some results instead.
[Investigate region codes for claim funding](https://trello.com/c/yTFD95ji/645-investigate-region-codes-for-claim-funding)
=> Correct regional area codes/names

app/components/placement/status_tag_component.rb, app/components/placement/summary_component.html.erb, app/views/placements/providers/partner_schools/placements/index.html.erb, app/views/placements/providers/partner_schools/placements/show.html.erb, app/views/placements/providers/placements/show.html.erb, app/views/placements/schools/placements/_details.html.erb, app/views/placements/schools/placements/preview.html.erb, app/views/shared/placements/_placement_details.html.erb, app/views/wizards/placements/add_placement_wizard/_preview_placement_step.html.erb, config/locales/en/placements/schools/placements.yml, spec/components/placement/status_tag_component_spec.rb, spec/components/previews/placement/status_tag_component_preview.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/primary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/schools/placements/school_user_edits_a_placement_with_no_mentors_spec.rb, spec/system/placements/schools/placements/school_user_views_and_deletes_a_placement_spec.rb, spec/system/placements/schools/placements/school_user_views_and_deletes_a_placement_with_partner_provider_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_spec.rb, spec/system/placements/schools/placements/secondary_school_user_edits_a_placement_with_javascript_disabled_spec.rb, spec/system/placements/support/schools/placements/primary_school_support_user_edits_a_placement_spec.rb, spec/system/placements/support/schools/placements/school_support_user_edits_a_placement_with_no_mentors_spec.rb, spec/system/placements/support/schools/placements/school_support_user_views_and_deletes_a_placement_spec.rb, spec/system/placements/support/schools/placements/school_support_user_views_and_deletes_a_placement_with_partner_provider_spec.rb, spec/system/placements/support/schools/placements/secondary_school_support_user_edits_a_placement_spec.rb
When a placement was assigned to a provider it would display as "Unavailable" when the provider was viewing the placement. This led to confusion and as a team we agreed this needed to be resolved.
- Adds new functionality to the status tag to conditonally render school and provider views
['Unavailable' tag causing confusion for assigned placements](https://trello.com/c/TXTSV5wn/599-unavailable-tag-causing-confusion-for-assigned-placements)
=> Update unavailable tag

app/models/claims/claim_window.rb, app/views/claims/schools/claims/index.html.erb, spec/models/claims/claim_window_spec.rb
The message was using the start and end years from the claim window, rather than the academic year which was causing confusion for users.
- Replaced the claim window `starts_on` and `ends_on` year for the academic year equivalent
- Delegates `starts_on` and `ends_on` to the academic year with prefix
- Check that the warning message references the academic year start and end date
[Typo on CFMT claim journey](https://trello.com/c/fbxy3PZs/628-typo-on-cfmt-claim-journey)
=> Fix claim guidance warning

terraform/domains/environment_domains/config/production.tfvars.json, terraform/domains/environment_domains/config/qa.tfvars.json, terraform/domains/environment_domains/config/sandbox.tfvars.json, terraform/domains/environment_domains/config/staging.tfvars.json
Configure rate limiting for all environments
Add global rate limit per IP for 5 minute intervals
Value for production global rate set from checking ingress logs for the last 4 weeks and is more than double any 10 minute period in that time.
make env domains-plan
https://trello.com/c/rmljcE5W/2345-add-rate-limiting-for-services
=> Add ingress rate limits

app/models/claims/provider.rb, spec/models/claims/provider_spec.rb
- Remove unnecessary `through` association between `providers` and `claims` 
https://trello.com/c/XUsra1qh/685-update-claimsprovider-claims-association
=> Remove unnecessary through association in providers for claims

app/models/placements/school.rb, app/models/school.rb, app/services/gias/csv_importer.rb, spec/models/placements/school_spec.rb, spec/models/school_spec.rb, spec/services/gias/csv_importer_spec.rb
We exclude closed schools when importing from GIAS but we don’t check if schools have closed and remove them if they were imported whilst they were open. This has caused a few issues with duplicate school names and onboarding the wrong schools.
- Moves the `partnerships` association to the base school model
- Deletes schools that do not have partnerships or that are onboarded from the service if they have been closed in GIAS
This is one you'll need to check out locally to test. You'll need to create a school locally via the console that uses a made up URN e.g. "999999", then run the GIAS import and verify that it has been removed.
[Remove closed schools from the service database](https://trello.com/c/R4DgQihv/663-remove-closed-schools-from-the-service-database)
=> Remove closed schools when syncing

.github/workflows/build_and_deploy.yml, .github/workflows/build_nocache.yml
Use a standard workflow for building container images without using image cache
Add a new github actions workflow for building images without using image cache
Check the workflow - https://github.com/DFE-Digital/itt-mentor-services/actions/runs/15437953594/job/43448692751?pr=1612
https://trello.com/c/ktsJEPED/2326-use-build-docker-image-github-action
=> Add image build workflow

app/controllers/claims/support/manually_onboarded_schools_controller.rb, app/controllers/claims/support/schools/add_school_controller.rb, app/views/claims/support/manually_onboarded_schools/index.html.erb, app/views/claims/support/settings/index.html.erb, app/wizards/claims/add_school_wizard.rb, config/locales/en/claims/support/manually_onboarded_schools.yml, config/locales/en/claims/support/settings.yml, config/routes/claims.rb, spec/components/previews/autocomplete_select_form_component_preview.rb, spec/components/previews/options_form_component_preview.rb, spec/system/claims/support/settings/support_user_views_manually_onboarded_schools_spec.rb, spec/system/claims/support/settings/support_user_views_manually_onboarded_schools_when_none_are_present_spec.rb, spec/wizards/claims/add_school_wizard_spec.rb
Claims needs a way to view which schools have been manually onboarded so that they can be cross referenced against whether they should have been.
- Adds the manually onboarded schools page to the support settings page
- Click on settings
- View the Manually onboarded schools page
[Add support console page to view manually onboarded schools](https://trello.com/c/bv50tUj7/710-add-support-console-page-to-view-manually-onboarded-schools)
=> Add page to display manually onboarded schools

app/decorators/placement_decorator.rb, app/views/placements/schools/placements/_details.html.erb, app/views/wizards/placements/edit_placement_wizard/_key_stage_step.html.erb, app/wizards/placements/add_hosting_interest_wizard/interested/placement_quantity_known_step.rb, app/wizards/placements/add_hosting_interest_wizard/list_placements_step.rb, app/wizards/placements/add_hosting_interest_wizard/subjects_known_step.rb, app/wizards/placements/edit_placement_wizard.rb, app/wizards/placements/edit_placement_wizard/key_stage_step.rb, config/locales/en/placements/schools/placements.yml, config/locales/en/wizards/placements/edit_placement_wizard.yml, spec/system/placements/schools/placements/school_user_edits_a_send_placement_spec.rb, spec/wizards/placements/edit_placement_wizard/key_stage_step_spec.rb, spec/wizards/placements/edit_placement_wizard_spec.rb
- Allow school users to change the key stage of a SEND placement.
- Add a step to the EditPlacementWizard to allow users to change the Key Stage of SEND placements.
Assuming you already have a SEND placement created
- Click on the SEND placement
- Click to "Change" the Key stage
- Select another key stage
- The key stage should be updated
https://trello.com/c/GVk0Tzvp/740-add-the-ability-to-change-the-key-stage-of-send-placements
https://github.com/user-attachments/assets/d83d3ca2-cdd3-4d57-b289-e1772af9aa81
=> Edit placement with key stage

app/controllers/placements/partnerships/add_partnership_controller.rb, app/views/placements/providers/partner_schools/index.html.erb, app/views/wizards/placements/add_partnership_wizard/_check_your_answers_step.html.erb, config/locales/en/placements/providers/partner_schools.yml, config/locales/en/placements/providers/partner_schools/add_partner_school.yml, config/locales/en/wizards/placements/add_partnership_wizard.yml, spec/system/placements/providers/partner_schools/placements/provider_user_views_a_placement_for_a_partner_school_spec.rb, spec/system/placements/providers/partner_schools/placements/provider_user_views_placment_list_for_partner_school_spec.rb, spec/system/placements/providers/partner_schools/provider_user_adds_a_school_spec.rb, spec/system/placements/providers/partner_schools/provider_user_adds_a_school_without_javascript_spec.rb, spec/system/placements/providers/partner_schools/provider_user_removes_partner_schools_spec.rb, spec/system/placements/providers/partner_schools/provider_user_views_a_populated_schools_list_spec.rb, spec/system/placements/providers/partner_schools/provider_user_views_a_provider_partner_school_spec.rb, spec/system/placements/providers/partner_schools/provider_user_views_an_empty_schools_list_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_adds_a_partner_school_without_javascript_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_removes_partner_schools_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_views_a_populated_schools_list_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_views_a_provider_partner_school_spec.rb, spec/system/placements/support/providers/partner_schools/support_user_views_an_empty_schools_list_spec.rb
- Remove content informing providers that they will need to add schools before they can be assigned to placements.
- Remove content informing providers that they will need to add schools before they can be assigned to placements.
- Navigate to "Schools"
- Note that the content has been removed from the index page.
- Click "Add school"
- Follow the journey
- On the Check Your Answers page, not that the contact has been remove
- Click "Confirm and add school"
- Note that the body has been removed from the success banner
https://trello.com/c/qTwylVKA/727-remove-mention-of-providers-having-to-add-school-before-they-can-be-assigned
=> Remove mention of adding schools before being assigned

app/services/concerns/regional_areas.rb
Chiltern and Slough have been succeeded by Buckinghamshire, so we're adding it to the Fringe areas.
- Added Buckinghamshire to Fringe areas
- Check code is correct
https://trello.com/c/ot7MLmUw/743-investigate-region-support-ticket
=> Add Buckinghamshire E06000060 to fringe regional area.

.rubocop.yml, config/locales/en/claims/user_mailer.yml, spec/mailers/claims/user_mailer_spec.rb
Users want to be able to click on a link to view their claim
- Add link to claim in clawback email
- Review content and screenshot
https://trello.com/c/npvq5gC7/747-add-link-to-claim-for-school-facing-clawback-email
=> Add link to claim for clawback email

app/components/placements/schools/summary_component.html.erb, app/components/placements/schools/summary_component.rb, app/controllers/placements/providers/find_controller.rb, app/models/placement.rb, app/models/school.rb, app/views/placements/providers/find/_details_navigation.html.erb, app/views/placements/providers/find/placement_information.html.erb, app/views/placements/providers/find/placements.html.erb, app/views/placements/providers/find/school_details.html.erb, config/locales/en/components/placements/schools/summary_component.yml, config/locales/en/placements/providers/find.yml, spec/components/placements/schools/summary_component_spec.rb, spec/system/placements/providers/find/provider_user_views_a_school_with_send_placements_spec.rb
- Add SEND information to Provider Find page.
- Add SEND information to School details in Provider index and show pages
Assuming you have either SEND placements or Potential SEND Placement details
- On the "Find" page, you should see a new "SEND placements" row in the school details
- Click a school offering SEND
- You should see the SEND placements/potential placement details displayed.
https://trello.com/c/jnIXRpNU/750-add-send-placement-details-to-provider-find-page
=> Add send placement details to provider find page

app/controllers/placements/providers/find_controller.rb, app/views/placements/providers/find/_details_navigation.html.erb, app/views/placements/providers/find/placement_contact.html.erb, app/views/placements/providers/find/school_details.html.erb, config/locales/en/placements/providers/find.yml, config/routes/placements.rb, spec/system/placements/providers/find/provider_user_views_a_not_hosting_school_spec.rb, spec/system/placements/providers/find/provider_user_views_a_placements_already_organised_school_spec.rb, spec/system/placements/providers/find/provider_user_views_a_school_which_is_not_onboarded_spec.rb, spec/system/placements/providers/find/provider_user_views_a_school_with_previous_filled_unfilled_placements_spec.rb, spec/system/placements/providers/find/provider_user_views_an_open_to_hosting_school_spec.rb, spec/system/placements/providers/find/provider_user_views_an_unfilled_placements_school_spec.rb
Users aren’t quite understanding what happens next in the journey, we’re improving our wayfinding to help address this.
Rename placement information secondary nav to contact. Add content to placements and contact pages. Move previously offered placements to school details. 
Go through the provider find pages and look for any discrepancies from the Figma files.
https://trello.com/c/MSNmNuvB/738-wayfinding-provider-view
Placements page: 
Contact page: 
School details page:
=> Wayfinding improvements to the provider find interface

app/controllers/placements/schools/placements/add_multiple_placements_controller.rb, app/controllers/placements/schools/placements/add_placement_controller.rb, app/mailers/placements/school_user_mailer.rb, app/services/placements/placements/notify_school/create_placements.rb, app/views/placements/school_user_mailer/placement_information_added_notification.text.erb, app/views/placements/schools/hosting_interests/add_hosting_interest/whats_next/_interested.html.erb, config/locales/en/placements/schools/hosting_interests.yml, spec/mailers/placements/school_user_mailer_spec.rb, spec/mailers/previews/placements/school_user_mailer_preview.rb, spec/services/placements/placements/notify_school/create_placements_spec.rb, spec/system/placements/schools/hosting_interest/add_hosting_interest/appetite_interested/school_user_completes_the_interested_journey_and_declares_primary_and_secondary_potential_placement_details_spec.rb, spec/system/placements/schools/placements/all_through_school_user_adds_a_placement_spec.rb, spec/system/placements/schools/placements/bulk_add_placements/school_user_bulk_adds_placements_for_primary_and_secondary_phases_spec.rb
Users aren’t quite understanding what happens next in the journey, we’re improving our wayfinding to help address this.
Update content on the whats next page.
Biforcate the placements created email so different content is shown for actively looking and interested schools.
Check the email and the content page against the figma designs
(https://trello.com/c/uaPrNF6B/736-wayfinding-amber-path)
Amber path email: 
Green path email:
=> 736 wayfinding amber path

spec/components/claims/claim_window_warning_banner_component_spec.rb
Claim window banner spec needs a start date as well as an end date; otherwise validation error is created when instantiating the claim_window object.
=> Fix claim window banner spec

app/controllers/api/provider_suggestions_controller.rb, app/wizards/claims/add_claim_wizard/provider_options_step.rb, app/wizards/claims/add_claim_wizard/provider_selection_step.rb, spec/factories/providers.rb, spec/requests/api/provider_suggestions_spec.rb, spec/system/claims/schools/claims/school_user_creates_a_claim_with_javascript_disabled_spec.rb, spec/system/claims/support/schools/claims/support_user_creates_a_claim_with_javascript_spec.rb
- When creating a claim, only accredited providers will appear in the autocomplete dropdown.
- Add `accredited` scope to claims controllers when searching for providers.
=> Claims can only be assigned to accredited providers

app/controllers/claims/support/claims_reminders_controller.rb, app/mailers/claims/user_mailer.rb, app/views/claims/support/claims_reminders/schools_not_submitted_claims.html.erb, app/views/claims/support/settings/index.html.erb, config/locales/en/claims/support/claims_reminders.yml, config/locales/en/claims/support/settings.yml, config/locales/en/claims/user_mailer.yml, config/routes/claims.rb, spec/mailers/claims/user_mailer_spec.rb, spec/mailers/previews/claims/user_mailer_preview.rb, spec/requests/claims/support/claims_reminders_spec.rb, spec/system/claims/support/create_a_claim_window_spec.rb, spec/system/claims/support/remove_a_claim_window_spec.rb, spec/system/claims/support/settings/onboard_multiple_schools/support_user_can_not_onboard_schools_when_there_are_no_claim_windows_spec.rb, spec/system/claims/support/settings/onboard_multiple_schools/support_user_does_not_select_a_claim_window_spec.rb, spec/system/claims/support/settings/onboard_multiple_schools/support_user_does_not_upload_a_file_spec.rb, spec/system/claims/support/settings/onboard_multiple_schools/support_user_onboards_multiple_schools_for_the_current_claim_window_spec.rb, spec/system/claims/support/settings/onboard_multiple_schools/support_user_onboards_multiple_schools_when_only_a_current_claim_window_exists_spec.rb, spec/system/claims/support/settings/onboard_multiple_schools/support_user_onboards_multiple_schools_when_only_a_future_claim_window_exists_spec.rb, spec/system/claims/support/settings/onboard_multiple_schools/support_user_uploads_a_file_with_the_wrong_headers_spec.rb, spec/system/claims/support/settings/onboard_multiple_users/support_user_does_not_upload_a_file_spec.rb, spec/system/claims/support/settings/onboard_multiple_users/support_user_onboards_users_spec.rb, spec/system/claims/support/settings/onboard_multiple_users/support_user_uploads_a_file_with_invalid_headers_spec.rb, spec/system/claims/support/settings/support_user_views_manually_onboarded_schools_spec.rb, spec/system/claims/support/settings/support_user_views_manually_onboarded_schools_when_none_are_present_spec.rb, spec/system/claims/support/settings/support_user_views_remind_schools_to_submit_claims_when_all_schools_claimed_spec.rb, spec/system/claims/support/settings/support_user_views_remind_schools_to_submit_claims_when_schools_have_not_claimed_spec.rb, spec/system/claims/support/support_users_adds_a_claim_window_which_includes_dates_within_an_existing_claim_window_spec.rb, spec/system/claims/support/update_a_claim_window_spec.rb, spec/system/claims/support/view_emails_spec.rb
We need to remind schools that have not claimed that the claim window is closing soon, instead of doing this manually we've opted to add the functionality to the service.
- Updates the structure of the settings page as it was becoming cluttered
- Adds a new mailer
- Adds a support page to send an email to users from schools who have not made claims for the current academic year
- Log in as colin
- Navigate to settings
- Review new format
- Click on "Remind schools to submit claims"
- Review content
https://trello.com/c/8hs4wPht/34-add-some-headers-descriptions-to-the-support-settings-page-to-improve-clarity
https://trello.com/c/C8srvib5/40-add-remind-schools-to-make-claims-support-service
=> Add claim reminder emails

app/controllers/claims/support/claims_reminders_controller.rb, app/mailers/claims/provider_mailer.rb, app/views/claims/support/claims_reminders/providers_not_submitted_claims.html.erb, app/views/claims/support/settings/index.html.erb, config/locales/en/claims/provider_mailer.yml, config/locales/en/claims/support/claims_reminders.yml, config/locales/en/claims/support/settings.yml, config/routes/claims.rb, spec/mailers/claims/provider_mailer_spec.rb, spec/mailers/previews/claims/provider_mailer_preview.rb, spec/requests/claims/support/claims_reminders_spec.rb, spec/system/claims/support/settings/support_user_views_remind_providers_to_submit_claims_when_all_schools_claimed_spec.rb, spec/system/claims/support/settings/support_user_views_remind_providers_to_submit_claims_when_schools_have_not_claimed_spec.rb
We need to remind providers that have no had claims assigned to them that the claim window is closing soon, instead of doing this manually we've opted to add the functionality to the service.
- Adds a new mailer
- Adds a support page to send an email to providers who have not had claims assigned to them for the current academic year
- Log in as colin
- Navigate to settings
- Click on "Remind providers to submit claims"
- Review content
https://trello.com/c/8hs4wPht/34-add-some-headers-descriptions-to-the-support-settings-page-to-improve-clarity
https://trello.com/c/TnJw6CsW/41-add-remind-providers-to-ask-schools-to-create-claims-support-service
=> Add remind providers tool to support console

app/models/claims/mentor_training.rb, app/services/claims/claim/clawback/clawback_requested.rb, app/views/claims/support/claims/_details.html.erb, app/views/wizards/claims/request_clawback_wizard/_check_your_answers_step.html.erb, app/wizards/claims/edit_request_clawback_wizard.rb, app/wizards/claims/request_clawback_wizard.rb, app/wizards/claims/request_clawback_wizard/check_your_answers_step.rb, app/wizards/claims/request_clawback_wizard/mentor_training_clawback_step.rb, config/locales/en/claims/support/claims.yml, config/locales/en/wizards/claims/request_clawback_wizard.yml, spec/models/claims/mentor_training_spec.rb, spec/services/claims/claim/clawback/clawback_requested_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_edits_a_mentor_training_for_a_clawback_request_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_requests_a_clawback_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_views_clawbacks_show_page_spec.rb, spec/wizards/claims/edit_request_clawback_wizard_spec.rb, spec/wizards/claims/request_clawback_wizard/check_your_answers_step_spec.rb, spec/wizards/claims/request_clawback_wizard/mentor_training_clawback_step_spec.rb, spec/wizards/claims/request_clawback_wizard_spec.rb
- Invert the logic on the clawback request to enter "Hours the mentor worked"
- Swap the logic and input on the clawback request wizard to allow users to enter the correct number of hours worked by the mentor, then calculate the clawback.
- Navigate to "Claims" -> "Clawback"
⚠️ You will need to have a claim with the status "Rejected by school" ⚠️ 
- Click the claim
- Click "Request clawback"
- You will now see that you must enter "Number of hours the mentor worked"
- Continue the journey
- On the check your answers page, you will see that the clawback amount is calculated and shown.
https://trello.com/c/4gMiigVt/44-invert-clawback-logic-to-calculate-clawback-amount
https://github.com/user-attachments/assets/5a4edf32-bcfa-4f68-a155-452dc18c1e85
=> Invert clawback logic

app/components/claims/claim/filter_form_component.rb, app/controllers/claims/support/providers_controller.rb, spec/requests/claims/support/providers_spec.rb
- Add scopes to remove `unaccredited` and `additional NIoT` providers from the Support Claims filters.
- Add scopes to remove `unaccredited` and `additional NIoT` providers from the Support Claims filters.
- Navigate to Claims
- Search for NIoT in the provider filter
- Only "NIoT: National Institute of Teaching, founded by the School-Led Development Trust" should appear
https://trello.com/c/rIKPSbUj/39-remove-additional-niot-orgs-from-claims-support-filters
=> Remove unaccredited and additional NIoT providers from claims filters

app/components/claim/card_component.html.erb, app/components/claim/card_component.rb, app/components/claims/claim/filter_form_component.html.erb, app/components/claims/claim/filter_form_component.rb, app/controllers/claims/support/claims/clawbacks_controller.rb, app/controllers/claims/support/claims/payments_controller.rb, app/controllers/claims/support/claims/samplings_controller.rb, app/controllers/claims/support/claims_controller.rb, app/decorators/claims/claim_decorator.rb, app/forms/claims/support/claims/filter_form.rb, app/queries/claims/claims_query.rb, app/views/claims/support/claims/clawbacks/index.html.erb, app/views/claims/support/claims/index.html.erb, app/views/claims/support/claims/payments/index.html.erb, app/views/claims/support/claims/samplings/index.html.erb, config/locales/en/activerecord.yml, config/locales/en/claims/support/claims.yml, config/locales/en/components/claim/card_component.yml, config/locales/en/components/claims/claim/filter_form_component.yml, spec/components/claim/card_component_spec.rb, spec/components/claims/claim/filter_form_component_spec.rb, spec/components/previews/claim/card_component_preview.rb, spec/decorators/claims/claim_decorator_spec.rb, spec/factories/providers.rb, spec/forms/claims/support/claims/filter_form_spec.rb, spec/queries/claims/claims_query_spec.rb, spec/system/claims/support/claims/sampling/support_user_filters_sampled_claims_by_support_user_spec.rb
- Add support users filter to the claims page.
- Add detail to the Claims card component to show assigned support users.
- Add support users filter to the claims page.
- Add detail to the Claims card component to show assigned support users.
- Navigate to "Claims"
⚠️ If you haven't already, assign some claims to support users ⚠️ 
- Use the "Support user" filter to filter results based on selected Support users.
https://trello.com/c/Xw2JCIrV/28-add-support-user-details-to-claim-summary-on-index-page-and-support-user-filter
https://github.com/user-attachments/assets/5ddb75fb-361f-4935-b378-e821550afec8
=> Add support user filter to claims index pages

app/jobs/claims/slack/daily_roundup_job.rb, app/slack_notifiers/claims/claim_slack_notifier.rb, spec/jobs/claims/slack/daily_roundup_job_spec.rb, spec/slack_notifiers/claims/claim_slack_notifier_spec.rb
- Correct academic year query on claims for Slack notification
- Add Average total amount to Slack notification
- Correct academic year query on claims for Slack notification
- Add Average total amount to Slack notification
https://trello.com/c/eG66dK64/26-add-average-claim-value-to-slack-bot
=> Add average claim amount to slack notification

app/models/academic_year.rb, app/models/claims/claim_window.rb, app/views/claims/schools/claims/index.html.erb, app/views/claims/support/schools/claims/index.html.erb, config/locales/en/claims/schools/claims.yml, spec/system/claims/schools/claims/claim_user_views_the_claims_index_page_when_claim_window_has_closed_but_another_window_is_upcoming_spec.rb, spec/system/claims/schools/claims/claim_user_views_the_claims_index_page_when_claim_window_has_closed_spec.rb
- Fix the logic to show when a claim window has closed.
- Fix the logic to show when a claim window has closed.
⚠️ The claim window must be closed ⚠️ 
- Navigate to claims.
- You will see an inset text informing you the claim window has closed.
=> Fix claim window warning

app/wizards/claims/invalid_provider_wizard.rb
Use the claim's set claim window instead of the current claim window to resolve 500 when no claim window is active.
=> Use claims' claim window instead of current

terraform/application/application.tf, terraform/application/variables.tf
Enforce containers to run as non-root user
Update the application and worker pods to run as non-root users
- Application should run without any issues.
- Application runs as non-root user
https://trello.com/c/YekUhaCn
=> Enforce non-root user

Gemfile.lock
My local setup adds darwin-24 to the gemfile everytime I run rspec. It is the latest version and we should have it in our repo.
Add darwin-24 to gemfile.lock
=> Add darwin 24 to gemfile.lock

app/models/school.rb, db/migrate/20250815112517_remove_email_address_from_schools.rb, db/schema.rb
Now that the codebase no longer uses email_address on schools anywhere; we can remove the column from the DB/ remove the ignore_column from the schools model.
Remove email_address from the schools table and remove the ignore column from the model. 
https://trello.com/c/kElByRGT/60-remove-school-email-address
=> Remove email address from schools

app/jobs/claims/school/onboard_schools_job.rb, app/models/academic_year.rb, app/models/claims/claim_window.rb, app/models/claims/eligibility.rb, app/wizards/claims/add_organisation_wizard.rb, app/wizards/claims/add_school_wizard.rb, db/migrate/20250821125922_remove_claim_window_from_eligibility.rb, db/schema.rb, spec/factories/eligibilities.rb, spec/models/academic_year_spec.rb, spec/models/claims/claim_window_spec.rb, spec/models/claims/eligibility_spec.rb, spec/requests/claims/support/claims_reminders_spec.rb, spec/system/claims/schools/claims/claim_user_changes_a_claim_details_via_check_your_answers_page_links_spec.rb, spec/system/claims/schools/claims/claim_user_creates_a_claim_spec.rb, spec/system/claims/schools/claims/claim_user_views_the_claims_index_page_when_claim_window_has_closed_but_another_window_is_upcoming_spec.rb, spec/system/claims/schools/claims/claim_user_views_the_claims_index_page_when_claim_window_has_closed_spec.rb, spec/system/claims/schools/claims/claims_user_creates_a_claim_for_a_mentor_with_a_previous_year_claim_spec.rb, spec/system/claims/schools/claims/claims_user_views_the_claims_index_page_when_claim_window_is_closing_spec.rb, spec/system/claims/schools/claims/claims_user_views_the_claims_index_page_when_mentors_are_present_spec.rb, spec/system/claims/schools/claims/claims_user_views_the_claims_index_page_when_no_mentors_are_present_spec.rb, spec/system/claims/support/settings/support_user_views_remind_schools_to_submit_claims_when_schools_have_not_claimed_spec.rb, spec/wizards/claims/add_organisation_wizard_spec.rb
Removes all references to the `claim_window_id` from the `eligibilities` table as we're now utilising the `academic_year_id` column to calculate eligibility.
- Removes the `claim_windows` foreign key from `eligibilities`
- Removed the `claim_window_id` column from `eligibilities`
- Updates specs to reflect these changes
- Ensure test suite passes, review migration for accuracy
https://trello.com/c/VAI8NRJp/126-remove-claimwindowid-from-eligibilites-table
=> Remove claim window from eligibility

app/jobs/claims/user/notify_users_of_invalid_provider_claims_job.rb, app/services/claims/claim/invalid_provider_notification.rb, config/scheduled_jobs.yml, spec/factories/academic_years.rb, spec/jobs/claims/user/notify_users_of_invalid_provider_claims_job_spec.rb, spec/services/claims/claim/invalid_provider_notification_spec.rb
Due to claims being created with invalid providers we have a number of claims which are invalid. We need our users to update those claims with hte correct provider details before they can be submitted for payment.
There is an existing mailer to send a notification to users about their invalid claims, we want to create a scheduled job that will email users every week on Monday at 09:00 to remind them that there are outstanding issues to resolve.
Make sure that we utilise the rate limiter service when sending these emails to prevent overloading Notify.
No Ui needed.
https://trello.com/c/gS3Mm6zd/131-create-service-to-email-users-with-invalid-claims
=> Add job to email users with invalid claims

app/controllers/claims/support/claims/request_clawback_controller.rb, app/services/claims/claim/clawback/clawback_not_required.rb, app/views/claims/support/claims/_details.html.erb, app/views/wizards/claims/request_clawback_wizard/_check_your_answers_step.html.erb, app/views/wizards/claims/request_clawback_wizard/_no_clawback_required_step.html.erb, app/wizards/claims/reject_claim_wizard.rb, app/wizards/claims/request_clawback_wizard.rb, app/wizards/claims/request_clawback_wizard/mentor_training_clawback_step.rb, app/wizards/claims/request_clawback_wizard/no_clawback_required_step.rb, config/locales/en/claims/support/claims.yml, config/locales/en/claims/support/claims/request_clawback.yml, config/locales/en/wizards/claims/request_clawback_wizard.yml, db/seeds.rb, spec/services/claims/claim/clawback/clawback_not_required_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_edits_a_clawback_request_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_edits_a_mentor_training_for_a_clawback_request_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_requests_a_clawback_with_all_mentors_incorrect_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_requests_a_clawback_with_one_mentor_incorrect_spec.rb, spec/system/claims/support/claims/clawbacks/support_user_views_clawbacks_show_page_spec.rb, spec/wizards/claims/request_clawback_wizard/mentor_training_clawback_step_spec.rb, spec/wizards/claims/request_clawback_wizard_spec.rb
If a claim has incorrectly been rejected by the provider and school, support users need a way to correct the hours a mentor has worked
- Allows support to enter the same number of hours a mentor originally worked and displays a warning when there are no hours to claw back
- If a claim has no hours clawed back for any mentors it is moved back to paid
- Audit some claims
- Mark the hours worked the same as the original hours
https://trello.com/c/jRVwj0AK/132-allow-clawback-to-equal-the-original-number-of-hours-if-a-clawback-has-been-requested-incorrectly
=> Allow clawback to be cancelled

app/jobs/claims/payment/create_and_deliver_job.rb, app/wizards/claims/submit_claims_to_be_paid_wizard.rb, spec/jobs/claims/payment/create_and_deliver_job_spec.rb, spec/wizards/claims/submit_claims_to_be_paid_wizard_spec.rb
The amount of claims are too large to send to the ESFA without the service timing out. Create a job to move this to a background process.
- Create create and deliver job
- Utilise new job
- Review logic
=> Move create and deliver service into a background job

app/controllers/claims/support/claims_reminders_controller.rb, app/mailers/claims/user_mailer.rb, app/views/claims/support/claims_reminders/school_has_signed_in_but_not_claimed.erb, app/views/claims/support/claims_reminders/schools_not_signed_in.html.erb, app/views/claims/support/claims_reminders/schools_not_submitted_claims.html.erb, app/views/claims/support/settings/index.html.erb, config/locales/en/claims/support/claims_reminders.yml, config/locales/en/claims/support/settings.yml, config/locales/en/claims/user_mailer.yml, config/routes/claims.rb, spec/mailers/claims/user_mailer_spec.rb, spec/mailers/previews/claims/user_mailer_preview.rb, spec/requests/claims/support/claims_reminders_spec.rb, spec/support/capybara.rb, spec/system/claims/support/settings/support_user_views_remind_schools_that_have_signed_in_to_make_claims_when_all_schools_have_claimed_spec.rb, spec/system/claims/support/settings/support_user_views_remind_schools_that_have_signed_in_to_make_claims_when_no_schools_have_claimed_spec.rb, spec/system/claims/support/settings/support_user_views_remind_schools_to_sign_in_when_all_schools_have_signed_in_spec.rb, spec/system/claims/support/settings/support_user_views_remind_schools_to_sign_in_when_schools_have_not_signed_in_spec.rb, spec/system/claims/support/settings/support_user_views_remind_schools_to_submit_claims_when_schools_have_not_claimed_spec.rb
Adds a mailer to remind schools who have not logged in to claim and a mailer to remind schools who have logged in but not claimed to claim.
- Adds 2 new mailers and adds access to them via the support settings page
- Navigate to settings
- View Remind schools to sign 
- View Remind schools that have signed in to make claims
https://trello.com/c/CtDq8olg/169-consider-any-actions-required-to-help-address-trends-on-schools-not-submitting-claims
=> Add new reminder emails for schools to support dashboard
